return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Showdowns",
            fb_cfg_dialogue = "Boss-Dialoge",
            fb_cfg_music = "Showdown-Musik",
            fb_cfg_fx = "Bildschirmeffekte",
            fb_cfg_cinematic = "Showdown-Inszenierung",
            fb_showdown_title = "SHOWDOWN",
            fb_cfg_intro_speed = "Intro-Tempo",
            fb_speed_slow = "Langsam",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Schnell",
            fb_cfg_min_ante = "Boss-Dialoge ab Ante",
            fb_cfg_dev_mode = "Entwicklertasten (F5-F7)",
            fb_cfg_showdown_enabled = "Eigener Showdown-Plan",
            fb_cfg_start_ante = "Erster Showdown im Ante",
            fb_cfg_every = "Danach alle N Antes",
            fb_cfg_preview = "Showdowns in Antes",
            fb_cfg_hard = "Hart! Frühe Showdowns sind brutal.",
            fb_cfg_next_ante = "Gilt ab dem nächsten Ante.",
            fb_cfg_group_dialogue = "Dialoge",
            fb_cfg_group_stage = "Showdown-Bühne",
            fb_credits_thanks = "Danke, dass du mit FinalBoss spielst!",
            fb_credits_lead = "Erstellt und gepflegt von",
            fb_credits_music = "Showdown-Musik:",
            fb_credits_music_by = "Adam Isiah (Orchester-Cover)",
            fb_credits_listen = "Auf YouTube anhören",
            fb_credits_github = "GitHub",
            fb_tip_me = "Trinkgeld geben",
            fb_tip_me_message_1 = "Wenn dir FinalBoss gefällt, gib mir doch",
            fb_tip_me_message_2 = "ein kleines Trinkgeld als Unterstützung.",
            fb_tip_me_message_3 = "Ich freue mich sehr darüber!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Bosse reden zurück, Showdowns werden zu Bosskämpfen.", "Von {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Du bist weit gekommen..."},
            fb_opener_2 = {"Und leider muss ich", "sagen..."},
            fb_opener_3 = {"Na. Du hast es", "geschafft."},
            fb_closer_1 = {"Du wirst mich nicht", "besiegen können."},
            fb_closer_2 = {"Hier endet", "dein Run."},
            fb_closer_3 = {"Zeig mir, was", "du drauf hast."},
            fb_gloat = {"Dieser Boss war", "zu viel..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Ich bin #1#!"},
            fb_generic_name_2 = {"Man nennt mich", "#1#."},
            fb_generic_name_3 = {"Seht her:", "#1#!"},
            fb_generic_intro_1 = {"Dein Glück", "endet hier."},
            fb_generic_intro_2 = {"Mal sehen, ob du", "das packst."},
            fb_generic_intro_3 = {"Lies meine Regeln", "genau..."},
            fb_generic_big_hand_1 = {"...Nicht übel."},
            fb_generic_big_hand_2 = {"Glückshand."},
            fb_generic_big_hand_3 = {"Hmpf. Schon wieder?"},
            fb_generic_close_1 = {"Warte, warte,", "WARTE!"},
            fb_generic_close_2 = {"Wag es ja nicht..."},
            fb_generic_close_3 = {"Das kann nicht sein..."},
            fb_generic_last_hand_1 = {"Noch eine Hand.", "Mach sie zählen."},
            fb_generic_last_hand_2 = {"Tick, tack..."},
            fb_generic_last_hand_3 = {"Letzte Chance,", "kleiner Joker."},
            fb_generic_disabled_1 = {"Meine Kraft...!", "Was hast du getan?"},
            fb_generic_disabled_2 = {"Hey! Das ist", "Betrug!"},
            fb_generic_disabled_3 = {"Ich fühle mich...", "schwach."},
            fb_generic_defeat_1 = {"Unmöglich..."},
            fb_generic_defeat_2 = {"Ich komme wieder,", "nächstes Ante..."},
            fb_generic_defeat_3 = {"Gut gespielt..."},
            fb_generic_gloat_1 = {"Dieser Boss war", "zu viel..."},
            fb_generic_gloat_2 = {"Die Bank", "gewinnt immer."},
            fb_generic_gloat_3 = {"Mehr Glück", "im nächsten Run."},
            fb_generic_interrupted_1 = {"Meine Rede!"},
            fb_generic_interrupted_2 = {"Okay... so läuft", "das also."},
            fb_generic_interrupted_3 = {"Nicht mal ein Hallo?"},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Aber ich bin", "Der Haken"},
            fb_bl_hook_intro_1 = {"Ich nehme mir", "ein paar Karten"},
            fb_bl_hook_intro_2 = {"Zwei Karten weg,", "jede Hand."},
            fb_bl_hook_big_hand_1 = {"Selbst mit weniger", "Karten?!"},
            fb_bl_hook_close_1 = {"Lass meine", "Karten los!"},
            fb_bl_hook_last_hand_1 = {"Endlich hab ich", "dich am Haken!"},
            fb_bl_hook_disabled_1 = {"Mein Haken!", "Er ist kaputt!"},
            fb_bl_hook_defeat_1 = {"Na gut... ich lass", "dich vom Haken."},
            fb_bl_hook_gloat_1 = {"Angebissen!"},
            fb_bl_hook_interrupted_1 = {"Unhöflich! Ich war", "mitten im Satz!"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Aber ich bin", "Der Ochse"},
            fb_bl_ox_intro_1 = {"Ich nehme dir", "all dein Geld"},
            fb_bl_ox_intro_2 = {"Deine Lieblingshand", "kostet dich alles."},
            fb_bl_ox_big_hand_1 = {"Pleite und trotzdem", "gewinnen?!"},
            fb_bl_ox_close_1 = {"Immer mit der Ruhe", "...Auch bei mir."},
            fb_bl_ox_last_hand_1 = {"Letzte Hand. Gib's", "aus oder verlier's."},
            fb_bl_ox_disabled_1 = {"Meine Hörner!", "Sie sind stumpf!"},
            fb_bl_ox_defeat_1 = {"Du hast den Stier", "bei den Hörnern..."},
            fb_bl_ox_gloat_1 = {"Jetzt bist", "du pleite!"},
            fb_bl_ox_interrupted_1 = {"Ach, SO willst du", "es also haben."},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Aber ich bin", "Das Haus"},
            fb_bl_house_intro_1 = {"Du bist", "BLIND!"},
            fb_bl_house_intro_2 = {"Die erste Hand geht", "aufs Haus. Blind!"},
            fb_bl_house_big_hand_1 = {"Blindes Glück und", "du gewinnst?!"},
            fb_bl_house_close_1 = {"Das Haus", "verliert nie!"},
            fb_bl_house_last_hand_1 = {"Kein blindes", "Glück mehr."},
            fb_bl_house_disabled_1 = {"Meine Augenbinde!", "Sie ist runter!"},
            fb_bl_house_defeat_1 = {"Das Haus...", "ist gefallen."},
            fb_bl_house_gloat_1 = {"Das Haus gewinnt!"},
            fb_bl_house_interrupted_1 = {"Hausregel: noch", "nicht spielen!"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Aber ich bin", "Die Mauer"},
            fb_bl_wall_intro_1 = {"Du bist gerade", "gegen eine gerannt"},
            fb_bl_wall_intro_2 = {"Versuch mal, diese", "Punktzahl zu erklimmen."},
            fb_bl_wall_big_hand_1 = {"Du hast meine", "Mauer erklommen?!"},
            fb_bl_wall_close_1 = {"Du kommst nicht", "durch!"},
            fb_bl_wall_last_hand_1 = {"Nichts mehr", "zu erklimmen."},
            fb_bl_wall_disabled_1 = {"Risse! Meine Mauer", "bekommt Risse!"},
            fb_bl_wall_defeat_1 = {"Die Mauer...", "stürzt ein."},
            fb_bl_wall_gloat_1 = {"Gegen die", "Wand, was?"},
            fb_bl_wall_interrupted_1 = {"Wie gegen eine Wand", "reden... Moment."},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Aber ich bin", "Das Rad"},
            fb_bl_wheel_intro_1 = {"Ich liebe...", "GLÜCKSSPIEL!"},
            fb_bl_wheel_intro_2 = {"Jede siebte Karte", "kommt verdeckt."},
            fb_bl_wheel_big_hand_1 = {"Fortuna mag dich", "heute."},
            fb_bl_wheel_close_1 = {"Mein Rad dreht", "durch!"},
            fb_bl_wheel_last_hand_1 = {"Letzte Drehung.", "Fühlst du dich gut?"},
            fb_bl_wheel_disabled_1 = {"Das Rad steht?", "Betrug!"},
            fb_bl_wheel_defeat_1 = {"Das Glücksrad...", "dreht sich gegen mich."},
            fb_bl_wheel_gloat_1 = {"Rad ab,", "Pech gehabt!"},
            fb_bl_wheel_interrupted_1 = {"Langsam! Ich dreh", "mich noch!"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Aber ich bin", "Der Arm"},
            fb_bl_arm_intro_1 = {"Ich gleiche deine", "Macht aus"},
            fb_bl_arm_intro_2 = {"Jede gespielte Hand", "sinkt eine Stufe."},
            fb_bl_arm_big_hand_1 = {"Diese Hand hat", "Muskeln..."},
            fb_bl_arm_close_1 = {"Armdrücken? Ich", "verliere!"},
            fb_bl_arm_last_hand_1 = {"Letzte Hand. Spiel", "nicht den Muskelmann."},
            fb_bl_arm_disabled_1 = {"Mein Arm hängt!", "Betrüger!"},
            fb_bl_arm_defeat_1 = {"Du hast meinen", "starken Arm besiegt."},
            fb_bl_arm_gloat_1 = {"Das war ein", "Abstieg!"},
            fb_bl_arm_interrupted_1 = {"Finger weg! Ich war", "noch am Posen!"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Aber ich bin", "Das Kreuz"},
            fb_bl_club_intro_1 = {"Ich hasse", "{C:green,E:1}Glückspilze{}"},
            fb_bl_club_intro_2 = {"Kreuz ist geschwächt.", "Tut mir leid."},
            fb_bl_club_big_hand_1 = {"Kein Kreuz, kein", "Problem?!"},
            fb_bl_club_close_1 = {"Schlag mich nicht", "damit!"},
            fb_bl_club_last_hand_1 = {"Letzte Hand. Lass", "das Kreuz daheim."},
            fb_bl_club_disabled_1 = {"Mein Kreuz hat", "keinen Biss mehr!"},
            fb_bl_club_defeat_1 = {"Club geschlossen.", "Zeit zu gehen..."},
            fb_bl_club_gloat_1 = {"Eins übergezogen!"},
            fb_bl_club_interrupted_1 = {"Hey! In meinem Club", "rede ich zuerst!"},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Aber ich bin", "Der Fisch"},
            fb_bl_fish_intro_1 = {"Überleg dir gut,", "was du spielst"},
            fb_bl_fish_intro_2 = {"Nach jeder Hand", "kommen Karten verdeckt."},
            fb_bl_fish_big_hand_1 = {"Da ist was faul", "an dieser Hand!"},
            fb_bl_fish_close_1 = {"Zieh mich nicht", "an Land!"},
            fb_bl_fish_last_hand_1 = {"Letzter Wurf.", "Hol ihn ein."},
            fb_bl_fish_disabled_1 = {"Meine Schuppen!", "Sie sind ab!"},
            fb_bl_fish_defeat_1 = {"Eingeholt...", "von einem Profi."},
            fb_bl_fish_gloat_1 = {"Dich hab ich", "nass gemacht!"},
            fb_bl_fish_interrupted_1 = {"Du hast mir die", "Leine gekappt!"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Aber ich bin", "Der Hellseher"},
            fb_bl_psychic_intro_1 = {"Ich hasse", "Unentschlossene"},
            fb_bl_psychic_intro_2 = {"Fünf Karten, nicht", "weniger. Ich sah es."},
            fb_bl_psychic_big_hand_1 = {"Das habe ich NICHT", "kommen sehen."},
            fb_bl_psychic_close_1 = {"Meine Kugel zeigt...", "Niederlage!"},
            fb_bl_psychic_last_hand_1 = {"Ich sehe deine", "letzte Hand."},
            fb_bl_psychic_disabled_1 = {"Meine Visionen!", "Sie sind weg!"},
            fb_bl_psychic_defeat_1 = {"Ich sah es kommen.", "...Oder doch nicht?"},
            fb_bl_psychic_gloat_1 = {"Hab ich's gesehen!"},
            fb_bl_psychic_interrupted_1 = {"Wusste ich's doch.", "...Trotzdem frech."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Aber ich bin", "Der Ansporn"},
            fb_bl_goad_intro_1 = {"Ich hasse", "{C:black,E:1}MACHT{}"},
            fb_bl_goad_intro_2 = {"Piks ist geschwächt.", "Grab tiefer."},
            fb_bl_goad_big_hand_1 = {"Nicht übel ohne", "dein Piks."},
            fb_bl_goad_close_1 = {"Wag es nicht,", "mein Grab zu graben!"},
            fb_bl_goad_last_hand_1 = {"Grab tief. Es ist", "deine letzte Hand."},
            fb_bl_goad_disabled_1 = {"Ich kann niemanden", "mehr anspornen!"},
            fb_bl_goad_defeat_1 = {"Verflixt nochmal,", "du hast gewonnen."},
            fb_bl_goad_gloat_1 = {"Schaufle", "dein Grab!"},
            fb_bl_goad_interrupted_1 = {"Du stichelst MICH?", "Na schön!"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Aber ich bin", "Das Wasser"},
            fb_bl_water_intro_1 = {"Gib mir", "deine Abwürfe"},
            fb_bl_water_intro_2 = {"Keine Abwürfe.", "Nicht ein Tropfen."},
            fb_bl_water_big_hand_1 = {"Keine Abwürfe und", "trotzdem gewonnen?!"},
            fb_bl_water_close_1 = {"Ich ertrinke!", "Wirf mir eine Leine!"},
            fb_bl_water_last_hand_1 = {"Letzte Hand. Schwimm", "oder geh unter."},
            fb_bl_water_disabled_1 = {"Die Abwürfe", "fließen wieder!"},
            fb_bl_water_defeat_1 = {"Ich bin ganz", "ausgetrocknet..."},
            fb_bl_water_gloat_1 = {"Du bist", "abgesoffen!"},
            fb_bl_water_interrupted_1 = {"Unterbrochen?! Gleich", "gehst du baden!"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Aber ich bin", "Das Fenster"},
            fb_bl_window_intro_1 = {"Ich hasse", "{C:yellow,E:1}Kapitalismus{}"},
            fb_bl_window_intro_2 = {"Karo ist geschwächt.", "Glänz weiter."},
            fb_bl_window_big_hand_1 = {"Wer braucht schon", "Karo?"},
            fb_bl_window_close_1 = {"Zerbrich mein", "Fenster nicht!"},
            fb_bl_window_last_hand_1 = {"Letzte Hand. Kein", "Glitzer erlaubt."},
            fb_bl_window_disabled_1 = {"Mein Fenster", "ist zerbrochen!"},
            fb_bl_window_defeat_1 = {"Mein Zeitfenster", "hat sich geschlossen."},
            fb_bl_window_gloat_1 = {"Karo? Geschwächt!"},
            fb_bl_window_interrupted_1 = {"Meine Worte fliegen", "aus dem Fenster?!"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Aber ich bin", "Die Handfessel"},
            fb_bl_manacle_intro_1 = {"Ich nehme dir", "deine {C:blue,E:1}Optionen{}"},
            fb_bl_manacle_intro_2 = {"Eine Karte weniger", "auf der Hand."},
            fb_bl_manacle_big_hand_1 = {"In Ketten und", "trotzdem gewinnen?!"},
            fb_bl_manacle_close_1 = {"Du streifst", "deine Ketten ab!"},
            fb_bl_manacle_last_hand_1 = {"Letzte Hand. Sogar", "in Handschellen."},
            fb_bl_manacle_disabled_1 = {"Die Fesseln!", "Sie sind ab!"},
            fb_bl_manacle_defeat_1 = {"Endlich frei...", "von mir."},
            fb_bl_manacle_gloat_1 = {"Handlungsunfähig!"},
            fb_bl_manacle_interrupted_1 = {"Halt! Dafür leg ich", "dich in Ketten!"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Aber ich bin", "Das Auge"},
            fb_bl_eye_intro_1 = {"Ich mag keine", "Routine"},
            fb_bl_eye_intro_2 = {"Nie dieselbe Hand", "zweimal spielen."},
            fb_bl_eye_big_hand_1 = {"Eine neue Hand?", "Ich seh dich."},
            fb_bl_eye_close_1 = {"Ich kann nicht", "hinsehen!"},
            fb_bl_eye_last_hand_1 = {"Ich sehe deine", "letzte Hand."},
            fb_bl_eye_disabled_1 = {"Mein Auge! Wer hat", "mir reingepikst?!"},
            fb_bl_eye_defeat_1 = {"Aus den Augen,", "aus dem Sinn..."},
            fb_bl_eye_gloat_1 = {"Hab ich's", "nicht gesagt!"},
            fb_bl_eye_interrupted_1 = {"Das hab ich gesehen!", "Wie unhöflich."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Aber ich bin", "Der Mund"},
            fb_bl_mouth_intro_1 = {"Ich liebe", "Routine"},
            fb_bl_mouth_intro_2 = {"Wähl eine Handart", "und bleib dabei."},
            fb_bl_mouth_big_hand_1 = {"Die alte Hand,", "immer noch stark..."},
            fb_bl_mouth_close_1 = {"Mein Mund steht", "weit offen!"},
            fb_bl_mouth_last_hand_1 = {"Letzte Hand. Selbe", "Art. Mund halten."},
            fb_bl_mouth_disabled_1 = {"Wer hat mir den", "Mund verboten?!"},
            fb_bl_mouth_defeat_1 = {"Mir fehlen", "die Worte..."},
            fb_bl_mouth_gloat_1 = {"Klappe, Verlierer!"},
            fb_bl_mouth_interrupted_1 = {"Hey! Dieser Mund", "redet noch!"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Aber ich bin", "Die Pflanze"},
            fb_bl_plant_intro_1 = {"Ich hasse", "freundliche Gesichter"},
            fb_bl_plant_intro_2 = {"Könige, Damen, Buben:", "alle geschwächt."},
            fb_bl_plant_big_hand_1 = {"Ohne Bildkarten?!", "Unglaublich."},
            fb_bl_plant_close_1 = {"Reiß mich nicht", "mit den Wurzeln aus!"},
            fb_bl_plant_last_hand_1 = {"Stell dich deiner", "letzten Hand."},
            fb_bl_plant_disabled_1 = {"Meine Blüten!", "Alle weg!"},
            fb_bl_plant_defeat_1 = {"Verwelkt...", "Ich wachse nach."},
            fb_bl_plant_gloat_1 = {"Sieh's ein,", "verloren!"},
            fb_bl_plant_interrupted_1 = {"Lass mich erst", "wachsen, du Hektiker!"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Aber ich bin", "Die Schlange"},
            fb_bl_serpent_intro_1 = {"Es gibt", "ein Defizit"},
            fb_bl_serpent_intro_2 = {"Spielen oder abwerfen:", "nur 3 Karten."},
            fb_bl_serpent_big_hand_1 = {"Drei Karten. Und du", "hast zugeschlagen!"},
            fb_bl_serpent_close_1 = {"Zieh jetzt nicht", "den Schwanz ein!"},
            fb_bl_serpent_last_hand_1 = {"Letzter Biss.", "Drei Karten."},
            fb_bl_serpent_disabled_1 = {"Meine Zähne! Zisch...", "Kein Gift mehr!"},
            fb_bl_serpent_defeat_1 = {"Haut abgestreift...", "und Stolz verloren."},
            fb_bl_serpent_gloat_1 = {"Auf Wiedersssehen!"},
            fb_bl_serpent_interrupted_1 = {"Zisch! Fall mir", "nicht ins Wort!"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Aber ich bin", "Die Säule"},
            fb_bl_pillar_intro_1 = {"Ich habe viel aus", "deinen Händen gelernt"},
            fb_bl_pillar_intro_2 = {"Gespielte Karten", "bleiben geschwächt."},
            fb_bl_pillar_big_hand_1 = {"Frische Karten?", "Clever."},
            fb_bl_pillar_close_1 = {"Meine Säule", "bröckelt!"},
            fb_bl_pillar_last_hand_1 = {"Letzte Hand. Alte", "Karten sind nutzlos."},
            fb_bl_pillar_disabled_1 = {"Mein Gedächtnis!", "Es... schwindet."},
            fb_bl_pillar_defeat_1 = {"Eine Säule der", "Gemeinschaft fällt."},
            fb_bl_pillar_gloat_1 = {"Ich steh noch!"},
            fb_bl_pillar_interrupted_1 = {"Hast du keinen Respekt", "vor dem Alter?"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Aber ich bin", "Die Nadel"},
            fb_bl_needle_intro_1 = {"Du hast nur", "eine Chance"},
            fb_bl_needle_intro_2 = {"Eine Hand. Mehr", "bekommst du nicht."},
            fb_bl_needle_big_hand_1 = {"Eine einzige Hand,", "so stark?!"},
            fb_bl_needle_close_1 = {"Nein! Nicht mit", "einer Hand!"},
            fb_bl_needle_last_hand_1 = {"Diese Hand ist", "deine einzige."},
            fb_bl_needle_disabled_1 = {"Meine Nadel!", "Sie ist stumpf!"},
            fb_bl_needle_defeat_1 = {"Scharf gespielt.", "Du hast mich."},
            fb_bl_needle_gloat_1 = {"Der Punkt", "geht an mich!"},
            fb_bl_needle_interrupted_1 = {"Wie spitz.", "Ich war nicht fertig!"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Aber ich bin", "Der Kopf"},
            fb_bl_head_intro_1 = {"Ich hasse", "{C:red,E:1}Verliebte{}"},
            fb_bl_head_intro_2 = {"Herz ist geschwächt.", "Kalt, oder?"},
            fb_bl_head_big_hand_1 = {"Du hast ohne Herz", "gewonnen?!"},
            fb_bl_head_close_1 = {"Hab ein Herz,", "mach mich nicht fertig!"},
            fb_bl_head_last_hand_1 = {"Letzte Hand. Kein", "Herz. Keine Gnade."},
            fb_bl_head_disabled_1 = {"Mein Kopf brummt!", "Herz geht wieder?"},
            fb_bl_head_defeat_1 = {"Kopf verloren...", "wegen dir."},
            fb_bl_head_gloat_1 = {"Herzlos, was?"},
            fb_bl_head_interrupted_1 = {"Hast du den Kopf", "verloren? Ich rede!"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Aber ich bin", "Der Zahn"},
            fb_bl_tooth_intro_1 = {"Ich steh auf", "Politik"},
            fb_bl_tooth_intro_2 = {"Jede gespielte Karte", "kostet dich $1."},
            fb_bl_tooth_big_hand_1 = {"Du hast gezahlt und", "trotzdem gewonnen?!"},
            fb_bl_tooth_close_1 = {"Zwing mich nicht,", "zur Zahnfee zu gehen!"},
            fb_bl_tooth_last_hand_1 = {"Letzte Hand,", "letzte Dollar."},
            fb_bl_tooth_disabled_1 = {"Mein Biss!", "Er ist weg!"},
            fb_bl_tooth_defeat_1 = {"Mit Zähnen und", "Klauen verloren."},
            fb_bl_tooth_gloat_1 = {"Zahl, du Trottel!"},
            fb_bl_tooth_interrupted_1 = {"Grr! Dafür wirst", "du bezahlen!"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Aber ich bin", "Der Feuerstein"},
            fb_bl_flint_intro_1 = {"Du musst", "Steuern zahlen"},
            fb_bl_flint_intro_2 = {"Chips und Mult", "werden halbiert."},
            fb_bl_flint_big_hand_1 = {"Halbe Kraft, und", "trotzdem ein Treffer?!"},
            fb_bl_flint_close_1 = {"Du zündest meinen", "Untergang!"},
            fb_bl_flint_last_hand_1 = {"Letzte Hand. Halber", "Funke."},
            fb_bl_flint_disabled_1 = {"Volle Kraft?!", "Unfair!"},
            fb_bl_flint_defeat_1 = {"Mein Funke", "ist erloschen."},
            fb_bl_flint_gloat_1 = {"Halber Spaß!"},
            fb_bl_flint_interrupted_1 = {"Funk mir nicht", "dazwischen!"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Aber ich bin", "Die Marke"},
            fb_bl_mark_intro_1 = {"Ich will nicht", "gesehen werden"},
            fb_bl_mark_intro_2 = {"Alle Bildkarten", "kommen verdeckt."},
            fb_bl_mark_big_hand_1 = {"Markierte Karten,", "trotzdem gewonnen?!"},
            fb_bl_mark_close_1 = {"Ich bin zur", "Niederlage markiert!"},
            fb_bl_mark_last_hand_1 = {"Letzte Hand. Wähl", "Gesichter blind."},
            fb_bl_mark_disabled_1 = {"Die Gesichter!", "Ich sehe sie!"},
            fb_bl_mark_defeat_1 = {"Du hast deine Marke", "bei mir gesetzt."},
            fb_bl_mark_gloat_1 = {"Zum Verlieren", "markiert!"},
            fb_bl_mark_interrupted_1 = {"Notiert. Du bist", "jetzt gezeichnet."},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Aber ich bin", "Bernsteineichel"},
            fb_bl_final_acorn_intro_1 = {"Ich mag", "CHAOS!"},
            fb_bl_final_acorn_intro_2 = {"Joker verdeckt,", "dann gemischt!"},
            fb_bl_final_acorn_big_hand_1 = {"Sogar im Chaos", "gewinnst du?!"},
            fb_bl_final_acorn_close_1 = {"Das ist verrückt!", "Ich knacke!"},
            fb_bl_final_acorn_last_hand_1 = {"Letzte Hand. Wo ist", "dein Joker?"},
            fb_bl_final_acorn_disabled_1 = {"Meine Eichel!", "Ordnung kehrt zurück?!"},
            fb_bl_final_acorn_defeat_1 = {"Du hast meine", "Schale geknackt..."},
            fb_bl_final_acorn_gloat_1 = {"Total eichelhart!"},
            fb_bl_final_acorn_interrupted_1 = {"Harte Nuss, was?", "Ich war nicht fertig!"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Aber ich bin", "Grünes Blatt"},
            fb_bl_final_leaf_intro_1 = {"Du musst dich von", "deinen Wurzeln lösen"},
            fb_bl_final_leaf_intro_2 = {"Verkauf einen Joker", "oder bleib geschwächt."},
            fb_bl_final_leaf_big_hand_1 = {"Du hast ein neues", "Blatt gewendet. Hmpf."},
            fb_bl_final_leaf_close_1 = {"Mein Blatt", "fällt!"},
            fb_bl_final_leaf_last_hand_1 = {"Letzte Hand.", "Joker verkaufen?"},
            fb_bl_final_leaf_disabled_1 = {"Mein Blatt! Es ist", "verwelkt!"},
            fb_bl_final_leaf_defeat_1 = {"Ich geh dahin...", "wie ein Blatt im Wind."},
            fb_bl_final_leaf_gloat_1 = {"Blatt-ant", "verloren!"},
            fb_bl_final_leaf_interrupted_1 = {"Schön. Spar dir die", "Höflichkeiten."},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Aber ich bin", "Violette Hülle"},
            fb_bl_final_vessel_intro_1 = {"Du bist gegen die", "große Mauer gerannt"},
            fb_bl_final_vessel_intro_2 = {"Eine riesige Blind.", "Setz die Segel!"},
            fb_bl_final_vessel_big_hand_1 = {"Ein Riesentreffer", "auf ein Riesenziel."},
            fb_bl_final_vessel_close_1 = {"Alle von Bord!", "...Meine, meine ich."},
            fb_bl_final_vessel_last_hand_1 = {"Letzte Hand. Dieses", "Schiff sinkt nicht."},
            fb_bl_final_vessel_disabled_1 = {"Meine Hülle!", "Sie sinkt!"},
            fb_bl_final_vessel_defeat_1 = {"Die Hülle...", "ist geleert."},
            fb_bl_final_vessel_gloat_1 = {"Riesen-Niederlage!"},
            fb_bl_final_vessel_interrupted_1 = {"Ablegen vor meiner", "Rede? Kühn."},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Aber ich bin", "Purpurrotes Herz"},
            fb_bl_final_heart_intro_1 = {"Ich leihe mir", "einen Joker"},
            fb_bl_final_heart_intro_2 = {"Jede Hand verliert", "ein Joker seine Kraft."},
            fb_bl_final_heart_big_hand_1 = {"Ein Joker weniger", "und trotzdem stark?"},
            fb_bl_final_heart_close_1 = {"Brich mir nicht", "das Herz!"},
            fb_bl_final_heart_last_hand_1 = {"Letzte Hand. Welcher", "Joker schweigt?"},
            fb_bl_final_heart_disabled_1 = {"Mein Herz! Es hat", "einen Schlag verpasst."},
            fb_bl_final_heart_defeat_1 = {"Mein Herz...", "ist gebrochen."},
            fb_bl_final_heart_gloat_1 = {"Schon", "Liebeskummer?"},
            fb_bl_final_heart_interrupted_1 = {"Du fällst mir ins Wort?", "Wie herzlos!"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Aber ich bin", "Himmelblaue Glocke"},
            fb_bl_final_bell_intro_1 = {"Ich möchte dich", "gern leiten"},
            fb_bl_final_bell_intro_2 = {"Eine Karte steckt", "in jeder Hand."},
            fb_bl_final_bell_big_hand_1 = {"Du bringst meine", "Zwangskarte zum Klingen?!"},
            fb_bl_final_bell_close_1 = {"Die Glocke läutet...", "für mich?!"},
            fb_bl_final_bell_last_hand_1 = {"Letzte Hand. Eine", "Karte ist Pflicht."},
            fb_bl_final_bell_disabled_1 = {"Meine Glocke schweigt!", "Betrüger!"},
            fb_bl_final_bell_defeat_1 = {"Die Glocke läutet", "für mich."},
            fb_bl_final_bell_gloat_1 = {"Ding dong,", "verloren!"},
            fb_bl_final_bell_interrupted_1 = {"Gerettet vom Gong?", "Diesmal nicht!"},
        }
    }
}
