return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Showdowns",
            fb_cfg_dialogue = "Boss dialogue",
            fb_cfg_music = "Showdown music",
            fb_cfg_fx = "Screen effects",
            fb_cfg_intro_speed = "Intro speed",
            fb_speed_slow = "Slow",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Fast",
            fb_cfg_min_ante = "Boss dialogue from ante",
            fb_cfg_dev_mode = "Developer keys (F5-F7)",
            fb_cfg_showdown_enabled = "Custom showdown schedule",
            fb_cfg_start_ante = "First showdown ante",
            fb_cfg_every = "Then every N antes",
            fb_cfg_preview = "Showdowns at antes:",
            fb_cfg_hard = "Hard! Early showdowns are brutal.",
            fb_cfg_next_ante = "Changes apply from the next ante.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"You've come too far..."},
            fb_opener_2 = {"And I'm sorry to say..."},
            fb_opener_3 = {"So. You made it."},
            fb_closer_1 = {"You will not be", "able to beat me."},
            fb_closer_2 = {"This is where", "your run ends."},
            fb_closer_3 = {"Show me what", "you've got."},
            fb_gloat = {"That boss was", "too much..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"I am #1#!"},
            fb_generic_name_2 = {"They call me", "#1#."},
            fb_generic_name_3 = {"Behold:", "#1#!"},
            fb_generic_intro_1 = {"Your luck", "ends here."},
            fb_generic_intro_2 = {"Let's see you", "handle this."},
            fb_generic_intro_3 = {"Read my rules", "carefully..."},
            fb_generic_big_hand_1 = {"...Not bad."},
            fb_generic_big_hand_2 = {"Lucky hand."},
            fb_generic_big_hand_3 = {"Hmph. Again?"},
            fb_generic_close_1 = {"Wait, wait,", "WAIT!"},
            fb_generic_close_2 = {"Don't you dare..."},
            fb_generic_close_3 = {"This can't be..."},
            fb_generic_last_hand_1 = {"One hand left.", "Make it count."},
            fb_generic_last_hand_2 = {"Tick, tock..."},
            fb_generic_last_hand_3 = {"Last chance,", "little joker."},
            fb_generic_disabled_1 = {"My power...!", "What did you do?"},
            fb_generic_disabled_2 = {"Hey! That's", "cheating!"},
            fb_generic_disabled_3 = {"I feel... weak."},
            fb_generic_defeat_1 = {"Impossible..."},
            fb_generic_defeat_2 = {"I'll be back", "next ante..."},
            fb_generic_defeat_3 = {"Well played..."},
            fb_generic_gloat_1 = {"That boss was", "too much..."},
            fb_generic_gloat_2 = {"The house", "always wins."},
            fb_generic_gloat_3 = {"Better luck", "next run."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"But I'm The Hook"},
            fb_bl_hook_intro_1 = {"I'm taking some", "of your cards"},
            fb_bl_hook_intro_2 = {"Two cards gone,", "every hand."},
            fb_bl_hook_big_hand_1 = {"Even with fewer", "cards?!"},
            fb_bl_hook_close_1 = {"Let go of", "those cards!"},
            fb_bl_hook_last_hand_1 = {"Hooked you", "at last!"},
            fb_bl_hook_disabled_1 = {"My hook!", "It's broken!"},
            fb_bl_hook_defeat_1 = {"Fine... I'll", "let you go."},
            fb_bl_hook_gloat_1 = {"The Hook:", "\"Got you hooked!\""},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"But I'm The Ox"},
            fb_bl_ox_intro_1 = {"I'm taking", "all your money"},
            fb_bl_ox_intro_2 = {"Your favorite hand", "costs you it all."},
            fb_bl_ox_big_hand_1 = {"Whoa! That hand", "was no bull!"},
            fb_bl_ox_close_1 = {"Hold your horses!", "...Mine too."},
            fb_bl_ox_last_hand_1 = {"Last hand. Spend", "it or lose it."},
            fb_bl_ox_disabled_1 = {"My horns!", "They went dull!"},
            fb_bl_ox_defeat_1 = {"You took the bull", "by the horns..."},
            fb_bl_ox_gloat_1 = {"The Ox:", "\"Now you're broke!\""},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"But I'm The House"},
            fb_bl_house_intro_1 = {"You are", "BLIND!"},
            fb_bl_house_intro_2 = {"First hand's on", "the house. Blind!"},
            fb_bl_house_big_hand_1 = {"Blind luck and", "you still won?!"},
            fb_bl_house_close_1 = {"The house", "never loses!"},
            fb_bl_house_last_hand_1 = {"No more", "blind luck."},
            fb_bl_house_disabled_1 = {"My blindfold!", "It fell off!"},
            fb_bl_house_defeat_1 = {"The house...", "has fallen."},
            fb_bl_house_gloat_1 = {"The House:", "\"The house wins!\""},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"But I'm The Wall"},
            fb_bl_wall_intro_1 = {"You just", "hit one"},
            fb_bl_wall_intro_2 = {"Try climbing", "this score."},
            fb_bl_wall_big_hand_1 = {"You scaled", "my wall?!"},
            fb_bl_wall_close_1 = {"You can't", "break through!"},
            fb_bl_wall_last_hand_1 = {"Nowhere left", "to climb."},
            fb_bl_wall_disabled_1 = {"Cracks! My wall", "is cracking!"},
            fb_bl_wall_defeat_1 = {"The wall...", "comes tumbling."},
            fb_bl_wall_gloat_1 = {"The Wall:", "\"Hit a wall, huh?\""},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"But I'm The Wheel"},
            fb_bl_wheel_intro_1 = {"I like...", "GAMBLING!"},
            fb_bl_wheel_intro_2 = {"One in seven cards", "comes face down."},
            fb_bl_wheel_big_hand_1 = {"Lady Luck loves", "you today."},
            fb_bl_wheel_close_1 = {"My wheel's", "spinning out!"},
            fb_bl_wheel_last_hand_1 = {"Last spin.", "Feeling lucky?"},
            fb_bl_wheel_disabled_1 = {"The wheel stopped?", "Rigged!"},
            fb_bl_wheel_defeat_1 = {"Wheel of fortune...", "turns on me."},
            fb_bl_wheel_gloat_1 = {"The Wheel:", "\"Wheel, that's that!\""},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"But I'm The Arm"},
            fb_bl_arm_intro_1 = {"I'm gonna balance", "your power"},
            fb_bl_arm_intro_2 = {"Every hand you play", "loses a level."},
            fb_bl_arm_big_hand_1 = {"That hand has", "some muscle..."},
            fb_bl_arm_close_1 = {"Arm wrestling?", "I'm losing!"},
            fb_bl_arm_last_hand_1 = {"One last hand.", "Don't flex it."},
            fb_bl_arm_disabled_1 = {"My arm went limp!", "Cheater!"},
            fb_bl_arm_defeat_1 = {"You've bested", "my strong arm."},
            fb_bl_arm_gloat_1 = {"The Arm:", "\"That's a downgrade!\""},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"But I'm The Club"},
            fb_bl_club_intro_1 = {"I hate", "{C:green,E:1}lucky{} players"},
            fb_bl_club_intro_2 = {"Clubs are", "debuffed. Sorry."},
            fb_bl_club_big_hand_1 = {"No clubs, no", "problem?!"},
            fb_bl_club_close_1 = {"Don't club me", "with that!"},
            fb_bl_club_last_hand_1 = {"Last hand. Leave", "the clubs home."},
            fb_bl_club_disabled_1 = {"My clubs lost", "their bite!"},
            fb_bl_club_defeat_1 = {"Club closed.", "Time to go..."},
            fb_bl_club_gloat_1 = {"The Club:", "\"Club'd you good!\""},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"But I'm The Fish"},
            fb_bl_fish_intro_1 = {"Be sure what", "you want to play"},
            fb_bl_fish_intro_2 = {"After each hand,", "cards come face down."},
            fb_bl_fish_big_hand_1 = {"Something's fishy", "about that hand!"},
            fb_bl_fish_close_1 = {"Don't reel me in!"},
            fb_bl_fish_last_hand_1 = {"Last cast.", "Reel it in."},
            fb_bl_fish_disabled_1 = {"My scales!", "They fell off!"},
            fb_bl_fish_defeat_1 = {"Reeled in...", "by a pro."},
            fb_bl_fish_gloat_1 = {"The Fish:", "\"You're all wet!\""},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"But I'm The Psychic"},
            fb_bl_psychic_intro_1 = {"I hate", "undecided players"},
            fb_bl_psychic_intro_2 = {"Five cards, no", "less. I foresaw it."},
            fb_bl_psychic_big_hand_1 = {"I did NOT", "see that coming."},
            fb_bl_psychic_close_1 = {"My crystal ball", "shows... defeat!"},
            fb_bl_psychic_last_hand_1 = {"I foresee your", "last hand."},
            fb_bl_psychic_disabled_1 = {"My visions!", "They're gone!"},
            fb_bl_psychic_defeat_1 = {"I saw this coming.", "...Or did I?"},
            fb_bl_psychic_gloat_1 = {"The Psychic:", "\"Saw that coming!\""},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"But I'm The Goad"},
            fb_bl_goad_intro_1 = {"I hate", "{C:black,E:1}POWER{}"},
            fb_bl_goad_intro_2 = {"Spades are debuffed.", "Dig deeper."},
            fb_bl_goad_big_hand_1 = {"Not bad without", "your spades."},
            fb_bl_goad_close_1 = {"Don't you dare", "dig my grave!"},
            fb_bl_goad_last_hand_1 = {"Dig deep. It's", "your last hand."},
            fb_bl_goad_disabled_1 = {"I can't goad", "anyone now!"},
            fb_bl_goad_defeat_1 = {"Call a spade a spade:", "I got outplayed."},
            fb_bl_goad_gloat_1 = {"The Goad:", "\"Dig your own grave!\""},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"But I'm The Water"},
            fb_bl_water_intro_1 = {"Give me", "your discards"},
            fb_bl_water_intro_2 = {"No discards.", "Not even a drop."},
            fb_bl_water_big_hand_1 = {"No discards and", "still won?!"},
            fb_bl_water_close_1 = {"I'm drowning!", "Throw me a line!"},
            fb_bl_water_last_hand_1 = {"Last hand. Sink", "or swim."},
            fb_bl_water_disabled_1 = {"My drought?!", "It's over?!"},
            fb_bl_water_defeat_1 = {"I'm all dried up..."},
            fb_bl_water_gloat_1 = {"The Water:", "\"You're all washed up!\""},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"But I'm The Window"},
            fb_bl_window_intro_1 = {"I hate", "{C:yellow,E:1}capitalism{}"},
            fb_bl_window_intro_2 = {"Diamonds are debuffed.", "Shine on."},
            fb_bl_window_big_hand_1 = {"Who needs diamonds", "anyway?"},
            fb_bl_window_close_1 = {"Don't break", "my window!"},
            fb_bl_window_last_hand_1 = {"Last hand. No", "bling allowed."},
            fb_bl_window_disabled_1 = {"My window cracked!", "Diamonds shine!"},
            fb_bl_window_defeat_1 = {"My window of", "opportunity shut."},
            fb_bl_window_gloat_1 = {"The Window:", "\"Diamonds? Debuffed!\""},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"But I'm The Manacle"},
            fb_bl_manacle_intro_1 = {"I'm taking", "your {C:blue,E:1}options{}"},
            fb_bl_manacle_intro_2 = {"One card fewer", "in your hand."},
            fb_bl_manacle_big_hand_1 = {"Chained down and", "still winning?!"},
            fb_bl_manacle_close_1 = {"You're slipping", "your chains!"},
            fb_bl_manacle_last_hand_1 = {"Last hand. In", "chains, no less."},
            fb_bl_manacle_disabled_1 = {"The shackles!", "They came off!"},
            fb_bl_manacle_defeat_1 = {"Free at last...", "of me."},
            fb_bl_manacle_gloat_1 = {"The Manacle:", "\"Hand-cuffed you!\""},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"But I'm The Eye"},
            fb_bl_eye_intro_1 = {"I don't", "like routine"},
            fb_bl_eye_intro_2 = {"Never play the same", "hand type twice."},
            fb_bl_eye_big_hand_1 = {"A new hand, huh?", "I see you."},
            fb_bl_eye_close_1 = {"I can't bear", "to watch!"},
            fb_bl_eye_last_hand_1 = {"Eye spy your", "last hand."},
            fb_bl_eye_disabled_1 = {"My eye! Who", "poked my eye?!"},
            fb_bl_eye_defeat_1 = {"Out of sight,", "out of mind..."},
            fb_bl_eye_gloat_1 = {"The Eye:", "\"Eye told you so!\""},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"But I'm The Mouth"},
            fb_bl_mouth_intro_1 = {"I love", "routine"},
            fb_bl_mouth_intro_2 = {"Pick one hand type", "and stick to it."},
            fb_bl_mouth_big_hand_1 = {"Same old hand,", "still strong..."},
            fb_bl_mouth_close_1 = {"My mouth is", "wide open!"},
            fb_bl_mouth_last_hand_1 = {"Last hand. Same", "type. Zip it."},
            fb_bl_mouth_disabled_1 = {"Who muzzled me?!"},
            fb_bl_mouth_defeat_1 = {"I'm speechless..."},
            fb_bl_mouth_gloat_1 = {"The Mouth:", "\"Zip it, loser!\""},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"But I'm The Plant"},
            fb_bl_plant_intro_1 = {"I hate", "friendly faces"},
            fb_bl_plant_intro_2 = {"Kings, queens, jacks:", "all debuffed."},
            fb_bl_plant_big_hand_1 = {"Without face cards?!", "Unbelievable."},
            fb_bl_plant_close_1 = {"Don't pull me", "up by the roots!"},
            fb_bl_plant_last_hand_1 = {"Face your", "last hand."},
            fb_bl_plant_disabled_1 = {"My petals!", "They're all gone!"},
            fb_bl_plant_defeat_1 = {"Wilted...", "I'll grow back."},
            fb_bl_plant_gloat_1 = {"The Plant:", "\"Face it, you lost!\""},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"But I'm The Serpent"},
            fb_bl_serpent_intro_1 = {"There is", "a deficit"},
            fb_bl_serpent_intro_2 = {"Play or discard,", "you draw only 3."},
            fb_bl_serpent_big_hand_1 = {"Three cards. And", "you still struck!"},
            fb_bl_serpent_close_1 = {"Don't snake out", "on me now!"},
            fb_bl_serpent_last_hand_1 = {"Last hand. Strike", "now or never."},
            fb_bl_serpent_disabled_1 = {"My fangs! Hiss...", "No venom left!"},
            fb_bl_serpent_defeat_1 = {"Shed my skin...", "and my pride."},
            fb_bl_serpent_gloat_1 = {"The Serpent:", "\"Sss-ee you later!\""},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"But I'm The Pillar"},
            fb_bl_pillar_intro_1 = {"I learned a lot", "from your past hands"},
            fb_bl_pillar_intro_2 = {"Played cards stay", "debuffed this ante."},
            fb_bl_pillar_big_hand_1 = {"Fresh cards?", "Smart."},
            fb_bl_pillar_close_1 = {"My pillar is", "crumbling!"},
            fb_bl_pillar_last_hand_1 = {"Last hand. Old", "cards are useless."},
            fb_bl_pillar_disabled_1 = {"My memory!", "It's... fading."},
            fb_bl_pillar_defeat_1 = {"A pillar of the", "community, fallen."},
            fb_bl_pillar_gloat_1 = {"The Pillar:", "\"Past hands? Rubble!\""},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"But I'm The Needle"},
            fb_bl_needle_intro_1 = {"You got only", "one chance"},
            fb_bl_needle_intro_2 = {"One hand. That's", "all you get."},
            fb_bl_needle_big_hand_1 = {"A single hand,", "that strong?!"},
            fb_bl_needle_close_1 = {"No! Not with", "one hand!"},
            fb_bl_needle_last_hand_1 = {"This hand is", "your only hand."},
            fb_bl_needle_disabled_1 = {"My needle!", "It's blunt!"},
            fb_bl_needle_defeat_1 = {"Sharp play.", "You got me."},
            fb_bl_needle_gloat_1 = {"The Needle:", "\"Point is, you lost!\""},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"But I'm The Head"},
            fb_bl_head_intro_1 = {"I hate", "{C:red,E:1}lovers{}"},
            fb_bl_head_intro_2 = {"Hearts are debuffed.", "Cold, isn't it?"},
            fb_bl_head_big_hand_1 = {"You won without", "heart?!"},
            fb_bl_head_close_1 = {"Have a heart,", "don't finish me!"},
            fb_bl_head_last_hand_1 = {"Last hand. No", "hearts. No mercy."},
            fb_bl_head_disabled_1 = {"My head hurts!", "Hearts work again?"},
            fb_bl_head_defeat_1 = {"Lost my head...", "over you."},
            fb_bl_head_gloat_1 = {"The Head:", "\"Heartless, huh?\""},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"But I'm The Tooth"},
            fb_bl_tooth_intro_1 = {"I'm into", "politics"},
            fb_bl_tooth_intro_2 = {"Every card you play", "costs you $1."},
            fb_bl_tooth_big_hand_1 = {"You paid and", "still won?!"},
            fb_bl_tooth_close_1 = {"Stop! You're", "pulling my teeth!"},
            fb_bl_tooth_last_hand_1 = {"Last hand,", "last dollars."},
            fb_bl_tooth_disabled_1 = {"My bite!", "It's gone!"},
            fb_bl_tooth_defeat_1 = {"Tooth and nail,", "I lost."},
            fb_bl_tooth_gloat_1 = {"The Tooth:", "\"Pay up, sucker!\""},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"But I'm The Flint"},
            fb_bl_flint_intro_1 = {"You must", "pay taxes"},
            fb_bl_flint_intro_2 = {"Base Chips & Mult", "are halved."},
            fb_bl_flint_big_hand_1 = {"Half the power,", "still a hit?!"},
            fb_bl_flint_close_1 = {"You're sparking", "my downfall!"},
            fb_bl_flint_last_hand_1 = {"Last hand. Half", "the spark."},
            fb_bl_flint_disabled_1 = {"Full power?!", "Not fair!"},
            fb_bl_flint_defeat_1 = {"My spark", "is out."},
            fb_bl_flint_gloat_1 = {"The Flint:", "\"Half the fun!\""},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"But I'm The Mark"},
            fb_bl_mark_intro_1 = {"I don't like", "to be seen"},
            fb_bl_mark_intro_2 = {"All face cards", "arrive face down."},
            fb_bl_mark_big_hand_1 = {"Marked cards,", "still a win?!"},
            fb_bl_mark_close_1 = {"I'm marked", "for defeat!"},
            fb_bl_mark_last_hand_1 = {"Last hand. Pick", "faces blindly."},
            fb_bl_mark_disabled_1 = {"The faces!", "I can see them!"},
            fb_bl_mark_defeat_1 = {"You've made your", "mark on me."},
            fb_bl_mark_gloat_1 = {"The Mark:", "\"Marked for loss!\""},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"But I'm Amber Acorn"},
            fb_bl_final_acorn_intro_1 = {"I like", "CHAOS!"},
            fb_bl_final_acorn_intro_2 = {"Jokers face down,", "then shuffled!"},
            fb_bl_final_acorn_big_hand_1 = {"Even in chaos,", "you win?!"},
            fb_bl_final_acorn_close_1 = {"This is nuts!", "I'm cracking!"},
            fb_bl_final_acorn_last_hand_1 = {"Last hand. Where", "is your joker?"},
            fb_bl_final_acorn_disabled_1 = {"My acorn!", "Order restored?!"},
            fb_bl_final_acorn_defeat_1 = {"You cracked", "my shell..."},
            fb_bl_final_acorn_gloat_1 = {"Amber Acorn:", "\"Totally nuts!\""},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"But I'm Verdant Leaf"},
            fb_bl_final_leaf_intro_1 = {"You must detach", "from your roots"},
            fb_bl_final_leaf_intro_2 = {"Sell a joker, or", "stay debuffed."},
            fb_bl_final_leaf_big_hand_1 = {"You turned a new", "leaf. Hmph."},
            fb_bl_final_leaf_close_1 = {"My leaf is", "falling!"},
            fb_bl_final_leaf_last_hand_1 = {"Last hand. Sell", "a joker?"},
            fb_bl_final_leaf_disabled_1 = {"My leaf! It", "withered away!"},
            fb_bl_final_leaf_defeat_1 = {"I'm leaving...", "like a leaf."},
            fb_bl_final_leaf_gloat_1 = {"Verdant Leaf:", "\"Leaf it to me!\""},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"But I'm Violet Vessel"},
            fb_bl_final_vessel_intro_1 = {"You just hit", "the great wall"},
            fb_bl_final_vessel_intro_2 = {"A truly vast blind.", "Sail on!"},
            fb_bl_final_vessel_big_hand_1 = {"A huge hit on", "a huge target."},
            fb_bl_final_vessel_close_1 = {"Abandon ship!", "...Mine, that is."},
            fb_bl_final_vessel_last_hand_1 = {"Last hand. This", "ship won't sink."},
            fb_bl_final_vessel_disabled_1 = {"My vessel!", "It's sinking!"},
            fb_bl_final_vessel_defeat_1 = {"The vessel...", "has been emptied."},
            fb_bl_final_vessel_gloat_1 = {"Violet Vessel:", "\"Vast defeat, huh?\""},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"But I'm Crimson Heart"},
            fb_bl_final_heart_intro_1 = {"I will borrow", "a joker"},
            fb_bl_final_heart_intro_2 = {"Each hand, a joker", "loses its power."},
            fb_bl_final_heart_big_hand_1 = {"A joker down and", "still strong?"},
            fb_bl_final_heart_close_1 = {"Don't break", "my heart!"},
            fb_bl_final_heart_last_hand_1 = {"Last hand. Which", "joker's silenced?"},
            fb_bl_final_heart_disabled_1 = {"My heart! It's", "skipped a beat."},
            fb_bl_final_heart_defeat_1 = {"My heart...", "is broken."},
            fb_bl_final_heart_gloat_1 = {"Crimson Heart:", "\"Heart-broken yet?\""},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"But I'm Cerulean Bell"},
            fb_bl_final_bell_intro_1 = {"I'd like", "to guide you"},
            fb_bl_final_bell_intro_2 = {"One card is forced", "into every hand."},
            fb_bl_final_bell_big_hand_1 = {"You made my forced", "card sing?!"},
            fb_bl_final_bell_close_1 = {"The bell tolls...", "for me?!"},
            fb_bl_final_bell_last_hand_1 = {"Last hand. One", "card is forced."},
            fb_bl_final_bell_disabled_1 = {"My bell is silent!", "Cheater!"},
            fb_bl_final_bell_defeat_1 = {"Cerulean silence...", "I'm done ringing."},
            fb_bl_final_bell_gloat_1 = {"Cerulean Bell:", "\"Ding dong, you lost!\""},
        }
    }
}
