return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Enfrentamientos",
            fb_cfg_dialogue = "Diálogo de jefes",
            fb_cfg_music = "Música de enfrentamientos",
            fb_cfg_fx = "Efectos de pantalla",
            fb_cfg_intro_speed = "Velocidad de la intro",
            fb_speed_slow = "Lenta",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Rápida",
            fb_cfg_min_ante = "Diálogo desde apuesta inicial",
            fb_cfg_dev_mode = "Teclas de desarrollo (F5-F7)",
            fb_cfg_showdown_enabled = "Enfrentamientos personalizados",
            fb_cfg_start_ante = "Primer enfrentamiento: apuesta inicial",
            fb_cfg_every = "Luego cada N apuestas iniciales",
            fb_cfg_preview = "Enfrentamientos en apuestas iniciales:",
            fb_cfg_hard = "¡Difícil! Los enfrentamientos tempranos son brutales.",
            fb_cfg_next_ante = "Los cambios aplican desde la próxima apuesta inicial.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Llegaste muy lejos..."},
            fb_opener_2 = {"Y lamento decirte..."},
            fb_opener_3 = {"Así que... lo lograste."},
            fb_closer_1 = {"No vas a", "poder vencerme."},
            fb_closer_2 = {"Aquí termina", "tu partida."},
            fb_closer_3 = {"Muéstrame de", "qué estás hecho."},
            fb_gloat = {"Ese jefe fue", "demasiado..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"¡Soy #1#!"},
            fb_generic_name_2 = {"Me llaman", "#1#."},
            fb_generic_name_3 = {"Contempla:", "¡#1#!"},
            fb_generic_intro_1 = {"Tu suerte", "se acaba aquí."},
            fb_generic_intro_2 = {"A ver cómo", "manejas esto."},
            fb_generic_intro_3 = {"Lee mis reglas", "con cuidado..."},
            fb_generic_big_hand_1 = {"...Nada mal."},
            fb_generic_big_hand_2 = {"Mano con suerte."},
            fb_generic_big_hand_3 = {"Hmph. ¿Otra vez?"},
            fb_generic_close_1 = {"¡Espera, espera,", "ESPERA!"},
            fb_generic_close_2 = {"No te atrevas..."},
            fb_generic_close_3 = {"Esto no puede ser..."},
            fb_generic_last_hand_1 = {"Una mano más.", "Que cuente."},
            fb_generic_last_hand_2 = {"Tic, tac..."},
            fb_generic_last_hand_3 = {"Última oportunidad,", "pequeño comodín."},
            fb_generic_disabled_1 = {"¡Mi poder...!", "¿Qué hiciste?"},
            fb_generic_disabled_2 = {"¡Oye! ¡Eso es", "trampa!"},
            fb_generic_disabled_3 = {"Me siento... débil."},
            fb_generic_defeat_1 = {"Imposible..."},
            fb_generic_defeat_2 = {"Volveré en la siguiente", "apuesta inicial..."},
            fb_generic_defeat_3 = {"Bien jugado..."},
            fb_generic_gloat_1 = {"Ese jefe fue", "demasiado..."},
            fb_generic_gloat_2 = {"La casa", "siempre gana."},
            fb_generic_gloat_3 = {"Mejor suerte la", "próxima partida."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Pero soy", "El garfio"},
            fb_bl_hook_intro_1 = {"Me llevo algunas", "de tus cartas"},
            fb_bl_hook_intro_2 = {"Dos cartas menos", "en cada mano."},
            fb_bl_hook_big_hand_1 = {"¡¿Aun con menos", "cartas?!"},
            fb_bl_hook_close_1 = {"¡Suelta esas", "cartas!"},
            fb_bl_hook_last_hand_1 = {"¡Por fin te", "enganché!"},
            fb_bl_hook_disabled_1 = {"¡Mi garfio!", "¡Se rompió!"},
            fb_bl_hook_defeat_1 = {"Está bien... te", "dejo ir."},
            fb_bl_hook_gloat_1 = {"El garfio:", "\"¡Caíste en el garfio!\""},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Pero soy", "El buey"},
            fb_bl_ox_intro_1 = {"Me llevo todo", "tu dinero"},
            fb_bl_ox_intro_2 = {"Tu mano favorita", "te cuesta todo."},
            fb_bl_ox_big_hand_1 = {"¡Esa mano embistió", "como un toro!"},
            fb_bl_ox_close_1 = {"¡Frena la carreta!", "El buey soy yo."},
            fb_bl_ox_last_hand_1 = {"Última mano. Gástalo", "o piérdelo."},
            fb_bl_ox_disabled_1 = {"¡Mis cuernos!", "¡Se desafilaron!"},
            fb_bl_ox_defeat_1 = {"Agarraste al toro", "por los cuernos..."},
            fb_bl_ox_gloat_1 = {"El buey:", "\"¡Ahora estás pelado!\""},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Pero soy", "La casa"},
            fb_bl_house_intro_1 = {"¡Estás", "CIEGO!"},
            fb_bl_house_intro_2 = {"La primera va por la", "casa. ¡A ciegas!"},
            fb_bl_house_big_hand_1 = {"¡¿Ciego y aun así", "ganaste?!"},
            fb_bl_house_close_1 = {"¡La casa", "nunca pierde!"},
            fb_bl_house_last_hand_1 = {"Se acabó la", "suerte a ciegas."},
            fb_bl_house_disabled_1 = {"¡Mi venda!", "¡Se cayó!"},
            fb_bl_house_defeat_1 = {"La casa...", "ha caído."},
            fb_bl_house_gloat_1 = {"La casa:", "\"¡La casa gana!\""},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Pero soy", "El muro"},
            fb_bl_wall_intro_1 = {"Acabas de", "chocar con uno"},
            fb_bl_wall_intro_2 = {"Intenta escalar", "este puntaje."},
            fb_bl_wall_big_hand_1 = {"¡¿Escalaste", "mi muro?!"},
            fb_bl_wall_close_1 = {"¡No podrás", "atravesarme!"},
            fb_bl_wall_last_hand_1 = {"Ya no queda", "nada que escalar."},
            fb_bl_wall_disabled_1 = {"¡Grietas! ¡Mi muro", "se agrieta!"},
            fb_bl_wall_defeat_1 = {"El muro...", "se derrumba."},
            fb_bl_wall_gloat_1 = {"El muro:", "\"¿Chocaste con el muro?\""},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Pero soy", "La rueda"},
            fb_bl_wheel_intro_1 = {"Me gusta...", "¡APOSTAR!"},
            fb_bl_wheel_intro_2 = {"Una de cada siete", "cartas, boca abajo."},
            fb_bl_wheel_big_hand_1 = {"La suerte te ama", "hoy."},
            fb_bl_wheel_close_1 = {"¡Mi rueda se", "descontrola!"},
            fb_bl_wheel_last_hand_1 = {"Último giro.", "¿Te sientes con suerte?"},
            fb_bl_wheel_disabled_1 = {"¿La rueda se detuvo?", "¡Trampa!"},
            fb_bl_wheel_defeat_1 = {"La rueda de la", "fortuna me abandona."},
            fb_bl_wheel_gloat_1 = {"La rueda:", "\"¡A rodar, perdedor!\""},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Pero soy", "El brazo"},
            fb_bl_arm_intro_1 = {"Voy a equilibrar", "tu poder"},
            fb_bl_arm_intro_2 = {"Cada mano que juegues", "baja un nivel."},
            fb_bl_arm_big_hand_1 = {"Esa mano tiene", "músculo..."},
            fb_bl_arm_close_1 = {"¿Pulso de brazos?", "¡Estoy perdiendo!"},
            fb_bl_arm_last_hand_1 = {"Última mano.", "No presumas."},
            fb_bl_arm_disabled_1 = {"¡Mi brazo quedó", "flojo! ¡Tramposo!"},
            fb_bl_arm_defeat_1 = {"Superaste a mi", "brazo fuerte."},
            fb_bl_arm_gloat_1 = {"El brazo:", "\"¡Te bajé de nivel!\""},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Pero soy", "El garrote"},
            fb_bl_club_intro_1 = {"Odio a los", "{C:green,E:1}suertudos{}"},
            fb_bl_club_intro_2 = {"Los tréboles se", "debilitan. Perdón."},
            fb_bl_club_big_hand_1 = {"¡¿Sin tréboles y", "sin problema?!"},
            fb_bl_club_close_1 = {"¡No me garrotees", "con eso!"},
            fb_bl_club_last_hand_1 = {"Última mano. Deja", "los tréboles en casa."},
            fb_bl_club_disabled_1 = {"¡Mis garrotes", "ya no pegan!"},
            fb_bl_club_defeat_1 = {"Se cierra el club.", "Hora de irme..."},
            fb_bl_club_gloat_1 = {"El garrote:", "\"¡Te di con todo!\""},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Pero soy", "El pez"},
            fb_bl_fish_intro_1 = {"Asegúrate de lo", "que quieres jugar"},
            fb_bl_fish_intro_2 = {"Tras cada mano, las", "cartas salen boca abajo."},
            fb_bl_fish_big_hand_1 = {"¡Esa mano huele", "a pescado!"},
            fb_bl_fish_close_1 = {"¡No me saques del agua!"},
            fb_bl_fish_last_hand_1 = {"Último lance.", "Recoge el sedal."},
            fb_bl_fish_disabled_1 = {"¡Mis escamas!", "¡Se cayeron!"},
            fb_bl_fish_defeat_1 = {"Me pescaste...", "como un experto."},
            fb_bl_fish_gloat_1 = {"El pez:", "\"¡Estás frito!\""},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Pero soy", "El psíquico"},
            fb_bl_psychic_intro_1 = {"Odio a los", "indecisos"},
            fb_bl_psychic_intro_2 = {"Cinco cartas, ni una", "menos. Lo predije."},
            fb_bl_psychic_big_hand_1 = {"Eso NO lo vi", "venir."},
            fb_bl_psychic_close_1 = {"Mi bola de cristal", "muestra... ¡derrota!"},
            fb_bl_psychic_last_hand_1 = {"Predigo tu", "última mano."},
            fb_bl_psychic_disabled_1 = {"¡Mis visiones!", "¡Se fueron!"},
            fb_bl_psychic_defeat_1 = {"Lo vi venir.", "...¿O no?"},
            fb_bl_psychic_gloat_1 = {"El psíquico:", "\"¡Lo vi venir!\""},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Pero soy", "La provocación"},
            fb_bl_goad_intro_1 = {"Odio el", "{C:black,E:1}PODER{}"},
            fb_bl_goad_intro_2 = {"Las espadas se debilitan.", "Cava más hondo."},
            fb_bl_goad_big_hand_1 = {"No está mal sin", "tus espadas."},
            fb_bl_goad_close_1 = {"¡No te atrevas a", "cavar mi tumba!"},
            fb_bl_goad_last_hand_1 = {"Cava hondo. Es tu", "última mano."},
            fb_bl_goad_disabled_1 = {"¡Ya no puedo", "provocar a nadie!"},
            fb_bl_goad_defeat_1 = {"Mandé cavar hondo...", "y me enterré solo."},
            fb_bl_goad_gloat_1 = {"La provocación:", "\"¡Cava tu propia tumba!\""},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Pero soy", "El agua"},
            fb_bl_water_intro_1 = {"Dame tus", "descartes"},
            fb_bl_water_intro_2 = {"Cero descartes.", "Ni una gota."},
            fb_bl_water_big_hand_1 = {"¡¿Sin descartes y", "aun así ganas?!"},
            fb_bl_water_close_1 = {"¡Me ahogo!", "¡Tírame un cabo!"},
            fb_bl_water_last_hand_1 = {"Última mano. Nadas", "o te hundes."},
            fb_bl_water_disabled_1 = {"¡Mi sequía!", "¡¿Se acabó?!"},
            fb_bl_water_defeat_1 = {"Me quedé seco..."},
            fb_bl_water_gloat_1 = {"El agua:", "\"¡Te llevó la corriente!\""},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Pero soy", "La ventana"},
            fb_bl_window_intro_1 = {"Odio el", "{C:yellow,E:1}capitalismo{}"},
            fb_bl_window_intro_2 = {"Diamantes debilitados.", "Sigue brillando."},
            fb_bl_window_big_hand_1 = {"¿Quién necesita", "diamantes?"},
            fb_bl_window_close_1 = {"¡No rompas", "mi ventana!"},
            fb_bl_window_last_hand_1 = {"Última mano. Nada", "de brillos."},
            fb_bl_window_disabled_1 = {"¡Mi ventana se agrietó!", "¡Brillan los diamantes!"},
            fb_bl_window_defeat_1 = {"Mi ventana de", "oportunidad se cerró."},
            fb_bl_window_gloat_1 = {"La ventana:", "\"¿Diamantes? ¡Débiles!\""},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Pero soy", "El grillete"},
            fb_bl_manacle_intro_1 = {"Me llevo tus", "{C:blue,E:1}opciones{}"},
            fb_bl_manacle_intro_2 = {"Una carta menos", "en tu mano."},
            fb_bl_manacle_big_hand_1 = {"¡¿Encadenado y aun", "así ganas?!"},
            fb_bl_manacle_close_1 = {"¡Te estás soltando", "de mis cadenas!"},
            fb_bl_manacle_last_hand_1 = {"Última mano. Y", "encadenado, además."},
            fb_bl_manacle_disabled_1 = {"¡Los grilletes!", "¡Se soltaron!"},
            fb_bl_manacle_defeat_1 = {"Libre al fin...", "de mí."},
            fb_bl_manacle_gloat_1 = {"El grillete:", "\"¡Te dejé esposado!\""},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Pero soy", "El ojo"},
            fb_bl_eye_intro_1 = {"No me gusta", "la rutina"},
            fb_bl_eye_intro_2 = {"Nunca juegues el mismo", "tipo de mano dos veces."},
            fb_bl_eye_big_hand_1 = {"¿Una mano nueva?", "Te estoy viendo."},
            fb_bl_eye_close_1 = {"¡No puedo", "ni mirar!"},
            fb_bl_eye_last_hand_1 = {"Ojo con tu", "última mano."},
            fb_bl_eye_disabled_1 = {"¡Mi ojo!", "¡¿Quién me lo picó?!"},
            fb_bl_eye_defeat_1 = {"Ojos que no ven,", "corazón que no siente..."},
            fb_bl_eye_gloat_1 = {"El ojo:", "\"¡Ojo, te lo dije!\""},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Pero soy", "La boca"},
            fb_bl_mouth_intro_1 = {"Amo la", "rutina"},
            fb_bl_mouth_intro_2 = {"Elige un tipo de mano", "y no lo sueltes."},
            fb_bl_mouth_big_hand_1 = {"La misma mano de", "siempre, y fuerte..."},
            fb_bl_mouth_close_1 = {"¡Tengo la boca", "bien abierta!"},
            fb_bl_mouth_last_hand_1 = {"Última mano. Mismo", "tipo. A callar."},
            fb_bl_mouth_disabled_1 = {"¡¿Quién me amordazó?!"},
            fb_bl_mouth_defeat_1 = {"Me quedé sin palabras..."},
            fb_bl_mouth_gloat_1 = {"La boca:", "\"¡Cállate, perdedor!\""},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Pero soy", "La planta"},
            fb_bl_plant_intro_1 = {"Odio las", "caras amables"},
            fb_bl_plant_intro_2 = {"Reyes, reinas, jotas:", "todos debilitados."},
            fb_bl_plant_big_hand_1 = {"¡¿Sin figuras?!", "Increíble."},
            fb_bl_plant_close_1 = {"¡No me arranques", "de raíz!"},
            fb_bl_plant_last_hand_1 = {"Enfrenta tu", "última mano."},
            fb_bl_plant_disabled_1 = {"¡Mis pétalos!", "¡Todos se fueron!"},
            fb_bl_plant_defeat_1 = {"Marchita...", "Volveré a crecer."},
            fb_bl_plant_gloat_1 = {"La planta:", "\"¡Dale la cara, perdiste!\""},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Pero soy", "La serpiente"},
            fb_bl_serpent_intro_1 = {"Hay un", "déficit"},
            fb_bl_serpent_intro_2 = {"Juegues o descartes,", "solo sacas 3."},
            fb_bl_serpent_big_hand_1 = {"¡¿Tres cartas y", "aun así pegas?!"},
            fb_bl_serpent_close_1 = {"¡No te escabullas", "ahora!"},
            fb_bl_serpent_last_hand_1 = {"Última mano. Ataca", "ahora o nunca."},
            fb_bl_serpent_disabled_1 = {"¡Mis colmillos! Ssss...", "¡Sin veneno!"},
            fb_bl_serpent_defeat_1 = {"Mudé de piel...", "y de orgullo."},
            fb_bl_serpent_gloat_1 = {"La serpiente:", "\"¡Hasta luegosss!\""},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Pero soy", "El pilar"},
            fb_bl_pillar_intro_1 = {"Aprendí mucho de", "tus manos pasadas"},
            fb_bl_pillar_intro_2 = {"Cartas jugadas debilitadas", "toda la apuesta inicial."},
            fb_bl_pillar_big_hand_1 = {"¿Cartas nuevas?", "Inteligente."},
            fb_bl_pillar_close_1 = {"¡Mi pilar se", "desmorona!"},
            fb_bl_pillar_last_hand_1 = {"Última mano. Las viejas", "cartas no sirven."},
            fb_bl_pillar_disabled_1 = {"¡Mi memoria!", "Se... desvanece."},
            fb_bl_pillar_defeat_1 = {"Un pilar de la", "comunidad, caído."},
            fb_bl_pillar_gloat_1 = {"El pilar:", "\"¿Manos viejas? ¡Ruinas!\""},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Pero soy", "La aguja"},
            fb_bl_needle_intro_1 = {"Solo tienes", "una oportunidad"},
            fb_bl_needle_intro_2 = {"Una mano. Eso es", "todo lo que tienes."},
            fb_bl_needle_big_hand_1 = {"¡¿Una sola mano,", "tan fuerte?!"},
            fb_bl_needle_close_1 = {"¡No! ¡Con una", "sola mano no!"},
            fb_bl_needle_last_hand_1 = {"Esta mano es", "tu única mano."},
            fb_bl_needle_disabled_1 = {"¡Mi aguja!", "¡Se desafiló!"},
            fb_bl_needle_defeat_1 = {"Jugada filosa.", "Me ganaste."},
            fb_bl_needle_gloat_1 = {"La aguja:", "\"¡Punto final: perdiste!\""},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Pero soy", "La cabeza"},
            fb_bl_head_intro_1 = {"Odio a los", "{C:red,E:1}enamorados{}"},
            fb_bl_head_intro_2 = {"Corazones debilitados.", "Qué frío, ¿no?"},
            fb_bl_head_big_hand_1 = {"¡¿Ganaste sin", "corazón?!"},
            fb_bl_head_close_1 = {"¡Ten corazón,", "no me acabes!"},
            fb_bl_head_last_hand_1 = {"Última mano. Sin", "corazones ni piedad."},
            fb_bl_head_disabled_1 = {"¡Me duele la cabeza!", "¿Vuelven los corazones?"},
            fb_bl_head_defeat_1 = {"Perdí la cabeza...", "por ti."},
            fb_bl_head_gloat_1 = {"La cabeza:", "\"¿Sin corazón, eh?\""},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Pero soy", "El diente"},
            fb_bl_tooth_intro_1 = {"Me interesa la", "política"},
            fb_bl_tooth_intro_2 = {"Cada carta que juegas", "te cuesta $1."},
            fb_bl_tooth_big_hand_1 = {"¡¿Pagaste y aun", "así ganaste?!"},
            fb_bl_tooth_close_1 = {"¡Basta! ¡Me estás", "sacando las muelas!"},
            fb_bl_tooth_last_hand_1 = {"Última mano,", "últimos billetes."},
            fb_bl_tooth_disabled_1 = {"¡Mi mordida!", "¡Se fue!"},
            fb_bl_tooth_defeat_1 = {"Con uñas y dientes,", "igual perdí."},
            fb_bl_tooth_gloat_1 = {"El diente:", "\"¡Paga, ingenuo!\""},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Pero soy", "El pedernal"},
            fb_bl_flint_intro_1 = {"Tienes que", "pagar impuestos"},
            fb_bl_flint_intro_2 = {"Fichas y multi base", "a la mitad."},
            fb_bl_flint_big_hand_1 = {"¡¿A medio poder", "y aun así pegas?!"},
            fb_bl_flint_close_1 = {"¡Tú encendiste", "mi caída!"},
            fb_bl_flint_last_hand_1 = {"Última mano. Mitad", "de chispa."},
            fb_bl_flint_disabled_1 = {"¡¿Poder total?!", "¡No es justo!"},
            fb_bl_flint_defeat_1 = {"Mi chispa", "se apagó."},
            fb_bl_flint_gloat_1 = {"El pedernal:", "\"¡Mitad de diversión!\""},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Pero soy", "La marca"},
            fb_bl_mark_intro_1 = {"No me gusta", "que me vean"},
            fb_bl_mark_intro_2 = {"Las figuras llegan", "boca abajo."},
            fb_bl_mark_big_hand_1 = {"¡¿Cartas marcadas y", "aun así ganas?!"},
            fb_bl_mark_close_1 = {"¡Estoy marcado", "para la derrota!"},
            fb_bl_mark_last_hand_1 = {"Última mano. Elige", "las caras a ciegas."},
            fb_bl_mark_disabled_1 = {"¡Las caras!", "¡Las puedo ver!"},
            fb_bl_mark_defeat_1 = {"Dejaste tu", "marca en mí."},
            fb_bl_mark_gloat_1 = {"La marca:", "\"¡Marcado para perder!\""},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Pero soy", "Bellota ambarina"},
            fb_bl_final_acorn_intro_1 = {"¡Me gusta", "el CAOS!"},
            fb_bl_final_acorn_intro_2 = {"¡Comodines boca", "abajo y mezclados!"},
            fb_bl_final_acorn_big_hand_1 = {"¡¿Hasta en el caos", "ganas?!"},
            fb_bl_final_acorn_close_1 = {"¡Esto es de locos!", "¡Me estoy quebrando!"},
            fb_bl_final_acorn_last_hand_1 = {"Última mano. ¿Dónde", "está tu comodín?"},
            fb_bl_final_acorn_disabled_1 = {"¡Mi bellota!", "¡¿Orden restaurado?!"},
            fb_bl_final_acorn_defeat_1 = {"Rompiste", "mi cáscara..."},
            fb_bl_final_acorn_gloat_1 = {"Bellota ambarina:", "\"¡Qué locura, perdedor!\""},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Pero soy", "Hoja verde"},
            fb_bl_final_leaf_intro_1 = {"Debes desprenderte", "de tus raíces"},
            fb_bl_final_leaf_intro_2 = {"Vende un comodín o", "sigue debilitado."},
            fb_bl_final_leaf_big_hand_1 = {"Pasaste la hoja.", "Hmph."},
            fb_bl_final_leaf_close_1 = {"¡Mi hoja se", "está cayendo!"},
            fb_bl_final_leaf_last_hand_1 = {"Última mano. ¿Vendes", "un comodín?"},
            fb_bl_final_leaf_disabled_1 = {"¡Mi hoja!", "¡Se marchitó!"},
            fb_bl_final_leaf_defeat_1 = {"Me voy... como", "hoja en el viento."},
            fb_bl_final_leaf_gloat_1 = {"Hoja verde:", "\"¡Pasa la hoja, perdedor!\""},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Pero soy", "Contenedor violeta"},
            fb_bl_final_vessel_intro_1 = {"Acabas de topar", "con la gran muralla"},
            fb_bl_final_vessel_intro_2 = {"Una ciega enorme.", "¡A navegar!"},
            fb_bl_final_vessel_big_hand_1 = {"Un golpe enorme a", "un blanco enorme."},
            fb_bl_final_vessel_close_1 = {"¡Abandonen el barco!", "...El mío, digo."},
            fb_bl_final_vessel_last_hand_1 = {"Última mano. Este", "barco no se hunde."},
            fb_bl_final_vessel_disabled_1 = {"¡Mi contenedor!", "¡Se hunde!"},
            fb_bl_final_vessel_defeat_1 = {"El contenedor...", "quedó vacío."},
            fb_bl_final_vessel_gloat_1 = {"Contenedor violeta:", "\"¿Derrota enorme, eh?\""},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Pero soy", "Corazón carmesí"},
            fb_bl_final_heart_intro_1 = {"Voy a pedirte", "un comodín prestado"},
            fb_bl_final_heart_intro_2 = {"En cada mano, un comodín", "pierde su poder."},
            fb_bl_final_heart_big_hand_1 = {"¿Sin un comodín y", "aun así pegas?"},
            fb_bl_final_heart_close_1 = {"¡No me rompas", "el corazón!"},
            fb_bl_final_heart_last_hand_1 = {"Última mano. ¿Qué", "comodín está callado?"},
            fb_bl_final_heart_disabled_1 = {"¡Mi corazón! Se", "saltó un latido."},
            fb_bl_final_heart_defeat_1 = {"Mi corazón...", "está roto."},
            fb_bl_final_heart_gloat_1 = {"Corazón carmesí:", "\"¿Con el corazón roto?\""},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Pero soy", "Campana cerúlea"},
            fb_bl_final_bell_intro_1 = {"Me gustaría", "guiarte"},
            fb_bl_final_bell_intro_2 = {"Una carta forzada", "en cada mano."},
            fb_bl_final_bell_big_hand_1 = {"¡¿Hiciste sonar mi", "carta forzada?!"},
            fb_bl_final_bell_close_1 = {"¡La campana dobla...", "¿por mí?!"},
            fb_bl_final_bell_last_hand_1 = {"Última mano. Una", "carta es forzada."},
            fb_bl_final_bell_disabled_1 = {"¡Mi campana calló!", "¡Tramposo!"},
            fb_bl_final_bell_defeat_1 = {"Silencio cerúleo...", "ya no repico."},
            fb_bl_final_bell_gloat_1 = {"Campana cerúlea:", "\"¡Ding dong, perdiste!\""},
        }
    }
}
