return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Enfrentamientos",
            fb_cfg_dialogue = "Diálogo de jefes",
            fb_cfg_music = "Música de enfrentamientos",
            fb_cfg_fx = "Efectos de pantalla",
            fb_cfg_cinematic = "Cinemáticas de enfrentamiento",
            fb_cfg_moves = "Movimientos de jefe",
            fb_cfg_phase_twists = "Las fases del jefe cambian las reglas",
            fb_showdown_title = "ENFRENTAMIENTO",
            fb_nemesis_title = "NÉMESIS",
            fb_nemesis_defeated = "NÉMESIS DERROTADA",
            fb_cfg_intro_speed = "Velocidad de la intro",
            fb_speed_slow = "Lenta",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Rápida",
            fb_cfg_min_ante = "Diálogo desde apuesta inicial",
            fb_cfg_memory = "Memoria de los jefes",
            fb_cfg_dev_mode = "Teclas de desarrollo (F5-F9)",
            fb_cfg_showdown_enabled = "Enfrentamientos personalizados",
            fb_cfg_start_ante = "Primer enfrentamiento: apuesta inicial",
            fb_cfg_every = "Luego cada N apuestas iniciales",
            fb_cfg_preview = "Enfrentamientos en apuestas iniciales",
            fb_cfg_hard = "¡Difícil! Los enfrentamientos tempranos son brutales.",
            fb_cfg_next_ante = "Los cambios se aplican a partir de la siguiente apuesta inicial.",
            fb_cfg_group_dialogue = "Diálogos",
            fb_cfg_group_stage = "Escenario del enfrentamiento",
            fb_credits_thanks = "¡Gracias por jugar con FinalBoss!",
            fb_credits_lead = "Creado y mantenido por",
            fb_credits_music = "Música de enfrentamientos:",
            fb_credits_music_by = "Adam Isiah (versión orquestal)",
            fb_credits_listen = "Escuchar en YouTube",
            fb_credits_github = "GitHub",
            fb_tip_me = "Invítame a un café",
            fb_tip_me_message_1 = "Si te gusta FinalBoss, plantéate darme",
            fb_tip_me_message_2 = "una pequeña propina como muestra de apoyo.",
            fb_tip_me_message_3 = "¡Te lo agradezco muchísimo!",
        },
        achievement_names = {
            ach_FinalBoss_fb_showdown_survivor = "Superviviente del enfrentamiento",
            ach_FinalBoss_fb_clean_sweep = "Limpieza total",
            ach_FinalBoss_fb_rude = "¡Maleducado!",
            ach_FinalBoss_fb_no_manners = "Sin modales",
            ach_FinalBoss_fb_last_laugh = "El que ríe el último",
            ach_FinalBoss_fb_overkill = "Paliza",
            ach_FinalBoss_fb_phase_skipper = "Saltafases",
            ach_FinalBoss_fb_comeback = "Remontada",
            ach_FinalBoss_fb_nemesis_slayer = "Verdugo de némesis",
            ach_FinalBoss_fb_twisted = "Retorcido",
        },
        achievement_descriptions = {
            ach_FinalBoss_fb_showdown_survivor = "Derrota a un jefe final",
            ach_FinalBoss_fb_clean_sweep = "Derrota a los 5 jefes finales del juego base",
            ach_FinalBoss_fb_rude = "Interrumpe a un jefe mientras habla",
            ach_FinalBoss_fb_no_manners = "Interrumpe a 10 jefes distintos",
            ach_FinalBoss_fb_last_laugh = "Derrota a un jefe con la mano justo después de que se riese de ti",
            ach_FinalBoss_fb_overkill = "Derrota a un jefe final en una sola mano con toda su vida",
            ach_FinalBoss_fb_phase_skipper = "Lleva a un jefe final de la fase I a la fase III en una sola mano",
            ach_FinalBoss_fb_comeback = "Derrota a un jefe final en tu última mano",
            ach_FinalBoss_fb_nemesis_slayer = "Derrota a tu némesis",
            ach_FinalBoss_fb_twisted = "Derrota a los 5 jefes finales del juego base con las reglas de fase activadas",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Los jefes te contestan y los enfrentamientos son combates épicos.", "Por {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Has llegado muy lejos..."},
            fb_opener_2 = {"Y siento decirte..."},
            fb_opener_3 = {"Así que lo has logrado."},
            fb_closer_1 = {"No vas a", "poder vencerme."},
            fb_closer_2 = {"Aquí acaba", "tu partida."},
            fb_closer_3 = {"Enséñame de qué", "estás hecho."},
            fb_gloat = {"Ese jefe era", "demasiado..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"¡Soy #1#!"},
            fb_generic_name_2 = {"Me llaman", "#1#."},
            fb_generic_name_3 = {"Admira:", "¡#1#!"},
            fb_generic_intro_1 = {"Aquí se acaba", "tu suerte."},
            fb_generic_intro_2 = {"A ver cómo te", "las apañas."},
            fb_generic_intro_3 = {"Lee mis reglas", "con cuidado..."},
            fb_generic_big_hand_1 = {"...Nada mal."},
            fb_generic_big_hand_2 = {"Mano de chiripa."},
            fb_generic_big_hand_3 = {"Hmph. ¿Otra vez?"},
            fb_generic_close_1 = {"¡Espera, espera,", "ESPERA!"},
            fb_generic_close_2 = {"Ni se te ocurra..."},
            fb_generic_close_3 = {"Esto no puede ser..."},
            fb_generic_last_hand_1 = {"Una mano más.", "Que cuente."},
            fb_generic_last_hand_2 = {"Tic, tac..."},
            fb_generic_last_hand_3 = {"Última oportunidad,", "pequeño comodín."},
            fb_generic_disabled_1 = {"¡Mi poder...!", "¿Qué has hecho?"},
            fb_generic_disabled_2 = {"¡Eh! ¡Eso es", "trampa!"},
            fb_generic_disabled_3 = {"Me siento... débil."},
            fb_generic_defeat_1 = {"Imposible..."},
            fb_generic_defeat_2 = {"Volveré en la siguiente", "apuesta inicial..."},
            fb_generic_defeat_3 = {"Bien jugado..."},
            fb_generic_gloat_1 = {"Ese jefe era", "demasiado..."},
            fb_generic_gloat_2 = {"La casa", "siempre gana."},
            fb_generic_gloat_3 = {"Más suerte la", "próxima partida."},
            fb_generic_interrupted_1 = {"¡Mi discurso!"},
            fb_generic_interrupted_2 = {"Vale... así que", "así van las cosas."},
            fb_generic_interrupted_3 = {"¿Ni un hola?"},
            fb_generic_phase2_1 = {"¡Basta de juegos!"},
            fb_generic_phase3_1 = {"¡Ahora sí que", "estoy furioso!"},
            fb_generic_rematch_won_1 = {"¿Tú otra vez?", "Me acuerdo de ti."},
            fb_generic_rematch_won_2 = {"Lo de la otra vez fue", "suerte. Admítelo."},
            fb_generic_rematch_won_3 = {"Hora de la revancha.", "He entrenado."},
            fb_generic_rematch_lost_1 = {"¿Vienes a por otra", "paliza?"},
            fb_generic_rematch_lost_2 = {"¿No aprendiste", "la última vez?"},
            fb_generic_rematch_lost_3 = {"Ah, eres tú.", "El perdedor."},

            -- Nemesis (shared, #1# = boss name)
            fb_nemesis_intro_1 = {"¿Te acuerdas de mí?", "#1# nunca olvida."},
            fb_nemesis_intro_2 = {"#1# otra vez.", "Tu némesis."},
            fb_nemesis_intro_3 = {"No puedes escapar", "de tu némesis."},
            fb_nemesis_defeat_1 = {"¡¿Cómo?! ¡Soy tu", "némesis!"},
            fb_nemesis_defeat_2 = {"#1#... se acabó."},
            fb_nemesis_defeat_3 = {"Esto no acaba", "aquí, rival..."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Pero soy", "El garfio"},
            fb_bl_hook_intro_1 = {"Me quedo con unas", "cuantas de tus cartas"},
            fb_bl_hook_intro_2 = {"Dos cartas menos", "en cada mano."},
            fb_bl_hook_big_hand_1 = {"¡¿Aun con menos", "cartas?!"},
            fb_bl_hook_close_1 = {"¡Suelta esas", "cartas!"},
            fb_bl_hook_last_hand_1 = {"¡Por fin has", "picado!"},
            fb_bl_hook_disabled_1 = {"¡Mi garfio!", "¡Se ha roto!"},
            fb_bl_hook_defeat_1 = {"Vale... te", "dejo marchar."},
            fb_bl_hook_gloat_1 = {"¡Has picado, majo!"},
            fb_bl_hook_interrupted_1 = {"¡Maleducado! ¡Estaba", "a media frase!"},
            fb_bl_hook_rematch_won_1 = {"La otra vez te", "soltaste del garfio."},
            fb_bl_hook_rematch_lost_1 = {"¿Vienes a picar", "otra vez, majo?"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Pero soy", "El buey"},
            fb_bl_ox_intro_1 = {"Me quedo con todo", "tu dinero"},
            fb_bl_ox_intro_2 = {"Tu mano favorita", "te cuesta todo."},
            fb_bl_ox_big_hand_1 = {"¡Esa mano ha embestido", "como un toro!"},
            fb_bl_ox_close_1 = {"¡Para el carro!", "El buey soy yo."},
            fb_bl_ox_last_hand_1 = {"Última mano. Gástalo", "o piérdelo."},
            fb_bl_ox_disabled_1 = {"¡Mis cuernos!", "¡Se han desafilado!"},
            fb_bl_ox_defeat_1 = {"Has cogido al toro", "por los cuernos..."},
            fb_bl_ox_gloat_1 = {"¡Ahora estás", "sin blanca!"},
            fb_bl_ox_interrupted_1 = {"Ah, conque ASÍ", "van a ser las cosas."},
            fb_bl_ox_rematch_won_1 = {"Esquivaste mis", "cuernos una vez..."},
            fb_bl_ox_rematch_lost_1 = {"¿Sigues sin blanca", "desde la última vez?"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Pero soy", "La casa"},
            fb_bl_house_intro_1 = {"¡Estás", "CIEGO!"},
            fb_bl_house_intro_2 = {"La primera invita la", "casa. ¡A ciegas!"},
            fb_bl_house_big_hand_1 = {"¡¿A ciegas y aun así", "has ganado?!"},
            fb_bl_house_close_1 = {"¡La casa", "nunca pierde!"},
            fb_bl_house_last_hand_1 = {"Se acabó la", "suerte a ciegas."},
            fb_bl_house_disabled_1 = {"¡Mi venda!", "¡Se ha caído!"},
            fb_bl_house_defeat_1 = {"La casa...", "ha caído."},
            fb_bl_house_gloat_1 = {"¡Gana la casa!"},
            fb_bl_house_interrupted_1 = {"Norma de la casa:", "¡aún no se juega!"},
            fb_bl_house_rematch_won_1 = {"La casa perdió una", "vez. Nunca más."},
            fb_bl_house_rematch_lost_1 = {"Bienvenido otra vez.", "La casa no olvida."},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Pero soy", "El muro"},
            fb_bl_wall_intro_1 = {"Acabas de", "chocar con uno"},
            fb_bl_wall_intro_2 = {"Intenta escalar", "esta puntuación."},
            fb_bl_wall_big_hand_1 = {"¡¿Has escalado", "mi muro?!"},
            fb_bl_wall_close_1 = {"¡No podrás", "atravesarme!"},
            fb_bl_wall_last_hand_1 = {"Ya no queda", "nada que escalar."},
            fb_bl_wall_disabled_1 = {"¡Grietas! ¡Mi muro", "se agrieta!"},
            fb_bl_wall_defeat_1 = {"El muro...", "se derrumba."},
            fb_bl_wall_gloat_1 = {"¿Te has dado", "de bruces?"},
            fb_bl_wall_interrupted_1 = {"Es como hablarle", "a la pared... oye."},
            fb_bl_wall_rematch_won_1 = {"Me escalaste una vez.", "No habrá segunda."},
            fb_bl_wall_rematch_lost_1 = {"¿Vienes a darte con", "el mismo muro?"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Pero soy", "La rueda"},
            fb_bl_wheel_intro_1 = {"Me encanta...", "¡APOSTAR!"},
            fb_bl_wheel_intro_2 = {"Una de cada siete", "cartas, boca abajo."},
            fb_bl_wheel_big_hand_1 = {"La suerte te quiere", "hoy."},
            fb_bl_wheel_close_1 = {"¡Mi rueda se", "descontrola!"},
            fb_bl_wheel_last_hand_1 = {"Último giro.", "¿Te sientes con suerte?"},
            fb_bl_wheel_disabled_1 = {"¿Se ha parado la rueda?", "¡Trampa!"},
            fb_bl_wheel_defeat_1 = {"La rueda de la", "fortuna me da la espalda."},
            fb_bl_wheel_gloat_1 = {"¡A rodar,", "perdedor!"},
            fb_bl_wheel_interrupted_1 = {"¡Eh, no tan rápido!", "¡Sigo girando!"},
            fb_bl_wheel_rematch_won_1 = {"La última tirada la", "suerte te sonrió..."},
            fb_bl_wheel_rematch_lost_1 = {"¿Otra vuelta? La casa", "tiene ventaja, colega."},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Pero soy", "El brazo"},
            fb_bl_arm_intro_1 = {"Voy a equilibrar", "tu poder"},
            fb_bl_arm_intro_2 = {"Cada mano que juegues", "baja un nivel."},
            fb_bl_arm_big_hand_1 = {"Esa mano tiene", "músculo..."},
            fb_bl_arm_close_1 = {"¿Pulso de brazos?", "¡Estoy perdiendo!"},
            fb_bl_arm_last_hand_1 = {"Última mano.", "No presumas."},
            fb_bl_arm_disabled_1 = {"¡Mi brazo se ha", "quedado flojo! ¡Tramposo!"},
            fb_bl_arm_defeat_1 = {"Has vencido a mi", "brazo fuerte."},
            fb_bl_arm_gloat_1 = {"¡Te he bajado", "de nivel!"},
            fb_bl_arm_interrupted_1 = {"¡Quieto! No había", "acabado de lucirme."},
            fb_bl_arm_rematch_won_1 = {"La otra vez me", "ganaste el pulso."},
            fb_bl_arm_rematch_lost_1 = {"¿Vienes a por otro", "pulso?"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Pero soy", "El garrote"},
            fb_bl_club_intro_1 = {"Odio a los", "{C:green,E:1}suertudos{}"},
            fb_bl_club_intro_2 = {"Los tréboles se", "debilitan. Lo siento."},
            fb_bl_club_big_hand_1 = {"¡¿Sin tréboles y", "sin problema?!"},
            fb_bl_club_close_1 = {"¡No me garrotees", "con eso!"},
            fb_bl_club_last_hand_1 = {"Última mano. Deja", "los tréboles en casa."},
            fb_bl_club_disabled_1 = {"¡Mis garrotes", "ya no pegan!"},
            fb_bl_club_defeat_1 = {"Se cierra el club.", "Hora de irse..."},
            fb_bl_club_gloat_1 = {"¡Te he dado", "con todo!"},
            fb_bl_club_interrupted_1 = {"¡Eh! En mi club", "hablo yo primero."},
            fb_bl_club_rematch_won_1 = {"La otra vez te colaste", "en mi club."},
            fb_bl_club_rematch_lost_1 = {"¿Has renovado el", "carné? Adelante."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Pero soy", "El pez"},
            fb_bl_fish_intro_1 = {"Asegúrate de lo", "que quieres jugar"},
            fb_bl_fish_intro_2 = {"Tras cada mano, las", "cartas salen boca abajo."},
            fb_bl_fish_big_hand_1 = {"¡Esa mano huele", "a pescado!"},
            fb_bl_fish_close_1 = {"¡No me saques del agua!"},
            fb_bl_fish_last_hand_1 = {"Último lance.", "Recoge el sedal."},
            fb_bl_fish_disabled_1 = {"¡Mis escamas!", "¡Se han caído!"},
            fb_bl_fish_defeat_1 = {"Me has pescado...", "como un profesional."},
            fb_bl_fish_gloat_1 = {"¡Estás frito!"},
            fb_bl_fish_interrupted_1 = {"¡Me has cortado", "el sedal!"},
            fb_bl_fish_rematch_won_1 = {"El que se me", "escapó..."},
            fb_bl_fish_rematch_lost_1 = {"¿Otra vez en mi", "anzuelo, pececillo?"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Pero soy", "El psíquico"},
            fb_bl_psychic_intro_1 = {"Odio a los", "indecisos"},
            fb_bl_psychic_intro_2 = {"Cinco cartas, ni una", "menos. Lo predije."},
            fb_bl_psychic_big_hand_1 = {"Eso NO lo vi", "venir."},
            fb_bl_psychic_close_1 = {"Mi bola de cristal", "muestra... ¡derrota!"},
            fb_bl_psychic_last_hand_1 = {"Predigo tu", "última mano."},
            fb_bl_psychic_disabled_1 = {"¡Mis visiones!", "¡Se han ido!"},
            fb_bl_psychic_defeat_1 = {"Lo vi venir.", "...¿O no?"},
            fb_bl_psychic_gloat_1 = {"¡Lo vi venir!"},
            fb_bl_psychic_interrupted_1 = {"Sabía que harías eso.", "...Pero qué maleducado."},
            fb_bl_psychic_rematch_won_1 = {"No predije tu", "última victoria."},
            fb_bl_psychic_rematch_lost_1 = {"Sabía que", "volverías."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Pero soy", "La provocación"},
            fb_bl_goad_intro_1 = {"Odio el", "{C:black,E:1}PODER{}"},
            fb_bl_goad_intro_2 = {"Las picas se debilitan.", "Cava más hondo."},
            fb_bl_goad_big_hand_1 = {"No está mal sin", "tus picas."},
            fb_bl_goad_close_1 = {"¡Ni se te ocurra", "cavar mi tumba!"},
            fb_bl_goad_last_hand_1 = {"Cava hondo. Es tu", "última mano."},
            fb_bl_goad_disabled_1 = {"¡Ya no puedo", "provocar a nadie!"},
            fb_bl_goad_defeat_1 = {"He mandado cavar hondo...", "y me he enterrado."},
            fb_bl_goad_gloat_1 = {"¡Cava tu", "propia tumba!"},
            fb_bl_goad_interrupted_1 = {"¿Provocarme A MÍ?", "Muy bien."},
            fb_bl_goad_rematch_won_1 = {"La otra vez saliste", "de la tumba."},
            fb_bl_goad_rematch_lost_1 = {"¿Vienes a cavar una", "tumba más honda?"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Pero soy", "El agua"},
            fb_bl_water_intro_1 = {"Dame tus", "descartes"},
            fb_bl_water_intro_2 = {"Cero descartes.", "Ni una gota."},
            fb_bl_water_big_hand_1 = {"¡¿Sin descartes y", "aun así ganas?!"},
            fb_bl_water_close_1 = {"¡Me ahogo!", "¡Échame un cabo!"},
            fb_bl_water_last_hand_1 = {"Última mano. Nadas", "o te hundes."},
            fb_bl_water_disabled_1 = {"¡Mi sequía!", "¡¿Se ha acabado?!"},
            fb_bl_water_defeat_1 = {"Me he quedado seco..."},
            fb_bl_water_gloat_1 = {"¡Te llevó la", "corriente!"},
            fb_bl_water_interrupted_1 = {"¿Me interrumpes?", "¡Te vas a hundir!"},
            fb_bl_water_rematch_won_1 = {"La otra vez te", "mantuviste a flote."},
            fb_bl_water_rematch_lost_1 = {"¿Vienes a por otro", "chapuzón?"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Pero soy", "La ventana"},
            fb_bl_window_intro_1 = {"Odio el", "{C:yellow,E:1}capitalismo{}"},
            fb_bl_window_intro_2 = {"Diamantes debilitados.", "Sigue brillando."},
            fb_bl_window_big_hand_1 = {"¿Quién necesita", "diamantes?"},
            fb_bl_window_close_1 = {"¡No rompas", "mi ventana!"},
            fb_bl_window_last_hand_1 = {"Última mano. Nada", "de brillos."},
            fb_bl_window_disabled_1 = {"¡Mi ventana, agrietada!", "¡Brillan los diamantes!"},
            fb_bl_window_defeat_1 = {"Mi ventana de", "oportunidad se cerró."},
            fb_bl_window_gloat_1 = {"¿Diamantes?", "¡Débiles!"},
            fb_bl_window_interrupted_1 = {"¡¿Mis palabras se van", "por la ventana?!"},
            fb_bl_window_rematch_won_1 = {"Una vez rompiste", "mi ventana."},
            fb_bl_window_rematch_lost_1 = {"¿Otra vez mirando", "escaparates?"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Pero soy", "El grillete"},
            fb_bl_manacle_intro_1 = {"Me llevo tus", "{C:blue,E:1}opciones{}"},
            fb_bl_manacle_intro_2 = {"Una carta menos", "en tu mano."},
            fb_bl_manacle_big_hand_1 = {"¡¿Encadenado y aun", "así ganas?!"},
            fb_bl_manacle_close_1 = {"¡Te estás soltando", "de mis cadenas!"},
            fb_bl_manacle_last_hand_1 = {"Última mano. Y", "encadenado, encima."},
            fb_bl_manacle_disabled_1 = {"¡Los grilletes!", "¡Se han soltado!"},
            fb_bl_manacle_defeat_1 = {"Libre al fin...", "de mí."},
            fb_bl_manacle_gloat_1 = {"¡Te he dejado", "esposado!"},
            fb_bl_manacle_interrupted_1 = {"¡Alto! Te encadenaré", "por esto."},
            fb_bl_manacle_rematch_won_1 = {"Una vez te soltaste", "de mis cadenas."},
            fb_bl_manacle_rematch_lost_1 = {"Otra vez", "encadenado, ya veo."},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Pero soy", "El ojo"},
            fb_bl_eye_intro_1 = {"No me gusta", "la rutina"},
            fb_bl_eye_intro_2 = {"Nunca juegues el mismo", "tipo de mano dos veces."},
            fb_bl_eye_big_hand_1 = {"¿Una mano nueva?", "Te estoy viendo."},
            fb_bl_eye_close_1 = {"¡No puedo", "ni mirar!"},
            fb_bl_eye_last_hand_1 = {"Ojo con tu", "última mano."},
            fb_bl_eye_disabled_1 = {"¡Mi ojo!", "¡¿Quién me lo ha picado?!"},
            fb_bl_eye_defeat_1 = {"Ojos que no ven,", "corazón que no siente..."},
            fb_bl_eye_gloat_1 = {"¡Ojo, te lo dije!"},
            fb_bl_eye_interrupted_1 = {"¡Lo he visto!", "Qué maleducado."},
            fb_bl_eye_rematch_won_1 = {"Te vigilo desde", "aquella derrota."},
            fb_bl_eye_rematch_lost_1 = {"Ya veo que", "has vuelto."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Pero soy", "La boca"},
            fb_bl_mouth_intro_1 = {"Adoro la", "rutina"},
            fb_bl_mouth_intro_2 = {"Elige un tipo de mano", "y no lo sueltes."},
            fb_bl_mouth_big_hand_1 = {"La misma mano de", "siempre, y fuerte..."},
            fb_bl_mouth_close_1 = {"¡Tengo la boca", "bien abierta!"},
            fb_bl_mouth_last_hand_1 = {"Última mano. Mismo", "tipo. A callar."},
            fb_bl_mouth_disabled_1 = {"¡¿Quién me ha callado?!"},
            fb_bl_mouth_defeat_1 = {"Me he quedado mudo..."},
            fb_bl_mouth_gloat_1 = {"¡Cállate,", "perdedor!"},
            fb_bl_mouth_interrupted_1 = {"¡Eh! ¡Esta boca", "seguía hablando!"},
            fb_bl_mouth_rematch_won_1 = {"La otra vez me", "cerraste la boca."},
            fb_bl_mouth_rematch_lost_1 = {"¿La misma rutina", "de la otra vez?"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Pero soy", "La planta"},
            fb_bl_plant_intro_1 = {"Odio las", "caras amables"},
            fb_bl_plant_intro_2 = {"Reyes, reinas, jotas:", "todos debilitados."},
            fb_bl_plant_big_hand_1 = {"¡¿Sin figuras?!", "Increíble."},
            fb_bl_plant_close_1 = {"¡No me arranques", "de raíz!"},
            fb_bl_plant_last_hand_1 = {"Afronta tu", "última mano."},
            fb_bl_plant_disabled_1 = {"¡Mis pétalos!", "¡Se han ido todos!"},
            fb_bl_plant_defeat_1 = {"Marchita...", "Volveré a crecer."},
            fb_bl_plant_gloat_1 = {"¡Dame la cara,", "perdiste!"},
            fb_bl_plant_interrupted_1 = {"Déjame crecer", "primero, impaciente."},
            fb_bl_plant_rematch_won_1 = {"Me arrancaste de raíz.", "He vuelto a crecer."},
            fb_bl_plant_rematch_lost_1 = {"Otra vez en mi", "jardín, ya veo."},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Pero soy", "La serpiente"},
            fb_bl_serpent_intro_1 = {"Hay un", "déficit"},
            fb_bl_serpent_intro_2 = {"Juegues o descartes,", "solo robas 3."},
            fb_bl_serpent_big_hand_1 = {"¡¿Tres cartas y", "aun así pegas?!"},
            fb_bl_serpent_close_1 = {"¡No te escabullas", "ahora!"},
            fb_bl_serpent_last_hand_1 = {"Última mano. Ataca", "ahora o nunca."},
            fb_bl_serpent_disabled_1 = {"¡Mis colmillos! Ssss...", "¡Sin veneno!"},
            fb_bl_serpent_defeat_1 = {"He mudado de piel...", "y de orgullo."},
            fb_bl_serpent_gloat_1 = {"¡Hasta luegosss!"},
            fb_bl_serpent_interrupted_1 = {"¡Sss! ¡No me", "interrumpas!"},
            fb_bl_serpent_rematch_won_1 = {"Una vez escapaste", "de mis anillos."},
            fb_bl_serpent_rematch_lost_1 = {"Asssí que", "has vuelto..."},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Pero soy", "El pilar"},
            fb_bl_pillar_intro_1 = {"He aprendido mucho de", "tus manos pasadas"},
            fb_bl_pillar_intro_2 = {"Cartas jugadas debilitadas", "toda la apuesta inicial."},
            fb_bl_pillar_big_hand_1 = {"¿Cartas nuevas?", "Inteligente."},
            fb_bl_pillar_close_1 = {"¡Mi pilar se", "desmorona!"},
            fb_bl_pillar_last_hand_1 = {"Última mano. Las viejas", "cartas no sirven."},
            fb_bl_pillar_disabled_1 = {"¡Mi memoria!", "Se... desvanece."},
            fb_bl_pillar_defeat_1 = {"Un pilar de la", "comunidad, caído."},
            fb_bl_pillar_gloat_1 = {"¿Manos viejas?", "¡Ruinas!"},
            fb_bl_pillar_interrupted_1 = {"¿No respetas", "a tus mayores?"},
            fb_bl_pillar_rematch_won_1 = {"Recuerdo cómo", "me venciste."},
            fb_bl_pillar_rematch_lost_1 = {"Recuerdo cómo", "perdiste."},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Pero soy", "La aguja"},
            fb_bl_needle_intro_1 = {"Solo tienes", "una oportunidad"},
            fb_bl_needle_intro_2 = {"Una mano. Eso es", "todo lo que tienes."},
            fb_bl_needle_big_hand_1 = {"¡¿Una sola mano,", "tan fuerte?!"},
            fb_bl_needle_close_1 = {"¡No! ¡Con una", "sola mano no!"},
            fb_bl_needle_last_hand_1 = {"Esta mano es", "tu única mano."},
            fb_bl_needle_disabled_1 = {"¡Mi aguja!", "¡Se ha desafilado!"},
            fb_bl_needle_defeat_1 = {"Jugada afilada.", "Me has ganado."},
            fb_bl_needle_gloat_1 = {"¡Punto final!", "¡Perdiste!"},
            fb_bl_needle_interrupted_1 = {"Qué punzante.", "¡No había acabado!"},
            fb_bl_needle_rematch_won_1 = {"Una sola mano me", "ganó la otra vez."},
            fb_bl_needle_rematch_lost_1 = {"Otra vez una sola", "oportunidad. ¿Fallarás?"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Pero soy", "La cabeza"},
            fb_bl_head_intro_1 = {"Odio a los", "{C:red,E:1}enamorados{}"},
            fb_bl_head_intro_2 = {"Corazones debilitados.", "Qué frío, ¿no?"},
            fb_bl_head_big_hand_1 = {"¡¿Has ganado sin", "corazón?!"},
            fb_bl_head_close_1 = {"¡Ten corazón,", "no me acabes!"},
            fb_bl_head_last_hand_1 = {"Última mano. Sin", "corazones ni piedad."},
            fb_bl_head_disabled_1 = {"¡Me duele la cabeza!", "¿Vuelven los corazones?"},
            fb_bl_head_defeat_1 = {"He perdido la cabeza...", "por ti."},
            fb_bl_head_gloat_1 = {"¿Sin corazón, eh?"},
            fb_bl_head_interrupted_1 = {"¿Has perdido la cabeza?", "¡Estoy hablando!"},
            fb_bl_head_rematch_won_1 = {"Me robaste el", "corazón... una vez."},
            fb_bl_head_rematch_lost_1 = {"¿Vienes a por otro", "corazón roto?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Pero soy", "El diente"},
            fb_bl_tooth_intro_1 = {"Me interesa la", "política"},
            fb_bl_tooth_intro_2 = {"Cada carta que juegas", "te cuesta $1."},
            fb_bl_tooth_big_hand_1 = {"¡¿Has pagado y aun", "así ganas?!"},
            fb_bl_tooth_close_1 = {"¡Basta! ¡Me estás", "sacando las muelas!"},
            fb_bl_tooth_last_hand_1 = {"Última mano,", "últimos dólares."},
            fb_bl_tooth_disabled_1 = {"¡Mi mordisco!", "¡Se ha ido!"},
            fb_bl_tooth_defeat_1 = {"Con uñas y dientes,", "he perdido igual."},
            fb_bl_tooth_gloat_1 = {"¡Paga, iluso!"},
            fb_bl_tooth_interrupted_1 = {"¡Grr! Me las vas", "a pagar."},
            fb_bl_tooth_rematch_won_1 = {"Todavía me debes", "lo de la otra vez."},
            fb_bl_tooth_rematch_lost_1 = {"¿Vienes a pagar", "tu deuda?"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Pero soy", "El pedernal"},
            fb_bl_flint_intro_1 = {"Tienes que", "pagar impuestos"},
            fb_bl_flint_intro_2 = {"Fichas y multi base", "a la mitad."},
            fb_bl_flint_big_hand_1 = {"¡¿A medio poder y", "aun así pegas?!"},
            fb_bl_flint_close_1 = {"¡Tú has encendido", "mi caída!"},
            fb_bl_flint_last_hand_1 = {"Última mano. Mitad", "de chispa."},
            fb_bl_flint_disabled_1 = {"¡¿Poder total?!", "¡No es justo!"},
            fb_bl_flint_defeat_1 = {"Mi chispa", "se ha apagado."},
            fb_bl_flint_gloat_1 = {"¡Mitad de", "diversión!"},
            fb_bl_flint_interrupted_1 = {"¡No me eches chispas!", "¡Estaba hablando!"},
            fb_bl_flint_rematch_won_1 = {"La otra vez te", "libraste de Hacienda."},
            fb_bl_flint_rematch_lost_1 = {"Otra vez la", "declaración. Paga."},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Pero soy", "La marca"},
            fb_bl_mark_intro_1 = {"No me gusta", "que me vean"},
            fb_bl_mark_intro_2 = {"Las figuras llegan", "boca abajo."},
            fb_bl_mark_big_hand_1 = {"¡¿Cartas marcadas y", "aun así ganas?!"},
            fb_bl_mark_close_1 = {"¡Estoy marcado", "para la derrota!"},
            fb_bl_mark_last_hand_1 = {"Última mano. Elige", "las caras a ciegas."},
            fb_bl_mark_disabled_1 = {"¡Las caras!", "¡Las veo!"},
            fb_bl_mark_defeat_1 = {"Has dejado tu", "marca en mí."},
            fb_bl_mark_gloat_1 = {"¡Marcado", "para perder!"},
            fb_bl_mark_interrupted_1 = {"Apuntado. Ahora estás", "marcado."},
            fb_bl_mark_rematch_won_1 = {"La otra vez me", "viste las caras."},
            fb_bl_mark_rematch_lost_1 = {"¿Sigues sin ver", "mis caras?"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Pero soy", "Bellota ambarina"},
            fb_bl_final_acorn_intro_1 = {"¡Me encanta", "el CAOS!"},
            fb_bl_final_acorn_intro_2 = {"¡Comodines boca", "abajo y mezclados!"},
            fb_bl_final_acorn_big_hand_1 = {"¡¿Hasta en el caos", "ganas?!"},
            fb_bl_final_acorn_close_1 = {"¡Esto es de locos!", "¡Me estoy quebrando!"},
            fb_bl_final_acorn_last_hand_1 = {"Última mano. ¿Dónde", "está tu comodín?"},
            fb_bl_final_acorn_disabled_1 = {"¡Mi bellota!", "¡¿Orden restaurado?!"},
            fb_bl_final_acorn_defeat_1 = {"Has roto", "mi cáscara..."},
            fb_bl_final_acorn_gloat_1 = {"¡Qué locura,", "perdedor!"},
            fb_bl_final_acorn_interrupted_1 = {"¡Bellotas! No", "había acabado."},
            fb_bl_final_acorn_phase2_1 = {"¡Ahora se pone", "de LOCOS!"},
            fb_bl_final_acorn_phase3_1 = {"¡Caos total!", "¡Fuera cáscara!"},
            fb_bl_final_acorn_rematch_won_1 = {"Ya me rompiste una", "vez. ¡Nunca más!"},
            fb_bl_final_acorn_rematch_lost_1 = {"¿Vienes a por más", "CAOS?"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Pero soy", "Hoja verde"},
            fb_bl_final_leaf_intro_1 = {"Debes desprenderte", "de tus raíces"},
            fb_bl_final_leaf_intro_2 = {"Vende un comodín o", "sigue debilitado."},
            fb_bl_final_leaf_big_hand_1 = {"Has pasado la hoja.", "Hmph."},
            fb_bl_final_leaf_close_1 = {"¡Mi hoja se", "está cayendo!"},
            fb_bl_final_leaf_last_hand_1 = {"Última mano. ¿Vendes", "un comodín?"},
            fb_bl_final_leaf_disabled_1 = {"¡Mi hoja!", "¡Se ha marchitado!"},
            fb_bl_final_leaf_defeat_1 = {"Me voy... como", "hoja en el viento."},
            fb_bl_final_leaf_gloat_1 = {"¡Pasa la hoja,", "perdedor!"},
            fb_bl_final_leaf_interrupted_1 = {"Bien. Sáltate las", "cortesías."},
            fb_bl_final_leaf_phase2_1 = {"¡Mis raíces", "se hunden más!"},
            fb_bl_final_leaf_phase3_1 = {"¡Marchítate", "conmigo!"},
            fb_bl_final_leaf_rematch_won_1 = {"Una vez te soltaste.", "Inténtalo otra vez."},
            fb_bl_final_leaf_rematch_lost_1 = {"¿Sigues aferrado", "a tus comodines?"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Pero soy", "Contenedor violeta"},
            fb_bl_final_vessel_intro_1 = {"Acabas de topar", "con la gran muralla"},
            fb_bl_final_vessel_intro_2 = {"Una ciega enorme.", "¡A navegar!"},
            fb_bl_final_vessel_big_hand_1 = {"Un golpe enorme a", "un blanco enorme."},
            fb_bl_final_vessel_close_1 = {"¡Abandonad el barco!", "...El mío, digo."},
            fb_bl_final_vessel_last_hand_1 = {"Última mano. Este", "barco no se hunde."},
            fb_bl_final_vessel_disabled_1 = {"¡Mi contenedor!", "¡Se hunde!"},
            fb_bl_final_vessel_defeat_1 = {"El contenedor...", "se ha vaciado."},
            fb_bl_final_vessel_gloat_1 = {"¿Derrota", "enorme, eh?"},
            fb_bl_final_vessel_interrupted_1 = {"¿Zarpar antes de mi", "discurso? Atrevido."},
            fb_bl_final_vessel_phase2_1 = {"¡Llenad la bodega!"},
            fb_bl_final_vessel_phase3_1 = {"¡Todos al fondo", "del mar!"},
            fb_bl_final_vessel_rematch_won_1 = {"Me hundiste una vez.", "Ya me han reparado."},
            fb_bl_final_vessel_rematch_lost_1 = {"¿Vienes a ahogarte", "en mi estela?"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Pero soy", "Corazón carmesí"},
            fb_bl_final_heart_intro_1 = {"Voy a pedirte", "un comodín prestado"},
            fb_bl_final_heart_intro_2 = {"En cada mano, un comodín", "pierde su poder."},
            fb_bl_final_heart_big_hand_1 = {"¿Sin un comodín y", "aun así pegas?"},
            fb_bl_final_heart_close_1 = {"¡No me rompas", "el corazón!"},
            fb_bl_final_heart_last_hand_1 = {"Última mano. ¿Qué", "comodín está callado?"},
            fb_bl_final_heart_disabled_1 = {"¡Mi corazón! Se", "ha saltado un latido."},
            fb_bl_final_heart_defeat_1 = {"Mi corazón...", "está roto."},
            fb_bl_final_heart_gloat_1 = {"¿Con el", "corazón roto?"},
            fb_bl_final_heart_interrupted_1 = {"¿Me interrumpes?", "¡Qué desalmado!"},
            fb_bl_final_heart_phase2_1 = {"¡Mi corazón", "late más rápido!"},
            fb_bl_final_heart_phase3_1 = {"¡Siente mi", "furia carmesí!"},
            fb_bl_final_heart_rematch_won_1 = {"La otra vez me", "rompiste el corazón."},
            fb_bl_final_heart_rematch_lost_1 = {"Mi corazón aún", "late por ti."},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Pero soy", "Campana cerúlea"},
            fb_bl_final_bell_intro_1 = {"Me gustaría", "guiarte"},
            fb_bl_final_bell_intro_2 = {"Una carta forzada", "en cada mano."},
            fb_bl_final_bell_big_hand_1 = {"¡¿Has hecho sonar mi", "carta forzada?!"},
            fb_bl_final_bell_close_1 = {"¡La campana dobla...", "¿por mí?!"},
            fb_bl_final_bell_last_hand_1 = {"Última mano. Una", "carta es forzada."},
            fb_bl_final_bell_disabled_1 = {"¡Mi campana ha callado!", "¡Tramposo!"},
            fb_bl_final_bell_defeat_1 = {"Silencio cerúleo...", "ya no repico."},
            fb_bl_final_bell_gloat_1 = {"¡Ding dong,", "perdiste!"},
            fb_bl_final_bell_interrupted_1 = {"¿Salvado por la", "campana? ¡Esta vez no!"},
            fb_bl_final_bell_phase2_1 = {"¡Óyeme repicar", "más fuerte!"},
            fb_bl_final_bell_phase3_1 = {"¡La campanada final!"},
            fb_bl_final_bell_rematch_won_1 = {"La otra vez me", "diste un campanazo."},
            fb_bl_final_bell_rematch_lost_1 = {"La campana dobla", "por ti otra vez."},
        }
    }
}
