return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Duels finaux",
            fb_cfg_dialogue = "Dialogues des boss",
            fb_cfg_music = "Musique des duels",
            fb_cfg_fx = "Effets d'écran",
            fb_cfg_intro_speed = "Vitesse de l'intro",
            fb_speed_slow = "Lente",
            fb_speed_normal = "Normale",
            fb_speed_fast = "Rapide",
            fb_cfg_min_ante = "Dialogues dès la mise initiale",
            fb_cfg_dev_mode = "Touches dev (F5-F7)",
            fb_cfg_showdown_enabled = "Calendrier de duels perso",
            fb_cfg_start_ante = "Premier duel à la mise",
            fb_cfg_every = "Puis toutes les N mises",
            fb_cfg_preview = "Duels aux mises initiales :",
            fb_cfg_hard = "Difficile ! Les duels précoces sont brutaux.",
            fb_cfg_next_ante = "Effectif dès la prochaine mise initiale.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Tu es allé trop loin..."},
            fb_opener_2 = {"Et j'ai le regret", "de dire..."},
            fb_opener_3 = {"Alors. Tu as réussi."},
            fb_closer_1 = {"Tu ne pourras pas", "me battre."},
            fb_closer_2 = {"C'est ici que ta", "partie s'arrête."},
            fb_closer_3 = {"Montre-moi ce que", "tu as dans le ventre."},
            fb_gloat = {"Ce boss était", "trop fort..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Je suis #1# !"},
            fb_generic_name_2 = {"On m'appelle", "#1#."},
            fb_generic_name_3 = {"Contemple :", "#1# !"},
            fb_generic_intro_1 = {"Ta chance", "s'arrête ici."},
            fb_generic_intro_2 = {"Voyons comment tu", "gères ça."},
            fb_generic_intro_3 = {"Lis bien", "mes règles..."},
            fb_generic_big_hand_1 = {"...Pas mal."},
            fb_generic_big_hand_2 = {"Main chanceuse."},
            fb_generic_big_hand_3 = {"Hmph. Encore ?"},
            fb_generic_close_1 = {"Attends, attends,", "ATTENDS !"},
            fb_generic_close_2 = {"N'ose même pas..."},
            fb_generic_close_3 = {"Ça ne se peut pas..."},
            fb_generic_last_hand_1 = {"Plus qu'une main.", "Fais-la compter."},
            fb_generic_last_hand_2 = {"Tic, tac..."},
            fb_generic_last_hand_3 = {"Dernière chance,", "petit joker."},
            fb_generic_disabled_1 = {"Mon pouvoir...!", "Qu'as-tu fait ?"},
            fb_generic_disabled_2 = {"Hé ! C'est de", "la triche !"},
            fb_generic_disabled_3 = {"Je me sens... faible."},
            fb_generic_defeat_1 = {"Impossible..."},
            fb_generic_defeat_2 = {"Je reviendrai à la", "prochaine mise..."},
            fb_generic_defeat_3 = {"Bien joué..."},
            fb_generic_gloat_1 = {"Ce boss était", "trop fort..."},
            fb_generic_gloat_2 = {"La banque", "gagne toujours."},
            fb_generic_gloat_3 = {"Plus de chance", "à la prochaine."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Mais je suis", "L'hameçon"},
            fb_bl_hook_intro_1 = {"Je prends quelques-unes", "de tes cartes"},
            fb_bl_hook_intro_2 = {"Deux cartes en moins,", "à chaque main."},
            fb_bl_hook_big_hand_1 = {"Même avec moins", "de cartes ?!"},
            fb_bl_hook_close_1 = {"Lâche ces", "cartes !"},
            fb_bl_hook_last_hand_1 = {"Ferré, enfin !"},
            fb_bl_hook_disabled_1 = {"Mon hameçon !", "Il est cassé !"},
            fb_bl_hook_defeat_1 = {"Bon... je te", "laisse filer."},
            fb_bl_hook_gloat_1 = {"L'hameçon :", "\"Tu as mordu !\""},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Mais je suis", "Le bœuf"},
            fb_bl_ox_intro_1 = {"Je prends tout", "ton argent"},
            fb_bl_ox_intro_2 = {"Ta main préférée", "te coûte tout."},
            fb_bl_ox_big_hand_1 = {"Fauché et tu", "gagnes encore ?!"},
            fb_bl_ox_close_1 = {"Calmos, cowboy !", "...Moi aussi."},
            fb_bl_ox_last_hand_1 = {"Dernière main.", "Dépense ou perds."},
            fb_bl_ox_disabled_1 = {"Mes cornes !", "Elles sont émoussées !"},
            fb_bl_ox_defeat_1 = {"Tu as pris le", "taureau par les cornes."},
            fb_bl_ox_gloat_1 = {"Le bœuf :", "\"Te voilà fauché !\""},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Mais je suis", "La maison"},
            fb_bl_house_intro_1 = {"Tu es", "AVEUGLE !"},
            fb_bl_house_intro_2 = {"La première main,", "c'est maison. Aveugle !"},
            fb_bl_house_big_hand_1 = {"À l'aveugle et tu", "gagnes quand même ?!"},
            fb_bl_house_close_1 = {"La maison", "ne perd jamais !"},
            fb_bl_house_last_hand_1 = {"Fini la chance", "à l'aveugle."},
            fb_bl_house_disabled_1 = {"Mon bandeau !", "Il est tombé !"},
            fb_bl_house_defeat_1 = {"La maison...", "s'est effondrée."},
            fb_bl_house_gloat_1 = {"La maison :", "\"La maison gagne !\""},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Mais je suis", "Le mur"},
            fb_bl_wall_intro_1 = {"Tu viens d'en", "heurter un"},
            fb_bl_wall_intro_2 = {"Essaie d'escalader", "ce score."},
            fb_bl_wall_big_hand_1 = {"Tu as escaladé", "mon mur ?!"},
            fb_bl_wall_close_1 = {"Tu ne passeras", "pas !"},
            fb_bl_wall_last_hand_1 = {"Plus rien", "à escalader."},
            fb_bl_wall_disabled_1 = {"Des fissures ! Mon", "mur se fissure !"},
            fb_bl_wall_defeat_1 = {"Le mur...", "s'écroule."},
            fb_bl_wall_gloat_1 = {"Le mur :", "\"Tu fonces dans le mur !\""},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Mais je suis", "La roue"},
            fb_bl_wheel_intro_1 = {"J'aime...", "LE JEU !"},
            fb_bl_wheel_intro_2 = {"Une carte sur sept", "arrive face cachée."},
            fb_bl_wheel_big_hand_1 = {"Dame Fortune", "t'aime bien."},
            fb_bl_wheel_close_1 = {"Ma roue", "déraille !"},
            fb_bl_wheel_last_hand_1 = {"Dernier tour.", "Tu te sens chanceux ?"},
            fb_bl_wheel_disabled_1 = {"La roue s'arrête ?", "Truqué !"},
            fb_bl_wheel_defeat_1 = {"La roue de la", "fortune tourne..."},
            fb_bl_wheel_gloat_1 = {"La roue :", "\"Roue libre, perdu !\""},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Mais je suis", "Le bras"},
            fb_bl_arm_intro_1 = {"Je vais équilibrer", "ta puissance"},
            fb_bl_arm_intro_2 = {"Chaque main jouée", "perd un niveau."},
            fb_bl_arm_big_hand_1 = {"Cette main a", "du muscle..."},
            fb_bl_arm_close_1 = {"Bras de fer ?", "Je perds !"},
            fb_bl_arm_last_hand_1 = {"Dernière main.", "Pas de zèle."},
            fb_bl_arm_disabled_1 = {"Mon bras est mou !", "Tricheur !"},
            fb_bl_arm_defeat_1 = {"Tu as vaincu", "mon bras fort."},
            fb_bl_arm_gloat_1 = {"Le bras :", "\"Rétrogradé !\""},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Mais je suis", "Le club"},
            fb_bl_club_intro_1 = {"Je déteste les", "{C:green,E:1}chanceux{}"},
            fb_bl_club_intro_2 = {"Les trèfles sont", "affaiblis. Désolé."},
            fb_bl_club_big_hand_1 = {"Sans trèfles, pas", "de souci ?!"},
            fb_bl_club_close_1 = {"Ne me tape pas", "avec ça !"},
            fb_bl_club_last_hand_1 = {"Dernière main.", "Laisse les trèfles."},
            fb_bl_club_disabled_1 = {"Mes trèfles ont", "perdu leur mordant !"},
            fb_bl_club_defeat_1 = {"Le club ferme.", "Il est temps d'y aller."},
            fb_bl_club_gloat_1 = {"Le club :", "\"Soirée terminée !\""},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Mais je suis", "Le poisson"},
            fb_bl_fish_intro_1 = {"Sois sûr de ce que", "tu veux jouer"},
            fb_bl_fish_intro_2 = {"Après chaque main,", "cartes face cachée."},
            fb_bl_fish_big_hand_1 = {"Il y a anguille", "sous roche !"},
            fb_bl_fish_close_1 = {"Ne me ramène", "pas à terre !"},
            fb_bl_fish_last_hand_1 = {"Dernier lancer.", "Ramène-le."},
            fb_bl_fish_disabled_1 = {"Mes écailles !", "Elles sont tombées !"},
            fb_bl_fish_defeat_1 = {"Ferré...", "par un pro."},
            fb_bl_fish_gloat_1 = {"Le poisson :", "\"T'es à l'eau !\""},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Mais je suis", "Le médium"},
            fb_bl_psychic_intro_1 = {"Je déteste les", "indécis"},
            fb_bl_psychic_intro_2 = {"Cinq cartes, pas", "moins. Je l'avais vu."},
            fb_bl_psychic_big_hand_1 = {"Ça, je ne l'ai PAS", "vu venir."},
            fb_bl_psychic_close_1 = {"Ma boule de cristal", "montre... la défaite !"},
            fb_bl_psychic_last_hand_1 = {"Je vois ta", "dernière main."},
            fb_bl_psychic_disabled_1 = {"Mes visions !", "Elles ont disparu !"},
            fb_bl_psychic_defeat_1 = {"Je l'avais vu venir.", "...Ou pas ?"},
            fb_bl_psychic_gloat_1 = {"Le médium :", "\"Je l'avais prédit !\""},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Mais je suis", "L'aiguillon"},
            fb_bl_goad_intro_1 = {"Je déteste le", "{C:black,E:1}POUVOIR{}"},
            fb_bl_goad_intro_2 = {"Piques affaiblis.", "Creuse plus profond."},
            fb_bl_goad_big_hand_1 = {"Pas mal sans", "tes piques."},
            fb_bl_goad_close_1 = {"N'ose pas creuser", "ma tombe !"},
            fb_bl_goad_last_hand_1 = {"Creuse. C'est ta", "dernière main."},
            fb_bl_goad_disabled_1 = {"Je ne peux plus", "piquer personne !"},
            fb_bl_goad_defeat_1 = {"Piqué au vif,", "tu as gagné."},
            fb_bl_goad_gloat_1 = {"L'aiguillon :", "\"Creuse ta tombe !\""},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Mais je suis", "L'eau"},
            fb_bl_water_intro_1 = {"Donne-moi", "tes défausses"},
            fb_bl_water_intro_2 = {"Zéro défausse.", "Pas une goutte."},
            fb_bl_water_big_hand_1 = {"Sans défausse et tu", "gagnes encore ?!"},
            fb_bl_water_close_1 = {"Je me noie !", "Lancez-moi une corde !"},
            fb_bl_water_last_hand_1 = {"Dernière main.", "Coule ou nage."},
            fb_bl_water_disabled_1 = {"Les défausses", "coulent à nouveau !"},
            fb_bl_water_defeat_1 = {"Je suis à sec..."},
            fb_bl_water_gloat_1 = {"L'eau :", "\"Tu es lessivé !\""},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Mais je suis", "La fenêtre"},
            fb_bl_window_intro_1 = {"Je déteste le", "{C:yellow,E:1}capitalisme{}"},
            fb_bl_window_intro_2 = {"Carreaux affaiblis.", "Brille toujours."},
            fb_bl_window_big_hand_1 = {"Qui a besoin de", "carreaux ?"},
            fb_bl_window_close_1 = {"Ne casse pas", "ma fenêtre !"},
            fb_bl_window_last_hand_1 = {"Dernière main.", "Pas de bling."},
            fb_bl_window_disabled_1 = {"Ma vitre est brisée !", "Les carreaux brillent !"},
            fb_bl_window_defeat_1 = {"Ma fenêtre de tir", "s'est refermée."},
            fb_bl_window_gloat_1 = {"La fenêtre :", "\"Carreaux ? Affaiblis !\""},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Mais je suis", "Les menottes"},
            fb_bl_manacle_intro_1 = {"Je te prends", "tes {C:blue,E:1}options{}"},
            fb_bl_manacle_intro_2 = {"Une carte de moins", "en main."},
            fb_bl_manacle_big_hand_1 = {"Enchaîné et tu", "gagnes encore ?!"},
            fb_bl_manacle_close_1 = {"Tu te libères", "de tes chaînes !"},
            fb_bl_manacle_last_hand_1 = {"Dernière main.", "Même menotté."},
            fb_bl_manacle_disabled_1 = {"Les fers !", "Ils sont tombés !"},
            fb_bl_manacle_defeat_1 = {"Libre enfin...", "de moi."},
            fb_bl_manacle_gloat_1 = {"Les menottes :", "\"Les mains liées !\""},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Mais je suis", "L'œil"},
            fb_bl_eye_intro_1 = {"Je n'aime pas", "la routine"},
            fb_bl_eye_intro_2 = {"Jamais deux fois le", "même type de main."},
            fb_bl_eye_big_hand_1 = {"Une nouvelle main ?", "Je te vois."},
            fb_bl_eye_close_1 = {"Je ne peux pas", "regarder !"},
            fb_bl_eye_last_hand_1 = {"Je vois ta", "dernière main."},
            fb_bl_eye_disabled_1 = {"Mon œil ! Qui m'a", "mis le doigt dedans ?!"},
            fb_bl_eye_defeat_1 = {"Loin des yeux,", "loin du cœur..."},
            fb_bl_eye_gloat_1 = {"L'œil :", "\"Je te l'avais dit !\""},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Mais je suis", "La bouche"},
            fb_bl_mouth_intro_1 = {"J'adore", "la routine"},
            fb_bl_mouth_intro_2 = {"Choisis un type de", "main et tiens-t'y."},
            fb_bl_mouth_big_hand_1 = {"Toujours la même,", "toujours forte..."},
            fb_bl_mouth_close_1 = {"Ma bouche est", "grande ouverte !"},
            fb_bl_mouth_last_hand_1 = {"Dernière main.", "Même type. Motus."},
            fb_bl_mouth_disabled_1 = {"Qui m'a bâillonné ?!"},
            fb_bl_mouth_defeat_1 = {"Je reste sans voix..."},
            fb_bl_mouth_gloat_1 = {"La bouche :", "\"Ferme-la, perdant !\""},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Mais je suis", "La plante"},
            fb_bl_plant_intro_1 = {"Je déteste les", "visages aimables"},
            fb_bl_plant_intro_2 = {"Rois, dames, valets :", "tous affaiblis."},
            fb_bl_plant_big_hand_1 = {"Sans figures ?!", "Incroyable."},
            fb_bl_plant_close_1 = {"Ne m'arrache pas", "par les racines !"},
            fb_bl_plant_last_hand_1 = {"Affronte ta", "dernière main."},
            fb_bl_plant_disabled_1 = {"Mes pétales !", "Ils sont tous partis !"},
            fb_bl_plant_defeat_1 = {"Fanée...", "Je repousserai."},
            fb_bl_plant_gloat_1 = {"La plante :", "\"Face à la défaite !\""},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Mais je suis", "Le serpent"},
            fb_bl_serpent_intro_1 = {"Il y a", "un déficit"},
            fb_bl_serpent_intro_2 = {"Jouer ou défausser :", "tu piocheras 3 cartes."},
            fb_bl_serpent_big_hand_1 = {"Trois cartes. Et", "tu as frappé !"},
            fb_bl_serpent_close_1 = {"Ne rampe pas", "devant moi !"},
            fb_bl_serpent_last_hand_1 = {"Dernière morsure.", "Trois cartes."},
            fb_bl_serpent_disabled_1 = {"Mes crocs ! Sss...", "Plus de venin !"},
            fb_bl_serpent_defeat_1 = {"J'ai mué...", "et perdu ma fierté."},
            fb_bl_serpent_gloat_1 = {"Le serpent :", "\"Sss-alut, perdant !\""},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Mais je suis", "Le pilier"},
            fb_bl_pillar_intro_1 = {"J'ai beaucoup appris", "de tes mains passées"},
            fb_bl_pillar_intro_2 = {"Les cartes jouées", "restent affaiblies."},
            fb_bl_pillar_big_hand_1 = {"Des cartes neuves ?", "Malin."},
            fb_bl_pillar_close_1 = {"Mon pilier", "s'effrite !"},
            fb_bl_pillar_last_hand_1 = {"Dernière main.", "Les vieilles : inutiles."},
            fb_bl_pillar_disabled_1 = {"Ma mémoire !", "Elle... s'efface."},
            fb_bl_pillar_defeat_1 = {"Un pilier de la", "communauté est tombé."},
            fb_bl_pillar_gloat_1 = {"Le pilier :", "\"Toujours debout !\""},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Mais je suis", "L'aiguille"},
            fb_bl_needle_intro_1 = {"Tu n'as qu'une", "seule chance"},
            fb_bl_needle_intro_2 = {"Une main. C'est tout", "ce que tu auras."},
            fb_bl_needle_big_hand_1 = {"Une seule main,", "aussi forte ?!"},
            fb_bl_needle_close_1 = {"Non ! Pas avec", "une seule main !"},
            fb_bl_needle_last_hand_1 = {"Cette main est", "ta seule main."},
            fb_bl_needle_disabled_1 = {"Mon aiguille !", "Elle est émoussée !"},
            fb_bl_needle_defeat_1 = {"Jeu pointu.", "Tu m'as eu."},
            fb_bl_needle_gloat_1 = {"L'aiguille :", "\"Piqué au vif !\""},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Mais je suis", "La tête"},
            fb_bl_head_intro_1 = {"Je déteste les", "{C:red,E:1}amoureux{}"},
            fb_bl_head_intro_2 = {"Cœurs affaiblis.", "Froid, non ?"},
            fb_bl_head_big_hand_1 = {"Tu as gagné sans", "cœur ?!"},
            fb_bl_head_close_1 = {"Aie un cœur,", "ne m'achève pas !"},
            fb_bl_head_last_hand_1 = {"Dernière main. Sans", "cœur. Sans pitié."},
            fb_bl_head_disabled_1 = {"J'ai mal à la tête !", "Les cœurs remarchent ?"},
            fb_bl_head_defeat_1 = {"J'ai perdu la tête...", "pour toi."},
            fb_bl_head_gloat_1 = {"La tête :", "\"Sans cœur, hein ?\""},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Mais je suis", "La dent"},
            fb_bl_tooth_intro_1 = {"Je m'intéresse", "à la politique"},
            fb_bl_tooth_intro_2 = {"Chaque carte jouée", "te coûte 1 $."},
            fb_bl_tooth_big_hand_1 = {"Tu as payé et tu", "gagnes encore ?!"},
            fb_bl_tooth_close_1 = {"Ne me fais pas", "voir la petite souris !"},
            fb_bl_tooth_last_hand_1 = {"Dernière main,", "derniers dollars."},
            fb_bl_tooth_disabled_1 = {"Ma morsure !", "Elle a disparu !"},
            fb_bl_tooth_defeat_1 = {"Bec et ongles,", "j'ai perdu."},
            fb_bl_tooth_gloat_1 = {"La dent :", "\"Crache au bassinet !\""},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Mais je suis", "Le silex"},
            fb_bl_flint_intro_1 = {"Tu dois", "payer des impôts"},
            fb_bl_flint_intro_2 = {"Jetons et Multi.", "sont réduits de moitié."},
            fb_bl_flint_big_hand_1 = {"Moitié moins de", "force, et ça touche ?!"},
            fb_bl_flint_close_1 = {"Tu étincelles", "ma chute !"},
            fb_bl_flint_last_hand_1 = {"Dernière main.", "Moitié d'étincelle."},
            fb_bl_flint_disabled_1 = {"Pleine puissance ?!", "Pas juste !"},
            fb_bl_flint_defeat_1 = {"Mon étincelle", "s'éteint."},
            fb_bl_flint_gloat_1 = {"Le silex :", "\"Moitié moins de fun !\""},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Mais je suis", "La marque"},
            fb_bl_mark_intro_1 = {"Je n'aime pas", "être vue"},
            fb_bl_mark_intro_2 = {"Toutes les figures", "arrivent face cachée."},
            fb_bl_mark_big_hand_1 = {"Cartes marquées,", "et tu gagnes ?!"},
            fb_bl_mark_close_1 = {"Je suis marquée", "pour la défaite !"},
            fb_bl_mark_last_hand_1 = {"Dernière main.", "Choisis à l'aveugle."},
            fb_bl_mark_disabled_1 = {"Les visages !", "Je les vois !"},
            fb_bl_mark_defeat_1 = {"Tu as laissé ta", "marque sur moi."},
            fb_bl_mark_gloat_1 = {"La marque :", "\"Marqué pour perdre !\""},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Mais je suis", "Gland ambre"},
            fb_bl_final_acorn_intro_1 = {"J'aime", "LE CHAOS !"},
            fb_bl_final_acorn_intro_2 = {"Jokers retournés,", "puis mélangés !"},
            fb_bl_final_acorn_big_hand_1 = {"Même dans le chaos,", "tu gagnes ?!"},
            fb_bl_final_acorn_close_1 = {"C'est dingue !", "Je me fissure !"},
            fb_bl_final_acorn_last_hand_1 = {"Dernière main. Où", "est ton joker ?"},
            fb_bl_final_acorn_disabled_1 = {"Mon gland !", "L'ordre revient ?!"},
            fb_bl_final_acorn_defeat_1 = {"Tu as brisé", "ma coquille..."},
            fb_bl_final_acorn_gloat_1 = {"Gland ambre :", "\"Complètement glandu !\""},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Mais je suis", "Feuille verte"},
            fb_bl_final_leaf_intro_1 = {"Tu dois te détacher", "de tes racines"},
            fb_bl_final_leaf_intro_2 = {"Vends un joker ou", "reste affaibli."},
            fb_bl_final_leaf_big_hand_1 = {"Tu tournes la page.", "Hmph."},
            fb_bl_final_leaf_close_1 = {"Ma feuille", "tombe !"},
            fb_bl_final_leaf_last_hand_1 = {"Dernière main.", "Vendre un joker ?"},
            fb_bl_final_leaf_disabled_1 = {"Ma feuille !", "Elle a séché !"},
            fb_bl_final_leaf_defeat_1 = {"Je m'en vais...", "comme une feuille."},
            fb_bl_final_leaf_gloat_1 = {"Feuille verte :", "\"Feuille morte !\""},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Mais je suis", "Vase violet"},
            fb_bl_final_vessel_intro_1 = {"Tu viens de heurter", "la grande muraille"},
            fb_bl_final_vessel_intro_2 = {"Une blinde immense.", "Largue les amarres !"},
            fb_bl_final_vessel_big_hand_1 = {"Un énorme coup sur", "une énorme cible."},
            fb_bl_final_vessel_close_1 = {"Tout le monde à l'eau !", "...Moi, je veux dire."},
            fb_bl_final_vessel_last_hand_1 = {"Dernière main. Ce", "vase ne coulera pas."},
            fb_bl_final_vessel_disabled_1 = {"Mon vase !", "Il coule !"},
            fb_bl_final_vessel_defeat_1 = {"Le vase...", "a été vidé."},
            fb_bl_final_vessel_gloat_1 = {"Vase violet :", "\"Naufrage total !\""},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Mais je suis", "Cœur écarlate"},
            fb_bl_final_heart_intro_1 = {"Je vais t'emprunter", "un joker"},
            fb_bl_final_heart_intro_2 = {"À chaque main, un joker", "perd son pouvoir."},
            fb_bl_final_heart_big_hand_1 = {"Un joker en moins et", "toujours fort ?"},
            fb_bl_final_heart_close_1 = {"Ne me brise pas", "le cœur !"},
            fb_bl_final_heart_last_hand_1 = {"Dernière main. Quel", "joker est muet ?"},
            fb_bl_final_heart_disabled_1 = {"Mon cœur ! Il a", "raté un battement."},
            fb_bl_final_heart_defeat_1 = {"Mon cœur...", "est brisé."},
            fb_bl_final_heart_gloat_1 = {"Cœur écarlate :", "\"Le cœur brisé ?\""},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Mais je suis", "Cloche céruléenne"},
            fb_bl_final_bell_intro_1 = {"J'aimerais", "te guider"},
            fb_bl_final_bell_intro_2 = {"Une carte est forcée", "dans chaque main."},
            fb_bl_final_bell_big_hand_1 = {"Tu fais sonner ma", "carte forcée ?!"},
            fb_bl_final_bell_close_1 = {"Le glas sonne...", "pour moi ?!"},
            fb_bl_final_bell_last_hand_1 = {"Dernière main. Une", "carte est forcée."},
            fb_bl_final_bell_disabled_1 = {"Ma cloche est muette !", "Tricheur !"},
            fb_bl_final_bell_defeat_1 = {"Le glas sonne", "pour moi."},
            fb_bl_final_bell_gloat_1 = {"Cloche céruléenne :", "\"Ding dong, perdu !\""},
        }
    }
}
