return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Duel Final",
            fb_cfg_dialogue = "Dialog boss",
            fb_cfg_music = "Musik duel final",
            fb_cfg_fx = "Efek layar",
            fb_cfg_cinematic = "Sinematik duel final",
            fb_showdown_title = "DUEL FINAL",
            fb_cfg_intro_speed = "Kecepatan intro",
            fb_speed_slow = "Lambat",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Cepat",
            fb_cfg_min_ante = "Dialog boss mulai Ante",
            fb_cfg_dev_mode = "Tombol developer (F5-F7)",
            fb_cfg_showdown_enabled = "Jadwal duel final kustom",
            fb_cfg_start_ante = "Ante duel final pertama",
            fb_cfg_every = "Lalu setiap N Ante",
            fb_cfg_preview = "Duel final di Ante",
            fb_cfg_hard = "Sulit! Duel final awal sangat brutal.",
            fb_cfg_next_ante = "Perubahan berlaku mulai Ante berikutnya.",
            fb_cfg_group_dialogue = "Dialog",
            fb_cfg_group_stage = "Panggung duel final",
            fb_credits_thanks = "Terima kasih sudah bermain dengan FinalBoss!",
            fb_credits_lead = "Dibuat dan dikelola oleh",
            fb_credits_music = "Musik duel final:",
            fb_credits_music_by = "Adam Isiah (cover orkestra)",
            fb_credits_listen = "Dengarkan di YouTube",
            fb_credits_github = "GitHub",
            fb_tip_me = "Beri Tip",
            fb_tip_me_message_1 = "Kalau kamu suka FinalBoss, pertimbangkan",
            fb_tip_me_message_2 = "memberi tip kecil sebagai dukungan.",
            fb_tip_me_message_3 = "Sangat saya hargai!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Boss membalas bicara dan duel final jadi pertarungan boss.", "Oleh {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Kamu sudah terlalu", "jauh..."},
            fb_opener_2 = {"Dan sayangnya,", "harus kubilang..."},
            fb_opener_3 = {"Jadi. Kamu sampai", "juga."},
            fb_closer_1 = {"Kamu tidak akan", "bisa mengalahkanku."},
            fb_closer_2 = {"Di sinilah run-mu", "berakhir."},
            fb_closer_3 = {"Tunjukkan apa", "yang kamu punya."},
            fb_gloat = {"Boss itu terlalu", "berat..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Aku #1#!"},
            fb_generic_name_2 = {"Mereka memanggilku", "#1#."},
            fb_generic_name_3 = {"Lihatlah:", "#1#!"},
            fb_generic_intro_1 = {"Keberuntunganmu", "berakhir di sini."},
            fb_generic_intro_2 = {"Coba lihat kamu", "mengatasi ini."},
            fb_generic_intro_3 = {"Baca aturanku", "baik-baik..."},
            fb_generic_big_hand_1 = {"...Lumayan."},
            fb_generic_big_hand_2 = {"Tangan beruntung."},
            fb_generic_big_hand_3 = {"Hmph. Lagi?"},
            fb_generic_close_1 = {"Tunggu, tunggu,", "TUNGGU!"},
            fb_generic_close_2 = {"Jangan berani-berani..."},
            fb_generic_close_3 = {"Ini tidak mungkin..."},
            fb_generic_last_hand_1 = {"Tinggal satu hand.", "Buat itu berarti."},
            fb_generic_last_hand_2 = {"Tik, tok..."},
            fb_generic_last_hand_3 = {"Kesempatan terakhir,", "joker kecil."},
            fb_generic_disabled_1 = {"Kekuatanku...!", "Apa yang kamu lakukan?"},
            fb_generic_disabled_2 = {"Hei! Itu curang!"},
            fb_generic_disabled_3 = {"Aku merasa... lemah."},
            fb_generic_defeat_1 = {"Mustahil..."},
            fb_generic_defeat_2 = {"Aku akan kembali", "di Ante berikutnya..."},
            fb_generic_defeat_3 = {"Mainmu bagus..."},
            fb_generic_gloat_1 = {"Boss itu terlalu", "berat..."},
            fb_generic_gloat_2 = {"Bandar selalu", "menang."},
            fb_generic_gloat_3 = {"Semoga lebih hoki", "di run berikutnya."},
            fb_generic_interrupted_1 = {"Pidatoku!"},
            fb_generic_interrupted_2 = {"Oke... jadi", "begitu caranya."},
            fb_generic_interrupted_3 = {"Tak ada salam?"},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Tapi aku", "The Hook"},
            fb_bl_hook_intro_1 = {"Kuambil beberapa", "kartumu"},
            fb_bl_hook_intro_2 = {"Dua kartu hilang,", "tiap hand."},
            fb_bl_hook_big_hand_1 = {"Kartu berkurang pun", "masih menang?!"},
            fb_bl_hook_close_1 = {"Lepaskan kartu", "itu!"},
            fb_bl_hook_last_hand_1 = {"Akhirnya kamu", "terkait kailku!"},
            fb_bl_hook_disabled_1 = {"Kailku!", "Patah!"},
            fb_bl_hook_defeat_1 = {"Baiklah... kamu", "kulepas."},
            fb_bl_hook_gloat_1 = {"Kena kail!"},
            fb_bl_hook_interrupted_1 = {"Kurang ajar! Aku", "belum selesai bicara!"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Tapi aku", "The Ox"},
            fb_bl_ox_intro_1 = {"Kuambil semua", "uangmu"},
            fb_bl_ox_intro_2 = {"Hand favoritmu", "menghabiskan semuanya."},
            fb_bl_ox_big_hand_1 = {"Bokek tapi masih", "menang?!"},
            fb_bl_ox_close_1 = {"Pelan-pelan!", "...Aku juga."},
            fb_bl_ox_last_hand_1 = {"Hand terakhir.", "Habiskan atau hilang."},
            fb_bl_ox_disabled_1 = {"Tandukku!", "Jadi tumpul!"},
            fb_bl_ox_defeat_1 = {"Kamu memegang", "tanduk banteng..."},
            fb_bl_ox_gloat_1 = {"Sekarang", "kamu bokek!"},
            fb_bl_ox_interrupted_1 = {"Oh, jadi BEGINI", "maumu, ya."},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Tapi aku", "The House"},
            fb_bl_house_intro_1 = {"Kamu", "BUTA!"},
            fb_bl_house_intro_2 = {"Hand pertama", "tertutup. Buta!"},
            fb_bl_house_big_hand_1 = {"Hoki buta dan kamu", "masih menang?!"},
            fb_bl_house_close_1 = {"Bandar tidak", "pernah kalah!"},
            fb_bl_house_last_hand_1 = {"Tidak ada lagi", "hoki buta."},
            fb_bl_house_disabled_1 = {"Penutup mataku!", "Terlepas!"},
            fb_bl_house_defeat_1 = {"The House...", "telah runtuh."},
            fb_bl_house_gloat_1 = {"Bandar menang!"},
            fb_bl_house_interrupted_1 = {"Aturan rumah:", "belum boleh main!"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Tapi aku", "The Wall"},
            fb_bl_wall_intro_1 = {"Kamu baru saja", "menabraknya"},
            fb_bl_wall_intro_2 = {"Coba panjat", "skor ini."},
            fb_bl_wall_big_hand_1 = {"Kamu memanjat", "tembokku?!"},
            fb_bl_wall_close_1 = {"Kamu tidak bisa", "menembusnya!"},
            fb_bl_wall_last_hand_1 = {"Tidak ada lagi", "yang bisa dipanjat."},
            fb_bl_wall_disabled_1 = {"Retak! Tembokku", "retak!"},
            fb_bl_wall_defeat_1 = {"Tembok...", "pun runtuh."},
            fb_bl_wall_gloat_1 = {"Mentok, kan?"},
            fb_bl_wall_interrupted_1 = {"Seperti bicara", "ke tembok... eh."},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Tapi aku", "The Wheel"},
            fb_bl_wheel_intro_1 = {"Aku suka...", "JUDI!"},
            fb_bl_wheel_intro_2 = {"Satu dari tujuh kartu", "datang tertutup."},
            fb_bl_wheel_big_hand_1 = {"Dewi Fortuna sayang", "kamu hari ini."},
            fb_bl_wheel_close_1 = {"Rodaku", "oleng!"},
            fb_bl_wheel_last_hand_1 = {"Putaran terakhir.", "Merasa hoki?"},
            fb_bl_wheel_disabled_1 = {"Roda berhenti?", "Curang!"},
            fb_bl_wheel_defeat_1 = {"Roda nasib...", "berbalik padaku."},
            fb_bl_wheel_gloat_1 = {"Roda berputar,", "kalah!"},
            fb_bl_wheel_interrupted_1 = {"Sabar! Aku masih", "berputar!"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Tapi aku", "The Arm"},
            fb_bl_arm_intro_1 = {"Akan kuseimbangkan", "kekuatanmu"},
            fb_bl_arm_intro_2 = {"Tiap hand yang kamu", "mainkan turun level."},
            fb_bl_arm_big_hand_1 = {"Hand itu ada", "ototnya..."},
            fb_bl_arm_close_1 = {"Adu panco?", "Aku kalah!"},
            fb_bl_arm_last_hand_1 = {"Satu hand lagi.", "Jangan pamer otot."},
            fb_bl_arm_disabled_1 = {"Lenganku lemas!", "Curang!"},
            fb_bl_arm_defeat_1 = {"Kamu mengalahkan", "lengan kuatku."},
            fb_bl_arm_gloat_1 = {"Turun level!"},
            fb_bl_arm_interrupted_1 = {"Lepaskan! Aku belum", "selesai pamer otot!"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Tapi aku", "The Club"},
            fb_bl_club_intro_1 = {"Aku benci pemain", "{C:green,E:1}hoki{}"},
            fb_bl_club_intro_2 = {"Keriting di-debuff.", "Maaf."},
            fb_bl_club_big_hand_1 = {"Tanpa keriting,", "tak masalah?!"},
            fb_bl_club_close_1 = {"Jangan pukul aku", "dengan itu!"},
            fb_bl_club_last_hand_1 = {"Hand terakhir. Tinggal", "keritingmu di rumah."},
            fb_bl_club_disabled_1 = {"Keritingku", "kehilangan taring!"},
            fb_bl_club_defeat_1 = {"Klub tutup.", "Saatnya pergi..."},
            fb_bl_club_gloat_1 = {"Klub tutup,", "kamu kalah!"},
            fb_bl_club_interrupted_1 = {"Hei! Di klubku,", "aku bicara duluan."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Tapi aku", "The Fish"},
            fb_bl_fish_intro_1 = {"Pastikan dulu apa", "yang mau kamu mainkan"},
            fb_bl_fish_intro_2 = {"Tiap hand, kartu", "datang tertutup."},
            fb_bl_fish_big_hand_1 = {"Ada yang amis dari", "hand itu!"},
            fb_bl_fish_close_1 = {"Jangan tarik", "aku ke darat!"},
            fb_bl_fish_last_hand_1 = {"Lemparan terakhir.", "Tarik talinya."},
            fb_bl_fish_disabled_1 = {"Sisikku!", "Rontok semua!"},
            fb_bl_fish_defeat_1 = {"Tertangkap...", "oleh sang ahli."},
            fb_bl_fish_gloat_1 = {"Kamu basah kuyup!"},
            fb_bl_fish_interrupted_1 = {"Kamu memotong", "tali pancingku!"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Tapi aku", "The Psychic"},
            fb_bl_psychic_intro_1 = {"Aku benci pemain", "yang ragu-ragu"},
            fb_bl_psychic_intro_2 = {"Lima kartu, tidak", "kurang. Sudah kuduga."},
            fb_bl_psychic_big_hand_1 = {"Itu TIDAK", "kuduga."},
            fb_bl_psychic_close_1 = {"Bola kristalku", "menunjukkan... kalah!"},
            fb_bl_psychic_last_hand_1 = {"Kulihat hand", "terakhirmu."},
            fb_bl_psychic_disabled_1 = {"Penglihatanku!", "Hilang semua!"},
            fb_bl_psychic_defeat_1 = {"Sudah kuduga.", "...Atau tidak?"},
            fb_bl_psychic_gloat_1 = {"Sudah kuduga!"},
            fb_bl_psychic_interrupted_1 = {"Sudah kuduga.", "...Tetap tidak sopan."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Tapi aku", "The Goad"},
            fb_bl_goad_intro_1 = {"Aku benci", "{C:black,E:1}KEKUASAAN{}"},
            fb_bl_goad_intro_2 = {"Sekop di-debuff.", "Gali lebih dalam."},
            fb_bl_goad_big_hand_1 = {"Lumayan tanpa", "sekopmu."},
            fb_bl_goad_close_1 = {"Jangan berani menggali", "kuburku!"},
            fb_bl_goad_last_hand_1 = {"Gali dalam-dalam. Ini", "hand terakhirmu."},
            fb_bl_goad_disabled_1 = {"Sekarang aku tak", "bisa memanas-manasi!"},
            fb_bl_goad_defeat_1 = {"Sialan,", "kamu menang."},
            fb_bl_goad_gloat_1 = {"Gali kuburmu", "sendiri!"},
            fb_bl_goad_interrupted_1 = {"Memancing AKU?", "Baiklah!"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Tapi aku", "The Water"},
            fb_bl_water_intro_1 = {"Serahkan", "discard-mu"},
            fb_bl_water_intro_2 = {"Tanpa discard.", "Setetes pun tidak."},
            fb_bl_water_big_hand_1 = {"Tanpa discard masih", "menang?!"},
            fb_bl_water_close_1 = {"Aku tenggelam!", "Lempar tali!"},
            fb_bl_water_last_hand_1 = {"Hand terakhir.", "Berenang atau tenggelam."},
            fb_bl_water_disabled_1 = {"Discard mengalir", "lagi!"},
            fb_bl_water_defeat_1 = {"Aku kering kerontang..."},
            fb_bl_water_gloat_1 = {"Kamu hanyut!"},
            fb_bl_water_interrupted_1 = {"Memotongku? Kamu", "akan tenggelam!"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Tapi aku", "The Window"},
            fb_bl_window_intro_1 = {"Aku benci", "{C:yellow,E:1}kapitalisme{}"},
            fb_bl_window_intro_2 = {"Wajik di-debuff.", "Terus bersinar."},
            fb_bl_window_big_hand_1 = {"Siapa butuh", "wajik?"},
            fb_bl_window_close_1 = {"Jangan pecahkan", "jendelaku!"},
            fb_bl_window_last_hand_1 = {"Hand terakhir. Dilarang", "berkilau."},
            fb_bl_window_disabled_1 = {"Jendelaku pecah!", "Wajik bersinar!"},
            fb_bl_window_defeat_1 = {"Jendela peluangku", "tertutup."},
            fb_bl_window_gloat_1 = {"Wajik? Di-debuff!"},
            fb_bl_window_interrupted_1 = {"Kata-kataku dibuang", "ke luar jendela?!"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Tapi aku", "The Manacle"},
            fb_bl_manacle_intro_1 = {"Kuambil", "{C:blue,E:1}pilihanmu{}"},
            fb_bl_manacle_intro_2 = {"Satu kartu lebih", "sedikit di tangan."},
            fb_bl_manacle_big_hand_1 = {"Terborgol tapi masih", "menang?!"},
            fb_bl_manacle_close_1 = {"Kamu lepas dari", "rantaiku!"},
            fb_bl_manacle_last_hand_1 = {"Hand terakhir. Dalam", "borgol pula."},
            fb_bl_manacle_disabled_1 = {"Borgolnya!", "Terlepas!"},
            fb_bl_manacle_defeat_1 = {"Akhirnya bebas...", "dariku."},
            fb_bl_manacle_gloat_1 = {"Tanganmu", "terborgol!"},
            fb_bl_manacle_interrupted_1 = {"Berhenti! Akan", "kurantai kamu!"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Tapi aku", "The Eye"},
            fb_bl_eye_intro_1 = {"Aku tak suka", "rutinitas"},
            fb_bl_eye_intro_2 = {"Jangan mainkan jenis", "hand sama dua kali."},
            fb_bl_eye_big_hand_1 = {"Hand baru, ya?", "Kulihat kamu."},
            fb_bl_eye_close_1 = {"Aku tak tega", "melihatnya!"},
            fb_bl_eye_last_hand_1 = {"Mataku mengawasi", "hand terakhirmu."},
            fb_bl_eye_disabled_1 = {"Mataku! Siapa yang", "menusuk mataku?!"},
            fb_bl_eye_defeat_1 = {"Jauh di mata,", "jauh di hati..."},
            fb_bl_eye_gloat_1 = {"Sudah kubilang!"},
            fb_bl_eye_interrupted_1 = {"Aku melihatnya!", "Tidak sopan."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Tapi aku", "The Mouth"},
            fb_bl_mouth_intro_1 = {"Aku suka", "rutinitas"},
            fb_bl_mouth_intro_2 = {"Pilih satu jenis hand", "dan patuhi."},
            fb_bl_mouth_big_hand_1 = {"Hand yang itu-itu", "saja, tetap kuat..."},
            fb_bl_mouth_close_1 = {"Mulutku", "menganga lebar!"},
            fb_bl_mouth_last_hand_1 = {"Hand terakhir. Jenis", "sama. Diam kamu."},
            fb_bl_mouth_disabled_1 = {"Siapa yang", "membungkamku?!"},
            fb_bl_mouth_defeat_1 = {"Aku kehabisan kata..."},
            fb_bl_mouth_gloat_1 = {"Diam, pecundang!"},
            fb_bl_mouth_interrupted_1 = {"Hei! Mulut ini", "masih bicara!"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Tapi aku", "The Plant"},
            fb_bl_plant_intro_1 = {"Aku benci", "wajah-wajah ramah"},
            fb_bl_plant_intro_2 = {"Raja, ratu, jack:", "semua di-debuff."},
            fb_bl_plant_big_hand_1 = {"Tanpa kartu wajah?!", "Luar biasa."},
            fb_bl_plant_close_1 = {"Jangan cabut aku", "sampai ke akar!"},
            fb_bl_plant_last_hand_1 = {"Hadapi hand", "terakhirmu."},
            fb_bl_plant_disabled_1 = {"Kelopakku!", "Hilang semua!"},
            fb_bl_plant_defeat_1 = {"Layu...", "Aku akan tumbuh lagi."},
            fb_bl_plant_gloat_1 = {"Akui saja,", "kamu kalah!"},
            fb_bl_plant_interrupted_1 = {"Biarkan aku tumbuh", "dulu, tak sabaran!"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Tapi aku", "The Serpent"},
            fb_bl_serpent_intro_1 = {"Ada", "defisit"},
            fb_bl_serpent_intro_2 = {"Main atau discard,", "kamu hanya tarik 3."},
            fb_bl_serpent_big_hand_1 = {"Tiga kartu. Dan", "kamu tetap menyerang!"},
            fb_bl_serpent_close_1 = {"Jangan kabur", "sekarang!"},
            fb_bl_serpent_last_hand_1 = {"Patukan terakhir.", "Tiga kartu."},
            fb_bl_serpent_disabled_1 = {"Taringku! Sss...", "Bisaku habis!"},
            fb_bl_serpent_defeat_1 = {"Kulit kulepas...", "begitu juga harga diri."},
            fb_bl_serpent_gloat_1 = {"Sss-ampai jumpa!"},
            fb_bl_serpent_interrupted_1 = {"Sss! Jangan", "potong omonganku!"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Tapi aku", "The Pillar"},
            fb_bl_pillar_intro_1 = {"Aku banyak belajar", "dari hand-mu dulu"},
            fb_bl_pillar_intro_2 = {"Kartu yang dimainkan", "di-debuff Ante ini."},
            fb_bl_pillar_big_hand_1 = {"Kartu baru?", "Pintar."},
            fb_bl_pillar_close_1 = {"Pilarku", "runtuh!"},
            fb_bl_pillar_last_hand_1 = {"Hand terakhir. Kartu", "lama tak berguna."},
            fb_bl_pillar_disabled_1 = {"Ingatanku!", "Memudar..."},
            fb_bl_pillar_defeat_1 = {"Pilar komunitas", "telah tumbang."},
            fb_bl_pillar_gloat_1 = {"Masih tegak!"},
            fb_bl_pillar_interrupted_1 = {"Tak hormat pada", "yang lebih tua?"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Tapi aku", "The Needle"},
            fb_bl_needle_intro_1 = {"Kamu hanya punya", "satu kesempatan"},
            fb_bl_needle_intro_2 = {"Satu hand. Hanya", "itu yang kamu dapat."},
            fb_bl_needle_big_hand_1 = {"Satu hand saja,", "sekuat itu?!"},
            fb_bl_needle_close_1 = {"Tidak! Jangan dengan", "satu hand!"},
            fb_bl_needle_last_hand_1 = {"Hand ini adalah", "satu-satunya."},
            fb_bl_needle_disabled_1 = {"Jarumku!", "Tumpul!"},
            fb_bl_needle_defeat_1 = {"Permainan tajam.", "Kamu menang."},
            fb_bl_needle_gloat_1 = {"Intinya,", "kamu kalah!"},
            fb_bl_needle_interrupted_1 = {"Tajam sekali.", "Aku belum selesai!"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Tapi aku", "The Head"},
            fb_bl_head_intro_1 = {"Aku benci", "{C:red,E:1}pecinta{}"},
            fb_bl_head_intro_2 = {"Hati di-debuff.", "Dingin, kan?"},
            fb_bl_head_big_hand_1 = {"Kamu menang tanpa", "hati?!"},
            fb_bl_head_close_1 = {"Punya hati dong,", "jangan habisi aku!"},
            fb_bl_head_last_hand_1 = {"Hand terakhir. Tanpa", "hati. Tanpa ampun."},
            fb_bl_head_disabled_1 = {"Kepalaku sakit!", "Hati aktif lagi?"},
            fb_bl_head_defeat_1 = {"Kehilangan kepala...", "gara-gara kamu."},
            fb_bl_head_gloat_1 = {"Tak punya", "hati, ya?"},
            fb_bl_head_interrupted_1 = {"Hilang akal, ya?", "Aku sedang bicara!"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Tapi aku", "The Tooth"},
            fb_bl_tooth_intro_1 = {"Aku suka", "politik"},
            fb_bl_tooth_intro_2 = {"Tiap kartu yang kamu", "mainkan bayar $1."},
            fb_bl_tooth_big_hand_1 = {"Sudah bayar dan", "masih menang?!"},
            fb_bl_tooth_close_1 = {"Jangan paksa aku", "bayar peri gigi!"},
            fb_bl_tooth_last_hand_1 = {"Hand terakhir,", "dolar terakhir."},
            fb_bl_tooth_disabled_1 = {"Gigitanku!", "Hilang!"},
            fb_bl_tooth_defeat_1 = {"Habis-habisan,", "aku kalah."},
            fb_bl_tooth_gloat_1 = {"Bayar,", "dasar bodoh!"},
            fb_bl_tooth_interrupted_1 = {"Grr! Kamu akan", "membayarnya!"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Tapi aku", "The Flint"},
            fb_bl_flint_intro_1 = {"Kamu harus", "bayar pajak"},
            fb_bl_flint_intro_2 = {"Chip dan Mult", "dibagi dua."},
            fb_bl_flint_big_hand_1 = {"Setengah kekuatan,", "masih kena?!"},
            fb_bl_flint_close_1 = {"Kamu memercikkan", "kejatuhanku!"},
            fb_bl_flint_last_hand_1 = {"Hand terakhir.", "Setengah percikan."},
            fb_bl_flint_disabled_1 = {"Kekuatan penuh?!", "Tidak adil!"},
            fb_bl_flint_defeat_1 = {"Percikanku", "padam."},
            fb_bl_flint_gloat_1 = {"Seru setengah!"},
            fb_bl_flint_interrupted_1 = {"Jangan memercik!", "Aku sedang bicara!"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Tapi aku", "The Mark"},
            fb_bl_mark_intro_1 = {"Aku tak suka", "dilihat"},
            fb_bl_mark_intro_2 = {"Semua kartu wajah", "datang tertutup."},
            fb_bl_mark_big_hand_1 = {"Kartu bertanda,", "masih menang?!"},
            fb_bl_mark_close_1 = {"Aku ditandai", "untuk kalah!"},
            fb_bl_mark_last_hand_1 = {"Hand terakhir. Pilih", "wajah dengan buta."},
            fb_bl_mark_disabled_1 = {"Wajah-wajahnya!", "Aku bisa lihat!"},
            fb_bl_mark_defeat_1 = {"Kamu meninggalkan", "tanda padaku."},
            fb_bl_mark_gloat_1 = {"Ditandai kalah!"},
            fb_bl_mark_interrupted_1 = {"Dicatat. Kamu", "sudah kutandai."},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Tapi aku", "Amber Acorn"},
            fb_bl_final_acorn_intro_1 = {"Aku suka", "KEKACAUAN!"},
            fb_bl_final_acorn_intro_2 = {"Joker ditutup,", "lalu diacak!"},
            fb_bl_final_acorn_big_hand_1 = {"Di tengah kekacauan", "kamu menang?!"},
            fb_bl_final_acorn_close_1 = {"Ini gila!", "Aku retak!"},
            fb_bl_final_acorn_last_hand_1 = {"Hand terakhir. Di mana", "jokermu?"},
            fb_bl_final_acorn_disabled_1 = {"Acornku!", "Kembali teratur?!"},
            fb_bl_final_acorn_defeat_1 = {"Kamu memecahkan", "cangkangku..."},
            fb_bl_final_acorn_gloat_1 = {"Gila-gilaan!"},
            fb_bl_final_acorn_interrupted_1 = {"Tunggu! Aku bahkan", "belum bertunas!"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Tapi aku", "Verdant Leaf"},
            fb_bl_final_leaf_intro_1 = {"Kamu harus lepas", "dari akarmu"},
            fb_bl_final_leaf_intro_2 = {"Jual satu joker, atau", "tetap di-debuff."},
            fb_bl_final_leaf_big_hand_1 = {"Kamu membuka lembaran", "baru. Hmph."},
            fb_bl_final_leaf_close_1 = {"Daunku", "berguguran!"},
            fb_bl_final_leaf_last_hand_1 = {"Hand terakhir. Jual", "satu joker?"},
            fb_bl_final_leaf_disabled_1 = {"Daunku!", "Layu seketika!"},
            fb_bl_final_leaf_defeat_1 = {"Aku pergi...", "seperti daun gugur."},
            fb_bl_final_leaf_gloat_1 = {"Gugur, kamu kalah!"},
            fb_bl_final_leaf_interrupted_1 = {"Baiklah. Lewati", "basa-basinya."},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Tapi aku", "Violet Vessel"},
            fb_bl_final_vessel_intro_1 = {"Kamu baru saja", "menabrak tembok raksasa"},
            fb_bl_final_vessel_intro_2 = {"Blind yang amat besar.", "Berlayarlah!"},
            fb_bl_final_vessel_big_hand_1 = {"Pukulan besar ke", "sasaran besar."},
            fb_bl_final_vessel_close_1 = {"Tinggalkan kapal!", "...Kapalku, maksudku."},
            fb_bl_final_vessel_last_hand_1 = {"Hand terakhir. Kapal", "ini tak akan karam."},
            fb_bl_final_vessel_disabled_1 = {"Kapalku!", "Tenggelam!"},
            fb_bl_final_vessel_defeat_1 = {"Bejana ini...", "telah kosong."},
            fb_bl_final_vessel_gloat_1 = {"Kalah telak!"},
            fb_bl_final_vessel_interrupted_1 = {"Berlayar sebelum", "pidatoku? Berani."},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Tapi aku", "Crimson Heart"},
            fb_bl_final_heart_intro_1 = {"Aku akan meminjam", "sebuah joker"},
            fb_bl_final_heart_intro_2 = {"Tiap hand, satu joker", "kehilangan kekuatan."},
            fb_bl_final_heart_big_hand_1 = {"Satu joker hilang dan", "masih kuat?"},
            fb_bl_final_heart_close_1 = {"Jangan patahkan", "hatiku!"},
            fb_bl_final_heart_last_hand_1 = {"Hand terakhir. Joker", "mana yang bungkam?"},
            fb_bl_final_heart_disabled_1 = {"Hatiku! Detaknya", "terlewat."},
            fb_bl_final_heart_defeat_1 = {"Hatiku...", "patah."},
            fb_bl_final_heart_gloat_1 = {"Sudah patah hati?"},
            fb_bl_final_heart_interrupted_1 = {"Memotongku?", "Tak punya hati!"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Tapi aku", "Cerulean Bell"},
            fb_bl_final_bell_intro_1 = {"Aku ingin", "membimbingmu"},
            fb_bl_final_bell_intro_2 = {"Satu kartu dipaksa", "masuk tiap hand."},
            fb_bl_final_bell_big_hand_1 = {"Kartu paksaanku", "kamu buat berdentang?!"},
            fb_bl_final_bell_close_1 = {"Lonceng berdentang...", "untukku?!"},
            fb_bl_final_bell_last_hand_1 = {"Hand terakhir. Satu", "kartu dipaksa."},
            fb_bl_final_bell_disabled_1 = {"Loncengku bisu!", "Curang!"},
            fb_bl_final_bell_defeat_1 = {"Lonceng berdentang", "untukku."},
            fb_bl_final_bell_gloat_1 = {"Ting tong,", "kamu kalah!"},
            fb_bl_final_bell_interrupted_1 = {"Diselamatkan bel?", "Tidak kali ini!"},
        }
    }
}
