return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Scontri finali",
            fb_cfg_dialogue = "Dialoghi dei boss",
            fb_cfg_music = "Musica degli scontri",
            fb_cfg_fx = "Effetti sullo schermo",
            fb_cfg_cinematic = "Cinematiche degli scontri",
            fb_cfg_moves = "Mosse dei boss",
            fb_cfg_phase_twists = "Le fasi dei boss cambiano le regole",
            fb_showdown_title = "SCONTRO FINALE",
            fb_nemesis_title = "NEMESI",
            fb_nemesis_defeated = "NEMESI SCONFITTA",
            fb_cfg_intro_speed = "Velocità intro",
            fb_speed_slow = "Lenta",
            fb_speed_normal = "Normale",
            fb_speed_fast = "Veloce",
            fb_cfg_min_ante = "Dialoghi dall'Ante",
            fb_cfg_memory = "Memoria dei boss",
            fb_cfg_dev_mode = "Tasti sviluppatore (F5-F9)",
            fb_cfg_showdown_enabled = "Scontri finali personalizzati",
            fb_cfg_start_ante = "Primo scontro all'Ante",
            fb_cfg_every = "Poi ogni N Ante",
            fb_cfg_preview = "Scontri agli Ante",
            fb_cfg_hard = "Difficile! Gli scontri iniziali sono brutali.",
            fb_cfg_next_ante = "Le modifiche valgono dal prossimo Ante.",
            fb_cfg_group_dialogue = "Dialoghi",
            fb_cfg_group_stage = "Palco dello scontro",
            fb_credits_thanks = "Grazie per giocare con FinalBoss!",
            fb_credits_lead = "Creato e mantenuto da",
            fb_credits_music = "Musica degli scontri:",
            fb_credits_music_by = "Adam Isiah (cover orchestrale)",
            fb_credits_listen = "Ascolta su YouTube",
            fb_credits_github = "GitHub",
            fb_tip_me = "Offrimi un caffè",
            fb_tip_me_message_1 = "Se ti piace FinalBoss, valuta di lasciarmi",
            fb_tip_me_message_2 = "una piccola mancia per sostenermi.",
            fb_tip_me_message_3 = "Lo apprezzo davvero tanto!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"I boss rispondono e gli scontri finali diventano battaglie.", "Di {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Sei arrivato troppo", "lontano..."},
            fb_opener_2 = {"E mi dispiace", "dirtelo..."},
            fb_opener_3 = {"Dunque. Ce l'hai fatta."},
            fb_closer_1 = {"Non riuscirai", "a battermi."},
            fb_closer_2 = {"Qui finisce", "la tua partita."},
            fb_closer_3 = {"Fammi vedere di", "che pasta sei fatto."},
            fb_gloat = {"Quel boss era", "troppo..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Io sono #1#!"},
            fb_generic_name_2 = {"Mi chiamano", "#1#."},
            fb_generic_name_3 = {"Ammira:", "#1#!"},
            fb_generic_intro_1 = {"La tua fortuna", "finisce qui."},
            fb_generic_intro_2 = {"Vediamo come te la", "cavi con questo."},
            fb_generic_intro_3 = {"Leggi bene", "le mie regole..."},
            fb_generic_big_hand_1 = {"...Niente male."},
            fb_generic_big_hand_2 = {"Mano fortunata."},
            fb_generic_big_hand_3 = {"Hmph. Ancora?"},
            fb_generic_close_1 = {"Aspetta, aspetta,", "ASPETTA!"},
            fb_generic_close_2 = {"Non osare..."},
            fb_generic_close_3 = {"Non può essere..."},
            fb_generic_last_hand_1 = {"Una mano sola.", "Falla valere."},
            fb_generic_last_hand_2 = {"Tic, tac..."},
            fb_generic_last_hand_3 = {"Ultima occasione,", "piccolo jolly."},
            fb_generic_disabled_1 = {"Il mio potere...!", "Che hai fatto?"},
            fb_generic_disabled_2 = {"Ehi! Questo è", "barare!"},
            fb_generic_disabled_3 = {"Mi sento... debole."},
            fb_generic_defeat_1 = {"Impossibile..."},
            fb_generic_defeat_2 = {"Tornerò al prossimo", "Ante..."},
            fb_generic_defeat_3 = {"Ben giocata..."},
            fb_generic_gloat_1 = {"Quel boss era", "troppo..."},
            fb_generic_gloat_2 = {"Il banco", "vince sempre."},
            fb_generic_gloat_3 = {"Più fortuna", "alla prossima."},
            fb_generic_interrupted_1 = {"Il mio discorso!"},
            fb_generic_interrupted_2 = {"Ok... quindi", "è così."},
            fb_generic_interrupted_3 = {"Neanche un ciao?"},
            fb_generic_phase2_1 = {"Basta giochi!"},
            fb_generic_phase3_1 = {"Ora sono", "davvero furioso!"},
            fb_generic_rematch_won_1 = {"Ancora tu?", "Mi ricordo di te."},
            fb_generic_rematch_won_2 = {"L'ultima volta era", "fortuna. Ammettilo."},
            fb_generic_rematch_won_3 = {"È ora della rivincita.", "Mi sono allenato."},
            fb_generic_rematch_lost_1 = {"Torni per un'altra", "batosta?"},
            fb_generic_rematch_lost_2 = {"Non hai imparato", "l'ultima volta?"},
            fb_generic_rematch_lost_3 = {"Ah, sei tu.", "Il perdente."},

            -- Nemesis (shared, #1# = boss name)
            fb_nemesis_intro_1 = {"Ti ricordi di me?", "#1# non dimentica."},
            fb_nemesis_intro_2 = {"Ancora #1#.", "La tua nemesi."},
            fb_nemesis_intro_3 = {"Non puoi sfuggire", "alla tua nemesi."},
            fb_nemesis_defeat_1 = {"Come?! Sono la", "tua nemesi!"},
            fb_nemesis_defeat_2 = {"#1#... spezzato."},
            fb_nemesis_defeat_3 = {"Non finisce qui,", "rivale..."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Ma io sono", "L'uncino"},
            fb_bl_hook_intro_1 = {"Mi prendo qualcuna", "delle tue carte"},
            fb_bl_hook_intro_2 = {"Due carte in meno,", "a ogni mano."},
            fb_bl_hook_big_hand_1 = {"Anche con meno", "carte?!"},
            fb_bl_hook_close_1 = {"Lascia stare", "quelle carte!"},
            fb_bl_hook_last_hand_1 = {"Finalmente ti ho", "agganciato!"},
            fb_bl_hook_disabled_1 = {"Il mio uncino!", "È rotto!"},
            fb_bl_hook_defeat_1 = {"E va bene... ti", "lascio andare."},
            fb_bl_hook_gloat_1 = {"Hai abboccato!"},
            fb_bl_hook_interrupted_1 = {"Maleducato! Ero a", "metà discorso!"},
            fb_bl_hook_rematch_won_1 = {"L'ultima volta sei", "sfuggito all'uncino."},
            fb_bl_hook_rematch_lost_1 = {"Torni ad", "abboccare?"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Ma io sono", "Il bue"},
            fb_bl_ox_intro_1 = {"Mi prendo tutti", "i tuoi soldi"},
            fb_bl_ox_intro_2 = {"La tua mano preferita", "ti costa tutto."},
            fb_bl_ox_big_hand_1 = {"Al verde e vinci", "ancora?!"},
            fb_bl_ox_close_1 = {"Calma i buoi!", "...Anche i miei."},
            fb_bl_ox_last_hand_1 = {"Ultima mano. Spendi", "o perdi."},
            fb_bl_ox_disabled_1 = {"Le mie corna!", "Sono spuntate!"},
            fb_bl_ox_defeat_1 = {"Hai preso il toro", "per le corna..."},
            fb_bl_ox_gloat_1 = {"Ora sei al verde!"},
            fb_bl_ox_interrupted_1 = {"Ah, quindi è COSÌ", "che andrà."},
            fb_bl_ox_rematch_won_1 = {"Hai schivato le mie", "corna una volta..."},
            fb_bl_ox_rematch_lost_1 = {"Ancora al verde", "dall'ultima volta?"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Ma io sono", "La casa"},
            fb_bl_house_intro_1 = {"Sei", "CIECO!"},
            fb_bl_house_intro_2 = {"La prima mano la", "offre la casa. Al buio!"},
            fb_bl_house_big_hand_1 = {"Fortuna cieca e hai", "vinto lo stesso?!"},
            fb_bl_house_close_1 = {"La casa non", "perde mai!"},
            fb_bl_house_last_hand_1 = {"Basta fortuna", "cieca."},
            fb_bl_house_disabled_1 = {"La mia benda!", "È caduta!"},
            fb_bl_house_defeat_1 = {"La casa...", "è crollata."},
            fb_bl_house_gloat_1 = {"Vince la casa!"},
            fb_bl_house_interrupted_1 = {"Regola della casa:", "non si gioca ancora!"},
            fb_bl_house_rematch_won_1 = {"La casa ha perso una", "volta. Mai più."},
            fb_bl_house_rematch_lost_1 = {"Bentornato.", "La casa non dimentica."},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Ma io sono", "Il muro"},
            fb_bl_wall_intro_1 = {"Ci hai appena", "sbattuto contro"},
            fb_bl_wall_intro_2 = {"Prova a scalare", "questo punteggio."},
            fb_bl_wall_big_hand_1 = {"Hai scalato", "il mio muro?!"},
            fb_bl_wall_close_1 = {"Non puoi", "sfondarmi!"},
            fb_bl_wall_last_hand_1 = {"Non c'è più", "niente da scalare."},
            fb_bl_wall_disabled_1 = {"Crepe! Il mio muro", "si crepa!"},
            fb_bl_wall_defeat_1 = {"Il muro...", "crolla."},
            fb_bl_wall_gloat_1 = {"Muro contro muro!"},
            fb_bl_wall_interrupted_1 = {"Come parlare", "al muro... aspetta."},
            fb_bl_wall_rematch_won_1 = {"Mi hai scalato una", "volta. Non due."},
            fb_bl_wall_rematch_lost_1 = {"Torni a sbattere contro", "lo stesso muro?"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Ma io sono", "La ruota"},
            fb_bl_wheel_intro_1 = {"Mi piace...", "AZZARDARE!"},
            fb_bl_wheel_intro_2 = {"Una carta su sette", "arriva coperta."},
            fb_bl_wheel_big_hand_1 = {"La Dea Bendata ti", "ama oggi."},
            fb_bl_wheel_close_1 = {"La mia ruota", "gira a vuoto!"},
            fb_bl_wheel_last_hand_1 = {"Ultimo giro.", "Ti senti fortunato?"},
            fb_bl_wheel_disabled_1 = {"La ruota si ferma?", "Truccato!"},
            fb_bl_wheel_defeat_1 = {"La ruota della", "fortuna gira..."},
            fb_bl_wheel_gloat_1 = {"Giri a vuoto!"},
            fb_bl_wheel_interrupted_1 = {"Ehi! Piano, sto", "ancora girando!"},
            fb_bl_wheel_rematch_won_1 = {"All'ultimo giro la", "fortuna ti ha sorriso..."},
            fb_bl_wheel_rematch_lost_1 = {"Un altro giro?", "Il banco è in vantaggio."},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Ma io sono", "Il braccio"},
            fb_bl_arm_intro_1 = {"Bilancerò il", "tuo potere"},
            fb_bl_arm_intro_2 = {"Ogni mano che giochi", "perde un livello."},
            fb_bl_arm_big_hand_1 = {"Quella mano ha", "dei muscoli..."},
            fb_bl_arm_close_1 = {"Braccio di ferro?", "Sto perdendo!"},
            fb_bl_arm_last_hand_1 = {"Ultima mano. Non", "fare il muscoloso."},
            fb_bl_arm_disabled_1 = {"Il mio braccio è", "floscio! Baro!"},
            fb_bl_arm_defeat_1 = {"Hai battuto il", "mio braccio forte."},
            fb_bl_arm_gloat_1 = {"Declassato!"},
            fb_bl_arm_interrupted_1 = {"Giù le mani! Non", "ho finito di posare!"},
            fb_bl_arm_rematch_won_1 = {"Hai vinto l'ultimo", "braccio di ferro."},
            fb_bl_arm_rematch_lost_1 = {"Torni per un altro", "braccio di ferro?"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Ma io sono", "Il fiore"},
            fb_bl_club_intro_1 = {"Odio i giocatori", "{C:green,E:1}fortunati{}"},
            fb_bl_club_intro_2 = {"I fiori sono debuffati.", "Scusa."},
            fb_bl_club_big_hand_1 = {"Senza fiori, nessun", "problema?!"},
            fb_bl_club_close_1 = {"Non darmele con", "quel bastone!"},
            fb_bl_club_last_hand_1 = {"Ultima mano. Lascia i", "fiori a casa."},
            fb_bl_club_disabled_1 = {"I miei fiori hanno", "perso il mordente!"},
            fb_bl_club_defeat_1 = {"Il fiore appassisce.", "È ora di andare..."},
            fb_bl_club_gloat_1 = {"Sei appassito!"},
            fb_bl_club_interrupted_1 = {"Ehi! Nel mio club", "parlo prima io."},
            fb_bl_club_rematch_won_1 = {"L'ultima volta ti sei", "imbucato nel mio club."},
            fb_bl_club_rematch_lost_1 = {"Tessera rinnovata?", "Bentornato."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Ma io sono", "Il pesce"},
            fb_bl_fish_intro_1 = {"Sii sicuro di cosa", "vuoi giocare"},
            fb_bl_fish_intro_2 = {"Dopo ogni mano le", "carte arrivano coperte."},
            fb_bl_fish_big_hand_1 = {"C'è puzza di", "pesce in quella mano!"},
            fb_bl_fish_close_1 = {"Non tirarmi su", "con la lenza!"},
            fb_bl_fish_last_hand_1 = {"Ultimo lancio.", "Recupera la lenza."},
            fb_bl_fish_disabled_1 = {"Le mie squame!", "Sono cadute!"},
            fb_bl_fish_defeat_1 = {"Pescato...", "da un professionista."},
            fb_bl_fish_gloat_1 = {"Sei in acqua!"},
            fb_bl_fish_interrupted_1 = {"Mi hai tagliato", "la lenza!"},
            fb_bl_fish_rematch_won_1 = {"Quello che", "mi è sfuggito..."},
            fb_bl_fish_rematch_lost_1 = {"Di nuovo all'amo,", "pesciolino?"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Ma io sono", "Il medium"},
            fb_bl_psychic_intro_1 = {"Odio i giocatori", "indecisi"},
            fb_bl_psychic_intro_2 = {"Cinque carte, non", "meno. L'avevo previsto."},
            fb_bl_psychic_big_hand_1 = {"Questo NON l'avevo", "previsto."},
            fb_bl_psychic_close_1 = {"La mia sfera mostra", "...sconfitta!"},
            fb_bl_psychic_last_hand_1 = {"Prevedo la tua", "ultima mano."},
            fb_bl_psychic_disabled_1 = {"Le mie visioni!", "Sono sparite!"},
            fb_bl_psychic_defeat_1 = {"Me l'aspettavo.", "...O forse no?"},
            fb_bl_psychic_gloat_1 = {"Lo avevo previsto!"},
            fb_bl_psychic_interrupted_1 = {"Sapevo che l'avresti", "fatto. Che maleducato."},
            fb_bl_psychic_rematch_won_1 = {"Non avevo previsto la", "tua ultima vittoria."},
            fb_bl_psychic_rematch_lost_1 = {"Sapevo che", "saresti tornato."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Ma io sono", "Il pungolo"},
            fb_bl_goad_intro_1 = {"Odio il", "{C:black,E:1}POTERE{}"},
            fb_bl_goad_intro_2 = {"Le picche sono debuffate.", "Scava più a fondo."},
            fb_bl_goad_big_hand_1 = {"Niente male senza", "le tue picche."},
            fb_bl_goad_close_1 = {"Non osare scavare", "la mia fossa!"},
            fb_bl_goad_last_hand_1 = {"Scava a fondo. È la", "tua ultima mano."},
            fb_bl_goad_disabled_1 = {"Ora non posso più", "pungolare nessuno!"},
            fb_bl_goad_defeat_1 = {"Punto sul vivo,", "hai vinto."},
            fb_bl_goad_gloat_1 = {"Scavati la fossa!"},
            fb_bl_goad_interrupted_1 = {"Provochi ME?", "Va bene!"},
            fb_bl_goad_rematch_won_1 = {"L'ultima volta sei", "uscito dalla fossa."},
            fb_bl_goad_rematch_lost_1 = {"Torni a scavarti una", "fossa più profonda?"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Ma io sono", "L'acqua"},
            fb_bl_water_intro_1 = {"Dammi", "i tuoi scarti"},
            fb_bl_water_intro_2 = {"Zero scarti.", "Neanche una goccia."},
            fb_bl_water_big_hand_1 = {"Senza scarti e hai", "vinto lo stesso?!"},
            fb_bl_water_close_1 = {"Sto annegando!", "Lanciatemi una fune!"},
            fb_bl_water_last_hand_1 = {"Ultima mano. Nuota", "o affonda."},
            fb_bl_water_disabled_1 = {"Gli scarti scorrono", "di nuovo!"},
            fb_bl_water_defeat_1 = {"Sono prosciugato..."},
            fb_bl_water_gloat_1 = {"Sei a mollo!"},
            fb_bl_water_interrupted_1 = {"Interrompermi? Ora", "sei in acque agitate!"},
            fb_bl_water_rematch_won_1 = {"L'ultima volta sei", "rimasto a galla."},
            fb_bl_water_rematch_lost_1 = {"Torni a finire", "a mollo?"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Ma io sono", "La finestra"},
            fb_bl_window_intro_1 = {"Odio il", "{C:yellow,E:1}capitalismo{}"},
            fb_bl_window_intro_2 = {"I quadri sono debuffati.", "Continua a brillare."},
            fb_bl_window_big_hand_1 = {"A chi servono", "i quadri?"},
            fb_bl_window_close_1 = {"Non rompere la", "mia finestra!"},
            fb_bl_window_last_hand_1 = {"Ultima mano. Vietato", "brillare."},
            fb_bl_window_disabled_1 = {"Il vetro è rotto!", "I quadri brillano!"},
            fb_bl_window_defeat_1 = {"La mia finestra di", "opportunità si chiude."},
            fb_bl_window_gloat_1 = {"Quadri? Debuffati!"},
            fb_bl_window_interrupted_1 = {"Le mie parole", "dalla finestra?!"},
            fb_bl_window_rematch_won_1 = {"Una volta hai sfondato", "la mia finestra."},
            fb_bl_window_rematch_lost_1 = {"Di nuovo a guardare", "le vetrine?"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Ma io sono", "La manetta"},
            fb_bl_manacle_intro_1 = {"Mi prendo le tue", "{C:blue,E:1}opzioni{}"},
            fb_bl_manacle_intro_2 = {"Una carta in meno", "in mano."},
            fb_bl_manacle_big_hand_1 = {"In catene e vinci", "ancora?!"},
            fb_bl_manacle_close_1 = {"Ti stai liberando", "dalle catene!"},
            fb_bl_manacle_last_hand_1 = {"Ultima mano. E pure", "ammanettato."},
            fb_bl_manacle_disabled_1 = {"Le manette!", "Sono saltate!"},
            fb_bl_manacle_defeat_1 = {"Libero alla fine...", "da me."},
            fb_bl_manacle_gloat_1 = {"Mani legate!"},
            fb_bl_manacle_interrupted_1 = {"Alt! Ti metterò", "in catene per questo!"},
            fb_bl_manacle_rematch_won_1 = {"Una volta hai spezzato", "le mie catene."},
            fb_bl_manacle_rematch_lost_1 = {"Di nuovo in catene,", "vedo."},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Ma io sono", "L'occhio"},
            fb_bl_eye_intro_1 = {"Non mi piace", "la routine"},
            fb_bl_eye_intro_2 = {"Mai lo stesso tipo di", "mano due volte."},
            fb_bl_eye_big_hand_1 = {"Una mano nuova?", "Ti tengo d'occhio."},
            fb_bl_eye_close_1 = {"Non riesco", "a guardare!"},
            fb_bl_eye_last_hand_1 = {"Vedo la tua", "ultima mano."},
            fb_bl_eye_disabled_1 = {"Il mio occhio! Chi", "me l'ha ficcato?!"},
            fb_bl_eye_defeat_1 = {"Lontano dagli occhi,", "lontano dal cuore..."},
            fb_bl_eye_gloat_1 = {"Te l'avevo detto!"},
            fb_bl_eye_interrupted_1 = {"L'ho visto!", "Che maleducato."},
            fb_bl_eye_rematch_won_1 = {"Ti osservo da", "quella sconfitta."},
            fb_bl_eye_rematch_lost_1 = {"Vedo che", "sei tornato."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Ma io sono", "La bocca"},
            fb_bl_mouth_intro_1 = {"Adoro", "la routine"},
            fb_bl_mouth_intro_2 = {"Scegli un tipo di", "mano e tienilo."},
            fb_bl_mouth_big_hand_1 = {"La solita mano,", "ancora forte..."},
            fb_bl_mouth_close_1 = {"La mia bocca è", "spalancata!"},
            fb_bl_mouth_last_hand_1 = {"Ultima mano. Stesso", "tipo. Zitto."},
            fb_bl_mouth_disabled_1 = {"Chi mi ha", "imbavagliato?!"},
            fb_bl_mouth_defeat_1 = {"Sono senza parole..."},
            fb_bl_mouth_gloat_1 = {"Zitto, perdente!"},
            fb_bl_mouth_interrupted_1 = {"Ehi! Questa bocca", "stava ancora parlando!"},
            fb_bl_mouth_rematch_won_1 = {"L'ultima volta mi hai", "chiuso la bocca."},
            fb_bl_mouth_rematch_lost_1 = {"Stessa routine", "dell'ultima volta?"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Ma io sono", "La pianta"},
            fb_bl_plant_intro_1 = {"Odio le", "facce amichevoli"},
            fb_bl_plant_intro_2 = {"Re, regine, fanti:", "tutti debuffati."},
            fb_bl_plant_big_hand_1 = {"Senza figure?!", "Incredibile."},
            fb_bl_plant_close_1 = {"Non strapparmi", "dalle radici!"},
            fb_bl_plant_last_hand_1 = {"Affronta la tua", "ultima mano."},
            fb_bl_plant_disabled_1 = {"I miei petali!", "Sono tutti spariti!"},
            fb_bl_plant_defeat_1 = {"Appassita...", "Ricrescerò."},
            fb_bl_plant_gloat_1 = {"Fattene una", "ragione!"},
            fb_bl_plant_interrupted_1 = {"Fammi crescere", "prima, impaziente!"},
            fb_bl_plant_rematch_won_1 = {"Mi hai sradicata.", "Sono ricresciuta."},
            fb_bl_plant_rematch_lost_1 = {"Di nuovo nel mio", "giardino, vedo."},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Ma io sono", "Il serpente"},
            fb_bl_serpent_intro_1 = {"C'è un", "deficit"},
            fb_bl_serpent_intro_2 = {"Giochi o scarti,", "peschi solo 3."},
            fb_bl_serpent_big_hand_1 = {"Tre carte. E hai", "colpito lo stesso!"},
            fb_bl_serpent_close_1 = {"Non strisciare via", "proprio ora!"},
            fb_bl_serpent_last_hand_1 = {"Ultimo morso.", "Tre carte."},
            fb_bl_serpent_disabled_1 = {"Le mie zanne! Sss...", "Niente più veleno!"},
            fb_bl_serpent_defeat_1 = {"Ho cambiato pelle...", "e perso l'orgoglio."},
            fb_bl_serpent_gloat_1 = {"Sss-alutami!"},
            fb_bl_serpent_interrupted_1 = {"Sss! Non", "interrompermi!"},
            fb_bl_serpent_rematch_won_1 = {"Una volta sei sfuggito", "alle mie spire."},
            fb_bl_serpent_rematch_lost_1 = {"Cosssì sei", "tornato..."},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Ma io sono", "Il pilastro"},
            fb_bl_pillar_intro_1 = {"Ho imparato molto", "dalle tue mani passate"},
            fb_bl_pillar_intro_2 = {"Le carte giocate restano", "debuffate in questo Ante."},
            fb_bl_pillar_big_hand_1 = {"Carte fresche?", "Furbo."},
            fb_bl_pillar_close_1 = {"Il mio pilastro", "si sgretola!"},
            fb_bl_pillar_last_hand_1 = {"Ultima mano. Le carte", "vecchie non servono."},
            fb_bl_pillar_disabled_1 = {"La mia memoria!", "Sta... svanendo."},
            fb_bl_pillar_defeat_1 = {"Un pilastro della", "comunità è caduto."},
            fb_bl_pillar_gloat_1 = {"Ancora in piedi!"},
            fb_bl_pillar_interrupted_1 = {"Nessun rispetto", "per gli anziani?"},
            fb_bl_pillar_rematch_won_1 = {"Ricordo come", "mi hai battuto."},
            fb_bl_pillar_rematch_lost_1 = {"Ricordo come", "hai perso."},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Ma io sono", "L'ago"},
            fb_bl_needle_intro_1 = {"Hai una sola", "possibilità"},
            fb_bl_needle_intro_2 = {"Una mano. È tutto", "quello che ottieni."},
            fb_bl_needle_big_hand_1 = {"Una sola mano,", "così forte?!"},
            fb_bl_needle_close_1 = {"No! Non con", "una mano sola!"},
            fb_bl_needle_last_hand_1 = {"Questa mano è", "la tua unica mano."},
            fb_bl_needle_disabled_1 = {"Il mio ago!", "È spuntato!"},
            fb_bl_needle_defeat_1 = {"Gioco affilato.", "Mi hai preso."},
            fb_bl_needle_gloat_1 = {"Il punto?", "Hai perso!"},
            fb_bl_needle_interrupted_1 = {"Che pungente.", "Non avevo finito!"},
            fb_bl_needle_rematch_won_1 = {"Una sola mano mi ha", "battuto l'ultima volta."},
            fb_bl_needle_rematch_lost_1 = {"Ancora una sola", "chance. La sbagli?"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Ma io sono", "La testa"},
            fb_bl_head_intro_1 = {"Odio gli", "{C:red,E:1}innamorati{}"},
            fb_bl_head_intro_2 = {"I cuori sono debuffati.", "Freddo, vero?"},
            fb_bl_head_big_hand_1 = {"Hai vinto senza", "cuore?!"},
            fb_bl_head_close_1 = {"Abbi cuore,", "non finirmi!"},
            fb_bl_head_last_hand_1 = {"Ultima mano. Niente", "cuori. Niente pietà."},
            fb_bl_head_disabled_1 = {"Che mal di testa!", "I cuori funzionano?"},
            fb_bl_head_defeat_1 = {"Ho perso la testa...", "per te."},
            fb_bl_head_gloat_1 = {"Senza cuore, eh?"},
            fb_bl_head_interrupted_1 = {"Hai perso la testa?", "Sto parlando!"},
            fb_bl_head_rematch_won_1 = {"Hai conquistato il mio", "cuore... una volta."},
            fb_bl_head_rematch_lost_1 = {"Torni per un altro", "cuore spezzato?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Ma io sono", "Il dente"},
            fb_bl_tooth_intro_1 = {"Mi interessa", "la politica"},
            fb_bl_tooth_intro_2 = {"Ogni carta che giochi", "ti costa $1."},
            fb_bl_tooth_big_hand_1 = {"Hai pagato e hai", "vinto lo stesso?!"},
            fb_bl_tooth_close_1 = {"Non farmi pagare la", "fatina dei denti!"},
            fb_bl_tooth_last_hand_1 = {"Ultima mano,", "ultimi dollari."},
            fb_bl_tooth_disabled_1 = {"Il mio morso!", "È sparito!"},
            fb_bl_tooth_defeat_1 = {"Con le unghie e", "coi denti, ho perso."},
            fb_bl_tooth_gloat_1 = {"Paga, pollo!"},
            fb_bl_tooth_interrupted_1 = {"Grr! Me la", "pagherai!"},
            fb_bl_tooth_rematch_won_1 = {"Hai ancora un conto", "in sospeso con me."},
            fb_bl_tooth_rematch_lost_1 = {"Torni a pagare", "il tuo debito?"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Ma io sono", "La selce"},
            fb_bl_flint_intro_1 = {"Devi", "pagare le tasse"},
            fb_bl_flint_intro_2 = {"Fiche e Molt", "sono dimezzati."},
            fb_bl_flint_big_hand_1 = {"Metà potenza,", "eppure colpisci?!"},
            fb_bl_flint_close_1 = {"Stai facendo scintille", "per la mia caduta!"},
            fb_bl_flint_last_hand_1 = {"Ultima mano. Metà", "scintilla."},
            fb_bl_flint_disabled_1 = {"Piena potenza?!", "Non è giusto!"},
            fb_bl_flint_defeat_1 = {"La mia scintilla", "si è spenta."},
            fb_bl_flint_gloat_1 = {"Metà del", "divertimento!"},
            fb_bl_flint_interrupted_1 = {"Niente scintille!", "Stavo parlando!"},
            fb_bl_flint_rematch_won_1 = {"L'ultima volta hai", "evaso le mie tasse."},
            fb_bl_flint_rematch_lost_1 = {"Di nuovo tempo", "di tasse. Paga."},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Ma io sono", "Il marchio"},
            fb_bl_mark_intro_1 = {"Non mi piace", "essere visto"},
            fb_bl_mark_intro_2 = {"Tutte le figure", "arrivano coperte."},
            fb_bl_mark_big_hand_1 = {"Carte segnate,", "eppure vinci?!"},
            fb_bl_mark_close_1 = {"Sono marchiato", "per la sconfitta!"},
            fb_bl_mark_last_hand_1 = {"Ultima mano. Scegli", "le facce alla cieca."},
            fb_bl_mark_disabled_1 = {"Le facce!", "Le vedo!"},
            fb_bl_mark_defeat_1 = {"Hai lasciato il", "tuo marchio su di me."},
            fb_bl_mark_gloat_1 = {"Marchiato", "perdente!"},
            fb_bl_mark_interrupted_1 = {"Annotato. Ora sei", "un marchiato."},
            fb_bl_mark_rematch_won_1 = {"L'ultima volta mi", "hai smascherato."},
            fb_bl_mark_rematch_lost_1 = {"Ancora non vedi", "i miei volti?"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Ma io sono", "Ghianda d'ambra"},
            fb_bl_final_acorn_intro_1 = {"Mi piace il", "CAOS!"},
            fb_bl_final_acorn_intro_2 = {"Jolly coperti,", "poi mescolati!"},
            fb_bl_final_acorn_big_hand_1 = {"Anche nel caos", "vinci?!"},
            fb_bl_final_acorn_close_1 = {"Che matti! Mi", "sto spaccando!"},
            fb_bl_final_acorn_last_hand_1 = {"Ultima mano. Dov'è", "il tuo jolly?"},
            fb_bl_final_acorn_disabled_1 = {"La mia ghianda!", "L'ordine torna?!"},
            fb_bl_final_acorn_defeat_1 = {"Hai rotto il", "mio guscio..."},
            fb_bl_final_acorn_gloat_1 = {"Roba da matti!"},
            fb_bl_final_acorn_interrupted_1 = {"Fermo! Non sono", "nemmeno germogliato!"},
            fb_bl_final_acorn_phase2_1 = {"Ora si fa", "da MATTI!"},
            fb_bl_final_acorn_phase3_1 = {"Caos totale!", "Via il guscio!"},
            fb_bl_final_acorn_rematch_won_1 = {"Mi hai spezzata una", "volta. Mai più!"},
            fb_bl_final_acorn_rematch_lost_1 = {"Torni per altro", "CAOS?"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Ma io sono", "Foglia verde"},
            fb_bl_final_leaf_intro_1 = {"Devi staccarti", "dalle tue radici"},
            fb_bl_final_leaf_intro_2 = {"Vendi un jolly o", "resta debuffato."},
            fb_bl_final_leaf_big_hand_1 = {"Hai voltato pagina.", "Hmph."},
            fb_bl_final_leaf_close_1 = {"La mia foglia", "sta cadendo!"},
            fb_bl_final_leaf_last_hand_1 = {"Ultima mano. Vendi", "un jolly?"},
            fb_bl_final_leaf_disabled_1 = {"La mia foglia!", "È appassita!"},
            fb_bl_final_leaf_defeat_1 = {"Me ne vado...", "come una foglia."},
            fb_bl_final_leaf_gloat_1 = {"Foglia perdente!"},
            fb_bl_final_leaf_interrupted_1 = {"Bene. Salta i", "convenevoli."},
            fb_bl_final_leaf_phase2_1 = {"Le mie radici", "affondano!"},
            fb_bl_final_leaf_phase3_1 = {"Appassisci con me!"},
            fb_bl_final_leaf_rematch_won_1 = {"Una volta hai mollato", "la presa. Riprova."},
            fb_bl_final_leaf_rematch_lost_1 = {"Ancora attaccato", "ai tuoi jolly?"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Ma io sono", "Contenitore violetto"},
            fb_bl_final_vessel_intro_1 = {"Hai appena colpito", "la grande muraglia"},
            fb_bl_final_vessel_intro_2 = {"Una blind vastissima.", "Salpa!"},
            fb_bl_final_vessel_big_hand_1 = {"Un colpo enorme su", "un bersaglio enorme."},
            fb_bl_final_vessel_close_1 = {"Abbandonate la nave!", "...La mia, intendo."},
            fb_bl_final_vessel_last_hand_1 = {"Ultima mano. Questa", "nave non affonda."},
            fb_bl_final_vessel_disabled_1 = {"Il mio contenitore!", "Sta affondando!"},
            fb_bl_final_vessel_defeat_1 = {"Il contenitore...", "è stato svuotato."},
            fb_bl_final_vessel_gloat_1 = {"Vasta sconfitta!"},
            fb_bl_final_vessel_interrupted_1 = {"Salpi prima del mio", "discorso? Audace."},
            fb_bl_final_vessel_phase2_1 = {"Riempite la stiva!"},
            fb_bl_final_vessel_phase3_1 = {"Tutti quanti", "negli abissi!"},
            fb_bl_final_vessel_rematch_won_1 = {"Mi hai affondato una", "volta. Mi hanno riparato."},
            fb_bl_final_vessel_rematch_lost_1 = {"Torni ad annegare", "nella mia scia?"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Ma io sono", "Cuore cremisi"},
            fb_bl_final_heart_intro_1 = {"Prenderò in prestito", "un jolly"},
            fb_bl_final_heart_intro_2 = {"A ogni mano un jolly", "perde il suo potere."},
            fb_bl_final_heart_big_hand_1 = {"Un jolly in meno e", "sei ancora forte?"},
            fb_bl_final_heart_close_1 = {"Non spezzarmi", "il cuore!"},
            fb_bl_final_heart_last_hand_1 = {"Ultima mano. Quale", "jolly è zittito?"},
            fb_bl_final_heart_disabled_1 = {"Il mio cuore! Ha", "saltato un battito."},
            fb_bl_final_heart_defeat_1 = {"Il mio cuore...", "è spezzato."},
            fb_bl_final_heart_gloat_1 = {"Cuore spezzato?"},
            fb_bl_final_heart_interrupted_1 = {"Mi interrompi?", "Che cuore di pietra!"},
            fb_bl_final_heart_phase2_1 = {"Il mio cuore", "batte più forte!"},
            fb_bl_final_heart_phase3_1 = {"Senti la mia", "furia cremisi!"},
            fb_bl_final_heart_rematch_won_1 = {"L'ultima volta mi hai", "spezzato il cuore."},
            fb_bl_final_heart_rematch_lost_1 = {"Il mio cuore batte", "ancora per te."},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Ma io sono", "Campana cerulea"},
            fb_bl_final_bell_intro_1 = {"Vorrei", "guidarti"},
            fb_bl_final_bell_intro_2 = {"Una carta è forzata", "in ogni mano."},
            fb_bl_final_bell_big_hand_1 = {"Hai fatto suonare la", "mia carta forzata?!"},
            fb_bl_final_bell_close_1 = {"La campana suona...", "per me?!"},
            fb_bl_final_bell_last_hand_1 = {"Ultima mano. Una", "carta è forzata."},
            fb_bl_final_bell_disabled_1 = {"La mia campana tace!", "Baro!"},
            fb_bl_final_bell_defeat_1 = {"La campana suona", "per me."},
            fb_bl_final_bell_gloat_1 = {"Din don,", "hai perso!"},
            fb_bl_final_bell_interrupted_1 = {"Salvato dal gong?", "Non stavolta!"},
            fb_bl_final_bell_phase2_1 = {"Sentimi suonare", "più forte!"},
            fb_bl_final_bell_phase3_1 = {"L'ultimo rintocco!"},
            fb_bl_final_bell_rematch_won_1 = {"L'ultima volta", "me le hai suonate."},
            fb_bl_final_bell_rematch_lost_1 = {"La campana suona", "ancora per te."},
        }
    }
}
