return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "決戦",
            fb_cfg_dialogue = "ボスのセリフ",
            fb_cfg_music = "決戦BGM",
            fb_cfg_fx = "画面エフェクト",
            fb_cfg_cinematic = "決戦の演出",
            fb_cfg_moves = "ボスの技",
            fb_cfg_phase_twists = "ボスのフェーズでルールが変わる",
            fb_showdown_title = "決戦",
            fb_nemesis_title = "宿敵",
            fb_nemesis_defeated = "宿敵撃破",
            fb_cfg_intro_speed = "イントロの速さ",
            fb_speed_slow = "遅い",
            fb_speed_normal = "普通",
            fb_speed_fast = "速い",
            fb_cfg_min_ante = "セリフ開始アンティ",
            fb_cfg_memory = "ボスの記憶",
            fb_cfg_dev_mode = "開発者キー (F5-F9)",
            fb_cfg_showdown_enabled = "決戦スケジュール設定",
            fb_cfg_start_ante = "最初の決戦アンティ",
            fb_cfg_every = "以降Nアンティごと",
            fb_cfg_preview = "決戦アンティ",
            fb_cfg_hard = "難関！序盤の決戦は過酷だ。",
            fb_cfg_next_ante = "変更は次のアンティから反映。",
            fb_cfg_group_dialogue = "セリフ",
            fb_cfg_group_stage = "決戦の舞台",
            fb_credits_thanks = "FinalBossで遊んでくれてありがとう！",
            fb_credits_lead = "制作・メンテナンス:",
            fb_credits_music = "決戦BGM:",
            fb_credits_music_by = "Adam Isiah (オーケストラカバー)",
            fb_credits_listen = "YouTubeで聴く",
            fb_credits_github = "GitHub",
            fb_tip_me = "チップを送る",
            fb_tip_me_message_1 = "FinalBossを気に入ってもらえたら",
            fb_tip_me_message_2 = "少額のチップで応援してもらえると嬉しいです。",
            fb_tip_me_message_3 = "本当にありがとうございます！",
        },
        -- Steamodded wraps achievement descriptions at spaces only (src/ui.lua:1094-1122), and a first
        -- word over 30 bytes leaves an empty first line: the spaces below are line breaks, never shown.
        achievement_names = {
            ach_FinalBoss_fb_showdown_survivor = "決戦の生還者",
            ach_FinalBoss_fb_clean_sweep = "完全制覇",
            ach_FinalBoss_fb_rude = "無礼者！",
            ach_FinalBoss_fb_no_manners = "礼儀知らず",
            ach_FinalBoss_fb_last_laugh = "最後に笑う者",
            ach_FinalBoss_fb_overkill = "オーバーキル",
            ach_FinalBoss_fb_phase_skipper = "フェーズ飛ばし",
            ach_FinalBoss_fb_comeback = "大逆転",
            ach_FinalBoss_fb_nemesis_slayer = "宿敵討ち",
            ach_FinalBoss_fb_twisted = "ひねくれ者",
        },
        achievement_descriptions = {
            ach_FinalBoss_fb_showdown_survivor = "ラスボスを倒す",
            ach_FinalBoss_fb_clean_sweep = "基本ゲームの ラスボス5体をすべて倒す",
            ach_FinalBoss_fb_rude = "話している最中の ボスを遮る",
            ach_FinalBoss_fb_no_manners = "10体の異なるボスの 話を遮る",
            ach_FinalBoss_fb_last_laugh = "ボスに笑われた直後の ハンドで倒す",
            ach_FinalBoss_fb_overkill = "HP満タンの ラスボスを1ハンドで倒す",
            ach_FinalBoss_fb_phase_skipper = "1ハンドでラスボスを フェーズIからIIIにする",
            ach_FinalBoss_fb_comeback = "最後のハンドで ラスボスを倒す",
            ach_FinalBoss_fb_nemesis_slayer = "宿敵を倒す",
            ach_FinalBoss_fb_twisted = "ルール変化ありで 基本ゲームのラスボス5体を倒す",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"ボスがしゃべり、決戦はボスバトルになる。", "作者 {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"ここまで来たか…"},
            fb_opener_2 = {"悪いが、", "言わせてもらう…"},
            fb_opener_3 = {"よく来たな。"},
            fb_closer_1 = {"貴様に俺は", "倒せん。"},
            fb_closer_2 = {"ここで貴様の", "ランは終わる。"},
            fb_closer_3 = {"実力を見せて", "みろ。"},
            fb_gloat = {"あのボスは", "強すぎた…"},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"俺は", "#1#だ！"},
            fb_generic_name_2 = {"人呼んで", "#1#！"},
            fb_generic_name_3 = {"見よ、", "#1#だ！"},
            fb_generic_intro_1 = {"貴様の運は", "ここまでだ。"},
            fb_generic_intro_2 = {"これを切り抜け", "られるかな？"},
            fb_generic_intro_3 = {"俺のルールを", "よく読め…"},
            fb_generic_big_hand_1 = {"…やるな。"},
            fb_generic_big_hand_2 = {"運のいい手だ。"},
            fb_generic_big_hand_3 = {"ふん。また？"},
            fb_generic_close_1 = {"待て、待て、", "待てっ！"},
            fb_generic_close_2 = {"やめろ…"},
            fb_generic_close_3 = {"まさか…"},
            fb_generic_last_hand_1 = {"残り1ハンド。", "決めてみろ。"},
            fb_generic_last_hand_2 = {"チク、タク…"},
            fb_generic_last_hand_3 = {"最後のチャンスだ、", "ジョーカー君。"},
            fb_generic_disabled_1 = {"俺の力が…！", "何をした？"},
            fb_generic_disabled_2 = {"おい！", "それはズルだ！"},
            fb_generic_disabled_3 = {"力が…", "抜けていく…"},
            fb_generic_defeat_1 = {"ありえん…"},
            fb_generic_defeat_2 = {"次のアンティで", "戻ってくる…"},
            fb_generic_defeat_3 = {"見事だ…"},
            fb_generic_gloat_1 = {"あのボスは", "強すぎた…"},
            fb_generic_gloat_2 = {"結局、", "胴元が勝つ。"},
            fb_generic_gloat_3 = {"次のランに", "期待しな。"},
            fb_generic_interrupted_1 = {"俺の演説が！"},
            fb_generic_interrupted_2 = {"そうか…", "そういうことか。"},
            fb_generic_interrupted_3 = {"挨拶もなしか？"},
            fb_generic_phase2_1 = {"遊びは終わりだ！"},
            fb_generic_phase3_1 = {"今度こそ", "本気で怒ったぞ！"},
            fb_generic_rematch_won_1 = {"また貴様か？", "覚えているぞ。"},
            fb_generic_rematch_won_2 = {"前回はまぐれだ。", "認めろ。"},
            fb_generic_rematch_won_3 = {"リベンジの時だ。", "鍛えてきたぞ。"},
            fb_generic_rematch_lost_1 = {"またボコられに", "来たのか？"},
            fb_generic_rematch_lost_2 = {"前回で", "懲りなかったか？"},
            fb_generic_rematch_lost_3 = {"ああ、貴様か。", "負け犬め。"},

            -- Nemesis (shared, #1# = boss name)
            fb_nemesis_intro_1 = {"覚えているか？", "#1#は忘れんぞ。"},
            fb_nemesis_intro_2 = {"また#1#だ。", "貴様の宿敵よ。"},
            fb_nemesis_intro_3 = {"宿敵からは", "逃げられんぞ。"},
            fb_nemesis_defeat_1 = {"なぜだ！？", "俺は宿敵だぞ！"},
            fb_nemesis_defeat_2 = {"#1#が…", "砕けた…"},
            fb_nemesis_defeat_3 = {"まだ終わらんぞ、", "ライバル…"},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"だが俺は", "フックだ！"},
            fb_bl_hook_intro_1 = {"貴様のカードを", "いくつか頂く"},
            fb_bl_hook_intro_2 = {"毎ハンド、", "2枚が消える。"},
            fb_bl_hook_big_hand_1 = {"カードが減っても", "勝つだと！？"},
            fb_bl_hook_close_1 = {"そのカードを", "放せ！"},
            fb_bl_hook_last_hand_1 = {"ついに釣り上げ", "たぞ！"},
            fb_bl_hook_disabled_1 = {"俺のフックが！", "折れた！"},
            fb_bl_hook_defeat_1 = {"よかろう…", "見逃してやる。"},
            fb_bl_hook_gloat_1 = {"釣れたな！"},
            fb_bl_hook_interrupted_1 = {"無礼な！まだ", "話の途中だ！"},
            fb_bl_hook_rematch_won_1 = {"前回は針から", "逃げやがったな。"},
            fb_bl_hook_rematch_lost_1 = {"また釣られに", "来たのか？"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"だが俺は", "雄牛だ！"},
            fb_bl_ox_intro_1 = {"貴様の金を", "全部頂く"},
            fb_bl_ox_intro_2 = {"得意なハンドは", "全財産を奪う。"},
            fb_bl_ox_big_hand_1 = {"無一文でも", "勝つのか！？"},
            fb_bl_ox_close_1 = {"落ち着け！", "…俺もな。"},
            fb_bl_ox_last_hand_1 = {"最後のハンド。", "使うか失うか。"},
            fb_bl_ox_disabled_1 = {"俺の角が！", "鈍った！"},
            fb_bl_ox_defeat_1 = {"闘牛の角を", "掴んだな…"},
            fb_bl_ox_gloat_1 = {"文無しだな！"},
            fb_bl_ox_interrupted_1 = {"ほう、そういう", "つもりか。"},
            fb_bl_ox_rematch_won_1 = {"一度は俺の角を", "かわしたな…"},
            fb_bl_ox_rematch_lost_1 = {"前回から", "まだ文無しか？"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"だが俺は", "家だ！"},
            fb_bl_house_intro_1 = {"貴様は", "目隠しだ！"},
            fb_bl_house_intro_2 = {"最初のハンドは", "伏せて配る！"},
            fb_bl_house_big_hand_1 = {"ブラインドでも", "勝つとは！？"},
            fb_bl_house_close_1 = {"家は決して", "負けん！"},
            fb_bl_house_last_hand_1 = {"もう運任せの", "目隠しは無い。"},
            fb_bl_house_disabled_1 = {"俺の目隠しが！", "外れた！"},
            fb_bl_house_defeat_1 = {"家が…", "崩れていく。"},
            fb_bl_house_gloat_1 = {"胴元の勝ち！"},
            fb_bl_house_interrupted_1 = {"家のルールだ、", "まだ打つな！"},
            fb_bl_house_rematch_won_1 = {"胴元の負けは一度だけ。", "二度はない。"},
            fb_bl_house_rematch_lost_1 = {"おかえり。", "胴元は覚えてるぞ。"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"だが俺は", "壁だ！"},
            fb_bl_wall_intro_1 = {"今まさに", "ぶつかったな"},
            fb_bl_wall_intro_2 = {"このスコアを", "登ってみろ。"},
            fb_bl_wall_big_hand_1 = {"俺の壁を", "登っただと！？"},
            fb_bl_wall_close_1 = {"貴様に壁は", "破れん！"},
            fb_bl_wall_last_hand_1 = {"もう登る場所は", "無い。"},
            fb_bl_wall_disabled_1 = {"ヒビが！", "壁が割れる！"},
            fb_bl_wall_defeat_1 = {"壁が…", "崩れ落ちる。"},
            fb_bl_wall_gloat_1 = {"壁にぶつかったな！"},
            fb_bl_wall_interrupted_1 = {"壁に話してる気分だ…", "あ、俺が壁か。"},
            fb_bl_wall_rematch_won_1 = {"一度は俺を越えたな。", "二度目はない。"},
            fb_bl_wall_rematch_lost_1 = {"また同じ壁に", "ぶつかりに来たか？"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"だが俺は", "ホイールだ！"},
            fb_bl_wheel_intro_1 = {"俺は…", "ギャンブル好き！"},
            fb_bl_wheel_intro_2 = {"7枚に1枚は", "伏せて配る。"},
            fb_bl_wheel_big_hand_1 = {"今日は女神が", "微笑んだな。"},
            fb_bl_wheel_close_1 = {"俺の輪が", "空回りだ！"},
            fb_bl_wheel_last_hand_1 = {"最後の一回転。", "運は味方か？"},
            fb_bl_wheel_disabled_1 = {"輪が止まった？", "イカサマだ！"},
            fb_bl_wheel_defeat_1 = {"運命の輪が", "俺に背を向けた。"},
            fb_bl_wheel_gloat_1 = {"運も尽きたな！"},
            fb_bl_wheel_interrupted_1 = {"待て！まだ", "回ってる途中だ！"},
            fb_bl_wheel_rematch_won_1 = {"前回の回転は", "運が良かったな…"},
            fb_bl_wheel_rematch_lost_1 = {"もう一回転？", "胴元有利だぜ。"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"だが俺は", "腕だ！"},
            fb_bl_arm_intro_1 = {"貴様の力の", "バランスを取る"},
            fb_bl_arm_intro_2 = {"出したハンドは", "レベルが下がる。"},
            fb_bl_arm_big_hand_1 = {"その手、", "筋肉があるな…"},
            fb_bl_arm_close_1 = {"腕相撲か？", "俺が負ける！"},
            fb_bl_arm_last_hand_1 = {"最後のハンド。", "力むなよ。"},
            fb_bl_arm_disabled_1 = {"腕に力が！", "イカサマだ！"},
            fb_bl_arm_defeat_1 = {"俺の剛腕を", "破ったか。"},
            fb_bl_arm_gloat_1 = {"レベルダウン！"},
            fb_bl_arm_interrupted_1 = {"手を出すな！", "自慢の途中だ！"},
            fb_bl_arm_rematch_won_1 = {"前回の腕相撲は", "貴様の勝ちだった。"},
            fb_bl_arm_rematch_lost_1 = {"また腕相撲を", "しに来たか？"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"だが俺は", "クラブだ！"},
            fb_bl_club_intro_1 = {"{C:green,E:1}運のいい{}奴は", "嫌いだ"},
            fb_bl_club_intro_2 = {"クラブは弱体化。", "悪いな。"},
            fb_bl_club_big_hand_1 = {"クラブ無しでも", "平気だと！？"},
            fb_bl_club_close_1 = {"それで俺を", "殴るな！"},
            fb_bl_club_last_hand_1 = {"最後のハンド。", "クラブは置いていけ。"},
            fb_bl_club_disabled_1 = {"クラブの牙が", "抜けた！"},
            fb_bl_club_defeat_1 = {"クラブは閉店だ。", "帰る時間か…"},
            fb_bl_club_gloat_1 = {"閉店ガラガラ！"},
            fb_bl_club_interrupted_1 = {"おい！俺のクラブ", "では俺が先だ！"},
            fb_bl_club_rematch_won_1 = {"前回は俺のクラブに", "殴り込んだな。"},
            fb_bl_club_rematch_lost_1 = {"会員更新か？", "おかえり。"},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"だが俺は", "魚だ！"},
            fb_bl_fish_intro_1 = {"出すカードは", "慎重に選べ"},
            fb_bl_fish_intro_2 = {"毎ハンド後、", "カードは伏せられる。"},
            fb_bl_fish_big_hand_1 = {"そのハンド、", "怪しいぞ！"},
            fb_bl_fish_close_1 = {"俺を釣り上げ", "るな！"},
            fb_bl_fish_last_hand_1 = {"最後の一投。", "釣り上げろ。"},
            fb_bl_fish_disabled_1 = {"俺のウロコが！", "剥がれた！"},
            fb_bl_fish_defeat_1 = {"釣られた…", "プロの腕だ。"},
            fb_bl_fish_gloat_1 = {"ずぶ濡れだな！"},
            fb_bl_fish_interrupted_1 = {"糸を切りやがった！"},
            fb_bl_fish_rematch_won_1 = {"逃した魚は", "大きい…"},
            fb_bl_fish_rematch_lost_1 = {"また俺の針に", "かかったか、小魚？"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"だが俺は", "サイキックだ！"},
            fb_bl_psychic_intro_1 = {"優柔不断な", "奴は嫌いだ"},
            fb_bl_psychic_intro_2 = {"5枚きっかり。", "予知していた。"},
            fb_bl_psychic_big_hand_1 = {"これは予知", "していない！"},
            fb_bl_psychic_close_1 = {"水晶玉が示す", "…敗北だと！"},
            fb_bl_psychic_last_hand_1 = {"貴様の最後の", "ハンドが見える。"},
            fb_bl_psychic_disabled_1 = {"俺の予知が！", "消えた！"},
            fb_bl_psychic_defeat_1 = {"予知していた。", "…いや、違う？"},
            fb_bl_psychic_gloat_1 = {"予知通りだ！"},
            fb_bl_psychic_interrupted_1 = {"そうすると思ったよ。", "…それでも無礼だ。"},
            fb_bl_psychic_rematch_won_1 = {"前回の貴様の勝利は", "予知できなかった。"},
            fb_bl_psychic_rematch_lost_1 = {"戻ってくると", "分かっていた。"},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"だが俺は", "ゴアドだ！"},
            fb_bl_goad_intro_1 = {"{C:black,E:1}権力{}が", "大嫌いだ"},
            fb_bl_goad_intro_2 = {"スペードは弱体化。", "もっと掘れ。"},
            fb_bl_goad_big_hand_1 = {"スペード無しで", "やるな。"},
            fb_bl_goad_close_1 = {"俺の墓穴を", "掘るな！"},
            fb_bl_goad_last_hand_1 = {"深く掘れ。最後の", "ハンドだ。"},
            fb_bl_goad_disabled_1 = {"もう誰も", "煽れん！"},
            fb_bl_goad_defeat_1 = {"くそっ、", "貴様の勝ちだ。"},
            fb_bl_goad_gloat_1 = {"墓穴を掘れ！"},
            fb_bl_goad_interrupted_1 = {"俺を挑発するか？", "いいだろう！"},
            fb_bl_goad_rematch_won_1 = {"前回は墓穴から", "這い出たな。"},
            fb_bl_goad_rematch_lost_1 = {"もっと深い墓穴を", "掘りに来たか？"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"だが俺は", "水だ！"},
            fb_bl_water_intro_1 = {"貴様の", "ディスカードを頂く"},
            fb_bl_water_intro_2 = {"ディスカード無し。", "一滴もな。"},
            fb_bl_water_big_hand_1 = {"ディスカード無しで", "勝つだと！？"},
            fb_bl_water_close_1 = {"溺れる！", "浮き輪をくれ！"},
            fb_bl_water_last_hand_1 = {"最後のハンド。", "泳ぐか沈むか。"},
            fb_bl_water_disabled_1 = {"ディスカードが", "流れ出した！"},
            fb_bl_water_defeat_1 = {"俺は干上がった…"},
            fb_bl_water_gloat_1 = {"水の泡だな！"},
            fb_bl_water_interrupted_1 = {"遮ったな？", "水に流さんぞ！"},
            fb_bl_water_rematch_won_1 = {"前回はなんとか", "浮いていたな。"},
            fb_bl_water_rematch_lost_1 = {"また溺れに", "来たのか？"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"だが俺は", "窓だ！"},
            fb_bl_window_intro_1 = {"{C:yellow,E:1}資本主義{}が", "大嫌いだ"},
            fb_bl_window_intro_2 = {"ダイヤは弱体化。", "輝き続けろ。"},
            fb_bl_window_big_hand_1 = {"ダイヤなんて", "誰が要る？"},
            fb_bl_window_close_1 = {"俺の窓を", "割るな！"},
            fb_bl_window_last_hand_1 = {"最後のハンド。", "輝きは禁止だ。"},
            fb_bl_window_disabled_1 = {"窓が割れた！", "ダイヤが輝く！"},
            fb_bl_window_defeat_1 = {"俺の好機の窓が", "閉じた。"},
            fb_bl_window_gloat_1 = {"ダイヤ？弱体化！"},
            fb_bl_window_interrupted_1 = {"俺の言葉を", "窓から捨てる気か！"},
            fb_bl_window_rematch_won_1 = {"一度は俺の窓を", "割ったな。"},
            fb_bl_window_rematch_lost_1 = {"またウィンドウ", "ショッピングか？"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"だが俺は", "手枷だ！"},
            fb_bl_manacle_intro_1 = {"貴様の", "{C:blue,E:1}選択肢{}を奪う"},
            fb_bl_manacle_intro_2 = {"手札が1枚", "減る。"},
            fb_bl_manacle_big_hand_1 = {"枷をはめられても", "勝つのか！？"},
            fb_bl_manacle_close_1 = {"鎖を振りほどく", "気か！"},
            fb_bl_manacle_last_hand_1 = {"最後のハンド。", "しかも枷付きだ。"},
            fb_bl_manacle_disabled_1 = {"枷が！", "外れた！"},
            fb_bl_manacle_defeat_1 = {"ついに自由か…", "俺から。"},
            fb_bl_manacle_gloat_1 = {"手も足も出ない！"},
            fb_bl_manacle_interrupted_1 = {"止まれ！その手、", "縛ってやる！"},
            fb_bl_manacle_rematch_won_1 = {"一度は俺の鎖を", "すり抜けたな。"},
            fb_bl_manacle_rematch_lost_1 = {"また鎖に", "つながれに来たか。"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"だが俺は", "目だ！"},
            fb_bl_eye_intro_1 = {"ルーティンは", "嫌いだ"},
            fb_bl_eye_intro_2 = {"同じ役は二度と", "出すな。"},
            fb_bl_eye_big_hand_1 = {"新しい役か？", "見ていたぞ。"},
            fb_bl_eye_close_1 = {"見て", "いられん！"},
            fb_bl_eye_last_hand_1 = {"貴様の最後の", "ハンド、見えた。"},
            fb_bl_eye_disabled_1 = {"俺の目が！", "誰が突いた！？"},
            fb_bl_eye_defeat_1 = {"目に見えなければ", "気にならん…"},
            fb_bl_eye_gloat_1 = {"言った通りだ！"},
            fb_bl_eye_interrupted_1 = {"見たぞ！", "無礼な。"},
            fb_bl_eye_rematch_won_1 = {"あの敗北以来、", "ずっと見ていたぞ。"},
            fb_bl_eye_rematch_lost_1 = {"戻ってきたのが", "見えるぞ。"},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"だが俺は", "口だ！"},
            fb_bl_mouth_intro_1 = {"ルーティンが", "大好きだ"},
            fb_bl_mouth_intro_2 = {"役を一つ選び、", "貫き通せ。"},
            fb_bl_mouth_big_hand_1 = {"同じ手でも", "まだ強い…"},
            fb_bl_mouth_close_1 = {"俺の口が", "全開だ！"},
            fb_bl_mouth_last_hand_1 = {"最後のハンド。", "同じ役だ。黙れ。"},
            fb_bl_mouth_disabled_1 = {"誰が俺に", "口輪を！？"},
            fb_bl_mouth_defeat_1 = {"言葉も出ない…"},
            fb_bl_mouth_gloat_1 = {"黙れ、負け犬！"},
            fb_bl_mouth_interrupted_1 = {"おい！この口は", "まだ喋ってた！"},
            fb_bl_mouth_rematch_won_1 = {"前回は口を", "封じられた。"},
            fb_bl_mouth_rematch_lost_1 = {"前回と同じ", "ルーティンか？"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"だが俺は", "プラントだ！"},
            fb_bl_plant_intro_1 = {"友好的な顔は", "大嫌いだ"},
            fb_bl_plant_intro_2 = {"絵札は全部", "弱体化だ。"},
            fb_bl_plant_big_hand_1 = {"絵札無しで！？", "信じられん。"},
            fb_bl_plant_close_1 = {"根こそぎ", "抜くな！"},
            fb_bl_plant_last_hand_1 = {"最後のハンドと", "向き合え。"},
            fb_bl_plant_disabled_1 = {"俺の花びらが！", "全て散った！"},
            fb_bl_plant_defeat_1 = {"枯れた…", "また生えてやる。"},
            fb_bl_plant_gloat_1 = {"現実を見ろ！"},
            fb_bl_plant_interrupted_1 = {"まず育たせろ、", "せっかちめ！"},
            fb_bl_plant_rematch_won_1 = {"根こそぎ抜かれたが、", "また生えたぞ。"},
            fb_bl_plant_rematch_lost_1 = {"また俺の庭に", "来たのか。"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"だが俺は", "サーペントだ！"},
            fb_bl_serpent_intro_1 = {"手札には", "不足がある"},
            fb_bl_serpent_intro_2 = {"出しても捨てても", "引くのは3枚だけ。"},
            fb_bl_serpent_big_hand_1 = {"3枚でも", "決めたか！"},
            fb_bl_serpent_close_1 = {"今さら逃げる", "な！"},
            fb_bl_serpent_last_hand_1 = {"最後の一噛み。", "3枚だけだ。"},
            fb_bl_serpent_disabled_1 = {"俺の牙が！シャー…", "毒が尽きた！"},
            fb_bl_serpent_defeat_1 = {"脱皮した…", "プライドも。"},
            fb_bl_serpent_gloat_1 = {"シャー！またな！"},
            fb_bl_serpent_interrupted_1 = {"シャー！話を", "遮るな！"},
            fb_bl_serpent_rematch_won_1 = {"一度は俺のとぐろから", "逃げたな。"},
            fb_bl_serpent_rematch_lost_1 = {"シャー…", "戻ってきたか…"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"だが俺は", "柱だ！"},
            fb_bl_pillar_intro_1 = {"過去のハンドから", "多くを学んだ"},
            fb_bl_pillar_intro_2 = {"出したカードは", "このアンティ弱体化。"},
            fb_bl_pillar_big_hand_1 = {"新しいカード？", "賢いな。"},
            fb_bl_pillar_close_1 = {"柱が", "崩れる！"},
            fb_bl_pillar_last_hand_1 = {"最後のハンド。", "古いカードは無駄だ。"},
            fb_bl_pillar_disabled_1 = {"記憶が…", "薄れていく。"},
            fb_bl_pillar_defeat_1 = {"大黒柱が", "倒れたか…"},
            fb_bl_pillar_gloat_1 = {"まだ立ってる！"},
            fb_bl_pillar_interrupted_1 = {"年長者を", "敬わんのか？"},
            fb_bl_pillar_rematch_won_1 = {"貴様の勝ち方、", "覚えているぞ。"},
            fb_bl_pillar_rematch_lost_1 = {"貴様の負け方、", "覚えているぞ。"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"だが俺は", "ニードルだ！"},
            fb_bl_needle_intro_1 = {"貴様の機会は", "一度きり"},
            fb_bl_needle_intro_2 = {"ハンドは1回。", "それだけだ。"},
            fb_bl_needle_big_hand_1 = {"たった1ハンドで", "この強さか！？"},
            fb_bl_needle_close_1 = {"ばかな！", "1ハンドで！"},
            fb_bl_needle_last_hand_1 = {"このハンドが", "唯一のハンドだ。"},
            fb_bl_needle_disabled_1 = {"俺の針が！", "鈍った！"},
            fb_bl_needle_defeat_1 = {"鋭い一手だ。", "やられた。"},
            fb_bl_needle_gloat_1 = {"要点は、負けだ！"},
            fb_bl_needle_interrupted_1 = {"チクリと来たな。", "まだ途中だ！"},
            fb_bl_needle_rematch_won_1 = {"前回はたった1ハンドに", "やられた。"},
            fb_bl_needle_rematch_lost_1 = {"またチャンスは1回。", "また外すか？"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"だが俺は", "頭だ！"},
            fb_bl_head_intro_1 = {"{C:red,E:1}恋人{}たちが", "大嫌いだ"},
            fb_bl_head_intro_2 = {"ハートは弱体化。", "冷たいだろ？"},
            fb_bl_head_big_hand_1 = {"ハート無しで", "勝っただと！？"},
            fb_bl_head_close_1 = {"情けをかけろ、", "止めを刺すな！"},
            fb_bl_head_last_hand_1 = {"最後のハンド。", "ハート無し。慈悲無し。"},
            fb_bl_head_disabled_1 = {"頭が痛い！", "ハートが戻った？"},
            fb_bl_head_defeat_1 = {"貴様のせいで", "頭を失った…"},
            fb_bl_head_gloat_1 = {"ハートレスか？"},
            fb_bl_head_interrupted_1 = {"頭がおかしいのか？", "俺が話してる！"},
            fb_bl_head_rematch_won_1 = {"一度は俺の心を", "奪ったな…"},
            fb_bl_head_rematch_lost_1 = {"また失恋しに", "来たのか？"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"だが俺は", "歯だ！"},
            fb_bl_tooth_intro_1 = {"俺は", "政治に夢中だ"},
            fb_bl_tooth_intro_2 = {"出すカード1枚", "ごとに$1払え。"},
            fb_bl_tooth_big_hand_1 = {"払ってなお", "勝つのか！？"},
            fb_bl_tooth_close_1 = {"歯の妖精には", "払わせるな！"},
            fb_bl_tooth_last_hand_1 = {"最後のハンド、", "最後のドル。"},
            fb_bl_tooth_disabled_1 = {"俺の噛む力が！", "消えた！"},
            fb_bl_tooth_defeat_1 = {"歯を食いしばって", "も負けたか。"},
            fb_bl_tooth_gloat_1 = {"払え、カモ！"},
            fb_bl_tooth_interrupted_1 = {"グルル！その分、", "払ってもらう！"},
            fb_bl_tooth_rematch_won_1 = {"前回の分、まだ", "払ってもらってないぞ。"},
            fb_bl_tooth_rematch_lost_1 = {"借金を返しに", "来たのか？"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"だが俺は", "フリントだ！"},
            fb_bl_flint_intro_1 = {"貴様は", "税を払え"},
            fb_bl_flint_intro_2 = {"チップと倍率は", "半分になる。"},
            fb_bl_flint_big_hand_1 = {"半分の力でも", "当てるか！？"},
            fb_bl_flint_close_1 = {"俺の破滅に", "火花を散らすな！"},
            fb_bl_flint_last_hand_1 = {"最後のハンド。", "火花は半分だ。"},
            fb_bl_flint_disabled_1 = {"フルパワー！？", "ずるいぞ！"},
            fb_bl_flint_defeat_1 = {"俺の火花が", "消えた。"},
            fb_bl_flint_gloat_1 = {"楽しさ半減！"},
            fb_bl_flint_interrupted_1 = {"火花を散らすな！", "話の途中だ！"},
            fb_bl_flint_rematch_won_1 = {"前回は税金を", "逃れやがったな。"},
            fb_bl_flint_rematch_lost_1 = {"また納税の季節だ。", "払え。"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"だが俺は", "マークだ！"},
            fb_bl_mark_intro_1 = {"見られるのは", "嫌いだ"},
            fb_bl_mark_intro_2 = {"絵札は全て", "伏せて配る。"},
            fb_bl_mark_big_hand_1 = {"印付きカードで", "勝つのか！？"},
            fb_bl_mark_close_1 = {"俺は敗北の", "印付きだ！"},
            fb_bl_mark_last_hand_1 = {"最後のハンド。", "顔は手探りで選べ。"},
            fb_bl_mark_disabled_1 = {"顔が！", "見えるぞ！"},
            fb_bl_mark_defeat_1 = {"貴様は俺に", "印を刻んだ。"},
            fb_bl_mark_gloat_1 = {"負けの印付き！"},
            fb_bl_mark_interrupted_1 = {"目をつけたぞ。", "覚えておけ。"},
            fb_bl_mark_rematch_won_1 = {"前回は俺の正体を", "見破ったな。"},
            fb_bl_mark_rematch_lost_1 = {"まだ俺の顔が", "見えないか？"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"だが俺は", "琥珀色のドングリだ！"},
            fb_bl_final_acorn_intro_1 = {"俺は", "混沌が好きだ！"},
            fb_bl_final_acorn_intro_2 = {"ジョーカーは伏せて", "シャッフル！"},
            fb_bl_final_acorn_big_hand_1 = {"混沌でも", "勝つのか！？"},
            fb_bl_final_acorn_close_1 = {"こりゃ堅い！", "割れそうだ！"},
            fb_bl_final_acorn_last_hand_1 = {"最後のハンド。", "ジョーカーはどこだ？"},
            fb_bl_final_acorn_disabled_1 = {"俺のドングリが！", "秩序が戻った！？"},
            fb_bl_final_acorn_defeat_1 = {"俺の殻を", "割ったな…"},
            fb_bl_final_acorn_gloat_1 = {"どんぐりころころ！"},
            fb_bl_final_acorn_interrupted_1 = {"待て待て！", "まだ芽も出てない！"},
            fb_bl_final_acorn_phase2_1 = {"ここからは", "もっと堅いぞ！"},
            fb_bl_final_acorn_phase3_1 = {"大混乱だ！", "殻を脱ぐぞ！"},
            fb_bl_final_acorn_rematch_won_1 = {"一度は俺を割ったな。", "二度とさせん！"},
            fb_bl_final_acorn_rematch_lost_1 = {"またカオスを", "求めて来たか？"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"だが俺は", "青々とした葉だ！"},
            fb_bl_final_leaf_intro_1 = {"貴様は根から", "離れねばならん"},
            fb_bl_final_leaf_intro_2 = {"ジョーカーを売れ。", "さもなくば弱体化。"},
            fb_bl_final_leaf_big_hand_1 = {"心機一転か。", "ふん。"},
            fb_bl_final_leaf_close_1 = {"俺の葉が", "落ちる！"},
            fb_bl_final_leaf_last_hand_1 = {"最後のハンド。", "ジョーカー売る？"},
            fb_bl_final_leaf_disabled_1 = {"俺の葉が！", "枯れた！"},
            fb_bl_final_leaf_defeat_1 = {"去るとしよう…", "葉のように。"},
            fb_bl_final_leaf_gloat_1 = {"枯れ葉のように", "散れ！"},
            fb_bl_final_leaf_interrupted_1 = {"いいだろう。", "挨拶は抜きだ。"},
            fb_bl_final_leaf_phase2_1 = {"俺の根は", "さらに深く！"},
            fb_bl_final_leaf_phase3_1 = {"共に枯れよ！"},
            fb_bl_final_leaf_rematch_won_1 = {"一度は手放せたな。", "もう一度やってみろ。"},
            fb_bl_final_leaf_rematch_lost_1 = {"まだジョーカーに", "しがみつくのか？"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"だが俺は", "バイオレットベッセルだ！"},
            fb_bl_final_vessel_intro_1 = {"万里の長城に", "ぶつかったな"},
            fb_bl_final_vessel_intro_2 = {"途方もなく巨大な", "ブラインド。出航！"},
            fb_bl_final_vessel_big_hand_1 = {"巨大な的への", "巨大な一撃。"},
            fb_bl_final_vessel_close_1 = {"総員退艦！", "…俺の船だが。"},
            fb_bl_final_vessel_last_hand_1 = {"最後のハンド。", "この船は沈まん。"},
            fb_bl_final_vessel_disabled_1 = {"俺の船が！", "沈んでいく！"},
            fb_bl_final_vessel_defeat_1 = {"船は…", "空になった。"},
            fb_bl_final_vessel_gloat_1 = {"大敗北だな！"},
            fb_bl_final_vessel_interrupted_1 = {"俺の話の前に出航か。", "大胆だな。"},
            fb_bl_final_vessel_phase2_1 = {"船倉を満たせ！"},
            fb_bl_final_vessel_phase3_1 = {"総員、", "深海へ！"},
            fb_bl_final_vessel_rematch_won_1 = {"一度は沈められたが、", "修理済みだ。"},
            fb_bl_final_vessel_rematch_lost_1 = {"俺の航跡で", "溺れに来たか？"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"だが俺は", "クリムゾンハートだ！"},
            fb_bl_final_heart_intro_1 = {"ジョーカーを", "一枚借りる"},
            fb_bl_final_heart_intro_2 = {"毎ハンド、ジョーカー", "1枚の力を奪う。"},
            fb_bl_final_heart_big_hand_1 = {"1枚欠けても", "まだ強いのか？"},
            fb_bl_final_heart_close_1 = {"俺の心を", "折るな！"},
            fb_bl_final_heart_last_hand_1 = {"最後のハンド。", "どれが黙る？"},
            fb_bl_final_heart_disabled_1 = {"俺の心臓が！", "鼓動が飛んだ。"},
            fb_bl_final_heart_defeat_1 = {"俺の心が…", "砕けた。"},
            fb_bl_final_heart_gloat_1 = {"失恋したか？"},
            fb_bl_final_heart_interrupted_1 = {"話を遮るのか？", "なんて薄情な！"},
            fb_bl_final_heart_phase2_1 = {"俺の鼓動が", "速くなる！"},
            fb_bl_final_heart_phase3_1 = {"真紅の怒りを", "思い知れ！"},
            fb_bl_final_heart_rematch_won_1 = {"前回は俺の心を", "砕いたな。"},
            fb_bl_final_heart_rematch_lost_1 = {"俺の心はまだ", "貴様に高鳴る。"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"だが俺は", "セルリアンベルだ！"},
            fb_bl_final_bell_intro_1 = {"貴様を", "導いてやろう"},
            fb_bl_final_bell_intro_2 = {"毎ハンド1枚、", "強制的に選ばれる。"},
            fb_bl_final_bell_big_hand_1 = {"強制カードを", "鳴らしたか！？"},
            fb_bl_final_bell_close_1 = {"鐘が鳴る…", "俺のために！？"},
            fb_bl_final_bell_last_hand_1 = {"最後のハンド。", "1枚は強制だ。"},
            fb_bl_final_bell_disabled_1 = {"鐘が鳴らん！", "イカサマだ！"},
            fb_bl_final_bell_defeat_1 = {"鐘が鳴る…", "俺のために。"},
            fb_bl_final_bell_gloat_1 = {"ゴーン、負けだ！"},
            fb_bl_final_bell_interrupted_1 = {"ゴングに救われた？", "今回は違う！"},
            fb_bl_final_bell_phase2_1 = {"もっと強く", "鳴り響け！"},
            fb_bl_final_bell_phase3_1 = {"最後の鐘だ！"},
            fb_bl_final_bell_rematch_won_1 = {"前回はガツンと", "鳴らされたな。"},
            fb_bl_final_bell_rematch_lost_1 = {"鐘はまた", "貴様のために鳴る。"},
        }
    }
}
