return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "결전",
            fb_cfg_dialogue = "보스 대사",
            fb_cfg_music = "결전 음악",
            fb_cfg_fx = "화면 효과",
            fb_cfg_cinematic = "결전 연출",
            fb_cfg_moves = "보스 기술",
            fb_cfg_phase_twists = "보스 페이즈가 규칙을 바꿈",
            fb_showdown_title = "결전",
            fb_cfg_intro_speed = "인트로 속도",
            fb_speed_slow = "느림",
            fb_speed_normal = "보통",
            fb_speed_fast = "빠름",
            fb_cfg_min_ante = "대사 시작 앤티",
            fb_cfg_memory = "보스 기억",
            fb_cfg_dev_mode = "개발자 키 (F5-F7)",
            fb_cfg_showdown_enabled = "결전 일정 직접 설정",
            fb_cfg_start_ante = "첫 결전 앤티",
            fb_cfg_every = "이후 N앤티마다",
            fb_cfg_preview = "결전 앤티",
            fb_cfg_hard = "어려움! 초반 결전은 가혹합니다.",
            fb_cfg_next_ante = "변경은 다음 앤티부터 적용됩니다.",
            fb_cfg_group_dialogue = "대사",
            fb_cfg_group_stage = "결전 무대",
            fb_credits_thanks = "FinalBoss를 플레이해 주셔서 감사합니다!",
            fb_credits_lead = "제작 및 관리:",
            fb_credits_music = "결전 음악:",
            fb_credits_music_by = "Adam Isiah (오케스트라 커버)",
            fb_credits_listen = "YouTube에서 듣기",
            fb_credits_github = "GitHub",
            fb_tip_me = "후원하기",
            fb_tip_me_message_1 = "FinalBoss가 마음에 드셨다면",
            fb_tip_me_message_2 = "작은 후원으로 응원해 주세요.",
            fb_tip_me_message_3 = "정말 감사합니다!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"보스가 말을 걸고, 결전은 보스전이 됩니다.", "제작 {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"너무 멀리 왔군..."},
            fb_opener_2 = {"안타깝지만", "말해주지..."},
            fb_opener_3 = {"그래. 여기까지", "왔군."},
            fb_closer_1 = {"넌 나를", "이길 수 없다."},
            fb_closer_2 = {"여기서 네 런은", "끝난다."},
            fb_closer_3 = {"네 실력을", "보여봐라."},
            fb_gloat = {"그 보스는", "너무 셌어..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"나는 바로", "#1#!"},
            fb_generic_name_2 = {"내 이름은", "#1#."},
            fb_generic_name_3 = {"보아라:", "#1#!"},
            fb_generic_intro_1 = {"네 운은", "여기서 끝이다."},
            fb_generic_intro_2 = {"이걸 어떻게", "넘기나 보자."},
            fb_generic_intro_3 = {"내 규칙을", "잘 읽어봐..."},
            fb_generic_big_hand_1 = {"...나쁘지 않군."},
            fb_generic_big_hand_2 = {"운 좋은 패군."},
            fb_generic_big_hand_3 = {"흥. 또?"},
            fb_generic_close_1 = {"잠깐, 잠깐,", "잠깐!"},
            fb_generic_close_2 = {"감히..."},
            fb_generic_close_3 = {"이럴 리가..."},
            fb_generic_last_hand_1 = {"남은 핸드는 하나.", "잘 쳐라."},
            fb_generic_last_hand_2 = {"똑딱, 똑딱..."},
            fb_generic_last_hand_3 = {"마지막 기회다,", "꼬마 조커."},
            fb_generic_disabled_1 = {"내 힘이...!", "무슨 짓을 했지?"},
            fb_generic_disabled_2 = {"이봐! 그건", "반칙이다!"},
            fb_generic_disabled_3 = {"힘이... 빠진다..."},
            fb_generic_defeat_1 = {"말도 안 돼..."},
            fb_generic_defeat_2 = {"다음 앤티에", "돌아오겠다..."},
            fb_generic_defeat_3 = {"잘 싸웠다..."},
            fb_generic_gloat_1 = {"그 보스는", "너무 셌어..."},
            fb_generic_gloat_2 = {"결국 하우스가", "이기는 법."},
            fb_generic_gloat_3 = {"다음 런엔", "행운을."},
            fb_generic_interrupted_1 = {"내 연설이!"},
            fb_generic_interrupted_2 = {"그래... 그렇게", "나온다 이거지."},
            fb_generic_interrupted_3 = {"인사도 없이?"},
            fb_generic_phase2_1 = {"장난은 끝이다!"},
            fb_generic_phase3_1 = {"이제 진짜", "화났다!"},
            fb_generic_rematch_won_1 = {"또 너냐?", "기억하고 있다."},
            fb_generic_rematch_won_2 = {"지난번엔 운이었다.", "인정해라."},
            fb_generic_rematch_won_3 = {"리벤지다.", "단련하고 왔다."},
            fb_generic_rematch_lost_1 = {"또 얻어맞으러", "왔나?"},
            fb_generic_rematch_lost_2 = {"지난번에", "배운 게 없나?"},
            fb_generic_rematch_lost_3 = {"아, 너구나.", "패배자."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"하지만 나는", "훅이다!"},
            fb_bl_hook_intro_1 = {"네 카드를", "몇 장 가져가지"},
            fb_bl_hook_intro_2 = {"매 핸드마다", "2장이 사라진다."},
            fb_bl_hook_big_hand_1 = {"카드가 줄었는데", "이겼다고?!"},
            fb_bl_hook_close_1 = {"그 카드들", "놓아라!"},
            fb_bl_hook_last_hand_1 = {"드디어 낚았다!"},
            fb_bl_hook_disabled_1 = {"내 훅이!", "부러졌다!"},
            fb_bl_hook_defeat_1 = {"좋아... 놔주지."},
            fb_bl_hook_gloat_1 = {"낚였구나!"},
            fb_bl_hook_interrupted_1 = {"무례하군! 아직", "말하는 중이었다!"},
            fb_bl_hook_rematch_won_1 = {"지난번엔 내 갈고리에서", "빠져나갔지."},
            fb_bl_hook_rematch_lost_1 = {"또 낚이러", "왔나?"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"하지만 나는", "황소다!"},
            fb_bl_ox_intro_1 = {"네 돈을", "전부 가져가겠다"},
            fb_bl_ox_intro_2 = {"최애 핸드는", "전재산을 앗아간다."},
            fb_bl_ox_big_hand_1 = {"빈털터리인데", "이기다니?!"},
            fb_bl_ox_close_1 = {"진정해!", "...나도."},
            fb_bl_ox_last_hand_1 = {"마지막 핸드.", "쓰든지 잃든지."},
            fb_bl_ox_disabled_1 = {"내 뿔이!", "무뎌졌다!"},
            fb_bl_ox_defeat_1 = {"황소의 뿔을", "잡았군..."},
            fb_bl_ox_gloat_1 = {"이제 빈털터리!"},
            fb_bl_ox_interrupted_1 = {"오호, 이렇게", "나오시겠다?"},
            fb_bl_ox_rematch_won_1 = {"한 번은 내 뿔을", "피했지..."},
            fb_bl_ox_rematch_lost_1 = {"지난번 이후로", "아직 빈털터리인가?"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"하지만 나는", "집이다!"},
            fb_bl_house_intro_1 = {"넌", "눈먼 신세다!"},
            fb_bl_house_intro_2 = {"첫 핸드는", "뒤집어서 준다!"},
            fb_bl_house_big_hand_1 = {"눈먼 운으로", "이기다니?!"},
            fb_bl_house_close_1 = {"집은 절대", "지지 않아!"},
            fb_bl_house_last_hand_1 = {"더는 눈먼", "행운은 없다."},
            fb_bl_house_disabled_1 = {"내 눈가리개가!", "떨어졌다!"},
            fb_bl_house_defeat_1 = {"집이...", "무너졌다."},
            fb_bl_house_gloat_1 = {"하우스 승!"},
            fb_bl_house_interrupted_1 = {"집의 규칙이다,", "아직 치지 마!"},
            fb_bl_house_rematch_won_1 = {"하우스가 진 건 한 번.", "다시는 없다."},
            fb_bl_house_rematch_lost_1 = {"돌아온 걸 환영한다.", "하우스는 기억한다."},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"하지만 나는", "벽이다!"},
            fb_bl_wall_intro_1 = {"방금 하나", "부딪혔군"},
            fb_bl_wall_intro_2 = {"이 점수를", "기어올라 봐라."},
            fb_bl_wall_big_hand_1 = {"내 벽을", "넘었다고?!"},
            fb_bl_wall_close_1 = {"넌 날 절대", "못 뚫어!"},
            fb_bl_wall_last_hand_1 = {"더는 오를", "곳이 없다."},
            fb_bl_wall_disabled_1 = {"금이 갔어!", "벽이 갈라진다!"},
            fb_bl_wall_defeat_1 = {"벽이...", "무너진다."},
            fb_bl_wall_gloat_1 = {"벽에 부딪혔지?"},
            fb_bl_wall_interrupted_1 = {"벽에 말하는 기분...", "아, 내가 벽이지."},
            fb_bl_wall_rematch_won_1 = {"한 번은 날 넘었지.", "두 번은 없다."},
            fb_bl_wall_rematch_lost_1 = {"또 같은 벽에", "부딪히러 왔나?"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"하지만 나는", "바퀴다!"},
            fb_bl_wheel_intro_1 = {"난...", "도박이 좋아!"},
            fb_bl_wheel_intro_2 = {"7장 중 1장은", "뒤집혀 나온다."},
            fb_bl_wheel_big_hand_1 = {"오늘은 행운의", "여신이 네 편이군."},
            fb_bl_wheel_close_1 = {"내 바퀴가", "헛돈다!"},
            fb_bl_wheel_last_hand_1 = {"마지막 회전.", "운이 따를까?"},
            fb_bl_wheel_disabled_1 = {"바퀴가 멈췄어?", "조작이다!"},
            fb_bl_wheel_defeat_1 = {"운명의 바퀴가", "나를 등졌다..."},
            fb_bl_wheel_gloat_1 = {"운이 다했군!"},
            fb_bl_wheel_interrupted_1 = {"워! 서두르지 마,", "아직 돌고 있다!"},
            fb_bl_wheel_rematch_won_1 = {"지난 판엔 운이", "좋았지..."},
            fb_bl_wheel_rematch_lost_1 = {"한 판 더?", "하우스가 유리하지."},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"하지만 나는", "팔이다!"},
            fb_bl_arm_intro_1 = {"네 힘의", "균형을 맞추지"},
            fb_bl_arm_intro_2 = {"낸 핸드마다", "레벨이 내려간다."},
            fb_bl_arm_big_hand_1 = {"그 핸드, 근육이", "좀 있군..."},
            fb_bl_arm_close_1 = {"팔씨름이라고?", "내가 진다!"},
            fb_bl_arm_last_hand_1 = {"마지막 핸드.", "힘주지 마라."},
            fb_bl_arm_disabled_1 = {"팔에 힘이 빠졌다!", "반칙이다!"},
            fb_bl_arm_defeat_1 = {"내 강한 팔을", "꺾었군."},
            fb_bl_arm_gloat_1 = {"레벨 다운!"},
            fb_bl_arm_interrupted_1 = {"손 떼! 아직 근육", "자랑 중이었다!"},
            fb_bl_arm_rematch_won_1 = {"지난번 팔씨름은", "네가 이겼지."},
            fb_bl_arm_rematch_lost_1 = {"또 팔씨름하러", "왔나?"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"하지만 나는", "클럽이다!"},
            fb_bl_club_intro_1 = {"{C:green,E:1}운 좋은{} 놈은", "질색이다"},
            fb_bl_club_intro_2 = {"클럽은 약화됐다.", "미안하군."},
            fb_bl_club_big_hand_1 = {"클럽 없이도", "멀쩡하다고?!"},
            fb_bl_club_close_1 = {"그걸로 날", "때리지 마!"},
            fb_bl_club_last_hand_1 = {"마지막 핸드.", "클럽은 두고 와라."},
            fb_bl_club_disabled_1 = {"내 클럽이", "힘을 잃었다!"},
            fb_bl_club_defeat_1 = {"클럽 폐업이다.", "갈 시간이군..."},
            fb_bl_club_gloat_1 = {"영업 종료!"},
            fb_bl_club_interrupted_1 = {"이봐! 내 클럽에선", "내가 먼저 말한다!"},
            fb_bl_club_rematch_won_1 = {"지난번엔 내 클럽에", "쳐들어왔지."},
            fb_bl_club_rematch_lost_1 = {"회원권 갱신했나?", "어서 와라."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"하지만 나는", "물고기다!"},
            fb_bl_fish_intro_1 = {"낼 카드는", "신중히 골라라"},
            fb_bl_fish_intro_2 = {"핸드를 낼 때마다", "카드가 뒤집힌다."},
            fb_bl_fish_big_hand_1 = {"그 핸드,", "뭔가 수상하군!"},
            fb_bl_fish_close_1 = {"날 건져", "올리지 마!"},
            fb_bl_fish_last_hand_1 = {"마지막 낚시.", "끌어올려라."},
            fb_bl_fish_disabled_1 = {"내 비늘이!", "떨어졌다!"},
            fb_bl_fish_defeat_1 = {"낚였다...", "프로에게."},
            fb_bl_fish_gloat_1 = {"물에 빠졌군!"},
            fb_bl_fish_interrupted_1 = {"내 낚싯줄을", "끊었겠다!"},
            fb_bl_fish_rematch_won_1 = {"놓친 고기가", "커 보이는 법..."},
            fb_bl_fish_rematch_lost_1 = {"또 내 낚싯바늘에", "걸렸나, 피라미?"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"하지만 나는", "심령술사다!"},
            fb_bl_psychic_intro_1 = {"우유부단한", "놈은 질색이다"},
            fb_bl_psychic_intro_2 = {"5장, 그 이하는", "안 된다. 예견했지."},
            fb_bl_psychic_big_hand_1 = {"이건 전혀", "예견 못 했다."},
            fb_bl_psychic_close_1 = {"수정구가 보여준", "건... 패배!"},
            fb_bl_psychic_last_hand_1 = {"네 마지막 핸드가", "보인다."},
            fb_bl_psychic_disabled_1 = {"내 환영이!", "사라졌다!"},
            fb_bl_psychic_defeat_1 = {"예견했다.", "...아닌가?"},
            fb_bl_psychic_gloat_1 = {"내 말이 맞았지!"},
            fb_bl_psychic_interrupted_1 = {"그럴 줄 알았다.", "...그래도 무례해."},
            fb_bl_psychic_rematch_won_1 = {"네 지난 승리는", "예견하지 못했다."},
            fb_bl_psychic_rematch_lost_1 = {"돌아올 줄", "알았다."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"하지만 나는", "자극이다!"},
            fb_bl_goad_intro_1 = {"{C:black,E:1}권력{}은", "질색이다"},
            fb_bl_goad_intro_2 = {"스페이드는 약화.", "더 깊이 파라."},
            fb_bl_goad_big_hand_1 = {"스페이드 없이도", "꽤 하는군."},
            fb_bl_goad_close_1 = {"감히 내 무덤을", "파지 마!"},
            fb_bl_goad_last_hand_1 = {"깊이 파라. 마지막", "핸드다."},
            fb_bl_goad_disabled_1 = {"이제 아무도", "자극 못 해!"},
            fb_bl_goad_defeat_1 = {"젠장,", "네가 이겼다."},
            fb_bl_goad_gloat_1 = {"제 무덤을 파라!"},
            fb_bl_goad_interrupted_1 = {"나를 도발해?", "좋다!"},
            fb_bl_goad_rematch_won_1 = {"지난번엔 무덤에서", "기어 나왔지."},
            fb_bl_goad_rematch_lost_1 = {"더 깊은 무덤을", "파러 왔나?"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"하지만 나는", "물이다!"},
            fb_bl_water_intro_1 = {"네 버리기를", "내놔라"},
            fb_bl_water_intro_2 = {"버리기 없음.", "한 방울도."},
            fb_bl_water_big_hand_1 = {"버리기 없이", "이겼다고?!"},
            fb_bl_water_close_1 = {"빠져 죽겠어!", "밧줄을 던져!"},
            fb_bl_water_last_hand_1 = {"마지막 핸드.", "헤엄치든 가라앉든."},
            fb_bl_water_disabled_1 = {"버리기가", "다시 흐른다!"},
            fb_bl_water_defeat_1 = {"바싹 말랐군..."},
            fb_bl_water_gloat_1 = {"물거품이 됐군!"},
            fb_bl_water_interrupted_1 = {"말을 끊어? 이제", "물 건너갔다!"},
            fb_bl_water_rematch_won_1 = {"지난번엔 용케", "떠 있었지."},
            fb_bl_water_rematch_lost_1 = {"또 물 먹으러", "왔나?"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"하지만 나는", "창문이다!"},
            fb_bl_window_intro_1 = {"{C:yellow,E:1}자본주의{}는", "질색이다"},
            fb_bl_window_intro_2 = {"다이아는 약화.", "계속 빛나 봐라."},
            fb_bl_window_big_hand_1 = {"다이아가", "뭐가 필요해?"},
            fb_bl_window_close_1 = {"내 창문을", "깨지 마!"},
            fb_bl_window_last_hand_1 = {"마지막 핸드.", "반짝임 금지."},
            fb_bl_window_disabled_1 = {"창문이 깨졌다!", "다이아가 빛난다!"},
            fb_bl_window_defeat_1 = {"내 기회의 창이", "닫혔다."},
            fb_bl_window_gloat_1 = {"다이아? 약화!"},
            fb_bl_window_interrupted_1 = {"내 말을 창밖으로", "던져버리겠다고?!"},
            fb_bl_window_rematch_won_1 = {"한 번은 내 창문을", "깼지."},
            fb_bl_window_rematch_lost_1 = {"또 아이쇼핑", "하러 왔나?"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"하지만 나는", "수갑이다!"},
            fb_bl_manacle_intro_1 = {"네 {C:blue,E:1}선택지{}를", "빼앗겠다"},
            fb_bl_manacle_intro_2 = {"손패가 한 장", "줄어든다."},
            fb_bl_manacle_big_hand_1 = {"수갑을 차고도", "이긴다고?!"},
            fb_bl_manacle_close_1 = {"사슬을", "벗어나는군!"},
            fb_bl_manacle_last_hand_1 = {"마지막 핸드.", "수갑까지 찼군."},
            fb_bl_manacle_disabled_1 = {"수갑이!", "풀렸다!"},
            fb_bl_manacle_defeat_1 = {"드디어 자유...", "나로부터."},
            fb_bl_manacle_gloat_1 = {"손도 못 쓰지?"},
            fb_bl_manacle_interrupted_1 = {"멈춰! 그 대가로", "족쇄를 채워주마!"},
            fb_bl_manacle_rematch_won_1 = {"한 번은 내 사슬을", "풀었지."},
            fb_bl_manacle_rematch_lost_1 = {"또 사슬에", "묶였군."},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"하지만 나는", "눈이다!"},
            fb_bl_eye_intro_1 = {"난 반복되는", "건 싫어"},
            fb_bl_eye_intro_2 = {"같은 족보는", "두 번 내지 마라."},
            fb_bl_eye_big_hand_1 = {"새 족보군?", "다 보고 있다."},
            fb_bl_eye_close_1 = {"차마", "못 보겠다!"},
            fb_bl_eye_last_hand_1 = {"네 마지막 핸드가", "보인다."},
            fb_bl_eye_disabled_1 = {"내 눈이! 누가", "찔렀어?!"},
            fb_bl_eye_defeat_1 = {"눈에서 멀어지면", "마음에서도..."},
            fb_bl_eye_gloat_1 = {"내 말이 맞지!"},
            fb_bl_eye_interrupted_1 = {"다 봤다!", "무례하군."},
            fb_bl_eye_rematch_won_1 = {"그 패배 이후로", "널 지켜봤다."},
            fb_bl_eye_rematch_lost_1 = {"돌아온 게", "보이는군."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"하지만 나는", "입이다!"},
            fb_bl_mouth_intro_1 = {"난 반복이", "좋아"},
            fb_bl_mouth_intro_2 = {"족보 하나를 골라", "끝까지 가라."},
            fb_bl_mouth_big_hand_1 = {"늘 같은 핸드인데", "여전히 세군..."},
            fb_bl_mouth_close_1 = {"내 입이", "떡 벌어졌다!"},
            fb_bl_mouth_last_hand_1 = {"마지막 핸드. 같은", "족보. 입 닫아."},
            fb_bl_mouth_disabled_1 = {"누가 내게", "재갈을?!"},
            fb_bl_mouth_defeat_1 = {"할 말을 잃었군..."},
            fb_bl_mouth_gloat_1 = {"입 닥쳐, 패배자!"},
            fb_bl_mouth_interrupted_1 = {"이봐! 이 입은", "아직 말하고 있었다!"},
            fb_bl_mouth_rematch_won_1 = {"지난번엔 내 입을", "막았지."},
            fb_bl_mouth_rematch_lost_1 = {"지난번과 같은", "루틴인가?"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"하지만 나는", "행성이다!"},
            fb_bl_plant_intro_1 = {"친근한 얼굴은", "질색이다"},
            fb_bl_plant_intro_2 = {"킹, 퀸, 잭:", "전부 약화."},
            fb_bl_plant_big_hand_1 = {"그림 카드 없이?!", "믿기지 않군."},
            fb_bl_plant_close_1 = {"뿌리째", "뽑지 마!"},
            fb_bl_plant_last_hand_1 = {"마지막 핸드를", "직시해라."},
            fb_bl_plant_disabled_1 = {"내 꽃잎이!", "다 사라졌다!"},
            fb_bl_plant_defeat_1 = {"시들었군...", "다시 자라겠다."},
            fb_bl_plant_gloat_1 = {"현실을 직시해!"},
            fb_bl_plant_interrupted_1 = {"좀 자라게 둬라,", "성질 급하긴!"},
            fb_bl_plant_rematch_won_1 = {"뿌리째 뽑혔지만", "다시 자랐다."},
            fb_bl_plant_rematch_lost_1 = {"또 내 정원에", "왔군."},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"하지만 나는", "뱀이다!"},
            fb_bl_serpent_intro_1 = {"카드가", "부족하지"},
            fb_bl_serpent_intro_2 = {"내든 버리든", "3장만 뽑는다."},
            fb_bl_serpent_big_hand_1 = {"3장인데도", "한 방 먹였군!"},
            fb_bl_serpent_close_1 = {"지금 도망치지", "마!"},
            fb_bl_serpent_last_hand_1 = {"마지막 한 방.", "카드는 3장."},
            fb_bl_serpent_disabled_1 = {"내 송곳니! 쉬익...", "독이 다 떨어졌다!"},
            fb_bl_serpent_defeat_1 = {"허물을 벗었군...", "자존심도."},
            fb_bl_serpent_gloat_1 = {"쉬익, 또 보자!"},
            fb_bl_serpent_interrupted_1 = {"쉬익! 말 끊지", "마라!"},
            fb_bl_serpent_rematch_won_1 = {"한 번은 내 똬리에서", "빠져나갔지."},
            fb_bl_serpent_rematch_lost_1 = {"쉬이익...", "돌아왔군..."},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"하지만 나는", "기둥이다!"},
            fb_bl_pillar_intro_1 = {"네 지난 핸드에서", "많이 배웠다"},
            fb_bl_pillar_intro_2 = {"낸 카드는 이번", "앤티 내내 약화."},
            fb_bl_pillar_big_hand_1 = {"새 카드라고?", "영리하군."},
            fb_bl_pillar_close_1 = {"내 기둥이", "무너진다!"},
            fb_bl_pillar_last_hand_1 = {"마지막 핸드.", "옛 카드는 쓸모없다."},
            fb_bl_pillar_disabled_1 = {"내 기억이!", "...흐려진다."},
            fb_bl_pillar_defeat_1 = {"공동체의 기둥이", "쓰러졌다."},
            fb_bl_pillar_gloat_1 = {"아직 서 있다!"},
            fb_bl_pillar_interrupted_1 = {"어른을 공경할", "줄 모르나?"},
            fb_bl_pillar_rematch_won_1 = {"네가 날 이긴 방법,", "기억하고 있다."},
            fb_bl_pillar_rematch_lost_1 = {"네가 진 방법,", "기억하고 있다."},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"하지만 나는", "바늘이다!"},
            fb_bl_needle_intro_1 = {"넌 기회가", "단 한 번뿐이다"},
            fb_bl_needle_intro_2 = {"핸드는 하나.", "그게 전부다."},
            fb_bl_needle_big_hand_1 = {"핸드 하나로", "이렇게 세다고?!"},
            fb_bl_needle_close_1 = {"안 돼! 핸드", "하나로는!"},
            fb_bl_needle_last_hand_1 = {"이 핸드가", "네 유일한 핸드."},
            fb_bl_needle_disabled_1 = {"내 바늘이!", "무뎌졌다!"},
            fb_bl_needle_defeat_1 = {"날카로운 플레이.", "내가 졌다."},
            fb_bl_needle_gloat_1 = {"핵심은 네 패배!"},
            fb_bl_needle_interrupted_1 = {"따끔하군.", "아직 안 끝났다!"},
            fb_bl_needle_rematch_won_1 = {"지난번엔 핸드 하나에", "당했지."},
            fb_bl_needle_rematch_lost_1 = {"또 기회는 한 번.", "또 놓칠 건가?"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"하지만 나는", "머리다!"},
            fb_bl_head_intro_1 = {"{C:red,E:1}연인{}은", "질색이다"},
            fb_bl_head_intro_2 = {"하트는 약화.", "차갑지?"},
            fb_bl_head_big_hand_1 = {"하트 없이", "이겼다고?!"},
            fb_bl_head_close_1 = {"인정을 베풀어,", "끝내지 마!"},
            fb_bl_head_last_hand_1 = {"마지막 핸드. 하트", "없다. 자비도 없다."},
            fb_bl_head_disabled_1 = {"머리가 아프다!", "하트가 돌아왔나?"},
            fb_bl_head_defeat_1 = {"너 때문에", "머리를 잃었다..."},
            fb_bl_head_gloat_1 = {"무정하군!"},
            fb_bl_head_interrupted_1 = {"정신 나갔나?", "내가 말하는 중이다!"},
            fb_bl_head_rematch_won_1 = {"한 번은 내 마음을", "얻었지..."},
            fb_bl_head_rematch_lost_1 = {"또 상처받으러", "왔나?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"하지만 나는", "이빨이다!"},
            fb_bl_tooth_intro_1 = {"난 정치에", "관심이 많지"},
            fb_bl_tooth_intro_2 = {"카드 한 장마다", "$1을 내라."},
            fb_bl_tooth_big_hand_1 = {"돈을 내고도", "이겼다고?!"},
            fb_bl_tooth_close_1 = {"이빨 요정에게", "돈 내게 하지 마!"},
            fb_bl_tooth_last_hand_1 = {"마지막 핸드,", "마지막 달러."},
            fb_bl_tooth_disabled_1 = {"내 이빨이!", "사라졌다!"},
            fb_bl_tooth_defeat_1 = {"이를 악물어도", "졌구나."},
            fb_bl_tooth_gloat_1 = {"돈 내, 호구야!"},
            fb_bl_tooth_interrupted_1 = {"으르렁! 그 대가를", "치르게 해주마!"},
            fb_bl_tooth_rematch_won_1 = {"지난번 몫, 아직", "받을 게 남았다."},
            fb_bl_tooth_rematch_lost_1 = {"빚 갚으러", "왔나?"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"하지만 나는", "부싯돌이다!"},
            fb_bl_flint_intro_1 = {"넌 세금을", "내야 한다"},
            fb_bl_flint_intro_2 = {"칩과 배수가", "절반이 된다."},
            fb_bl_flint_big_hand_1 = {"힘이 절반인데", "명중이라고?!"},
            fb_bl_flint_close_1 = {"내 몰락에", "불꽃을 튀기다니!"},
            fb_bl_flint_last_hand_1 = {"마지막 핸드.", "불꽃은 절반."},
            fb_bl_flint_disabled_1 = {"풀파워라고?!", "불공평해!"},
            fb_bl_flint_defeat_1 = {"내 불꽃이", "꺼졌다."},
            fb_bl_flint_gloat_1 = {"재미도 반토막!"},
            fb_bl_flint_interrupted_1 = {"불똥 튀기지 마!", "말하는 중이었다!"},
            fb_bl_flint_rematch_won_1 = {"지난번엔 세금을", "떼먹었지."},
            fb_bl_flint_rematch_lost_1 = {"또 세금 철이다.", "내라."},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"하지만 나는", "가면이다!"},
            fb_bl_mark_intro_1 = {"난 보이는 게", "싫다"},
            fb_bl_mark_intro_2 = {"그림 카드는 모두", "뒤집혀 나온다."},
            fb_bl_mark_big_hand_1 = {"뒤집힌 카드로", "이겼다고?!"},
            fb_bl_mark_close_1 = {"난 패배로", "낙인찍혔다!"},
            fb_bl_mark_last_hand_1 = {"마지막 핸드. 얼굴을", "눈감고 골라라."},
            fb_bl_mark_disabled_1 = {"얼굴이!", "다 보인다!"},
            fb_bl_mark_defeat_1 = {"내게 네 흔적을", "남겼군."},
            fb_bl_mark_gloat_1 = {"패배로 낙인!"},
            fb_bl_mark_interrupted_1 = {"기억해 두지.", "넌 찍혔다."},
            fb_bl_mark_rematch_won_1 = {"지난번엔 내 가면을", "꿰뚫어 봤지."},
            fb_bl_mark_rematch_lost_1 = {"아직도 내 얼굴이", "안 보이나?"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"하지만 나는", "호박색 도토리다!"},
            fb_bl_final_acorn_intro_1 = {"난", "혼돈이 좋아!"},
            fb_bl_final_acorn_intro_2 = {"조커는 뒤집고", "섞어버린다!"},
            fb_bl_final_acorn_big_hand_1 = {"혼돈 속에서도", "이긴다고?!"},
            fb_bl_final_acorn_close_1 = {"이거 완전 딱딱해!", "금이 간다!"},
            fb_bl_final_acorn_last_hand_1 = {"마지막 핸드.", "네 조커는 어디?"},
            fb_bl_final_acorn_disabled_1 = {"내 도토리!", "질서가 돌아왔어?!"},
            fb_bl_final_acorn_defeat_1 = {"내 껍질을", "깨버렸군..."},
            fb_bl_final_acorn_gloat_1 = {"도토리 키 재기!"},
            fb_bl_final_acorn_interrupted_1 = {"잠깐! 아직 싹도", "안 텄다고!"},
            fb_bl_final_acorn_phase2_1 = {"이제부터", "더 딱딱해진다!"},
            fb_bl_final_acorn_phase3_1 = {"완전한 혼돈!", "껍질을 벗는다!"},
            fb_bl_final_acorn_rematch_won_1 = {"한 번은 날 깼지.", "다신 안 돼!"},
            fb_bl_final_acorn_rematch_lost_1 = {"또 혼돈을", "원하나?"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"하지만 나는", "심록색 잎사귀다!"},
            fb_bl_final_leaf_intro_1 = {"넌 뿌리에서", "떨어져야 해"},
            fb_bl_final_leaf_intro_2 = {"조커를 팔거나", "약화 상태 유지."},
            fb_bl_final_leaf_big_hand_1 = {"새 출발을", "했군. 흥."},
            fb_bl_final_leaf_close_1 = {"내 잎이", "떨어진다!"},
            fb_bl_final_leaf_last_hand_1 = {"마지막 핸드.", "조커 팔래?"},
            fb_bl_final_leaf_disabled_1 = {"내 잎이!", "말라버렸다!"},
            fb_bl_final_leaf_defeat_1 = {"떠나마...", "낙엽처럼."},
            fb_bl_final_leaf_gloat_1 = {"낙엽처럼 져라!"},
            fb_bl_final_leaf_interrupted_1 = {"좋다. 인사는", "생략하지."},
            fb_bl_final_leaf_phase2_1 = {"내 뿌리가", "더 깊어진다!"},
            fb_bl_final_leaf_phase3_1 = {"나와 함께", "시들어라!"},
            fb_bl_final_leaf_rematch_won_1 = {"한 번은 놓아줬지.", "다시 해 봐라."},
            fb_bl_final_leaf_rematch_lost_1 = {"아직도 조커에", "매달리나?"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"하지만 나는", "보라색 술잔이다!"},
            fb_bl_final_vessel_intro_1 = {"만리장성에", "부딪혔군"},
            fb_bl_final_vessel_intro_2 = {"엄청나게 거대한", "블라인드. 출항!"},
            fb_bl_final_vessel_big_hand_1 = {"거대한 과녁에", "거대한 한 방."},
            fb_bl_final_vessel_close_1 = {"전원 퇴함!", "...내 배 말이다."},
            fb_bl_final_vessel_last_hand_1 = {"마지막 핸드.", "이 배는 안 가라앉아."},
            fb_bl_final_vessel_disabled_1 = {"내 술잔이!", "가라앉는다!"},
            fb_bl_final_vessel_defeat_1 = {"술잔이...", "비어버렸다."},
            fb_bl_final_vessel_gloat_1 = {"완패했군!"},
            fb_bl_final_vessel_interrupted_1 = {"내 연설 전에", "출항이라니. 대담하군."},
            fb_bl_final_vessel_phase2_1 = {"화물칸을 채워라!"},
            fb_bl_final_vessel_phase3_1 = {"전원,", "심해로!"},
            fb_bl_final_vessel_rematch_won_1 = {"한 번은 날 침몰시켰지.", "수리는 끝났다."},
            fb_bl_final_vessel_rematch_lost_1 = {"내 항적에", "빠져 죽으러 왔나?"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"하지만 나는", "진홍색 술잔이다!"},
            fb_bl_final_heart_intro_1 = {"조커 한 장을", "빌리겠다"},
            fb_bl_final_heart_intro_2 = {"매 핸드 조커 하나가", "힘을 잃는다."},
            fb_bl_final_heart_big_hand_1 = {"조커가 빠졌는데", "아직 세군?"},
            fb_bl_final_heart_close_1 = {"내 마음을", "부수지 마!"},
            fb_bl_final_heart_last_hand_1 = {"마지막 핸드. 어느", "조커가 침묵?"},
            fb_bl_final_heart_disabled_1 = {"내 심장이!", "한 박자 걸렀다."},
            fb_bl_final_heart_defeat_1 = {"내 마음이...", "부서졌다."},
            fb_bl_final_heart_gloat_1 = {"상심했나?"},
            fb_bl_final_heart_interrupted_1 = {"내 말을 끊어?", "무정하군!"},
            fb_bl_final_heart_phase2_1 = {"내 심장이", "더 빨리 뛴다!"},
            fb_bl_final_heart_phase3_1 = {"진홍빛 분노를", "느껴라!"},
            fb_bl_final_heart_rematch_won_1 = {"지난번엔 내 마음을", "부쉈지."},
            fb_bl_final_heart_rematch_lost_1 = {"내 심장은 아직", "너를 위해 뛴다."},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"하지만 나는", "하늘색 종이다!"},
            fb_bl_final_bell_intro_1 = {"널 이끌어", "주고 싶군"},
            fb_bl_final_bell_intro_2 = {"매 핸드 카드 한 장이", "강제로 선택된다."},
            fb_bl_final_bell_big_hand_1 = {"내 강제 카드를", "울렸다고?!"},
            fb_bl_final_bell_close_1 = {"종이 울린다...", "나를 위해?!"},
            fb_bl_final_bell_last_hand_1 = {"마지막 핸드.", "카드 한 장 강제."},
            fb_bl_final_bell_disabled_1 = {"내 종이 조용해!", "반칙이다!"},
            fb_bl_final_bell_defeat_1 = {"종이 울린다", "나를 위해."},
            fb_bl_final_bell_gloat_1 = {"땡땡, 졌구나!"},
            fb_bl_final_bell_interrupted_1 = {"종소리에 살았다고?", "이번엔 아니다!"},
            fb_bl_final_bell_phase2_1 = {"더 크게", "울려주마!"},
            fb_bl_final_bell_phase3_1 = {"마지막 종소리다!"},
            fb_bl_final_bell_rematch_won_1 = {"지난번엔 내 종을", "제대로 울렸지."},
            fb_bl_final_bell_rematch_lost_1 = {"종은 다시", "너를 위해 울린다."},
        }
    }
}
