return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Showdowns",
            fb_cfg_dialogue = "Baasdialogen",
            fb_cfg_music = "Showdown-muziek",
            fb_cfg_fx = "Schermeffecten",
            fb_cfg_intro_speed = "Introsnelheid",
            fb_speed_slow = "Langzaam",
            fb_speed_normal = "Normaal",
            fb_speed_fast = "Snel",
            fb_cfg_min_ante = "Baasdialogen vanaf Ante",
            fb_cfg_dev_mode = "Ontwikkelaarstoetsen (F5-F7)",
            fb_cfg_showdown_enabled = "Eigen showdown-schema",
            fb_cfg_start_ante = "Eerste showdown bij Ante",
            fb_cfg_every = "Daarna elke N Ante's",
            fb_cfg_preview = "Showdowns bij Ante:",
            fb_cfg_hard = "Zwaar! Vroege showdowns zijn bruut.",
            fb_cfg_next_ante = "Wijzigingen gelden vanaf de volgende Ante.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Je bent te ver", "gekomen..."},
            fb_opener_2 = {"En helaas moet ik", "zeggen..."},
            fb_opener_3 = {"Dus. Je hebt het", "gehaald."},
            fb_closer_1 = {"Je gaat me niet", "kunnen verslaan."},
            fb_closer_2 = {"Hier eindigt", "jouw run."},
            fb_closer_3 = {"Laat maar zien wat", "je in huis hebt."},
            fb_gloat = {"Die baas was", "te veel..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Ik ben #1#!"},
            fb_generic_name_2 = {"Ze noemen me", "#1#."},
            fb_generic_name_3 = {"Aanschouw:", "#1#!"},
            fb_generic_intro_1 = {"Je geluk", "eindigt hier."},
            fb_generic_intro_2 = {"Eens kijken hoe je", "hier mee omgaat."},
            fb_generic_intro_3 = {"Lees mijn regels", "goed..."},
            fb_generic_big_hand_1 = {"...Niet slecht."},
            fb_generic_big_hand_2 = {"Mazzelhand."},
            fb_generic_big_hand_3 = {"Hmpf. Alweer?"},
            fb_generic_close_1 = {"Wacht, wacht,", "WACHT!"},
            fb_generic_close_2 = {"Waag het niet..."},
            fb_generic_close_3 = {"Dit kan niet..."},
            fb_generic_last_hand_1 = {"Nog één hand.", "Laat hem tellen."},
            fb_generic_last_hand_2 = {"Tik, tak..."},
            fb_generic_last_hand_3 = {"Laatste kans,", "kleine joker."},
            fb_generic_disabled_1 = {"Mijn kracht...!", "Wat heb je gedaan?"},
            fb_generic_disabled_2 = {"Hé! Dat is", "valsspelen!"},
            fb_generic_disabled_3 = {"Ik voel me... zwak."},
            fb_generic_defeat_1 = {"Onmogelijk..."},
            fb_generic_defeat_2 = {"Ik kom terug bij", "de volgende Ante..."},
            fb_generic_defeat_3 = {"Goed gespeeld..."},
            fb_generic_gloat_1 = {"Die baas was", "te veel..."},
            fb_generic_gloat_2 = {"De bank", "wint altijd."},
            fb_generic_gloat_3 = {"Beter geluk", "volgende run."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Maar ik ben", "De haak"},
            fb_bl_hook_intro_1 = {"Ik neem een paar", "van je kaarten"},
            fb_bl_hook_intro_2 = {"Twee kaarten weg,", "elke hand."},
            fb_bl_hook_big_hand_1 = {"Zelfs met minder", "kaarten?!"},
            fb_bl_hook_close_1 = {"Blijf van die", "kaarten af!"},
            fb_bl_hook_last_hand_1 = {"Eindelijk heb ik", "je aan de haak!"},
            fb_bl_hook_disabled_1 = {"Mijn haak!", "Hij is kapot!"},
            fb_bl_hook_defeat_1 = {"Goed... ik laat", "je van de haak."},
            fb_bl_hook_gloat_1 = {"De haak:", "\"Aan de haak geslagen!\""},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Maar ik ben", "De os"},
            fb_bl_ox_intro_1 = {"Ik neem al", "je geld"},
            fb_bl_ox_intro_2 = {"Je favoriete hand", "kost je alles."},
            fb_bl_ox_big_hand_1 = {"Blut en toch", "winnen?!"},
            fb_bl_ox_close_1 = {"Rustig aan!", "...Ik ook."},
            fb_bl_ox_last_hand_1 = {"Laatste hand. Geef het", "uit of verlies het."},
            fb_bl_ox_disabled_1 = {"Mijn hoorns!", "Ze zijn bot!"},
            fb_bl_ox_defeat_1 = {"Je greep de stier", "bij de hoorns..."},
            fb_bl_ox_gloat_1 = {"De os:", "\"Nu ben je blut!\""},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Maar ik ben", "Het huis"},
            fb_bl_house_intro_1 = {"Je bent", "BLIND!"},
            fb_bl_house_intro_2 = {"De eerste hand is van", "het huis. Blind!"},
            fb_bl_house_big_hand_1 = {"Blind geluk en je", "won toch?!"},
            fb_bl_house_close_1 = {"Het huis verliest", "nooit!"},
            fb_bl_house_last_hand_1 = {"Geen blind geluk", "meer."},
            fb_bl_house_disabled_1 = {"Mijn blinddoek!", "Hij viel af!"},
            fb_bl_house_defeat_1 = {"Het huis...", "is gevallen."},
            fb_bl_house_gloat_1 = {"Het huis:", "\"Het huis wint!\""},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Maar ik ben", "De muur"},
            fb_bl_wall_intro_1 = {"Je bent er net", "tegenaan gelopen"},
            fb_bl_wall_intro_2 = {"Probeer deze score", "maar te beklimmen."},
            fb_bl_wall_big_hand_1 = {"Je hebt mijn muur", "beklommen?!"},
            fb_bl_wall_close_1 = {"Je breekt er", "niet doorheen!"},
            fb_bl_wall_last_hand_1 = {"Er is niets meer", "te beklimmen."},
            fb_bl_wall_disabled_1 = {"Scheuren! Mijn muur", "barst!"},
            fb_bl_wall_defeat_1 = {"De muur...", "stort in."},
            fb_bl_wall_gloat_1 = {"De muur:", "\"Tegen de muur!\""},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Maar ik ben", "Het rad"},
            fb_bl_wheel_intro_1 = {"Ik hou van...", "GOKKEN!"},
            fb_bl_wheel_intro_2 = {"Eén op de zeven kaarten", "komt omgekeerd."},
            fb_bl_wheel_big_hand_1 = {"Vrouwe Fortuna", "mag je vandaag."},
            fb_bl_wheel_close_1 = {"Mijn rad draait", "door!"},
            fb_bl_wheel_last_hand_1 = {"Laatste draai.", "Voel je je gelukkig?"},
            fb_bl_wheel_disabled_1 = {"Het rad stopt?", "Vals spel!"},
            fb_bl_wheel_defeat_1 = {"Het rad van fortuin", "draait tegen me..."},
            fb_bl_wheel_gloat_1 = {"Het rad:", "\"Rad voor ogen!\""},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Maar ik ben", "Het wapen"},
            fb_bl_arm_intro_1 = {"Ik breng jouw", "macht in balans"},
            fb_bl_arm_intro_2 = {"Elke hand die je speelt", "verliest een niveau."},
            fb_bl_arm_big_hand_1 = {"Die hand heeft", "spierkracht..."},
            fb_bl_arm_close_1 = {"Armpje drukken?", "Ik verlies!"},
            fb_bl_arm_last_hand_1 = {"Laatste hand. Spierbal", "niet te vroeg."},
            fb_bl_arm_disabled_1 = {"Mijn arm hangt slap!", "Valsspeler!"},
            fb_bl_arm_defeat_1 = {"Je hebt mijn sterke", "arm verslagen."},
            fb_bl_arm_gloat_1 = {"Het wapen:", "\"Een stapje terug!\""},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Maar ik ben", "De klaver"},
            fb_bl_club_intro_1 = {"Ik haat", "{C:green,E:1}mazzelaars{}"},
            fb_bl_club_intro_2 = {"Klaveren zijn gedebuft.", "Sorry."},
            fb_bl_club_big_hand_1 = {"Geen klaveren, geen", "probleem?!"},
            fb_bl_club_close_1 = {"Sla me er niet", "mee neer!"},
            fb_bl_club_last_hand_1 = {"Laatste hand. Laat de", "klaveren thuis."},
            fb_bl_club_disabled_1 = {"Mijn klaveren", "hebben geen beet meer!"},
            fb_bl_club_defeat_1 = {"Klaver dicht.", "Tijd om te gaan..."},
            fb_bl_club_gloat_1 = {"De klaver:", "\"Klaverjassen!\""},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Maar ik ben", "De vis"},
            fb_bl_fish_intro_1 = {"Wees zeker van wat", "je wilt spelen"},
            fb_bl_fish_intro_2 = {"Na elke hand komen", "kaarten omgekeerd."},
            fb_bl_fish_big_hand_1 = {"Er is iets visserigs", "aan die hand!"},
            fb_bl_fish_close_1 = {"Haal me niet", "binnen!"},
            fb_bl_fish_last_hand_1 = {"Laatste worp.", "Haal hem binnen."},
            fb_bl_fish_disabled_1 = {"Mijn schubben!", "Ze zijn eraf!"},
            fb_bl_fish_defeat_1 = {"Binnengehaald...", "door een prof."},
            fb_bl_fish_gloat_1 = {"De vis:", "\"Je bent kopje-onder!\""},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Maar ik ben", "De helderziende"},
            fb_bl_psychic_intro_1 = {"Ik haat", "twijfelaars"},
            fb_bl_psychic_intro_2 = {"Vijf kaarten, niet", "minder. Ik zag het."},
            fb_bl_psychic_big_hand_1 = {"Dat zag ik NIET", "aankomen."},
            fb_bl_psychic_close_1 = {"Mijn glazen bol toont", "...nederlaag!"},
            fb_bl_psychic_last_hand_1 = {"Ik voorzie je", "laatste hand."},
            fb_bl_psychic_disabled_1 = {"Mijn visioenen!", "Ze zijn weg!"},
            fb_bl_psychic_defeat_1 = {"Ik zag het aankomen.", "...Of toch niet?"},
            fb_bl_psychic_gloat_1 = {"De helderziende:", "\"Ik zag het al!\""},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Maar ik ben", "De aansporing"},
            fb_bl_goad_intro_1 = {"Ik haat", "{C:black,E:1}MACHT{}"},
            fb_bl_goad_intro_2 = {"Schoppen zijn gedebuft.", "Graaf dieper."},
            fb_bl_goad_big_hand_1 = {"Niet slecht zonder", "je schoppen."},
            fb_bl_goad_close_1 = {"Waag het niet mijn", "graf te graven!"},
            fb_bl_goad_last_hand_1 = {"Graaf diep. Het is je", "laatste hand."},
            fb_bl_goad_disabled_1 = {"Ik kan nu niemand", "meer aansporen!"},
            fb_bl_goad_defeat_1 = {"Verdorie,", "je hebt gewonnen."},
            fb_bl_goad_gloat_1 = {"De aansporing:", "\"Graaf je eigen graf!\""},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Maar ik ben", "Het water"},
            fb_bl_water_intro_1 = {"Geef me", "je weggooien"},
            fb_bl_water_intro_2 = {"Geen weggooien.", "Geen druppel."},
            fb_bl_water_big_hand_1 = {"Geen weggooien en toch", "gewonnen?!"},
            fb_bl_water_close_1 = {"Ik verdrink!", "Gooi me een lijn!"},
            fb_bl_water_last_hand_1 = {"Laatste hand. Zwem", "of zink."},
            fb_bl_water_disabled_1 = {"Weggooien stroomt", "weer!"},
            fb_bl_water_defeat_1 = {"Ik ben helemaal", "opgedroogd..."},
            fb_bl_water_gloat_1 = {"Het water:", "\"Je bent verzopen!\""},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Maar ik ben", "Het raam"},
            fb_bl_window_intro_1 = {"Ik haat", "{C:yellow,E:1}kapitalisme{}"},
            fb_bl_window_intro_2 = {"Ruiten zijn gedebuft.", "Blijf schitteren."},
            fb_bl_window_big_hand_1 = {"Wie heeft er", "ruiten nodig?"},
            fb_bl_window_close_1 = {"Breek mijn", "raam niet!"},
            fb_bl_window_last_hand_1 = {"Laatste hand. Geen", "bling toegestaan."},
            fb_bl_window_disabled_1 = {"Mijn raam is gebroken!", "Ruiten schitteren!"},
            fb_bl_window_defeat_1 = {"Mijn kans is", "verkeken."},
            fb_bl_window_gloat_1 = {"Het raam:", "\"Ruiten? Gedebuft!\""},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Maar ik ben", "Boeien"},
            fb_bl_manacle_intro_1 = {"Ik neem je", "{C:blue,E:1}opties{}"},
            fb_bl_manacle_intro_2 = {"Eén kaart minder", "in je hand."},
            fb_bl_manacle_big_hand_1 = {"Geboeid en toch", "winnen?!"},
            fb_bl_manacle_close_1 = {"Je glipt uit", "je boeien!"},
            fb_bl_manacle_last_hand_1 = {"Laatste hand. In", "boeien nog wel."},
            fb_bl_manacle_disabled_1 = {"De boeien!", "Ze vallen af!"},
            fb_bl_manacle_defeat_1 = {"Eindelijk vrij...", "van mij."},
            fb_bl_manacle_gloat_1 = {"Boeien:", "\"Handen omhoog!\""},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Maar ik ben", "Het oog"},
            fb_bl_eye_intro_1 = {"Ik hou niet van", "sleur"},
            fb_bl_eye_intro_2 = {"Nooit hetzelfde type", "hand twee keer."},
            fb_bl_eye_big_hand_1 = {"Een nieuwe hand?", "Ik zie je."},
            fb_bl_eye_close_1 = {"Ik kan er niet", "naar kijken!"},
            fb_bl_eye_last_hand_1 = {"Ik zie je", "laatste hand."},
            fb_bl_eye_disabled_1 = {"Mijn oog! Wie prikte", "in mijn oog?!"},
            fb_bl_eye_defeat_1 = {"Uit het oog,", "uit het hart..."},
            fb_bl_eye_gloat_1 = {"Het oog:", "\"Ik zei het toch!\""},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Maar ik ben", "De mond"},
            fb_bl_mouth_intro_1 = {"Ik hou van", "sleur"},
            fb_bl_mouth_intro_2 = {"Kies één type hand", "en blijf erbij."},
            fb_bl_mouth_big_hand_1 = {"Dezelfde oude hand,", "nog steeds sterk..."},
            fb_bl_mouth_close_1 = {"Mijn mond staat", "wagenwijd open!"},
            fb_bl_mouth_last_hand_1 = {"Laatste hand. Zelfde", "type. Mond dicht."},
            fb_bl_mouth_disabled_1 = {"Wie heeft me een", "muilkorf omgedaan?!"},
            fb_bl_mouth_defeat_1 = {"Ik ben sprakeloos..."},
            fb_bl_mouth_gloat_1 = {"De mond:", "\"Houd je mond, loser!\""},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Maar ik ben", "De plant"},
            fb_bl_plant_intro_1 = {"Ik haat", "vriendelijke gezichten"},
            fb_bl_plant_intro_2 = {"Koningen, vrouwen, boeren:", "allemaal gedebuft."},
            fb_bl_plant_big_hand_1 = {"Zonder plaatjes?!", "Ongelooflijk."},
            fb_bl_plant_close_1 = {"Trek me niet met", "wortel en al uit!"},
            fb_bl_plant_last_hand_1 = {"Zie je laatste", "hand onder ogen."},
            fb_bl_plant_disabled_1 = {"Mijn blaadjes!", "Ze zijn allemaal weg!"},
            fb_bl_plant_defeat_1 = {"Verwelkt...", "Ik groei wel terug."},
            fb_bl_plant_gloat_1 = {"De plant:", "\"Zie het onder ogen!\""},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Maar ik ben", "Het serpent"},
            fb_bl_serpent_intro_1 = {"Er is een", "tekort"},
            fb_bl_serpent_intro_2 = {"Spelen of weggooien,", "je trekt maar 3."},
            fb_bl_serpent_big_hand_1 = {"Drie kaarten. En je", "sloeg toch toe!"},
            fb_bl_serpent_close_1 = {"Kronkel nu niet", "weg!"},
            fb_bl_serpent_last_hand_1 = {"Laatste beet.", "Drie kaarten."},
            fb_bl_serpent_disabled_1 = {"Mijn giftanden! Sss...", "Geen gif meer!"},
            fb_bl_serpent_defeat_1 = {"Vervelde mijn huid...", "en mijn trots."},
            fb_bl_serpent_gloat_1 = {"Het serpent:", "\"Tot sissens!\""},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Maar ik ben", "De pilaar"},
            fb_bl_pillar_intro_1 = {"Ik leerde veel van", "je vorige handen"},
            fb_bl_pillar_intro_2 = {"Gespeelde kaarten", "blijven gedebuft."},
            fb_bl_pillar_big_hand_1 = {"Verse kaarten?", "Slim."},
            fb_bl_pillar_close_1 = {"Mijn pilaar", "brokkelt af!"},
            fb_bl_pillar_last_hand_1 = {"Laatste hand. Oude", "kaarten zijn nutteloos."},
            fb_bl_pillar_disabled_1 = {"Mijn geheugen!", "Het... vervaagt."},
            fb_bl_pillar_defeat_1 = {"Een pilaar van de", "samenleving valt."},
            fb_bl_pillar_gloat_1 = {"De pilaar:", "\"Nog steeds overeind!\""},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Maar ik ben", "De naald"},
            fb_bl_needle_intro_1 = {"Je hebt maar", "één kans"},
            fb_bl_needle_intro_2 = {"Eén hand. Meer krijg", "je niet."},
            fb_bl_needle_big_hand_1 = {"Eén enkele hand,", "zo sterk?!"},
            fb_bl_needle_close_1 = {"Nee! Niet met", "één hand!"},
            fb_bl_needle_last_hand_1 = {"Deze hand is", "je enige hand."},
            fb_bl_needle_disabled_1 = {"Mijn naald!", "Hij is bot!"},
            fb_bl_needle_defeat_1 = {"Scherp gespeeld.", "Je hebt me."},
            fb_bl_needle_gloat_1 = {"De naald:", "\"Punt is, je verloor!\""},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Maar ik ben", "Het hoofd"},
            fb_bl_head_intro_1 = {"Ik haat", "{C:red,E:1}verliefden{}"},
            fb_bl_head_intro_2 = {"Harten zijn gedebuft.", "Koud, hè?"},
            fb_bl_head_big_hand_1 = {"Je won zonder", "hart?!"},
            fb_bl_head_close_1 = {"Heb een hart,", "maak me niet af!"},
            fb_bl_head_last_hand_1 = {"Laatste hand. Geen", "harten. Geen genade."},
            fb_bl_head_disabled_1 = {"Mijn hoofd bonkt!", "Werken harten weer?"},
            fb_bl_head_defeat_1 = {"Mijn hoofd verloren...", "door jou."},
            fb_bl_head_gloat_1 = {"Het hoofd:", "\"Hartloos, hè?\""},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Maar ik ben", "De tand"},
            fb_bl_tooth_intro_1 = {"Ik ben in", "de politiek"},
            fb_bl_tooth_intro_2 = {"Elke kaart die je speelt", "kost je $1."},
            fb_bl_tooth_big_hand_1 = {"Je betaalde en won", "toch?!"},
            fb_bl_tooth_close_1 = {"Dwing me niet de", "tandenfee te betalen!"},
            fb_bl_tooth_last_hand_1 = {"Laatste hand,", "laatste dollars."},
            fb_bl_tooth_disabled_1 = {"Mijn beet!", "Hij is weg!"},
            fb_bl_tooth_defeat_1 = {"Met tand en nagel", "verloren."},
            fb_bl_tooth_gloat_1 = {"De tand:", "\"Betalen, sukkel!\""},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Maar ik ben", "De vuursteen"},
            fb_bl_flint_intro_1 = {"Je moet", "belasting betalen"},
            fb_bl_flint_intro_2 = {"Fiches en Multi", "worden gehalveerd."},
            fb_bl_flint_big_hand_1 = {"Halve kracht, toch", "raak?!"},
            fb_bl_flint_close_1 = {"Je slaat vonken uit", "mijn ondergang!"},
            fb_bl_flint_last_hand_1 = {"Laatste hand. Halve", "vonk."},
            fb_bl_flint_disabled_1 = {"Volle kracht?!", "Niet eerlijk!"},
            fb_bl_flint_defeat_1 = {"Mijn vonk", "is gedoofd."},
            fb_bl_flint_gloat_1 = {"De vuursteen:", "\"Half plezier!\""},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Maar ik ben", "Het teken"},
            fb_bl_mark_intro_1 = {"Ik word liever", "niet gezien"},
            fb_bl_mark_intro_2 = {"Alle plaatjes komen", "omgekeerd."},
            fb_bl_mark_big_hand_1 = {"Gemarkeerde kaarten,", "toch gewonnen?!"},
            fb_bl_mark_close_1 = {"Ik ben getekend", "voor de nederlaag!"},
            fb_bl_mark_last_hand_1 = {"Laatste hand. Kies", "gezichten blind."},
            fb_bl_mark_disabled_1 = {"De gezichten!", "Ik zie ze!"},
            fb_bl_mark_defeat_1 = {"Je hebt je stempel", "op mij gedrukt."},
            fb_bl_mark_gloat_1 = {"Het teken:", "\"Getekend: verliezer!\""},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Maar ik ben", "Amberkleurige eikel"},
            fb_bl_final_acorn_intro_1 = {"Ik hou van", "CHAOS!"},
            fb_bl_final_acorn_intro_2 = {"Jokers omgekeerd,", "dan geschud!"},
            fb_bl_final_acorn_big_hand_1 = {"Zelfs in chaos", "win je?!"},
            fb_bl_final_acorn_close_1 = {"Wat een nootgeval!", "Ik barst!"},
            fb_bl_final_acorn_last_hand_1 = {"Laatste hand. Waar", "is je joker?"},
            fb_bl_final_acorn_disabled_1 = {"Mijn eikel!", "Orde hersteld?!"},
            fb_bl_final_acorn_defeat_1 = {"Je hebt mijn", "schil gekraakt..."},
            fb_bl_final_acorn_gloat_1 = {"Amberkleurige eikel:", "\"Eikelrijk verloren!\""},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Maar ik ben", "Groen blaadje"},
            fb_bl_final_leaf_intro_1 = {"Je moet loskomen", "van je wortels"},
            fb_bl_final_leaf_intro_2 = {"Verkoop een joker of", "blijf gedebuft."},
            fb_bl_final_leaf_big_hand_1 = {"Je sloeg een nieuw", "blad om. Hmpf."},
            fb_bl_final_leaf_close_1 = {"Mijn blaadje", "valt!"},
            fb_bl_final_leaf_last_hand_1 = {"Laatste hand.", "Een joker verkopen?"},
            fb_bl_final_leaf_disabled_1 = {"Mijn blaadje! Het is", "verdord!"},
            fb_bl_final_leaf_defeat_1 = {"Ik ga heen...", "als een blad."},
            fb_bl_final_leaf_gloat_1 = {"Groen blaadje:", "\"Blad, blad, verloren!\""},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Maar ik ben", "Violet vat"},
            fb_bl_final_vessel_intro_1 = {"Je liep net tegen", "de grote muur aan"},
            fb_bl_final_vessel_intro_2 = {"Een gigantische blind.", "Zeil maar door!"},
            fb_bl_final_vessel_big_hand_1 = {"Een enorme klap op", "een enorm doelwit."},
            fb_bl_final_vessel_close_1 = {"Verlaat het schip!", "...Het mijne, bedoel ik."},
            fb_bl_final_vessel_last_hand_1 = {"Laatste hand. Dit", "schip zinkt niet."},
            fb_bl_final_vessel_disabled_1 = {"Mijn vat!", "Het zinkt!"},
            fb_bl_final_vessel_defeat_1 = {"Het vat...", "is leeggemaakt."},
            fb_bl_final_vessel_gloat_1 = {"Violet vat:", "\"Vat je 'm? Verloren!\""},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Maar ik ben", "Karmozijnrood hart"},
            fb_bl_final_heart_intro_1 = {"Ik leen even", "een joker"},
            fb_bl_final_heart_intro_2 = {"Elke hand verliest een", "joker zijn kracht."},
            fb_bl_final_heart_big_hand_1 = {"Een joker minder en", "toch sterk?"},
            fb_bl_final_heart_close_1 = {"Breek mijn hart", "niet!"},
            fb_bl_final_heart_last_hand_1 = {"Laatste hand. Welke", "joker is stil?"},
            fb_bl_final_heart_disabled_1 = {"Mijn hart! Het sloeg", "een slag over."},
            fb_bl_final_heart_defeat_1 = {"Mijn hart...", "is gebroken."},
            fb_bl_final_heart_gloat_1 = {"Karmozijnrood hart:", "\"Al liefdesverdriet?\""},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Maar ik ben", "Azuurblauwe bel"},
            fb_bl_final_bell_intro_1 = {"Ik wil je", "graag begeleiden"},
            fb_bl_final_bell_intro_2 = {"Eén kaart wordt in", "elke hand geforceerd."},
            fb_bl_final_bell_big_hand_1 = {"Je liet mijn geforceerde", "kaart klinken?!"},
            fb_bl_final_bell_close_1 = {"De bel luidt...", "voor mij?!"},
            fb_bl_final_bell_last_hand_1 = {"Laatste hand. Eén", "kaart is geforceerd."},
            fb_bl_final_bell_disabled_1 = {"Mijn bel is stil!", "Valsspeler!"},
            fb_bl_final_bell_defeat_1 = {"De bel luidt", "voor mij."},
            fb_bl_final_bell_gloat_1 = {"Azuurblauwe bel:", "\"Ding dong, verloren!\""},
        }
    }
}
