return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Showdowns",
            fb_cfg_dialogue = "Baasdialogen",
            fb_cfg_music = "Showdown-muziek",
            fb_cfg_fx = "Schermeffecten",
            fb_cfg_cinematic = "Showdown-filmpjes",
            fb_cfg_moves = "Baasacties",
            fb_cfg_phase_twists = "Baasfases veranderen de regels",
            fb_showdown_title = "SHOWDOWN",
            fb_cfg_intro_speed = "Introsnelheid",
            fb_speed_slow = "Langzaam",
            fb_speed_normal = "Normaal",
            fb_speed_fast = "Snel",
            fb_cfg_min_ante = "Baasdialogen vanaf Ante",
            fb_cfg_memory = "Baasgeheugen",
            fb_cfg_dev_mode = "Ontwikkelaarstoetsen (F5-F7)",
            fb_cfg_showdown_enabled = "Eigen showdown-schema",
            fb_cfg_start_ante = "Eerste showdown bij Ante",
            fb_cfg_every = "Daarna elke N Ante's",
            fb_cfg_preview = "Showdowns bij Ante",
            fb_cfg_hard = "Zwaar! Vroege showdowns zijn bruut.",
            fb_cfg_next_ante = "Wijzigingen gelden vanaf de volgende Ante.",
            fb_cfg_group_dialogue = "Dialogen",
            fb_cfg_group_stage = "Showdown-podium",
            fb_credits_thanks = "Bedankt voor het spelen met FinalBoss!",
            fb_credits_lead = "Gemaakt en onderhouden door",
            fb_credits_music = "Showdown-muziek:",
            fb_credits_music_by = "Adam Isiah (orkestrale cover)",
            fb_credits_listen = "Luister op YouTube",
            fb_credits_github = "GitHub",
            fb_tip_me = "Geef een fooi",
            fb_tip_me_message_1 = "Vind je FinalBoss leuk? Overweeg dan",
            fb_tip_me_message_2 = "een kleine fooi om je steun te tonen.",
            fb_tip_me_message_3 = "Dat wordt enorm gewaardeerd!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Bazen praten terug en showdowns worden baasgevechten.", "Door {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Je bent te ver", "gekomen..."},
            fb_opener_2 = {"En helaas moet ik", "zeggen..."},
            fb_opener_3 = {"Dus. Je hebt het", "gehaald."},
            fb_closer_1 = {"Je gaat me niet", "kunnen verslaan."},
            fb_closer_2 = {"Hier eindigt", "jouw run."},
            fb_closer_3 = {"Laat maar zien wat", "je in huis hebt."},
            fb_gloat = {"Die baas was", "te veel..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Ik ben #1#!"},
            fb_generic_name_2 = {"Ze noemen me", "#1#."},
            fb_generic_name_3 = {"Aanschouw:", "#1#!"},
            fb_generic_intro_1 = {"Je geluk", "eindigt hier."},
            fb_generic_intro_2 = {"Eens kijken hoe je", "hier mee omgaat."},
            fb_generic_intro_3 = {"Lees mijn regels", "goed..."},
            fb_generic_big_hand_1 = {"...Niet slecht."},
            fb_generic_big_hand_2 = {"Mazzelhand."},
            fb_generic_big_hand_3 = {"Hmpf. Alweer?"},
            fb_generic_close_1 = {"Wacht, wacht,", "WACHT!"},
            fb_generic_close_2 = {"Waag het niet..."},
            fb_generic_close_3 = {"Dit kan niet..."},
            fb_generic_last_hand_1 = {"Nog één hand.", "Laat hem tellen."},
            fb_generic_last_hand_2 = {"Tik, tak..."},
            fb_generic_last_hand_3 = {"Laatste kans,", "kleine joker."},
            fb_generic_disabled_1 = {"Mijn kracht...!", "Wat heb je gedaan?"},
            fb_generic_disabled_2 = {"Hé! Dat is", "valsspelen!"},
            fb_generic_disabled_3 = {"Ik voel me... zwak."},
            fb_generic_defeat_1 = {"Onmogelijk..."},
            fb_generic_defeat_2 = {"Ik kom terug bij", "de volgende Ante..."},
            fb_generic_defeat_3 = {"Goed gespeeld..."},
            fb_generic_gloat_1 = {"Die baas was", "te veel..."},
            fb_generic_gloat_2 = {"De bank", "wint altijd."},
            fb_generic_gloat_3 = {"Beter geluk", "volgende run."},
            fb_generic_interrupted_1 = {"Mijn toespraak!"},
            fb_generic_interrupted_2 = {"Oké... dus zo", "zit het."},
            fb_generic_interrupted_3 = {"Niet eens een hallo?"},
            fb_generic_phase2_1 = {"Genoeg spelletjes!"},
            fb_generic_phase3_1 = {"Nu ben ik", "echt boos!"},
            fb_generic_rematch_won_1 = {"Jij weer?", "Ik herinner me jou."},
            fb_generic_rematch_won_2 = {"Vorige keer was", "geluk. Geef toe."},
            fb_generic_rematch_won_3 = {"Tijd voor revanche.", "Ik heb getraind."},
            fb_generic_rematch_lost_1 = {"Kom je voor nog", "een pak slaag?"},
            fb_generic_rematch_lost_2 = {"Niks geleerd", "van vorige keer?"},
            fb_generic_rematch_lost_3 = {"O, jij bent het.", "De verliezer."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Maar ik ben", "De haak"},
            fb_bl_hook_intro_1 = {"Ik neem een paar", "van je kaarten"},
            fb_bl_hook_intro_2 = {"Twee kaarten weg,", "elke hand."},
            fb_bl_hook_big_hand_1 = {"Zelfs met minder", "kaarten?!"},
            fb_bl_hook_close_1 = {"Blijf van die", "kaarten af!"},
            fb_bl_hook_last_hand_1 = {"Eindelijk heb ik", "je aan de haak!"},
            fb_bl_hook_disabled_1 = {"Mijn haak!", "Hij is kapot!"},
            fb_bl_hook_defeat_1 = {"Goed... ik laat", "je van de haak."},
            fb_bl_hook_gloat_1 = {"Aan de haak", "geslagen!"},
            fb_bl_hook_interrupted_1 = {"Onbeleefd! Ik was", "midden in mijn zin!"},
            fb_bl_hook_rematch_won_1 = {"Vorige keer glipte", "je van mijn haak."},
            fb_bl_hook_rematch_lost_1 = {"Wil je weer", "aan de haak?"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Maar ik ben", "De os"},
            fb_bl_ox_intro_1 = {"Ik neem al", "je geld"},
            fb_bl_ox_intro_2 = {"Je favoriete hand", "kost je alles."},
            fb_bl_ox_big_hand_1 = {"Blut en toch", "winnen?!"},
            fb_bl_ox_close_1 = {"Rustig aan!", "...Ik ook."},
            fb_bl_ox_last_hand_1 = {"Laatste hand. Geef het", "uit of verlies het."},
            fb_bl_ox_disabled_1 = {"Mijn hoorns!", "Ze zijn bot!"},
            fb_bl_ox_defeat_1 = {"Je greep de stier", "bij de hoorns..."},
            fb_bl_ox_gloat_1 = {"Nu ben je blut!"},
            fb_bl_ox_interrupted_1 = {"O, dus ZO", "gaan we het doen."},
            fb_bl_ox_rematch_won_1 = {"Je ontweek mijn", "hoorns één keer..."},
            fb_bl_ox_rematch_lost_1 = {"Nog steeds blut", "van vorige keer?"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Maar ik ben", "Het huis"},
            fb_bl_house_intro_1 = {"Je bent", "BLIND!"},
            fb_bl_house_intro_2 = {"De eerste hand is van", "het huis. Blind!"},
            fb_bl_house_big_hand_1 = {"Blind geluk en je", "won toch?!"},
            fb_bl_house_close_1 = {"Het huis verliest", "nooit!"},
            fb_bl_house_last_hand_1 = {"Geen blind geluk", "meer."},
            fb_bl_house_disabled_1 = {"Mijn blinddoek!", "Hij viel af!"},
            fb_bl_house_defeat_1 = {"Het huis...", "is gevallen."},
            fb_bl_house_gloat_1 = {"Het huis wint!"},
            fb_bl_house_interrupted_1 = {"Huisregel: nog", "niet spelen!"},
            fb_bl_house_rematch_won_1 = {"Het huis verloor één", "keer. Nooit meer."},
            fb_bl_house_rematch_lost_1 = {"Welkom terug.", "Het huis vergeet niets."},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Maar ik ben", "De muur"},
            fb_bl_wall_intro_1 = {"Je bent er net", "tegenaan gelopen"},
            fb_bl_wall_intro_2 = {"Probeer deze score", "maar te beklimmen."},
            fb_bl_wall_big_hand_1 = {"Je hebt mijn muur", "beklommen?!"},
            fb_bl_wall_close_1 = {"Je breekt er", "niet doorheen!"},
            fb_bl_wall_last_hand_1 = {"Er is niets meer", "te beklimmen."},
            fb_bl_wall_disabled_1 = {"Scheuren! Mijn muur", "barst!"},
            fb_bl_wall_defeat_1 = {"De muur...", "stort in."},
            fb_bl_wall_gloat_1 = {"Tegen de muur!"},
            fb_bl_wall_interrupted_1 = {"Net praten tegen", "een muur... wacht."},
            fb_bl_wall_rematch_won_1 = {"Je kwam één keer over", "me heen. Niet weer."},
            fb_bl_wall_rematch_lost_1 = {"Wil je weer tegen", "dezelfde muur?"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Maar ik ben", "Het rad"},
            fb_bl_wheel_intro_1 = {"Ik hou van...", "GOKKEN!"},
            fb_bl_wheel_intro_2 = {"Eén op de zeven kaarten", "komt omgekeerd."},
            fb_bl_wheel_big_hand_1 = {"Vrouwe Fortuna", "mag je vandaag."},
            fb_bl_wheel_close_1 = {"Mijn rad draait", "door!"},
            fb_bl_wheel_last_hand_1 = {"Laatste draai.", "Voel je je gelukkig?"},
            fb_bl_wheel_disabled_1 = {"Het rad stopt?", "Vals spel!"},
            fb_bl_wheel_defeat_1 = {"Het rad van fortuin", "draait tegen me..."},
            fb_bl_wheel_gloat_1 = {"Rad voor ogen!"},
            fb_bl_wheel_interrupted_1 = {"Ho! Niet zo snel,", "ik draai nog!"},
            fb_bl_wheel_rematch_won_1 = {"Vorige draai zat", "het geluk mee..."},
            fb_bl_wheel_rematch_lost_1 = {"Nog een draai?", "De bank wint, vriend."},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Maar ik ben", "Het wapen"},
            fb_bl_arm_intro_1 = {"Ik breng jouw", "macht in balans"},
            fb_bl_arm_intro_2 = {"Elke hand die je speelt", "verliest een niveau."},
            fb_bl_arm_big_hand_1 = {"Die hand heeft", "spierkracht..."},
            fb_bl_arm_close_1 = {"Armpje drukken?", "Ik verlies!"},
            fb_bl_arm_last_hand_1 = {"Laatste hand. Spierbal", "niet te vroeg."},
            fb_bl_arm_disabled_1 = {"Mijn arm hangt slap!", "Valsspeler!"},
            fb_bl_arm_defeat_1 = {"Je hebt mijn sterke", "arm verslagen."},
            fb_bl_arm_gloat_1 = {"Een stapje terug!"},
            fb_bl_arm_interrupted_1 = {"Handen thuis! Ik", "was nog aan het pronken!"},
            fb_bl_arm_rematch_won_1 = {"Vorige keer won je", "het armworstelen."},
            fb_bl_arm_rematch_lost_1 = {"Zin in nog een", "potje armworstelen?"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Maar ik ben", "De klaver"},
            fb_bl_club_intro_1 = {"Ik haat", "{C:green,E:1}mazzelaars{}"},
            fb_bl_club_intro_2 = {"Klaveren zijn gedebuft.", "Sorry."},
            fb_bl_club_big_hand_1 = {"Geen klaveren, geen", "probleem?!"},
            fb_bl_club_close_1 = {"Sla me er niet", "mee neer!"},
            fb_bl_club_last_hand_1 = {"Laatste hand. Laat de", "klaveren thuis."},
            fb_bl_club_disabled_1 = {"Mijn klaveren", "hebben geen beet meer!"},
            fb_bl_club_defeat_1 = {"Klaver dicht.", "Tijd om te gaan..."},
            fb_bl_club_gloat_1 = {"Klaverjassen!"},
            fb_bl_club_interrupted_1 = {"Hé! In mijn club", "praat ik eerst."},
            fb_bl_club_rematch_won_1 = {"Vorige keer drong je", "mijn club binnen."},
            fb_bl_club_rematch_lost_1 = {"Lidmaatschap verlengd?", "Welkom terug."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Maar ik ben", "De vis"},
            fb_bl_fish_intro_1 = {"Wees zeker van wat", "je wilt spelen"},
            fb_bl_fish_intro_2 = {"Na elke hand komen", "kaarten omgekeerd."},
            fb_bl_fish_big_hand_1 = {"Er is iets visserigs", "aan die hand!"},
            fb_bl_fish_close_1 = {"Haal me niet", "binnen!"},
            fb_bl_fish_last_hand_1 = {"Laatste worp.", "Haal hem binnen."},
            fb_bl_fish_disabled_1 = {"Mijn schubben!", "Ze zijn eraf!"},
            fb_bl_fish_defeat_1 = {"Binnengehaald...", "door een prof."},
            fb_bl_fish_gloat_1 = {"Je bent", "kopje-onder!"},
            fb_bl_fish_interrupted_1 = {"Je hebt mijn lijn", "doorgeknipt!"},
            fb_bl_fish_rematch_won_1 = {"Die ene die", "ontsnapte..."},
            fb_bl_fish_rematch_lost_1 = {"Weer aan mijn", "haak, visje?"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Maar ik ben", "De helderziende"},
            fb_bl_psychic_intro_1 = {"Ik haat", "twijfelaars"},
            fb_bl_psychic_intro_2 = {"Vijf kaarten, niet", "minder. Ik zag het."},
            fb_bl_psychic_big_hand_1 = {"Dat zag ik NIET", "aankomen."},
            fb_bl_psychic_close_1 = {"Mijn glazen bol toont", "...nederlaag!"},
            fb_bl_psychic_last_hand_1 = {"Ik voorzie je", "laatste hand."},
            fb_bl_psychic_disabled_1 = {"Mijn visioenen!", "Ze zijn weg!"},
            fb_bl_psychic_defeat_1 = {"Ik zag het aankomen.", "...Of toch niet?"},
            fb_bl_psychic_gloat_1 = {"Ik zag het al!"},
            fb_bl_psychic_interrupted_1 = {"Wist ik het toch.", "...Nog steeds onbeleefd."},
            fb_bl_psychic_rematch_won_1 = {"Je laatste winst zag", "ik niet aankomen."},
            fb_bl_psychic_rematch_lost_1 = {"Ik wist dat je", "terug zou komen."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Maar ik ben", "De aansporing"},
            fb_bl_goad_intro_1 = {"Ik haat", "{C:black,E:1}MACHT{}"},
            fb_bl_goad_intro_2 = {"Schoppen zijn gedebuft.", "Graaf dieper."},
            fb_bl_goad_big_hand_1 = {"Niet slecht zonder", "je schoppen."},
            fb_bl_goad_close_1 = {"Waag het niet mijn", "graf te graven!"},
            fb_bl_goad_last_hand_1 = {"Graaf diep. Het is je", "laatste hand."},
            fb_bl_goad_disabled_1 = {"Ik kan nu niemand", "meer aansporen!"},
            fb_bl_goad_defeat_1 = {"Verdorie,", "je hebt gewonnen."},
            fb_bl_goad_gloat_1 = {"Graaf je", "eigen graf!"},
            fb_bl_goad_interrupted_1 = {"MIJ uitdagen?", "Prima!"},
            fb_bl_goad_rematch_won_1 = {"Vorige keer groef", "je jezelf uit."},
            fb_bl_goad_rematch_lost_1 = {"Kom je een dieper", "graf graven?"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Maar ik ben", "Het water"},
            fb_bl_water_intro_1 = {"Geef me", "je weggooien"},
            fb_bl_water_intro_2 = {"Geen weggooien.", "Geen druppel."},
            fb_bl_water_big_hand_1 = {"Geen weggooien en toch", "gewonnen?!"},
            fb_bl_water_close_1 = {"Ik verdrink!", "Gooi me een lijn!"},
            fb_bl_water_last_hand_1 = {"Laatste hand. Zwem", "of zink."},
            fb_bl_water_disabled_1 = {"Weggooien stroomt", "weer!"},
            fb_bl_water_defeat_1 = {"Ik ben helemaal", "opgedroogd..."},
            fb_bl_water_gloat_1 = {"Je bent verzopen!"},
            fb_bl_water_interrupted_1 = {"Onderbreken? Het water", "staat je aan de lippen!"},
            fb_bl_water_rematch_won_1 = {"Vorige keer bleef", "je boven water."},
            fb_bl_water_rematch_lost_1 = {"Kom je weer", "kopje-onder?"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Maar ik ben", "Het raam"},
            fb_bl_window_intro_1 = {"Ik haat", "{C:yellow,E:1}kapitalisme{}"},
            fb_bl_window_intro_2 = {"Ruiten zijn gedebuft.", "Blijf schitteren."},
            fb_bl_window_big_hand_1 = {"Wie heeft er", "ruiten nodig?"},
            fb_bl_window_close_1 = {"Breek mijn", "raam niet!"},
            fb_bl_window_last_hand_1 = {"Laatste hand. Geen", "bling toegestaan."},
            fb_bl_window_disabled_1 = {"Mijn raam is gebroken!", "Ruiten schitteren!"},
            fb_bl_window_defeat_1 = {"Mijn kans is", "verkeken."},
            fb_bl_window_gloat_1 = {"Ruiten? Gedebuft!"},
            fb_bl_window_interrupted_1 = {"Mijn woorden gaan", "het raam uit?!"},
            fb_bl_window_rematch_won_1 = {"Je brak één keer", "door mijn raam."},
            fb_bl_window_rematch_lost_1 = {"Weer aan het", "etalagekijken?"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Maar ik ben", "Boeien"},
            fb_bl_manacle_intro_1 = {"Ik neem je", "{C:blue,E:1}opties{}"},
            fb_bl_manacle_intro_2 = {"Eén kaart minder", "in je hand."},
            fb_bl_manacle_big_hand_1 = {"Geboeid en toch", "winnen?!"},
            fb_bl_manacle_close_1 = {"Je glipt uit", "je boeien!"},
            fb_bl_manacle_last_hand_1 = {"Laatste hand. In", "boeien nog wel."},
            fb_bl_manacle_disabled_1 = {"De boeien!", "Ze vallen af!"},
            fb_bl_manacle_defeat_1 = {"Eindelijk vrij...", "van mij."},
            fb_bl_manacle_gloat_1 = {"Handen omhoog!"},
            fb_bl_manacle_interrupted_1 = {"Halt! Daarvoor leg", "ik je aan de ketting!"},
            fb_bl_manacle_rematch_won_1 = {"Je glipte één keer", "uit mijn ketens."},
            fb_bl_manacle_rematch_lost_1 = {"Weer aan de", "ketting, zie ik."},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Maar ik ben", "Het oog"},
            fb_bl_eye_intro_1 = {"Ik hou niet van", "sleur"},
            fb_bl_eye_intro_2 = {"Nooit hetzelfde type", "hand twee keer."},
            fb_bl_eye_big_hand_1 = {"Een nieuwe hand?", "Ik zie je."},
            fb_bl_eye_close_1 = {"Ik kan er niet", "naar kijken!"},
            fb_bl_eye_last_hand_1 = {"Ik zie je", "laatste hand."},
            fb_bl_eye_disabled_1 = {"Mijn oog! Wie prikte", "in mijn oog?!"},
            fb_bl_eye_defeat_1 = {"Uit het oog,", "uit het hart..."},
            fb_bl_eye_gloat_1 = {"Ik zei het toch!"},
            fb_bl_eye_interrupted_1 = {"Dat zag ik!", "Wat onbeleefd."},
            fb_bl_eye_rematch_won_1 = {"Ik hou je in de gaten", "sinds die nederlaag."},
            fb_bl_eye_rematch_lost_1 = {"Ik zie dat je", "terug bent."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Maar ik ben", "De mond"},
            fb_bl_mouth_intro_1 = {"Ik hou van", "sleur"},
            fb_bl_mouth_intro_2 = {"Kies één type hand", "en blijf erbij."},
            fb_bl_mouth_big_hand_1 = {"Dezelfde oude hand,", "nog steeds sterk..."},
            fb_bl_mouth_close_1 = {"Mijn mond staat", "wagenwijd open!"},
            fb_bl_mouth_last_hand_1 = {"Laatste hand. Zelfde", "type. Mond dicht."},
            fb_bl_mouth_disabled_1 = {"Wie heeft me een", "muilkorf omgedaan?!"},
            fb_bl_mouth_defeat_1 = {"Ik ben sprakeloos..."},
            fb_bl_mouth_gloat_1 = {"Houd je mond,", "loser!"},
            fb_bl_mouth_interrupted_1 = {"Hé! Deze mond", "praatte nog!"},
            fb_bl_mouth_rematch_won_1 = {"Vorige keer snoerde", "je me de mond."},
            fb_bl_mouth_rematch_lost_1 = {"Zelfde routine als", "vorige keer?"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Maar ik ben", "De plant"},
            fb_bl_plant_intro_1 = {"Ik haat", "vriendelijke gezichten"},
            fb_bl_plant_intro_2 = {"Koningen, vrouwen, boeren:", "allemaal gedebuft."},
            fb_bl_plant_big_hand_1 = {"Zonder plaatjes?!", "Ongelooflijk."},
            fb_bl_plant_close_1 = {"Trek me niet met", "wortel en al uit!"},
            fb_bl_plant_last_hand_1 = {"Zie je laatste", "hand onder ogen."},
            fb_bl_plant_disabled_1 = {"Mijn blaadjes!", "Ze zijn allemaal weg!"},
            fb_bl_plant_defeat_1 = {"Verwelkt...", "Ik groei wel terug."},
            fb_bl_plant_gloat_1 = {"Zie het", "onder ogen!"},
            fb_bl_plant_interrupted_1 = {"Laat me eerst groeien,", "ongeduldig ding!"},
            fb_bl_plant_rematch_won_1 = {"Je rukte me uit.", "Ik groeide terug."},
            fb_bl_plant_rematch_lost_1 = {"Weer in mijn", "tuin, zie ik."},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Maar ik ben", "Het serpent"},
            fb_bl_serpent_intro_1 = {"Er is een", "tekort"},
            fb_bl_serpent_intro_2 = {"Spelen of weggooien,", "je trekt maar 3."},
            fb_bl_serpent_big_hand_1 = {"Drie kaarten. En je", "sloeg toch toe!"},
            fb_bl_serpent_close_1 = {"Kronkel nu niet", "weg!"},
            fb_bl_serpent_last_hand_1 = {"Laatste beet.", "Drie kaarten."},
            fb_bl_serpent_disabled_1 = {"Mijn giftanden! Sss...", "Geen gif meer!"},
            fb_bl_serpent_defeat_1 = {"Vervelde mijn huid...", "en mijn trots."},
            fb_bl_serpent_gloat_1 = {"Tot sissens!"},
            fb_bl_serpent_interrupted_1 = {"Sss! Val me niet", "in de rede!"},
            fb_bl_serpent_rematch_won_1 = {"Je ontsnapte één keer", "aan mijn kronkels."},
            fb_bl_serpent_rematch_lost_1 = {"Sssoo, je bent", "terug..."},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Maar ik ben", "De pilaar"},
            fb_bl_pillar_intro_1 = {"Ik leerde veel van", "je vorige handen"},
            fb_bl_pillar_intro_2 = {"Gespeelde kaarten", "blijven gedebuft."},
            fb_bl_pillar_big_hand_1 = {"Verse kaarten?", "Slim."},
            fb_bl_pillar_close_1 = {"Mijn pilaar", "brokkelt af!"},
            fb_bl_pillar_last_hand_1 = {"Laatste hand. Oude", "kaarten zijn nutteloos."},
            fb_bl_pillar_disabled_1 = {"Mijn geheugen!", "Het... vervaagt."},
            fb_bl_pillar_defeat_1 = {"Een pilaar van de", "samenleving valt."},
            fb_bl_pillar_gloat_1 = {"Nog steeds", "overeind!"},
            fb_bl_pillar_interrupted_1 = {"Geen respect voor", "je ouderen?"},
            fb_bl_pillar_rematch_won_1 = {"Ik weet nog hoe", "je me versloeg."},
            fb_bl_pillar_rematch_lost_1 = {"Ik weet nog hoe", "je verloor."},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Maar ik ben", "De naald"},
            fb_bl_needle_intro_1 = {"Je hebt maar", "één kans"},
            fb_bl_needle_intro_2 = {"Eén hand. Meer krijg", "je niet."},
            fb_bl_needle_big_hand_1 = {"Eén enkele hand,", "zo sterk?!"},
            fb_bl_needle_close_1 = {"Nee! Niet met", "één hand!"},
            fb_bl_needle_last_hand_1 = {"Deze hand is", "je enige hand."},
            fb_bl_needle_disabled_1 = {"Mijn naald!", "Hij is bot!"},
            fb_bl_needle_defeat_1 = {"Scherp gespeeld.", "Je hebt me."},
            fb_bl_needle_gloat_1 = {"Punt is,", "je verloor!"},
            fb_bl_needle_interrupted_1 = {"Wat stekelig.", "Ik was niet klaar!"},
            fb_bl_needle_rematch_won_1 = {"Eén hand versloeg", "me vorige keer."},
            fb_bl_needle_rematch_lost_1 = {"Weer één kans.", "Mis je hem weer?"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Maar ik ben", "Het hoofd"},
            fb_bl_head_intro_1 = {"Ik haat", "{C:red,E:1}verliefden{}"},
            fb_bl_head_intro_2 = {"Harten zijn gedebuft.", "Koud, hè?"},
            fb_bl_head_big_hand_1 = {"Je won zonder", "hart?!"},
            fb_bl_head_close_1 = {"Heb een hart,", "maak me niet af!"},
            fb_bl_head_last_hand_1 = {"Laatste hand. Geen", "harten. Geen genade."},
            fb_bl_head_disabled_1 = {"Mijn hoofd bonkt!", "Werken harten weer?"},
            fb_bl_head_defeat_1 = {"Mijn hoofd verloren...", "door jou."},
            fb_bl_head_gloat_1 = {"Hartloos, hè?"},
            fb_bl_head_interrupted_1 = {"Ben je je hoofd", "kwijt? Ik praat!"},
            fb_bl_head_rematch_won_1 = {"Je won mijn hart...", "één keer."},
            fb_bl_head_rematch_lost_1 = {"Kom je voor nog meer", "liefdesverdriet?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Maar ik ben", "De tand"},
            fb_bl_tooth_intro_1 = {"Ik ben in", "de politiek"},
            fb_bl_tooth_intro_2 = {"Elke kaart die je speelt", "kost je $1."},
            fb_bl_tooth_big_hand_1 = {"Je betaalde en won", "toch?!"},
            fb_bl_tooth_close_1 = {"Dwing me niet de", "tandenfee te betalen!"},
            fb_bl_tooth_last_hand_1 = {"Laatste hand,", "laatste dollars."},
            fb_bl_tooth_disabled_1 = {"Mijn beet!", "Hij is weg!"},
            fb_bl_tooth_defeat_1 = {"Met tand en nagel", "verloren."},
            fb_bl_tooth_gloat_1 = {"Betalen, sukkel!"},
            fb_bl_tooth_interrupted_1 = {"Grr! Dat ga je", "me betalen!"},
            fb_bl_tooth_rematch_won_1 = {"Je bent me nog wat", "schuldig van toen."},
            fb_bl_tooth_rematch_lost_1 = {"Kom je je schuld", "betalen?"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Maar ik ben", "De vuursteen"},
            fb_bl_flint_intro_1 = {"Je moet", "belasting betalen"},
            fb_bl_flint_intro_2 = {"Fiches en Multi", "worden gehalveerd."},
            fb_bl_flint_big_hand_1 = {"Halve kracht, toch", "raak?!"},
            fb_bl_flint_close_1 = {"Je slaat vonken uit", "mijn ondergang!"},
            fb_bl_flint_last_hand_1 = {"Laatste hand. Halve", "vonk."},
            fb_bl_flint_disabled_1 = {"Volle kracht?!", "Niet eerlijk!"},
            fb_bl_flint_defeat_1 = {"Mijn vonk", "is gedoofd."},
            fb_bl_flint_gloat_1 = {"Half plezier!"},
            fb_bl_flint_interrupted_1 = {"Geen vonken!", "Ik was aan het praten!"},
            fb_bl_flint_rematch_won_1 = {"Vorige keer ontdook", "je mijn belasting."},
            fb_bl_flint_rematch_lost_1 = {"Weer belastingtijd.", "Betalen."},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Maar ik ben", "Het teken"},
            fb_bl_mark_intro_1 = {"Ik word liever", "niet gezien"},
            fb_bl_mark_intro_2 = {"Alle plaatjes komen", "omgekeerd."},
            fb_bl_mark_big_hand_1 = {"Gemarkeerde kaarten,", "toch gewonnen?!"},
            fb_bl_mark_close_1 = {"Ik ben getekend", "voor de nederlaag!"},
            fb_bl_mark_last_hand_1 = {"Laatste hand. Kies", "gezichten blind."},
            fb_bl_mark_disabled_1 = {"De gezichten!", "Ik zie ze!"},
            fb_bl_mark_defeat_1 = {"Je hebt je stempel", "op mij gedrukt."},
            fb_bl_mark_gloat_1 = {"Getekend als", "verliezer!"},
            fb_bl_mark_interrupted_1 = {"Genoteerd. Je bent", "nu getekend."},
            fb_bl_mark_rematch_won_1 = {"Vorige keer zag je", "dwars door me heen."},
            fb_bl_mark_rematch_lost_1 = {"Zie je mijn gezichten", "nog steeds niet?"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Maar ik ben", "Amberkleurige eikel"},
            fb_bl_final_acorn_intro_1 = {"Ik hou van", "CHAOS!"},
            fb_bl_final_acorn_intro_2 = {"Jokers omgekeerd,", "dan geschud!"},
            fb_bl_final_acorn_big_hand_1 = {"Zelfs in chaos", "win je?!"},
            fb_bl_final_acorn_close_1 = {"Wat een nootgeval!", "Ik barst!"},
            fb_bl_final_acorn_last_hand_1 = {"Laatste hand. Waar", "is je joker?"},
            fb_bl_final_acorn_disabled_1 = {"Mijn eikel!", "Orde hersteld?!"},
            fb_bl_final_acorn_defeat_1 = {"Je hebt mijn", "schil gekraakt..."},
            fb_bl_final_acorn_gloat_1 = {"Eikelrijk", "verloren!"},
            fb_bl_final_acorn_interrupted_1 = {"Eikel! Ik was", "nog niet klaar!"},
            fb_bl_final_acorn_phase2_1 = {"Nu wordt het", "een NOOTGEVAL!"},
            fb_bl_final_acorn_phase3_1 = {"Totale chaos!", "De schil eraf!"},
            fb_bl_final_acorn_rematch_won_1 = {"Je kraakte me één", "keer. Nooit meer!"},
            fb_bl_final_acorn_rematch_lost_1 = {"Kom je voor meer", "CHAOS?"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Maar ik ben", "Groen blaadje"},
            fb_bl_final_leaf_intro_1 = {"Je moet loskomen", "van je wortels"},
            fb_bl_final_leaf_intro_2 = {"Verkoop een joker of", "blijf gedebuft."},
            fb_bl_final_leaf_big_hand_1 = {"Je sloeg een nieuw", "blad om. Hmpf."},
            fb_bl_final_leaf_close_1 = {"Mijn blaadje", "valt!"},
            fb_bl_final_leaf_last_hand_1 = {"Laatste hand.", "Een joker verkopen?"},
            fb_bl_final_leaf_disabled_1 = {"Mijn blaadje! Het is", "verdord!"},
            fb_bl_final_leaf_defeat_1 = {"Ik ga heen...", "als een blad."},
            fb_bl_final_leaf_gloat_1 = {"Blad, blad,", "verloren!"},
            fb_bl_final_leaf_interrupted_1 = {"Prima. Sla de", "beleefdheden over."},
            fb_bl_final_leaf_phase2_1 = {"Mijn wortels", "groeien dieper!"},
            fb_bl_final_leaf_phase3_1 = {"Verwelk met mij!"},
            fb_bl_final_leaf_rematch_won_1 = {"Je liet één keer los.", "Probeer het weer."},
            fb_bl_final_leaf_rematch_lost_1 = {"Nog steeds gehecht", "aan je jokers?"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Maar ik ben", "Violet vat"},
            fb_bl_final_vessel_intro_1 = {"Je liep net tegen", "de grote muur aan"},
            fb_bl_final_vessel_intro_2 = {"Een gigantische blind.", "Zeil maar door!"},
            fb_bl_final_vessel_big_hand_1 = {"Een enorme klap op", "een enorm doelwit."},
            fb_bl_final_vessel_close_1 = {"Verlaat het schip!", "...Het mijne, bedoel ik."},
            fb_bl_final_vessel_last_hand_1 = {"Laatste hand. Dit", "schip zinkt niet."},
            fb_bl_final_vessel_disabled_1 = {"Mijn vat!", "Het zinkt!"},
            fb_bl_final_vessel_defeat_1 = {"Het vat...", "is leeggemaakt."},
            fb_bl_final_vessel_gloat_1 = {"Vat je 'm?", "Verloren!"},
            fb_bl_final_vessel_interrupted_1 = {"Uitvaren voor mijn", "toespraak? Gedurfd."},
            fb_bl_final_vessel_phase2_1 = {"Vul het ruim!"},
            fb_bl_final_vessel_phase3_1 = {"Alle hens", "naar de diepte!"},
            fb_bl_final_vessel_rematch_won_1 = {"Je liet me zinken.", "Ik ben weer opgeknapt."},
            fb_bl_final_vessel_rematch_lost_1 = {"Kom je verdrinken", "in mijn kielzog?"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Maar ik ben", "Karmozijnrood hart"},
            fb_bl_final_heart_intro_1 = {"Ik leen even", "een joker"},
            fb_bl_final_heart_intro_2 = {"Elke hand verliest een", "joker zijn kracht."},
            fb_bl_final_heart_big_hand_1 = {"Een joker minder en", "toch sterk?"},
            fb_bl_final_heart_close_1 = {"Breek mijn hart", "niet!"},
            fb_bl_final_heart_last_hand_1 = {"Laatste hand. Welke", "joker is stil?"},
            fb_bl_final_heart_disabled_1 = {"Mijn hart! Het sloeg", "een slag over."},
            fb_bl_final_heart_defeat_1 = {"Mijn hart...", "is gebroken."},
            fb_bl_final_heart_gloat_1 = {"Al liefdesverdriet?"},
            fb_bl_final_heart_interrupted_1 = {"Je onderbreekt me?", "Wat harteloos!"},
            fb_bl_final_heart_phase2_1 = {"Mijn hart", "klopt sneller!"},
            fb_bl_final_heart_phase3_1 = {"Voel mijn", "karmijnrode woede!"},
            fb_bl_final_heart_rematch_won_1 = {"Vorige keer brak", "je mijn hart."},
            fb_bl_final_heart_rematch_lost_1 = {"Mijn hart klopt", "nog voor jou."},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Maar ik ben", "Azuurblauwe bel"},
            fb_bl_final_bell_intro_1 = {"Ik wil je", "graag begeleiden"},
            fb_bl_final_bell_intro_2 = {"Eén kaart wordt in", "elke hand geforceerd."},
            fb_bl_final_bell_big_hand_1 = {"Je liet mijn geforceerde", "kaart klinken?!"},
            fb_bl_final_bell_close_1 = {"De bel luidt...", "voor mij?!"},
            fb_bl_final_bell_last_hand_1 = {"Laatste hand. Eén", "kaart is geforceerd."},
            fb_bl_final_bell_disabled_1 = {"Mijn bel is stil!", "Valsspeler!"},
            fb_bl_final_bell_defeat_1 = {"De bel luidt", "voor mij."},
            fb_bl_final_bell_gloat_1 = {"Ding dong,", "verloren!"},
            fb_bl_final_bell_interrupted_1 = {"Gered door de bel?", "Deze keer niet!"},
            fb_bl_final_bell_phase2_1 = {"Hoor me", "harder luiden!"},
            fb_bl_final_bell_phase3_1 = {"De laatste slag!"},
            fb_bl_final_bell_rematch_won_1 = {"Vorige keer kreeg ik", "flink op mijn klep."},
            fb_bl_final_bell_rematch_lost_1 = {"De bel luidt weer", "voor jou."},
        }
    }
}
