return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Pojedynki",
            fb_cfg_dialogue = "Dialogi bossów",
            fb_cfg_music = "Muzyka pojedynków",
            fb_cfg_fx = "Efekty ekranu",
            fb_cfg_intro_speed = "Prędkość intra",
            fb_speed_slow = "Wolno",
            fb_speed_normal = "Normalnie",
            fb_speed_fast = "Szybko",
            fb_cfg_min_ante = "Dialogi bossów od Wejścia",
            fb_cfg_dev_mode = "Klawisze deweloperskie (F5-F7)",
            fb_cfg_showdown_enabled = "Własny harmonogram pojedynków",
            fb_cfg_start_ante = "Pierwszy pojedynek: Wejście",
            fb_cfg_every = "Potem co N Wejść",
            fb_cfg_preview = "Pojedynki na Wejściach:",
            fb_cfg_hard = "Trudno! Wczesne pojedynki są brutalne.",
            fb_cfg_next_ante = "Zmiany działają od następnego Wejścia.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Zaszedłeś za daleko..."},
            fb_opener_2 = {"I z przykrością", "muszę powiedzieć..."},
            fb_opener_3 = {"No proszę.", "Dotarłeś tu."},
            fb_closer_1 = {"Nie zdołasz", "mnie pokonać."},
            fb_closer_2 = {"Tu kończy się", "twój run."},
            fb_closer_3 = {"Pokaż, na co", "cię stać."},
            fb_gloat = {"Ten boss był", "za silny..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Jestem #1#!"},
            fb_generic_name_2 = {"Mówią na mnie", "#1#."},
            fb_generic_name_3 = {"Oto on:", "#1#!"},
            fb_generic_intro_1 = {"Twoje szczęście", "kończy się tutaj."},
            fb_generic_intro_2 = {"Zobaczymy, jak", "sobie z tym poradzisz."},
            fb_generic_intro_3 = {"Czytaj uważnie", "moje zasady..."},
            fb_generic_big_hand_1 = {"...Nieźle."},
            fb_generic_big_hand_2 = {"Szczęśliwa ręka."},
            fb_generic_big_hand_3 = {"Hmpf. Znowu?"},
            fb_generic_close_1 = {"Czekaj, czekaj,", "CZEKAJ!"},
            fb_generic_close_2 = {"Nie waż się..."},
            fb_generic_close_3 = {"To niemożliwe..."},
            fb_generic_last_hand_1 = {"Jedna ręka została.", "Niech się liczy."},
            fb_generic_last_hand_2 = {"Tik, tak..."},
            fb_generic_last_hand_3 = {"Ostatnia szansa,", "mały jokerze."},
            fb_generic_disabled_1 = {"Moja moc...!", "Coś ty zrobił?"},
            fb_generic_disabled_2 = {"Hej! To", "oszustwo!"},
            fb_generic_disabled_3 = {"Czuję się... słabo."},
            fb_generic_defeat_1 = {"Niemożliwe..."},
            fb_generic_defeat_2 = {"Wrócę przy kolejnym", "Wejściu..."},
            fb_generic_defeat_3 = {"Dobra gra..."},
            fb_generic_gloat_1 = {"Ten boss był", "za silny..."},
            fb_generic_gloat_2 = {"Kasyno", "zawsze wygrywa."},
            fb_generic_gloat_3 = {"Więcej szczęścia", "w następnym runie."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Ale ja jestem", "Hak"},
            fb_bl_hook_intro_1 = {"Zabieram ci", "kilka kart"},
            fb_bl_hook_intro_2 = {"Dwie karty mniej,", "co rękę."},
            fb_bl_hook_big_hand_1 = {"Nawet z mniejszą", "liczbą kart?!"},
            fb_bl_hook_close_1 = {"Zostaw te", "karty!"},
            fb_bl_hook_last_hand_1 = {"W końcu złapany", "na hak!"},
            fb_bl_hook_disabled_1 = {"Mój hak!", "Jest zepsuty!"},
            fb_bl_hook_defeat_1 = {"Dobra... zdejmę", "cię z haka."},
            fb_bl_hook_gloat_1 = {"Hak:", "\"Złapany na haczyk!\""},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Ale ja jestem", "Wół"},
            fb_bl_ox_intro_1 = {"Zabieram ci", "wszystkie pieniądze"},
            fb_bl_ox_intro_2 = {"Ulubiona ręka", "kosztuje cię wszystko."},
            fb_bl_ox_big_hand_1 = {"Bez grosza i", "wciąż wygrywasz?!"},
            fb_bl_ox_close_1 = {"Wolniej, kowboju!", "...Ja też."},
            fb_bl_ox_last_hand_1 = {"Ostatnia ręka. Wydaj", "albo strać."},
            fb_bl_ox_disabled_1 = {"Moje rogi!", "Stępiały!"},
            fb_bl_ox_defeat_1 = {"Chwyciłeś byka", "za rogi..."},
            fb_bl_ox_gloat_1 = {"Wół:", "\"Teraz jesteś spłukany!\""},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Ale ja jestem", "Dom"},
            fb_bl_house_intro_1 = {"Jesteś", "ŚLEPY!"},
            fb_bl_house_intro_2 = {"Pierwsza ręka na koszt", "domu. Na ślepo!"},
            fb_bl_house_big_hand_1 = {"Ślepy los, a ty", "i tak wygrałeś?!"},
            fb_bl_house_close_1 = {"Dom nigdy", "nie przegrywa!"},
            fb_bl_house_last_hand_1 = {"Koniec ze ślepym", "szczęściem."},
            fb_bl_house_disabled_1 = {"Moja opaska!", "Spadła!"},
            fb_bl_house_defeat_1 = {"Dom...", "upadł."},
            fb_bl_house_gloat_1 = {"Dom:", "\"Dom wygrywa!\""},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Ale ja jestem", "Mur"},
            fb_bl_wall_intro_1 = {"Właśnie w jakiś", "uderzyłeś"},
            fb_bl_wall_intro_2 = {"Spróbuj wspiąć się", "na ten wynik."},
            fb_bl_wall_big_hand_1 = {"Wspiąłeś się", "na mój mur?!"},
            fb_bl_wall_close_1 = {"Nie przebijesz", "się!"},
            fb_bl_wall_last_hand_1 = {"Nie ma już po", "czym się wspinać."},
            fb_bl_wall_disabled_1 = {"Pęknięcia! Mój mur", "pęka!"},
            fb_bl_wall_defeat_1 = {"Mur...", "się wali."},
            fb_bl_wall_gloat_1 = {"Mur:", "\"Mur beton!\""},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Ale ja jestem", "Koło"},
            fb_bl_wheel_intro_1 = {"Lubię...", "HAZARD!"},
            fb_bl_wheel_intro_2 = {"Co siódma karta", "leży zakryta."},
            fb_bl_wheel_big_hand_1 = {"Fortuna cię", "dziś lubi."},
            fb_bl_wheel_close_1 = {"Moje koło", "się zacina!"},
            fb_bl_wheel_last_hand_1 = {"Ostatni obrót.", "Czujesz fart?"},
            fb_bl_wheel_disabled_1 = {"Koło stanęło?", "Ustawione!"},
            fb_bl_wheel_defeat_1 = {"Koło fortuny...", "obróciło się przeciw mnie."},
            fb_bl_wheel_gloat_1 = {"Koło:", "\"Koło się zamknęło!\""},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Ale ja jestem", "Ramię"},
            fb_bl_arm_intro_1 = {"Zrównoważę", "twoją moc"},
            fb_bl_arm_intro_2 = {"Każda zagrana ręka", "traci poziom."},
            fb_bl_arm_big_hand_1 = {"Ta ręka ma", "muskuły..."},
            fb_bl_arm_close_1 = {"Siłowanie na rękę?", "Przegrywam!"},
            fb_bl_arm_last_hand_1 = {"Ostatnia ręka.", "Nie napinaj się."},
            fb_bl_arm_disabled_1 = {"Moje ramię zwiotczało!", "Oszust!"},
            fb_bl_arm_defeat_1 = {"Pokonałeś moje", "silne ramię."},
            fb_bl_arm_gloat_1 = {"Ramię:", "\"Ręce opadają!\""},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Ale ja jestem", "Klub"},
            fb_bl_club_intro_1 = {"Nienawidzę", "{C:green,E:1}szczęściarzy{}"},
            fb_bl_club_intro_2 = {"Trefle osłabione.", "Przykro mi."},
            fb_bl_club_big_hand_1 = {"Bez trefli, bez", "problemu?!"},
            fb_bl_club_close_1 = {"Nie bij mnie", "tym!"},
            fb_bl_club_last_hand_1 = {"Ostatnia ręka. Zostaw", "trefle w domu."},
            fb_bl_club_disabled_1 = {"Moje trefle straciły", "pazur!"},
            fb_bl_club_defeat_1 = {"Klub zamknięty.", "Czas na mnie..."},
            fb_bl_club_gloat_1 = {"Klub:", "\"Klub zamknięty!\""},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Ale ja jestem", "Ryba"},
            fb_bl_fish_intro_1 = {"Bądź pewien, co", "chcesz zagrać"},
            fb_bl_fish_intro_2 = {"Po każdej ręce karty", "leżą zakryte."},
            fb_bl_fish_big_hand_1 = {"Coś tu śmierdzi", "rybą!"},
            fb_bl_fish_close_1 = {"Nie wyciągaj", "mnie na brzeg!"},
            fb_bl_fish_last_hand_1 = {"Ostatni rzut.", "Zwijaj żyłkę."},
            fb_bl_fish_disabled_1 = {"Moje łuski!", "Odpadły!"},
            fb_bl_fish_defeat_1 = {"Złowiony...", "przez zawodowca."},
            fb_bl_fish_gloat_1 = {"Ryba:", "\"Wpadłeś w sieć!\""},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Ale ja jestem", "Medium"},
            fb_bl_psychic_intro_1 = {"Nienawidzę", "niezdecydowanych"},
            fb_bl_psychic_intro_2 = {"Pięć kart, nie mniej.", "Przewidziałem to."},
            fb_bl_psychic_big_hand_1 = {"Tego NIE", "przewidziałem."},
            fb_bl_psychic_close_1 = {"Moja kula pokazuje", "...porażkę!"},
            fb_bl_psychic_last_hand_1 = {"Widzę twoją", "ostatnią rękę."},
            fb_bl_psychic_disabled_1 = {"Moje wizje!", "Zniknęły!"},
            fb_bl_psychic_defeat_1 = {"Widziałem to.", "...Czy aby na pewno?"},
            fb_bl_psychic_gloat_1 = {"Medium:", "\"Przewidziałem to!\""},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Ale ja jestem", "Oścień"},
            fb_bl_goad_intro_1 = {"Nienawidzę", "{C:black,E:1}WŁADZY{}"},
            fb_bl_goad_intro_2 = {"Piki osłabione.", "Kop głębiej."},
            fb_bl_goad_big_hand_1 = {"Nieźle bez", "twoich pików."},
            fb_bl_goad_close_1 = {"Nie waż się kopać", "mi grobu!"},
            fb_bl_goad_last_hand_1 = {"Kop głęboko. To twoja", "ostatnia ręka."},
            fb_bl_goad_disabled_1 = {"Teraz nikogo", "nie podjudzę!"},
            fb_bl_goad_defeat_1 = {"Do licha,", "wygrałeś."},
            fb_bl_goad_gloat_1 = {"Oścień:", "\"Kop swój grób!\""},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Ale ja jestem", "Woda"},
            fb_bl_water_intro_1 = {"Oddaj mi", "swoje zrzutki"},
            fb_bl_water_intro_2 = {"Zero zrzutek.", "Ani kropli."},
            fb_bl_water_big_hand_1 = {"Bez zrzutek i", "wciąż wygrywasz?!"},
            fb_bl_water_close_1 = {"Tonę!", "Rzućcie linę!"},
            fb_bl_water_last_hand_1 = {"Ostatnia ręka.", "Płyń albo tonij."},
            fb_bl_water_disabled_1 = {"Zrzutki znów", "płyną!"},
            fb_bl_water_defeat_1 = {"Wyschłem do cna..."},
            fb_bl_water_gloat_1 = {"Woda:", "\"Poszło na dno!\""},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Ale ja jestem", "Okno"},
            fb_bl_window_intro_1 = {"Nienawidzę", "{C:yellow,E:1}kapitalizmu{}"},
            fb_bl_window_intro_2 = {"Karo osłabione.", "Świeć dalej."},
            fb_bl_window_big_hand_1 = {"Komu potrzebne", "karo?"},
            fb_bl_window_close_1 = {"Nie tłucz", "mojego okna!"},
            fb_bl_window_last_hand_1 = {"Ostatnia ręka. Zakaz", "błyskotek."},
            fb_bl_window_disabled_1 = {"Moje okno pękło!", "Karo błyszczą!"},
            fb_bl_window_defeat_1 = {"Okno możliwości", "się zamknęło."},
            fb_bl_window_gloat_1 = {"Okno:", "\"Karo? Osłabione!\""},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Ale ja jestem", "Kajdany"},
            fb_bl_manacle_intro_1 = {"Zabieram ci", "{C:blue,E:1}opcje{}"},
            fb_bl_manacle_intro_2 = {"Jedna karta mniej", "na ręce."},
            fb_bl_manacle_big_hand_1 = {"W kajdanach i", "wciąż wygrywasz?!"},
            fb_bl_manacle_close_1 = {"Zrzucasz", "swoje kajdany!"},
            fb_bl_manacle_last_hand_1 = {"Ostatnia ręka. I to", "w kajdankach."},
            fb_bl_manacle_disabled_1 = {"Kajdany!", "Spadły!"},
            fb_bl_manacle_defeat_1 = {"W końcu wolny...", "ode mnie."},
            fb_bl_manacle_gloat_1 = {"Kajdany:", "\"Ręce do góry!\""},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Ale ja jestem", "Oko"},
            fb_bl_eye_intro_1 = {"Nie lubię", "rutyny"},
            fb_bl_eye_intro_2 = {"Nigdy ten sam układ", "dwa razy."},
            fb_bl_eye_big_hand_1 = {"Nowy układ? Mam", "cię na oku."},
            fb_bl_eye_close_1 = {"Nie mogę", "na to patrzeć!"},
            fb_bl_eye_last_hand_1 = {"Widzę twoją", "ostatnią rękę."},
            fb_bl_eye_disabled_1 = {"Moje oko! Kto mi", "w nie dźgnął?!"},
            fb_bl_eye_defeat_1 = {"Z oczu, z serca", "precz..."},
            fb_bl_eye_gloat_1 = {"Oko:", "\"Mówiłem, że widzę!\""},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Ale ja jestem", "Usta"},
            fb_bl_mouth_intro_1 = {"Uwielbiam", "rutynę"},
            fb_bl_mouth_intro_2 = {"Wybierz jeden układ", "i się go trzymaj."},
            fb_bl_mouth_big_hand_1 = {"Ten sam układ,", "wciąż mocny..."},
            fb_bl_mouth_close_1 = {"Usta mam", "szeroko otwarte!"},
            fb_bl_mouth_last_hand_1 = {"Ostatnia ręka. Ten sam", "układ. Cisza."},
            fb_bl_mouth_disabled_1 = {"Kto mi założył", "kaganiec?!"},
            fb_bl_mouth_defeat_1 = {"Odebrało mi mowę..."},
            fb_bl_mouth_gloat_1 = {"Usta:", "\"Cicho, przegrywie!\""},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Ale ja jestem", "Roślina"},
            fb_bl_plant_intro_1 = {"Nienawidzę", "przyjaznych twarzy"},
            fb_bl_plant_intro_2 = {"Królowie, damy, walety:", "wszystkie osłabione."},
            fb_bl_plant_big_hand_1 = {"Bez figur?!", "Niesamowite."},
            fb_bl_plant_close_1 = {"Nie wyrywaj mnie", "z korzeniami!"},
            fb_bl_plant_last_hand_1 = {"Spójrz w twarz", "ostatniej ręce."},
            fb_bl_plant_disabled_1 = {"Moje płatki!", "Wszystkie zniknęły!"},
            fb_bl_plant_defeat_1 = {"Zwiędłem...", "Odrosnę."},
            fb_bl_plant_gloat_1 = {"Roślina:", "\"Spójrz prawdzie w oczy!\""},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Ale ja jestem", "Wąż"},
            fb_bl_serpent_intro_1 = {"Jest", "deficyt"},
            fb_bl_serpent_intro_2 = {"Zagrasz czy zrzucisz,", "dobierasz tylko 3."},
            fb_bl_serpent_big_hand_1 = {"Trzy karty. A i tak", "uderzyłeś!"},
            fb_bl_serpent_close_1 = {"Nie uciekaj", "teraz!"},
            fb_bl_serpent_last_hand_1 = {"Ostatnie ukąszenie.", "Trzy karty."},
            fb_bl_serpent_disabled_1 = {"Moje kły! Sss...", "Koniec jadu!"},
            fb_bl_serpent_defeat_1 = {"Zrzuciłem skórę...", "i dumę."},
            fb_bl_serpent_gloat_1 = {"Wąż:", "\"Do sss-zobaczenia!\""},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Ale ja jestem", "Filar"},
            fb_bl_pillar_intro_1 = {"Wiele się nauczyłem", "z twoich dawnych rąk"},
            fb_bl_pillar_intro_2 = {"Zagrane karty zostają", "osłabione w tym Wejściu."},
            fb_bl_pillar_big_hand_1 = {"Świeże karty?", "Sprytnie."},
            fb_bl_pillar_close_1 = {"Mój filar", "się kruszy!"},
            fb_bl_pillar_last_hand_1 = {"Ostatnia ręka. Stare", "karty są bezużyteczne."},
            fb_bl_pillar_disabled_1 = {"Moja pamięć!", "Zanika..."},
            fb_bl_pillar_defeat_1 = {"Filar społeczności", "upadł."},
            fb_bl_pillar_gloat_1 = {"Filar:", "\"Wciąż stoję!\""},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Ale ja jestem", "Igła"},
            fb_bl_needle_intro_1 = {"Masz tylko", "jedną szansę"},
            fb_bl_needle_intro_2 = {"Jedna ręka. Tylko", "tyle dostaniesz."},
            fb_bl_needle_big_hand_1 = {"Jedna ręka,", "tak mocna?!"},
            fb_bl_needle_close_1 = {"Nie! Nie jedną", "ręką!"},
            fb_bl_needle_last_hand_1 = {"Ta ręka to", "twoja jedyna ręka."},
            fb_bl_needle_disabled_1 = {"Moja igła!", "Jest tępa!"},
            fb_bl_needle_defeat_1 = {"Ostra gra.", "Masz mnie."},
            fb_bl_needle_gloat_1 = {"Igła:", "\"Wbiłem szpilę!\""},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Ale ja jestem", "Głowa"},
            fb_bl_head_intro_1 = {"Nienawidzę", "{C:red,E:1}zakochanych{}"},
            fb_bl_head_intro_2 = {"Kiery osłabione.", "Zimno, prawda?"},
            fb_bl_head_big_hand_1 = {"Wygrałeś bez", "serca?!"},
            fb_bl_head_close_1 = {"Miej serce,", "nie dobijaj mnie!"},
            fb_bl_head_last_hand_1 = {"Ostatnia ręka. Bez", "serc. Bez litości."},
            fb_bl_head_disabled_1 = {"Boli mnie głowa!", "Kiery znów działają?"},
            fb_bl_head_defeat_1 = {"Straciłem głowę...", "przez ciebie."},
            fb_bl_head_gloat_1 = {"Głowa:", "\"Bez serca, co?\""},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Ale ja jestem", "Ząb"},
            fb_bl_tooth_intro_1 = {"Interesuję się", "polityką"},
            fb_bl_tooth_intro_2 = {"Każda zagrana karta", "kosztuje cię $1."},
            fb_bl_tooth_big_hand_1 = {"Zapłaciłeś, a ty", "i tak wygrałeś?!"},
            fb_bl_tooth_close_1 = {"Nie każ mi płacić", "wróżce zębuszce!"},
            fb_bl_tooth_last_hand_1 = {"Ostatnia ręka,", "ostatnie dolary."},
            fb_bl_tooth_disabled_1 = {"Mój kieł!", "Zniknął!"},
            fb_bl_tooth_defeat_1 = {"Zębami i pazurami,", "a jednak przegrałem."},
            fb_bl_tooth_gloat_1 = {"Ząb:", "\"Płać, frajerze!\""},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Ale ja jestem", "Krzemień"},
            fb_bl_flint_intro_1 = {"Musisz", "płacić podatki"},
            fb_bl_flint_intro_2 = {"Żetony i mnożnik", "są zmniejszone o połowę."},
            fb_bl_flint_big_hand_1 = {"Pół mocy, a i tak", "trafiasz?!"},
            fb_bl_flint_close_1 = {"Krzesasz iskry", "z mojego upadku!"},
            fb_bl_flint_last_hand_1 = {"Ostatnia ręka. Pół", "iskry."},
            fb_bl_flint_disabled_1 = {"Pełna moc?!", "Nie fair!"},
            fb_bl_flint_defeat_1 = {"Moja iskra", "zgasła."},
            fb_bl_flint_gloat_1 = {"Krzemień:", "\"Pół zabawy!\""},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Ale ja jestem", "Cel"},
            fb_bl_mark_intro_1 = {"Nie lubię", "być widziany"},
            fb_bl_mark_intro_2 = {"Wszystkie figury", "leżą zakryte."},
            fb_bl_mark_big_hand_1 = {"Znaczone karty,", "a i tak wygrałeś?!"},
            fb_bl_mark_close_1 = {"Jestem na celowniku", "porażki!"},
            fb_bl_mark_last_hand_1 = {"Ostatnia ręka. Wybierz", "twarze na ślepo."},
            fb_bl_mark_disabled_1 = {"Twarze!", "Widzę je!"},
            fb_bl_mark_defeat_1 = {"Zostawiłeś na mnie", "swój ślad."},
            fb_bl_mark_gloat_1 = {"Cel:", "\"Cel trafiony!\""},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Ale ja jestem", "Bursztynowy żołądź"},
            fb_bl_final_acorn_intro_1 = {"Lubię", "CHAOS!"},
            fb_bl_final_acorn_intro_2 = {"Jokery zakryte,", "potem przetasowane!"},
            fb_bl_final_acorn_big_hand_1 = {"Nawet w chaosie", "wygrywasz?!"},
            fb_bl_final_acorn_close_1 = {"To szaleństwo!", "Pękam!"},
            fb_bl_final_acorn_last_hand_1 = {"Ostatnia ręka. Gdzie", "jest twój joker?"},
            fb_bl_final_acorn_disabled_1 = {"Mój żołądź!", "Porządek wrócił?!"},
            fb_bl_final_acorn_defeat_1 = {"Rozbiłeś", "moją skorupę..."},
            fb_bl_final_acorn_gloat_1 = {"Bursztynowy żołądź:", "\"Twardy orzech!\""},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Ale ja jestem", "Zielony liść"},
            fb_bl_final_leaf_intro_1 = {"Musisz oderwać się", "od swoich korzeni"},
            fb_bl_final_leaf_intro_2 = {"Sprzedaj jokera albo", "zostań osłabiony."},
            fb_bl_final_leaf_big_hand_1 = {"Przewróciłeś nową", "kartę. Hmpf."},
            fb_bl_final_leaf_close_1 = {"Mój liść", "opada!"},
            fb_bl_final_leaf_last_hand_1 = {"Ostatnia ręka.", "Sprzedać jokera?"},
            fb_bl_final_leaf_disabled_1 = {"Mój liść!", "Uschnął!"},
            fb_bl_final_leaf_defeat_1 = {"Odchodzę...", "jak liść z drzewa."},
            fb_bl_final_leaf_gloat_1 = {"Zielony liść:", "\"Spadasz jak liść!\""},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Ale ja jestem", "Fioletowe naczynie"},
            fb_bl_final_vessel_intro_1 = {"Właśnie uderzyłeś", "w wielki mur"},
            fb_bl_final_vessel_intro_2 = {"Naprawdę ogromna blind.", "Podnieś żagle!"},
            fb_bl_final_vessel_big_hand_1 = {"Ogromny cios w", "ogromny cel."},
            fb_bl_final_vessel_close_1 = {"Opuścić statek!", "...Mój, to znaczy."},
            fb_bl_final_vessel_last_hand_1 = {"Ostatnia ręka. Ten", "statek nie zatonie."},
            fb_bl_final_vessel_disabled_1 = {"Moje naczynie!", "Tonie!"},
            fb_bl_final_vessel_defeat_1 = {"Naczynie...", "zostało opróżnione."},
            fb_bl_final_vessel_gloat_1 = {"Fioletowe naczynie:", "\"Pusto! Przegrałeś!\""},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Ale ja jestem", "Szkarłatne serce"},
            fb_bl_final_heart_intro_1 = {"Pożyczę sobie", "jokera"},
            fb_bl_final_heart_intro_2 = {"Co rękę joker traci", "swoją moc."},
            fb_bl_final_heart_big_hand_1 = {"Joker mniej, a wciąż", "mocny?"},
            fb_bl_final_heart_close_1 = {"Nie łam", "mi serca!"},
            fb_bl_final_heart_last_hand_1 = {"Ostatnia ręka. Który", "joker milczy?"},
            fb_bl_final_heart_disabled_1 = {"Moje serce! Przeskoczyło", "jedno uderzenie."},
            fb_bl_final_heart_defeat_1 = {"Moje serce...", "jest złamane."},
            fb_bl_final_heart_gloat_1 = {"Szkarłatne serce:", "\"Złamane serce?\""},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Ale ja jestem", "Modry dzwonek"},
            fb_bl_final_bell_intro_1 = {"Chciałbym", "cię poprowadzić"},
            fb_bl_final_bell_intro_2 = {"Jedna karta jest", "wymuszona w każdej ręce."},
            fb_bl_final_bell_big_hand_1 = {"Wymuszona karta", "zadzwoniła?!"},
            fb_bl_final_bell_close_1 = {"Dzwon bije...", "dla mnie?!"},
            fb_bl_final_bell_last_hand_1 = {"Ostatnia ręka. Jedna", "karta wymuszona."},
            fb_bl_final_bell_disabled_1 = {"Mój dzwonek milczy!", "Oszust!"},
            fb_bl_final_bell_defeat_1 = {"Dzwon bije", "dla mnie."},
            fb_bl_final_bell_gloat_1 = {"Modry dzwonek:", "\"Dzyń dzyń, przegrałeś!\""},
        }
    }
}
