return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Confrontos",
            fb_cfg_dialogue = "Diálogos de chefes",
            fb_cfg_music = "Música dos confrontos",
            fb_cfg_fx = "Efeitos de tela",
            fb_cfg_cinematic = "Cinemáticas de confronto",
            fb_cfg_moves = "Golpes dos chefes",
            fb_cfg_phase_twists = "Fases dos chefes mudam as regras",
            fb_showdown_title = "CONFRONTO FINAL",
            fb_cfg_intro_speed = "Velocidade da intro",
            fb_speed_slow = "Lenta",
            fb_speed_normal = "Normal",
            fb_speed_fast = "Rápida",
            fb_cfg_min_ante = "Diálogos a partir da Aposta",
            fb_cfg_memory = "Memória dos chefes",
            fb_cfg_dev_mode = "Teclas de dev (F5-F7)",
            fb_cfg_showdown_enabled = "Calendário de confrontos",
            fb_cfg_start_ante = "Primeiro confronto na Aposta",
            fb_cfg_every = "Depois a cada N Apostas",
            fb_cfg_preview = "Confrontos nas Apostas",
            fb_cfg_hard = "Difícil! Confrontos cedo são brutais.",
            fb_cfg_next_ante = "Mudanças valem a partir da próxima Aposta.",
            fb_cfg_group_dialogue = "Diálogos",
            fb_cfg_group_stage = "Palco do confronto",
            fb_credits_thanks = "Obrigado por jogar com o FinalBoss!",
            fb_credits_lead = "Criado e mantido por",
            fb_credits_music = "Música dos confrontos:",
            fb_credits_music_by = "Adam Isiah (cover orquestral)",
            fb_credits_listen = "Ouvir no YouTube",
            fb_credits_github = "GitHub",
            fb_tip_me = "Me dê uma gorjeta",
            fb_tip_me_message_1 = "Se você curte o FinalBoss, considere me dar",
            fb_tip_me_message_2 = "uma pequena gorjeta para mostrar seu apoio.",
            fb_tip_me_message_3 = "Agradeço muito!",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Os chefes respondem e os confrontos viram lutas contra chefes.", "Por {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Você chegou longe", "demais..."},
            fb_opener_2 = {"E lamento dizer..."},
            fb_opener_3 = {"Então. Você", "conseguiu chegar."},
            fb_closer_1 = {"Você não vai", "conseguir me vencer."},
            fb_closer_2 = {"É aqui que a sua", "run termina."},
            fb_closer_3 = {"Mostre do que", "você é capaz."},
            fb_gloat = {"Esse chefe foi", "demais..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Eu sou #1#!"},
            fb_generic_name_2 = {"Me chamam de", "#1#."},
            fb_generic_name_3 = {"Contemple:", "#1#!"},
            fb_generic_intro_1 = {"Sua sorte", "acaba aqui."},
            fb_generic_intro_2 = {"Vamos ver como", "você lida com isso."},
            fb_generic_intro_3 = {"Leia minhas regras", "com cuidado..."},
            fb_generic_big_hand_1 = {"...Nada mal."},
            fb_generic_big_hand_2 = {"Mão de sorte."},
            fb_generic_big_hand_3 = {"Hmph. De novo?"},
            fb_generic_close_1 = {"Espera, espera,", "ESPERA!"},
            fb_generic_close_2 = {"Não se atreva..."},
            fb_generic_close_3 = {"Isso não pode ser..."},
            fb_generic_last_hand_1 = {"Falta uma mão.", "Faça valer."},
            fb_generic_last_hand_2 = {"Tique, taque..."},
            fb_generic_last_hand_3 = {"Última chance,", "curingazinho."},
            fb_generic_disabled_1 = {"Meu poder...!", "O que você fez?"},
            fb_generic_disabled_2 = {"Ei! Isso é", "trapaça!"},
            fb_generic_disabled_3 = {"Estou me sentindo...", "fraco."},
            fb_generic_defeat_1 = {"Impossível..."},
            fb_generic_defeat_2 = {"Volto na próxima", "Aposta..."},
            fb_generic_defeat_3 = {"Bem jogado..."},
            fb_generic_gloat_1 = {"Esse chefe foi", "demais..."},
            fb_generic_gloat_2 = {"A banca", "sempre vence."},
            fb_generic_gloat_3 = {"Mais sorte na", "próxima run."},
            fb_generic_interrupted_1 = {"Meu discurso!"},
            fb_generic_interrupted_2 = {"Ok... então", "é assim."},
            fb_generic_interrupted_3 = {"Nem um oi?"},
            fb_generic_phase2_1 = {"Chega de brincadeira!"},
            fb_generic_phase3_1 = {"Agora eu fiquei", "furioso de verdade!"},
            fb_generic_rematch_won_1 = {"Você de novo?", "Eu me lembro de você."},
            fb_generic_rematch_won_2 = {"Da última vez foi", "sorte. Admita."},
            fb_generic_rematch_won_3 = {"Hora da revanche.", "Eu treinei."},
            fb_generic_rematch_lost_1 = {"Voltou pra levar", "outra surra?"},
            fb_generic_rematch_lost_2 = {"Não aprendeu", "da última vez?"},
            fb_generic_rematch_lost_3 = {"Ah, é você.", "O perdedor."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Mas eu sou", "O Gancho"},
            fb_bl_hook_intro_1 = {"Vou levar algumas", "das suas cartas"},
            fb_bl_hook_intro_2 = {"Duas cartas a menos,", "a cada mão."},
            fb_bl_hook_big_hand_1 = {"Mesmo com menos", "cartas?!"},
            fb_bl_hook_close_1 = {"Solte essas", "cartas!"},
            fb_bl_hook_last_hand_1 = {"Enfim fisguei", "você!"},
            fb_bl_hook_disabled_1 = {"Meu gancho!", "Quebrou!"},
            fb_bl_hook_defeat_1 = {"Tudo bem... vou", "soltar você."},
            fb_bl_hook_gloat_1 = {"Fisgado!"},
            fb_bl_hook_interrupted_1 = {"Grosso! Eu estava", "no meio da fala!"},
            fb_bl_hook_rematch_won_1 = {"Da última vez você", "escapou do gancho."},
            fb_bl_hook_rematch_lost_1 = {"Voltou pra ser", "fisgado de novo?"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Mas eu sou", "O Touro"},
            fb_bl_ox_intro_1 = {"Vou levar todo", "o seu dinheiro"},
            fb_bl_ox_intro_2 = {"Sua mão favorita", "custa tudo."},
            fb_bl_ox_big_hand_1 = {"Sem um tostão e", "ainda ganhando?!"},
            fb_bl_ox_close_1 = {"Calma, peão!", "...Eu também."},
            fb_bl_ox_last_hand_1 = {"Última mão. Gaste", "ou perca."},
            fb_bl_ox_disabled_1 = {"Meus chifres!", "Ficaram cegos!"},
            fb_bl_ox_defeat_1 = {"Você pegou o touro", "pelos chifres..."},
            fb_bl_ox_gloat_1 = {"Agora está falido!"},
            fb_bl_ox_interrupted_1 = {"Ah, então é ASSIM", "que vai ser."},
            fb_bl_ox_rematch_won_1 = {"Você escapou dos meus", "chifres uma vez..."},
            fb_bl_ox_rematch_lost_1 = {"Ainda falido desde", "a última vez?"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Mas eu sou", "A Casa"},
            fb_bl_house_intro_1 = {"Você está", "CEGO!"},
            fb_bl_house_intro_2 = {"A primeira mão é por", "conta da casa. Cego!"},
            fb_bl_house_big_hand_1 = {"Sorte cega e você", "ainda ganhou?!"},
            fb_bl_house_close_1 = {"A casa nunca", "perde!"},
            fb_bl_house_last_hand_1 = {"Chega de sorte", "cega."},
            fb_bl_house_disabled_1 = {"Minha venda!", "Caiu!"},
            fb_bl_house_defeat_1 = {"A casa...", "caiu."},
            fb_bl_house_gloat_1 = {"A casa ganha!"},
            fb_bl_house_interrupted_1 = {"Regra da casa:", "ainda não se joga!"},
            fb_bl_house_rematch_won_1 = {"A casa perdeu uma vez.", "Nunca mais."},
            fb_bl_house_rematch_lost_1 = {"Bem-vindo de volta.", "A casa não esquece."},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Mas eu sou", "O Muro"},
            fb_bl_wall_intro_1 = {"Você acabou de", "bater em um"},
            fb_bl_wall_intro_2 = {"Tente escalar", "esta pontuação."},
            fb_bl_wall_big_hand_1 = {"Você escalou", "o meu muro?!"},
            fb_bl_wall_close_1 = {"Você não vai", "me derrubar!"},
            fb_bl_wall_last_hand_1 = {"Não há mais", "onde escalar."},
            fb_bl_wall_disabled_1 = {"Rachaduras! Meu muro", "está rachando!"},
            fb_bl_wall_defeat_1 = {"O muro...", "desaba."},
            fb_bl_wall_gloat_1 = {"Deu de cara", "no muro!"},
            fb_bl_wall_interrupted_1 = {"É como falar com", "a parede... opa."},
            fb_bl_wall_rematch_won_1 = {"Você me escalou uma", "vez. Duas, não."},
            fb_bl_wall_rematch_lost_1 = {"Voltou pra dar de", "cara no mesmo muro?"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Mas eu sou", "A Roda"},
            fb_bl_wheel_intro_1 = {"Eu gosto de...", "APOSTAR!"},
            fb_bl_wheel_intro_2 = {"Uma em sete cartas", "vem virada."},
            fb_bl_wheel_big_hand_1 = {"A Dama Sorte gosta", "de você hoje."},
            fb_bl_wheel_close_1 = {"Minha roda está", "descontrolada!"},
            fb_bl_wheel_last_hand_1 = {"Último giro.", "Sentindo a sorte?"},
            fb_bl_wheel_disabled_1 = {"A roda parou?", "Tá armado!"},
            fb_bl_wheel_defeat_1 = {"A roda da fortuna", "gira contra mim..."},
            fb_bl_wheel_gloat_1 = {"A roda girou!"},
            fb_bl_wheel_interrupted_1 = {"Opa! Calma, ainda", "estou girando!"},
            fb_bl_wheel_rematch_won_1 = {"Sua sorte durou", "a última rodada..."},
            fb_bl_wheel_rematch_lost_1 = {"Mais uma rodada?", "A banca tem vantagem."},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Mas eu sou", "O Braço"},
            fb_bl_arm_intro_1 = {"Vou equilibrar", "o seu poder"},
            fb_bl_arm_intro_2 = {"Toda mão que você joga", "perde um nível."},
            fb_bl_arm_big_hand_1 = {"Essa mão tem", "músculos..."},
            fb_bl_arm_close_1 = {"Queda de braço?", "Estou perdendo!"},
            fb_bl_arm_last_hand_1 = {"Última mão. Sem", "fazer pose."},
            fb_bl_arm_disabled_1 = {"Meu braço amoleceu!", "Trapaceiro!"},
            fb_bl_arm_defeat_1 = {"Você venceu meu", "braço forte."},
            fb_bl_arm_gloat_1 = {"Rebaixado!"},
            fb_bl_arm_interrupted_1 = {"Tira a mão! Eu ainda", "estava me exibindo!"},
            fb_bl_arm_rematch_won_1 = {"Da última vez você", "venceu a queda de braço."},
            fb_bl_arm_rematch_lost_1 = {"Voltou pra outra", "queda de braço?"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Mas eu sou", "Paulada"},
            fb_bl_club_intro_1 = {"Odeio jogadores", "{C:green,E:1}sortudos{}"},
            fb_bl_club_intro_2 = {"Paus estão debilitados.", "Desculpe."},
            fb_bl_club_big_hand_1 = {"Sem paus, sem", "problema?!"},
            fb_bl_club_close_1 = {"Não me dê pau", "com isso!"},
            fb_bl_club_last_hand_1 = {"Última mão. Deixe os", "paus em casa."},
            fb_bl_club_disabled_1 = {"Meus paus perderam", "a força!"},
            fb_bl_club_defeat_1 = {"Clube fechado.", "Hora de ir..."},
            fb_bl_club_gloat_1 = {"Levou pau!"},
            fb_bl_club_interrupted_1 = {"Ei! No meu clube,", "eu falo primeiro."},
            fb_bl_club_rematch_won_1 = {"Da última vez você", "invadiu meu clube."},
            fb_bl_club_rematch_lost_1 = {"Renovou a carteirinha?", "Bem-vindo de volta."},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Mas eu sou", "O Peixe"},
            fb_bl_fish_intro_1 = {"Tenha certeza do", "que vai jogar"},
            fb_bl_fish_intro_2 = {"Após cada mão, as", "cartas vêm viradas."},
            fb_bl_fish_big_hand_1 = {"Tem coisa podre", "nessa mão!"},
            fb_bl_fish_close_1 = {"Não me puxe", "para a margem!"},
            fb_bl_fish_last_hand_1 = {"Último lançamento.", "Recolha a linha."},
            fb_bl_fish_disabled_1 = {"Minhas escamas!", "Caíram!"},
            fb_bl_fish_defeat_1 = {"Fisgado...", "por um profissional."},
            fb_bl_fish_gloat_1 = {"Você se afogou!"},
            fb_bl_fish_interrupted_1 = {"Você cortou", "minha linha!"},
            fb_bl_fish_rematch_won_1 = {"Aquele que", "escapou..."},
            fb_bl_fish_rematch_lost_1 = {"De volta ao meu", "anzol, peixinho?"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Mas eu sou", "O Psíquico"},
            fb_bl_psychic_intro_1 = {"Odeio jogadores", "indecisos"},
            fb_bl_psychic_intro_2 = {"Cinco cartas, nem", "menos. Eu previ."},
            fb_bl_psychic_big_hand_1 = {"Isso eu NÃO", "previ."},
            fb_bl_psychic_close_1 = {"Minha bola de cristal", "mostra... derrota!"},
            fb_bl_psychic_last_hand_1 = {"Prevejo a sua", "última mão."},
            fb_bl_psychic_disabled_1 = {"Minhas visões!", "Sumiram!"},
            fb_bl_psychic_defeat_1 = {"Eu previ isso.", "...Ou não?"},
            fb_bl_psychic_gloat_1 = {"Eu já sabia!"},
            fb_bl_psychic_interrupted_1 = {"Eu sabia que você", "faria isso. Grosso."},
            fb_bl_psychic_rematch_won_1 = {"Não previ sua", "última vitória."},
            fb_bl_psychic_rematch_lost_1 = {"Eu sabia que", "você voltaria."},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Mas eu sou", "Aguilhão"},
            fb_bl_goad_intro_1 = {"Odeio o", "{C:black,E:1}PODER{}"},
            fb_bl_goad_intro_2 = {"Espadas debilitadas.", "Cave mais fundo."},
            fb_bl_goad_big_hand_1 = {"Nada mal sem as", "suas espadas."},
            fb_bl_goad_close_1 = {"Não se atreva a", "cavar minha cova!"},
            fb_bl_goad_last_hand_1 = {"Cave fundo. É sua", "última mão."},
            fb_bl_goad_disabled_1 = {"Agora não consigo", "instigar ninguém!"},
            fb_bl_goad_defeat_1 = {"Maldição,", "você venceu."},
            fb_bl_goad_gloat_1 = {"Cave sua", "própria cova!"},
            fb_bl_goad_interrupted_1 = {"Me provocando?", "Muito bem!"},
            fb_bl_goad_rematch_won_1 = {"Da última vez você", "saiu da cova."},
            fb_bl_goad_rematch_lost_1 = {"Voltou pra cavar", "uma cova mais funda?"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Mas eu sou", "A Água"},
            fb_bl_water_intro_1 = {"Me dê os seus", "descartes"},
            fb_bl_water_intro_2 = {"Sem descartes.", "Nem uma gota."},
            fb_bl_water_big_hand_1 = {"Sem descartes e", "ainda ganhou?!"},
            fb_bl_water_close_1 = {"Estou me afogando!", "Joguem uma corda!"},
            fb_bl_water_last_hand_1 = {"Última mão. Nade", "ou afunde."},
            fb_bl_water_disabled_1 = {"Os descartes voltam", "a fluir!"},
            fb_bl_water_defeat_1 = {"Estou todo seco..."},
            fb_bl_water_gloat_1 = {"Foi por água", "abaixo!"},
            fb_bl_water_interrupted_1 = {"Me interromper? Agora", "você está afundando!"},
            fb_bl_water_rematch_won_1 = {"Da última vez você", "ficou à tona."},
            fb_bl_water_rematch_lost_1 = {"Voltou pra levar", "outro caldo?"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Mas eu sou", "A Janela"},
            fb_bl_window_intro_1 = {"Odeio o", "{C:yellow,E:1}capitalismo{}"},
            fb_bl_window_intro_2 = {"Ouros debilitados.", "Continue brilhando."},
            fb_bl_window_big_hand_1 = {"Quem precisa de", "ouros?"},
            fb_bl_window_close_1 = {"Não quebre", "minha janela!"},
            fb_bl_window_last_hand_1 = {"Última mão. Brilho", "proibido."},
            fb_bl_window_disabled_1 = {"Minha janela rachou!", "Ouros brilham!"},
            fb_bl_window_defeat_1 = {"Minha janela de", "oportunidade fechou."},
            fb_bl_window_gloat_1 = {"Ouros?", "Debilitados!"},
            fb_bl_window_interrupted_1 = {"Minhas palavras vão", "pela janela?!"},
            fb_bl_window_rematch_won_1 = {"Você quebrou minha", "janela uma vez."},
            fb_bl_window_rematch_lost_1 = {"Olhando vitrines", "de novo?"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Mas eu sou", "As Algemas"},
            fb_bl_manacle_intro_1 = {"Vou levar as suas", "{C:blue,E:1}opções{}"},
            fb_bl_manacle_intro_2 = {"Uma carta a menos", "na sua mão."},
            fb_bl_manacle_big_hand_1 = {"Algemado e ainda", "ganhando?!"},
            fb_bl_manacle_close_1 = {"Você está se soltando", "das correntes!"},
            fb_bl_manacle_last_hand_1 = {"Última mão. E ainda", "por cima, algemado."},
            fb_bl_manacle_disabled_1 = {"As algemas!", "Soltaram!"},
            fb_bl_manacle_defeat_1 = {"Livre enfim...", "de mim."},
            fb_bl_manacle_gloat_1 = {"Mãos ao alto!"},
            fb_bl_manacle_interrupted_1 = {"Alto lá! Vou te", "acorrentar por isso!"},
            fb_bl_manacle_rematch_won_1 = {"Uma vez você escapou", "das minhas correntes."},
            fb_bl_manacle_rematch_lost_1 = {"De volta às", "correntes, hein?"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Mas eu sou", "O Olho"},
            fb_bl_eye_intro_1 = {"Não gosto de", "rotina"},
            fb_bl_eye_intro_2 = {"Nunca o mesmo tipo de", "mão duas vezes."},
            fb_bl_eye_big_hand_1 = {"Uma mão nova?", "Estou de olho."},
            fb_bl_eye_close_1 = {"Não consigo", "olhar!"},
            fb_bl_eye_last_hand_1 = {"Estou de olho na", "sua última mão."},
            fb_bl_eye_disabled_1 = {"Meu olho! Quem", "me cutucou?!"},
            fb_bl_eye_defeat_1 = {"Longe dos olhos,", "longe do coração..."},
            fb_bl_eye_gloat_1 = {"Eu avisei!"},
            fb_bl_eye_interrupted_1 = {"Eu vi isso!", "Que grosseria."},
            fb_bl_eye_rematch_won_1 = {"Eu te vigio desde", "aquela derrota."},
            fb_bl_eye_rematch_lost_1 = {"Vejo que", "você voltou."},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Mas eu sou", "A Boca"},
            fb_bl_mouth_intro_1 = {"Adoro", "rotina"},
            fb_bl_mouth_intro_2 = {"Escolha um tipo de mão", "e fique nele."},
            fb_bl_mouth_big_hand_1 = {"A mesma velha mão,", "ainda forte..."},
            fb_bl_mouth_close_1 = {"Minha boca está", "escancarada!"},
            fb_bl_mouth_last_hand_1 = {"Última mão. Mesmo", "tipo. Boca fechada."},
            fb_bl_mouth_disabled_1 = {"Quem me", "amordaçou?!"},
            fb_bl_mouth_defeat_1 = {"Estou sem palavras..."},
            fb_bl_mouth_gloat_1 = {"Cala a boca,", "perdedor!"},
            fb_bl_mouth_interrupted_1 = {"Ei! Esta boca", "ainda falava!"},
            fb_bl_mouth_rematch_won_1 = {"Da última vez você", "me calou a boca."},
            fb_bl_mouth_rematch_lost_1 = {"A mesma rotina", "da última vez?"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Mas eu sou", "A Planta"},
            fb_bl_plant_intro_1 = {"Odeio rostos", "amigáveis"},
            fb_bl_plant_intro_2 = {"Reis, damas, valetes:", "todos debilitados."},
            fb_bl_plant_big_hand_1 = {"Sem figuras?!", "Inacreditável."},
            fb_bl_plant_close_1 = {"Não me arranque", "pelas raízes!"},
            fb_bl_plant_last_hand_1 = {"Encare a sua", "última mão."},
            fb_bl_plant_disabled_1 = {"Minhas pétalas!", "Sumiram todas!"},
            fb_bl_plant_defeat_1 = {"Murchei...", "Vou crescer de novo."},
            fb_bl_plant_gloat_1 = {"Encare: você perdeu!"},
            fb_bl_plant_interrupted_1 = {"Me deixe crescer", "primeiro, apressado!"},
            fb_bl_plant_rematch_won_1 = {"Você me arrancou.", "Eu cresci de novo."},
            fb_bl_plant_rematch_lost_1 = {"De volta ao meu", "jardim, hein?"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Mas eu sou", "A Serpente"},
            fb_bl_serpent_intro_1 = {"Existe", "um déficit"},
            fb_bl_serpent_intro_2 = {"Jogue ou descarte,", "só compra 3."},
            fb_bl_serpent_big_hand_1 = {"Três cartas. E você", "ainda acertou!"},
            fb_bl_serpent_close_1 = {"Não se enrosque", "agora!"},
            fb_bl_serpent_last_hand_1 = {"Último bote.", "Três cartas."},
            fb_bl_serpent_disabled_1 = {"Minhas presas! Sss...", "Sem veneno!"},
            fb_bl_serpent_defeat_1 = {"Troquei de pele...", "e perdi o orgulho."},
            fb_bl_serpent_gloat_1 = {"Sss-aia daí!"},
            fb_bl_serpent_interrupted_1 = {"Sss! Não me", "interrompa!"},
            fb_bl_serpent_rematch_won_1 = {"Uma vez você escapou", "dos meus anéis."},
            fb_bl_serpent_rematch_lost_1 = {"Sssurpresa...", "você voltou."},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Mas eu sou", "O Pilar"},
            fb_bl_pillar_intro_1 = {"Aprendi muito com", "suas mãos passadas"},
            fb_bl_pillar_intro_2 = {"Cartas jogadas ficam", "debilitadas nesta Aposta."},
            fb_bl_pillar_big_hand_1 = {"Cartas novas?", "Esperto."},
            fb_bl_pillar_close_1 = {"Meu pilar está", "ruindo!"},
            fb_bl_pillar_last_hand_1 = {"Última mão. Cartas", "velhas não servem."},
            fb_bl_pillar_disabled_1 = {"Minha memória!", "Está... sumindo."},
            fb_bl_pillar_defeat_1 = {"Um pilar da", "comunidade caiu."},
            fb_bl_pillar_gloat_1 = {"Ainda de pé!"},
            fb_bl_pillar_interrupted_1 = {"Nenhum respeito", "pelos mais velhos?"},
            fb_bl_pillar_rematch_won_1 = {"Eu lembro como", "você me venceu."},
            fb_bl_pillar_rematch_lost_1 = {"Eu lembro como", "você perdeu."},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Mas eu sou", "A Agulha"},
            fb_bl_needle_intro_1 = {"Você só tem", "uma chance"},
            fb_bl_needle_intro_2 = {"Uma mão. É tudo", "o que você ganha."},
            fb_bl_needle_big_hand_1 = {"Uma única mão,", "tão forte?!"},
            fb_bl_needle_close_1 = {"Não! Não com", "uma mão!"},
            fb_bl_needle_last_hand_1 = {"Esta mão é a sua", "única mão."},
            fb_bl_needle_disabled_1 = {"Minha agulha!", "Está cega!"},
            fb_bl_needle_defeat_1 = {"Jogada afiada.", "Você me pegou."},
            fb_bl_needle_gloat_1 = {"Ponto final!", "Você perdeu!"},
            fb_bl_needle_interrupted_1 = {"Que alfinetada.", "Eu não terminei!"},
            fb_bl_needle_rematch_won_1 = {"Uma mão só me venceu", "da última vez."},
            fb_bl_needle_rematch_lost_1 = {"Uma chance de novo.", "Vai errar de novo?"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Mas eu sou", "A Cabeça"},
            fb_bl_head_intro_1 = {"Odeio os", "{C:red,E:1}apaixonados{}"},
            fb_bl_head_intro_2 = {"Copas debilitadas.", "Frio, não é?"},
            fb_bl_head_big_hand_1 = {"Você ganhou sem", "coração?!"},
            fb_bl_head_close_1 = {"Tenha coração,", "não me acabe!"},
            fb_bl_head_last_hand_1 = {"Última mão. Sem", "copas. Sem piedade."},
            fb_bl_head_disabled_1 = {"Minha cabeça dói!", "Copas voltaram?"},
            fb_bl_head_defeat_1 = {"Perdi a cabeça...", "por você."},
            fb_bl_head_gloat_1 = {"Sem coração, né?"},
            fb_bl_head_interrupted_1 = {"Perdeu a cabeça?", "Estou falando!"},
            fb_bl_head_rematch_won_1 = {"Você ganhou meu", "coração... uma vez."},
            fb_bl_head_rematch_lost_1 = {"Voltou pra outro", "coração partido?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Mas eu sou", "O Dente"},
            fb_bl_tooth_intro_1 = {"Eu curto", "política"},
            fb_bl_tooth_intro_2 = {"Cada carta que você", "joga custa $1."},
            fb_bl_tooth_big_hand_1 = {"Pagou e ainda", "ganhou?!"},
            fb_bl_tooth_close_1 = {"Não me faça pagar", "a fada do dente!"},
            fb_bl_tooth_last_hand_1 = {"Última mão,", "últimos dólares."},
            fb_bl_tooth_disabled_1 = {"Minha mordida!", "Sumiu!"},
            fb_bl_tooth_defeat_1 = {"Com unhas e dentes,", "perdi."},
            fb_bl_tooth_gloat_1 = {"Pague, otário!"},
            fb_bl_tooth_interrupted_1 = {"Grr! Você vai", "pagar por isso!"},
            fb_bl_tooth_rematch_won_1 = {"Você ainda me deve", "da última vez."},
            fb_bl_tooth_rematch_lost_1 = {"Voltou pra pagar", "sua dívida?"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Mas eu sou", "A Pederneira"},
            fb_bl_flint_intro_1 = {"Você deve", "pagar impostos"},
            fb_bl_flint_intro_2 = {"Fichas e Multi", "pela metade."},
            fb_bl_flint_big_hand_1 = {"Metade do poder,", "e ainda acerta?!"},
            fb_bl_flint_close_1 = {"Você está faiscando", "a minha queda!"},
            fb_bl_flint_last_hand_1 = {"Última mão. Metade", "da faísca."},
            fb_bl_flint_disabled_1 = {"Poder total?!", "Não é justo!"},
            fb_bl_flint_defeat_1 = {"Minha faísca", "se apagou."},
            fb_bl_flint_gloat_1 = {"Metade da", "diversão!"},
            fb_bl_flint_interrupted_1 = {"Sem faíscas!", "Eu estava falando!"},
            fb_bl_flint_rematch_won_1 = {"Da última vez você", "sonegou meus impostos."},
            fb_bl_flint_rematch_lost_1 = {"Época de impostos", "de novo. Pague."},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Mas eu sou", "A Marca"},
            fb_bl_mark_intro_1 = {"Não gosto de", "ser vista"},
            fb_bl_mark_intro_2 = {"Todas as figuras", "chegam viradas."},
            fb_bl_mark_big_hand_1 = {"Cartas marcadas e", "ainda ganhou?!"},
            fb_bl_mark_close_1 = {"Estou marcada", "para a derrota!"},
            fb_bl_mark_last_hand_1 = {"Última mão. Escolha", "rostos às cegas."},
            fb_bl_mark_disabled_1 = {"Os rostos!", "Estou vendo!"},
            fb_bl_mark_defeat_1 = {"Você deixou sua", "marca em mim."},
            fb_bl_mark_gloat_1 = {"Marcado para", "perder!"},
            fb_bl_mark_interrupted_1 = {"Anotado. Agora", "você está marcado."},
            fb_bl_mark_rematch_won_1 = {"Da última vez você", "me desmascarou."},
            fb_bl_mark_rematch_lost_1 = {"Ainda não consegue", "ver meus rostos?"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Mas eu sou", "Semente Dourada"},
            fb_bl_final_acorn_intro_1 = {"Eu gosto de", "CAOS!"},
            fb_bl_final_acorn_intro_2 = {"Curingas virados,", "depois embaralhados!"},
            fb_bl_final_acorn_big_hand_1 = {"Até no caos", "você ganha?!"},
            fb_bl_final_acorn_close_1 = {"Isso é uma loucura!", "Estou rachando!"},
            fb_bl_final_acorn_last_hand_1 = {"Última mão. Onde", "está seu curinga?"},
            fb_bl_final_acorn_disabled_1 = {"Minha semente!", "A ordem voltou?!"},
            fb_bl_final_acorn_defeat_1 = {"Você quebrou", "minha casca..."},
            fb_bl_final_acorn_gloat_1 = {"Uma casca de noz!"},
            fb_bl_final_acorn_interrupted_1 = {"Calma! Eu nem", "brotei ainda!"},
            fb_bl_final_acorn_phase2_1 = {"Agora a coisa", "fica LOUCA!"},
            fb_bl_final_acorn_phase3_1 = {"Caos total!", "Fora a casca!"},
            fb_bl_final_acorn_rematch_won_1 = {"Você me rachou uma", "vez. Nunca mais!"},
            fb_bl_final_acorn_rematch_lost_1 = {"Voltou pra mais", "CAOS?"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Mas eu sou", "Folha Verdejante"},
            fb_bl_final_leaf_intro_1 = {"Você deve se soltar", "das suas raízes"},
            fb_bl_final_leaf_intro_2 = {"Venda um curinga ou", "fique debilitado."},
            fb_bl_final_leaf_big_hand_1 = {"Você virou a", "página. Hmph."},
            fb_bl_final_leaf_close_1 = {"Minha folha", "está caindo!"},
            fb_bl_final_leaf_last_hand_1 = {"Última mão. Vender", "um curinga?"},
            fb_bl_final_leaf_disabled_1 = {"Minha folha!", "Secou!"},
            fb_bl_final_leaf_defeat_1 = {"Estou indo...", "como uma folha."},
            fb_bl_final_leaf_gloat_1 = {"Folheou, perdeu!"},
            fb_bl_final_leaf_interrupted_1 = {"Tudo bem. Pule as", "formalidades."},
            fb_bl_final_leaf_phase2_1 = {"Minhas raízes", "vão mais fundo!"},
            fb_bl_final_leaf_phase3_1 = {"Murche comigo!"},
            fb_bl_final_leaf_rematch_won_1 = {"Você se desapegou uma", "vez. Tente de novo."},
            fb_bl_final_leaf_rematch_lost_1 = {"Ainda preso", "aos seus curingas?"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Mas eu sou", "Recipiente Roxo"},
            fb_bl_final_vessel_intro_1 = {"Você acabou de bater", "na grande muralha"},
            fb_bl_final_vessel_intro_2 = {"Uma blind enorme.", "Navegue!"},
            fb_bl_final_vessel_big_hand_1 = {"Um golpe enorme em", "um alvo enorme."},
            fb_bl_final_vessel_close_1 = {"Abandonar o navio!", "...O meu, quero dizer."},
            fb_bl_final_vessel_last_hand_1 = {"Última mão. Este", "navio não afunda."},
            fb_bl_final_vessel_disabled_1 = {"Meu recipiente!", "Está afundando!"},
            fb_bl_final_vessel_defeat_1 = {"O recipiente...", "foi esvaziado."},
            fb_bl_final_vessel_gloat_1 = {"Derrota vazia!"},
            fb_bl_final_vessel_interrupted_1 = {"Zarpar antes do meu", "discurso? Ousado."},
            fb_bl_final_vessel_phase2_1 = {"Encham o porão!"},
            fb_bl_final_vessel_phase3_1 = {"Todos ao", "fundo do mar!"},
            fb_bl_final_vessel_rematch_won_1 = {"Você me afundou uma", "vez. Fui reformado."},
            fb_bl_final_vessel_rematch_lost_1 = {"Voltou pra se afogar", "no meu rastro?"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Mas eu sou", "Coração Rubro"},
            fb_bl_final_heart_intro_1 = {"Vou pegar um", "curinga emprestado"},
            fb_bl_final_heart_intro_2 = {"Cada mão, um curinga", "perde o poder."},
            fb_bl_final_heart_big_hand_1 = {"Um curinga a menos e", "ainda forte?"},
            fb_bl_final_heart_close_1 = {"Não quebre", "meu coração!"},
            fb_bl_final_heart_last_hand_1 = {"Última mão. Qual", "curinga está mudo?"},
            fb_bl_final_heart_disabled_1 = {"Meu coração! Falhou", "uma batida."},
            fb_bl_final_heart_defeat_1 = {"Meu coração...", "está partido."},
            fb_bl_final_heart_gloat_1 = {"Coração partido?"},
            fb_bl_final_heart_interrupted_1 = {"Me interromper?", "Que sem coração!"},
            fb_bl_final_heart_phase2_1 = {"Meu coração", "bate mais rápido!"},
            fb_bl_final_heart_phase3_1 = {"Sinta minha", "fúria carmesim!"},
            fb_bl_final_heart_rematch_won_1 = {"Da última vez você", "partiu meu coração."},
            fb_bl_final_heart_rematch_lost_1 = {"Meu coração ainda", "bate por você."},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Mas eu sou", "Sino Cerúleo"},
            fb_bl_final_bell_intro_1 = {"Eu gostaria de", "guiar você"},
            fb_bl_final_bell_intro_2 = {"Uma carta é forçada", "em toda mão."},
            fb_bl_final_bell_big_hand_1 = {"Você fez minha carta", "forçada tocar?!"},
            fb_bl_final_bell_close_1 = {"O sino toca...", "por mim?!"},
            fb_bl_final_bell_last_hand_1 = {"Última mão. Uma", "carta é forçada."},
            fb_bl_final_bell_disabled_1 = {"Meu sino está mudo!", "Trapaceiro!"},
            fb_bl_final_bell_defeat_1 = {"O sino toca", "por mim."},
            fb_bl_final_bell_gloat_1 = {"Blém blém, perdeu!"},
            fb_bl_final_bell_interrupted_1 = {"Salvo pelo gongo?", "Não desta vez!"},
            fb_bl_final_bell_phase2_1 = {"Ouça-me tocar", "mais alto!"},
            fb_bl_final_bell_phase3_1 = {"O último badalo!"},
            fb_bl_final_bell_rematch_won_1 = {"Da última vez você", "me fez badalar."},
            fb_bl_final_bell_rematch_lost_1 = {"O sino dobra por", "você de novo."},
        }
    }
}
