return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "Поединки",
            fb_cfg_dialogue = "Диалоги боссов",
            fb_cfg_music = "Музыка поединков",
            fb_cfg_fx = "Эффекты экрана",
            fb_cfg_cinematic = "Сцены поединков",
            fb_showdown_title = "ПОЕДИНОК",
            fb_cfg_intro_speed = "Скорость заставки",
            fb_speed_slow = "Медленно",
            fb_speed_normal = "Обычно",
            fb_speed_fast = "Быстро",
            fb_cfg_min_ante = "Диалоги боссов с анте",
            fb_cfg_dev_mode = "Клавиши разработчика (F5-F7)",
            fb_cfg_showdown_enabled = "Свое расписание поединков",
            fb_cfg_start_ante = "Первый поединок на анте",
            fb_cfg_every = "Затем каждые N анте",
            fb_cfg_preview = "Поединки на анте:",
            fb_cfg_hard = "Сложно! Ранние поединки жестоки.",
            fb_cfg_next_ante = "Изменения вступят со следующего анте.",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"Ты зашел слишком", "далеко..."},
            fb_opener_2 = {"И, к сожалению,", "должен сказать..."},
            fb_opener_3 = {"Что ж. Ты", "добрался."},
            fb_closer_1 = {"Тебе не победить", "меня."},
            fb_closer_2 = {"Здесь твой забег", "заканчивается."},
            fb_closer_3 = {"Покажи, на что", "ты способен."},
            fb_gloat = {"Этот босс был", "слишком силен..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"Я #1#!"},
            fb_generic_name_2 = {"Меня зовут", "#1#."},
            fb_generic_name_3 = {"Узри:", "#1#!"},
            fb_generic_intro_1 = {"Твоя удача", "здесь кончается."},
            fb_generic_intro_2 = {"Посмотрим, как ты", "справишься."},
            fb_generic_intro_3 = {"Читай мои правила", "внимательно..."},
            fb_generic_big_hand_1 = {"...Неплохо."},
            fb_generic_big_hand_2 = {"Везучая рука."},
            fb_generic_big_hand_3 = {"Хм. Опять?"},
            fb_generic_close_1 = {"Постой, постой,", "ПОСТОЙ!"},
            fb_generic_close_2 = {"Не смей..."},
            fb_generic_close_3 = {"Это невозможно..."},
            fb_generic_last_hand_1 = {"Одна рука осталась.", "Не промахнись."},
            fb_generic_last_hand_2 = {"Тик-так..."},
            fb_generic_last_hand_3 = {"Последний шанс,", "малыш-джокер."},
            fb_generic_disabled_1 = {"Моя сила...!", "Что ты сделал?"},
            fb_generic_disabled_2 = {"Эй! Это", "жульничество!"},
            fb_generic_disabled_3 = {"Я чувствую...", "слабость."},
            fb_generic_defeat_1 = {"Невозможно..."},
            fb_generic_defeat_2 = {"Я вернусь на", "следующем анте..."},
            fb_generic_defeat_3 = {"Хорошо сыграно..."},
            fb_generic_gloat_1 = {"Этот босс был", "слишком силен..."},
            fb_generic_gloat_2 = {"Казино", "всегда в плюсе."},
            fb_generic_gloat_3 = {"Удачи в", "следующем забеге."},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"Но я", "Крюк"},
            fb_bl_hook_intro_1 = {"Я заберу несколько", "твоих карт"},
            fb_bl_hook_intro_2 = {"Две карты долой", "с каждой руки."},
            fb_bl_hook_big_hand_1 = {"Даже с меньшим", "числом карт?!"},
            fb_bl_hook_close_1 = {"Брось эти", "карты!"},
            fb_bl_hook_last_hand_1 = {"Наконец-то ты", "на крючке!"},
            fb_bl_hook_disabled_1 = {"Мой крюк!", "Он сломан!"},
            fb_bl_hook_defeat_1 = {"Ладно... сниму", "тебя с крючка."},
            fb_bl_hook_gloat_1 = {"Попался на крючок!"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"Но я", "Буйвол"},
            fb_bl_ox_intro_1 = {"Я заберу все", "твои деньги"},
            fb_bl_ox_intro_2 = {"Любимая рука", "стоит тебе всего."},
            fb_bl_ox_big_hand_1 = {"Без гроша и", "все равно побеждаешь?!"},
            fb_bl_ox_close_1 = {"Не гони лошадей!", "...Я тоже."},
            fb_bl_ox_last_hand_1 = {"Последняя рука.", "Трать или теряй."},
            fb_bl_ox_disabled_1 = {"Мои рога!", "Они затупились!"},
            fb_bl_ox_defeat_1 = {"Ты взял быка", "за рога..."},
            fb_bl_ox_gloat_1 = {"Теперь ты банкрот!"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"Но я", "Дом"},
            fb_bl_house_intro_1 = {"Ты", "СЛЕП!"},
            fb_bl_house_intro_2 = {"Первая рука за счет", "заведения. Вслепую!"},
            fb_bl_house_big_hand_1 = {"Слепая удача, а ты", "все равно выиграл?!"},
            fb_bl_house_close_1 = {"Дом никогда", "не проигрывает!"},
            fb_bl_house_last_hand_1 = {"Больше никакой", "слепой удачи."},
            fb_bl_house_disabled_1 = {"Моя повязка!", "Она упала!"},
            fb_bl_house_defeat_1 = {"Дом...", "рухнул."},
            fb_bl_house_gloat_1 = {"Дом выигрывает!"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"Но я", "Стена"},
            fb_bl_wall_intro_1 = {"Ты только что", "врезался в нее"},
            fb_bl_wall_intro_2 = {"Попробуй взобраться", "на этот счет."},
            fb_bl_wall_big_hand_1 = {"Ты перелез", "через мою стену?!"},
            fb_bl_wall_close_1 = {"Тебе не", "пробить меня!"},
            fb_bl_wall_last_hand_1 = {"Больше некуда", "взбираться."},
            fb_bl_wall_disabled_1 = {"Трещины! Моя стена", "трескается!"},
            fb_bl_wall_defeat_1 = {"Стена...", "рушится."},
            fb_bl_wall_gloat_1 = {"Уперся в стену!"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"Но я", "Колесо"},
            fb_bl_wheel_intro_1 = {"Я люблю...", "АЗАРТ!"},
            fb_bl_wheel_intro_2 = {"Каждая седьмая карта", "ложится рубашкой."},
            fb_bl_wheel_big_hand_1 = {"Госпожа Удача", "сегодня с тобой."},
            fb_bl_wheel_close_1 = {"Мое колесо", "слетает с оси!"},
            fb_bl_wheel_last_hand_1 = {"Последний оборот.", "Чувствуешь удачу?"},
            fb_bl_wheel_disabled_1 = {"Колесо встало?", "Подстроено!"},
            fb_bl_wheel_defeat_1 = {"Колесо фортуны", "повернулось против меня."},
            fb_bl_wheel_gloat_1 = {"Колесо", "повернулось!"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"Но я", "Рука"},
            fb_bl_arm_intro_1 = {"Я уравновешу", "твою силу"},
            fb_bl_arm_intro_2 = {"Каждая сыгранная рука", "теряет уровень."},
            fb_bl_arm_big_hand_1 = {"У этой руки", "есть мускулы..."},
            fb_bl_arm_close_1 = {"Армрестлинг?", "Я проигрываю!"},
            fb_bl_arm_last_hand_1 = {"Последняя рука.", "Не напрягайся."},
            fb_bl_arm_disabled_1 = {"Моя рука обмякла!", "Жулик!"},
            fb_bl_arm_defeat_1 = {"Ты победил мою", "сильную руку."},
            fb_bl_arm_gloat_1 = {"Руки опустились!"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"Но я", "Трефа"},
            fb_bl_club_intro_1 = {"Ненавижу", "{C:green,E:1}везунчиков{}"},
            fb_bl_club_intro_2 = {"Трефы ослаблены.", "Извини."},
            fb_bl_club_big_hand_1 = {"Без треф и", "никаких проблем?!"},
            fb_bl_club_close_1 = {"Не бей меня", "этим!"},
            fb_bl_club_last_hand_1 = {"Последняя рука.", "Оставь трефы дома."},
            fb_bl_club_disabled_1 = {"Мои трефы", "потеряли хватку!"},
            fb_bl_club_defeat_1 = {"Клуб закрыт.", "Пора уходить..."},
            fb_bl_club_gloat_1 = {"Получи дубинкой!"},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"Но я", "Рыба"},
            fb_bl_fish_intro_1 = {"Будь уверен, что", "хочешь сыграть"},
            fb_bl_fish_intro_2 = {"После каждой руки", "карты рубашкой вверх."},
            fb_bl_fish_big_hand_1 = {"Что-то тут нечисто", "с этой рукой!"},
            fb_bl_fish_close_1 = {"Не вытаскивай", "меня на берег!"},
            fb_bl_fish_last_hand_1 = {"Последний заброс.", "Тяни леску."},
            fb_bl_fish_disabled_1 = {"Моя чешуя!", "Она слетела!"},
            fb_bl_fish_defeat_1 = {"Поймана...", "профессионалом."},
            fb_bl_fish_gloat_1 = {"Ты сел на мель!"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"Но я", "Экстрасенс"},
            fb_bl_psychic_intro_1 = {"Ненавижу", "нерешительных"},
            fb_bl_psychic_intro_2 = {"Пять карт, не меньше.", "Я это предвидел."},
            fb_bl_psychic_big_hand_1 = {"Этого я НЕ", "предвидел."},
            fb_bl_psychic_close_1 = {"Мой шар показывает...", "поражение!"},
            fb_bl_psychic_last_hand_1 = {"Я вижу твою", "последнюю руку."},
            fb_bl_psychic_disabled_1 = {"Мои видения!", "Они пропали!"},
            fb_bl_psychic_defeat_1 = {"Я это предвидел.", "...Или нет?"},
            fb_bl_psychic_gloat_1 = {"Я так и знал!"},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"Но я", "Побуждение"},
            fb_bl_goad_intro_1 = {"Ненавижу", "{C:black,E:1}ВЛАСТЬ{}"},
            fb_bl_goad_intro_2 = {"Пики ослаблены.", "Копай глубже."},
            fb_bl_goad_big_hand_1 = {"Неплохо и без", "твоих пик."},
            fb_bl_goad_close_1 = {"Не смей копать", "мне могилу!"},
            fb_bl_goad_last_hand_1 = {"Копай глубже. Это", "твоя последняя рука."},
            fb_bl_goad_disabled_1 = {"Теперь я никого", "не подзадорю!"},
            fb_bl_goad_defeat_1 = {"Черт возьми,", "ты победил."},
            fb_bl_goad_gloat_1 = {"Копай себе могилу!"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"Но я", "Вода"},
            fb_bl_water_intro_1 = {"Отдай мне", "свои сбросы"},
            fb_bl_water_intro_2 = {"Ни одного сброса.", "Ни капли."},
            fb_bl_water_big_hand_1 = {"Без сбросов и все", "равно победа?!"},
            fb_bl_water_close_1 = {"Я тону!", "Бросьте веревку!"},
            fb_bl_water_last_hand_1 = {"Последняя рука.", "Плыви или тони."},
            fb_bl_water_disabled_1 = {"Сбросы снова", "текут!"},
            fb_bl_water_defeat_1 = {"Я совсем", "высохла..."},
            fb_bl_water_gloat_1 = {"Ты смыт!"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"Но я", "Окно"},
            fb_bl_window_intro_1 = {"Ненавижу", "{C:yellow,E:1}капитализм{}"},
            fb_bl_window_intro_2 = {"Бубны ослаблены.", "Продолжай сиять."},
            fb_bl_window_big_hand_1 = {"Кому вообще", "нужны бубны?"},
            fb_bl_window_close_1 = {"Не разбей", "мое окно!"},
            fb_bl_window_last_hand_1 = {"Последняя рука.", "Блеск запрещен."},
            fb_bl_window_disabled_1 = {"Мое окно треснуло!", "Бубны сияют!"},
            fb_bl_window_defeat_1 = {"Мое окно", "возможностей закрылось."},
            fb_bl_window_gloat_1 = {"Бубны? Ослаблены!"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"Но я", "Кандалы"},
            fb_bl_manacle_intro_1 = {"Я заберу твои", "{C:blue,E:1}варианты{}"},
            fb_bl_manacle_intro_2 = {"На одну карту", "меньше в руке."},
            fb_bl_manacle_big_hand_1 = {"В кандалах и все", "равно побеждаешь?!"},
            fb_bl_manacle_close_1 = {"Ты сбрасываешь", "мои оковы!"},
            fb_bl_manacle_last_hand_1 = {"Последняя рука. Да", "еще и в кандалах."},
            fb_bl_manacle_disabled_1 = {"Кандалы!", "Они спали!"},
            fb_bl_manacle_defeat_1 = {"Наконец свободен...", "от меня."},
            fb_bl_manacle_gloat_1 = {"Руки в наручниках!"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"Но я", "Глаз"},
            fb_bl_eye_intro_1 = {"Не люблю", "рутину"},
            fb_bl_eye_intro_2 = {"Никогда не играй один", "тип руки дважды."},
            fb_bl_eye_big_hand_1 = {"Новая рука? Я", "слежу за тобой."},
            fb_bl_eye_close_1 = {"Я не могу", "на это смотреть!"},
            fb_bl_eye_last_hand_1 = {"Я вижу твою", "последнюю руку."},
            fb_bl_eye_disabled_1 = {"Мой глаз! Кто мне", "в него ткнул?!"},
            fb_bl_eye_defeat_1 = {"С глаз долой,", "из сердца вон..."},
            fb_bl_eye_gloat_1 = {"Я же говорил!"},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"Но я", "Пасть"},
            fb_bl_mouth_intro_1 = {"Обожаю", "рутину"},
            fb_bl_mouth_intro_2 = {"Выбери один тип руки", "и держись его."},
            fb_bl_mouth_big_hand_1 = {"Все та же рука,", "все еще сильна..."},
            fb_bl_mouth_close_1 = {"Моя пасть", "широко раскрыта!"},
            fb_bl_mouth_last_hand_1 = {"Последняя рука. Тот же", "тип. Молчи."},
            fb_bl_mouth_disabled_1 = {"Кто надел на меня", "намордник?!"},
            fb_bl_mouth_defeat_1 = {"У меня нет слов..."},
            fb_bl_mouth_gloat_1 = {"Заткнись,", "неудачник!"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"Но я", "Цветок"},
            fb_bl_plant_intro_1 = {"Ненавижу", "дружелюбные лица"},
            fb_bl_plant_intro_2 = {"Короли, дамы, валеты:", "все ослаблены."},
            fb_bl_plant_big_hand_1 = {"Без картинок?!", "Невероятно."},
            fb_bl_plant_close_1 = {"Не вырывай меня", "с корнем!"},
            fb_bl_plant_last_hand_1 = {"Взгляни в лицо", "последней руке."},
            fb_bl_plant_disabled_1 = {"Мои лепестки!", "Все пропали!"},
            fb_bl_plant_defeat_1 = {"Увял...", "Я отрасту снова."},
            fb_bl_plant_gloat_1 = {"Взгляни правде", "в лицо!"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"Но я", "Змей"},
            fb_bl_serpent_intro_1 = {"Есть", "дефицит"},
            fb_bl_serpent_intro_2 = {"Сыграл или сбросил,", "берешь только 3."},
            fb_bl_serpent_big_hand_1 = {"Три карты. И ты", "все равно ударил!"},
            fb_bl_serpent_close_1 = {"Не уползай", "сейчас!"},
            fb_bl_serpent_last_hand_1 = {"Последний укус.", "Три карты."},
            fb_bl_serpent_disabled_1 = {"Мои клыки! Ссс...", "Яда больше нет!"},
            fb_bl_serpent_defeat_1 = {"Сбросил кожу...", "и гордость."},
            fb_bl_serpent_gloat_1 = {"До ссс-видания!"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"Но я", "Столп"},
            fb_bl_pillar_intro_1 = {"Я многому научился", "на твоих руках"},
            fb_bl_pillar_intro_2 = {"Сыгранные карты", "ослаблены на этом анте."},
            fb_bl_pillar_big_hand_1 = {"Свежие карты?", "Умно."},
            fb_bl_pillar_close_1 = {"Мой столп", "рушится!"},
            fb_bl_pillar_last_hand_1 = {"Последняя рука.", "Старые карты бесполезны."},
            fb_bl_pillar_disabled_1 = {"Моя память!", "Она... гаснет."},
            fb_bl_pillar_defeat_1 = {"Столп общества", "пал."},
            fb_bl_pillar_gloat_1 = {"Все еще стою!"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"Но я", "Игла"},
            fb_bl_needle_intro_1 = {"У тебя только", "один шанс"},
            fb_bl_needle_intro_2 = {"Одна рука. Это все,", "что ты получишь."},
            fb_bl_needle_big_hand_1 = {"Одна-единственная", "рука, и такая сильная?!"},
            fb_bl_needle_close_1 = {"Нет! Не одной", "рукой!"},
            fb_bl_needle_last_hand_1 = {"Эта рука", "твоя единственная."},
            fb_bl_needle_disabled_1 = {"Моя игла!", "Она затупилась!"},
            fb_bl_needle_defeat_1 = {"Острая игра.", "Ты меня достал."},
            fb_bl_needle_gloat_1 = {"Уколола тебя!"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"Но я", "Голова"},
            fb_bl_head_intro_1 = {"Ненавижу", "{C:red,E:1}влюбленных{}"},
            fb_bl_head_intro_2 = {"Червы ослаблены.", "Холодно, да?"},
            fb_bl_head_big_hand_1 = {"Ты победил без", "сердца?!"},
            fb_bl_head_close_1 = {"Имей сердце,", "не добивай меня!"},
            fb_bl_head_last_hand_1 = {"Последняя рука. Без", "червей. Без пощады."},
            fb_bl_head_disabled_1 = {"У меня болит голова!", "Червы снова работают?"},
            fb_bl_head_defeat_1 = {"Потеряла голову...", "из-за тебя."},
            fb_bl_head_gloat_1 = {"Бессердечный, да?"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"Но я", "Зуб"},
            fb_bl_tooth_intro_1 = {"Я увлекаюсь", "политикой"},
            fb_bl_tooth_intro_2 = {"Каждая сыгранная карта", "стоит тебе $1."},
            fb_bl_tooth_big_hand_1 = {"Ты заплатил и все", "равно победил?!"},
            fb_bl_tooth_close_1 = {"Не заставляй меня", "платить зубной фее!"},
            fb_bl_tooth_last_hand_1 = {"Последняя рука,", "последние доллары."},
            fb_bl_tooth_disabled_1 = {"Мой укус!", "Он пропал!"},
            fb_bl_tooth_defeat_1 = {"Зубами и когтями,", "я проиграл."},
            fb_bl_tooth_gloat_1 = {"Плати, простофиля!"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"Но я", "Кремень"},
            fb_bl_flint_intro_1 = {"Ты должен", "платить налоги"},
            fb_bl_flint_intro_2 = {"Фишки и множитель", "делятся пополам."},
            fb_bl_flint_big_hand_1 = {"Половина силы, а", "попадание?!"},
            fb_bl_flint_close_1 = {"Ты высекаешь искру", "моего падения!"},
            fb_bl_flint_last_hand_1 = {"Последняя рука.", "Половина искры."},
            fb_bl_flint_disabled_1 = {"Полная сила?!", "Нечестно!"},
            fb_bl_flint_defeat_1 = {"Моя искра", "погасла."},
            fb_bl_flint_gloat_1 = {"Половина веселья!"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"Но я", "Знак"},
            fb_bl_mark_intro_1 = {"Не люблю, когда", "на меня смотрят"},
            fb_bl_mark_intro_2 = {"Все картинки приходят", "рубашкой вверх."},
            fb_bl_mark_big_hand_1 = {"Меченые карты,", "а ты победил?!"},
            fb_bl_mark_close_1 = {"Я отмечен", "для поражения!"},
            fb_bl_mark_last_hand_1 = {"Последняя рука. Выбирай", "лица вслепую."},
            fb_bl_mark_disabled_1 = {"Лица!", "Я их вижу!"},
            fb_bl_mark_defeat_1 = {"Ты оставил на мне", "свой знак."},
            fb_bl_mark_gloat_1 = {"Отмечен", "проигрышем!"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"Но я", "Янтарный желудь"},
            fb_bl_final_acorn_intro_1 = {"Я люблю", "ХАОС!"},
            fb_bl_final_acorn_intro_2 = {"Джокеры рубашкой вверх,", "затем перемешаны!"},
            fb_bl_final_acorn_big_hand_1 = {"Даже в хаосе", "ты побеждаешь?!"},
            fb_bl_final_acorn_close_1 = {"Это безумие!", "Я трескаюсь!"},
            fb_bl_final_acorn_last_hand_1 = {"Последняя рука. Где", "твой джокер?"},
            fb_bl_final_acorn_disabled_1 = {"Мой желудь!", "Порядок вернулся?!"},
            fb_bl_final_acorn_defeat_1 = {"Ты расколол", "мою скорлупу..."},
            fb_bl_final_acorn_gloat_1 = {"Вот это орех!"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"Но я", "Зеленый лист"},
            fb_bl_final_leaf_intro_1 = {"Ты должен оторваться", "от своих корней"},
            fb_bl_final_leaf_intro_2 = {"Продай джокера или", "останься ослабленным."},
            fb_bl_final_leaf_big_hand_1 = {"Ты начал с чистого", "листа. Хм."},
            fb_bl_final_leaf_close_1 = {"Мой лист", "падает!"},
            fb_bl_final_leaf_last_hand_1 = {"Последняя рука.", "Продать джокера?"},
            fb_bl_final_leaf_disabled_1 = {"Мой лист!", "Он засох!"},
            fb_bl_final_leaf_defeat_1 = {"Я ухожу...", "как лист."},
            fb_bl_final_leaf_gloat_1 = {"Листай на выход!"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"Но я", "Фиолетовый сосуд"},
            fb_bl_final_vessel_intro_1 = {"Ты только что врезался", "в Великую стену"},
            fb_bl_final_vessel_intro_2 = {"Поистине огромный", "блайнд. Плыви!"},
            fb_bl_final_vessel_big_hand_1 = {"Огромный удар по", "огромной цели."},
            fb_bl_final_vessel_close_1 = {"Покинуть корабль!", "...Мой, то есть."},
            fb_bl_final_vessel_last_hand_1 = {"Последняя рука. Этот", "корабль не утонет."},
            fb_bl_final_vessel_disabled_1 = {"Мой сосуд!", "Он тонет!"},
            fb_bl_final_vessel_defeat_1 = {"Сосуд...", "опустел."},
            fb_bl_final_vessel_gloat_1 = {"Полное поражение!"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"Но я", "Багровое сердце"},
            fb_bl_final_heart_intro_1 = {"Я одолжу", "джокера"},
            fb_bl_final_heart_intro_2 = {"Каждую руку джокер", "теряет силу."},
            fb_bl_final_heart_big_hand_1 = {"Джокер выбыл, а ты", "все еще силен?"},
            fb_bl_final_heart_close_1 = {"Не разбивай", "мне сердце!"},
            fb_bl_final_heart_last_hand_1 = {"Последняя рука. Какой", "джокер молчит?"},
            fb_bl_final_heart_disabled_1 = {"Мое сердце! Оно", "пропустило удар."},
            fb_bl_final_heart_defeat_1 = {"Мое сердце...", "разбито."},
            fb_bl_final_heart_gloat_1 = {"Сердце разбито?"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"Но я", "Лазурный колокольчик"},
            fb_bl_final_bell_intro_1 = {"Я хотел бы", "направлять тебя"},
            fb_bl_final_bell_intro_2 = {"Одна карта навязана", "в каждой руке."},
            fb_bl_final_bell_big_hand_1 = {"Ты заставил мою", "карту звенеть?!"},
            fb_bl_final_bell_close_1 = {"Колокол звонит...", "по мне?!"},
            fb_bl_final_bell_last_hand_1 = {"Последняя рука. Одна", "карта навязана."},
            fb_bl_final_bell_disabled_1 = {"Мой колокольчик молчит!", "Жулик!"},
            fb_bl_final_bell_defeat_1 = {"Колокол звонит", "по мне."},
            fb_bl_final_bell_gloat_1 = {"Динь-дон,", "проиграл!"},
        }
    }
}
