return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "决战",
            fb_cfg_dialogue = "Boss对话",
            fb_cfg_music = "决战音乐",
            fb_cfg_fx = "屏幕特效",
            fb_cfg_cinematic = "决战过场动画",
            fb_showdown_title = "决战",
            fb_cfg_intro_speed = "开场速度",
            fb_speed_slow = "慢速",
            fb_speed_normal = "普通",
            fb_speed_fast = "快速",
            fb_cfg_min_ante = "对话起始底注",
            fb_cfg_dev_mode = "开发者按键 (F5-F7)",
            fb_cfg_showdown_enabled = "自定义决战安排",
            fb_cfg_start_ante = "首次决战底注",
            fb_cfg_every = "之后每N个底注",
            fb_cfg_preview = "决战底注",
            fb_cfg_hard = "困难！前期决战极其残酷。",
            fb_cfg_next_ante = "更改将从下个底注起生效。",
            fb_cfg_group_dialogue = "对话",
            fb_cfg_group_stage = "决战舞台",
            fb_credits_thanks = "感谢你游玩FinalBoss！",
            fb_credits_lead = "制作与维护：",
            fb_credits_music = "决战音乐：",
            fb_credits_music_by = "Adam Isiah（管弦乐翻奏）",
            fb_credits_listen = "在YouTube上收听",
            fb_credits_github = "GitHub",
            fb_tip_me = "打赏我",
            fb_tip_me_message_1 = "如果你喜欢FinalBoss，",
            fb_tip_me_message_2 = "欢迎小额打赏以示支持。",
            fb_tip_me_message_3 = "非常感谢！",
        },
        quips = {
            -- Config menu header card
            fb_cfg_header = {"Boss会开口说话，决战化身Boss战。", "作者 {C:green,E:1}@SirMaiquis{}"},

            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"你走得太远了..."},
            fb_opener_2 = {"很遗憾，我得", "告诉你..."},
            fb_opener_3 = {"那么。你", "还是来了。"},
            fb_closer_1 = {"你不可能", "打败我。"},
            fb_closer_2 = {"你的这局", "到此为止。"},
            fb_closer_3 = {"让我看看", "你的本事。"},
            fb_gloat = {"那个Boss", "太强了..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"我是", "#1#！"},
            fb_generic_name_2 = {"人称", "#1#。"},
            fb_generic_name_3 = {"看好了：", "#1#！"},
            fb_generic_intro_1 = {"你的好运", "到此为止。"},
            fb_generic_intro_2 = {"看你怎么", "应付这个。"},
            fb_generic_intro_3 = {"仔细读读", "我的规则..."},
            fb_generic_big_hand_1 = {"...还不赖。"},
            fb_generic_big_hand_2 = {"走运的一手。"},
            fb_generic_big_hand_3 = {"哼。又来？"},
            fb_generic_close_1 = {"等等，等等，", "等一下！"},
            fb_generic_close_2 = {"你敢..."},
            fb_generic_close_3 = {"这不可能..."},
            fb_generic_last_hand_1 = {"只剩一手了。", "好好打。"},
            fb_generic_last_hand_2 = {"滴答，滴答..."},
            fb_generic_last_hand_3 = {"最后的机会，", "小丑。"},
            fb_generic_disabled_1 = {"我的力量...！", "你做了什么？"},
            fb_generic_disabled_2 = {"喂！这是", "作弊！"},
            fb_generic_disabled_3 = {"我觉得...", "好虚弱。"},
            fb_generic_defeat_1 = {"不可能..."},
            fb_generic_defeat_2 = {"下个底注", "我会回来..."},
            fb_generic_defeat_3 = {"打得好..."},
            fb_generic_gloat_1 = {"那个Boss", "太强了..."},
            fb_generic_gloat_2 = {"庄家", "永远会赢。"},
            fb_generic_gloat_3 = {"下局", "好运吧。"},
            fb_generic_interrupted_1 = {"我的演讲！"},
            fb_generic_interrupted_2 = {"好吧…原来", "是这样。"},
            fb_generic_interrupted_3 = {"连声招呼都不打？"},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"但我是", "钩子！"},
            fb_bl_hook_intro_1 = {"我要拿走", "你几张牌"},
            fb_bl_hook_intro_2 = {"每次出牌，", "弃掉两张牌。"},
            fb_bl_hook_big_hand_1 = {"牌少了", "还能赢？！"},
            fb_bl_hook_close_1 = {"放开我的", "牌！"},
            fb_bl_hook_last_hand_1 = {"终于把你", "钩住了！"},
            fb_bl_hook_disabled_1 = {"我的钩子！", "断了！"},
            fb_bl_hook_defeat_1 = {"好吧...", "放你走。"},
            fb_bl_hook_gloat_1 = {"上钩了！"},
            fb_bl_hook_interrupted_1 = {"没礼貌！我话还", "没说完！"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"但我是", "公牛！"},
            fb_bl_ox_intro_1 = {"我要拿走", "你所有的钱"},
            fb_bl_ox_intro_2 = {"出最常用牌型", "钱就清零。"},
            fb_bl_ox_big_hand_1 = {"身无分文", "还能赢？！"},
            fb_bl_ox_close_1 = {"别急！", "...我也是。"},
            fb_bl_ox_last_hand_1 = {"最后一手。", "花光或失去。"},
            fb_bl_ox_disabled_1 = {"我的角！", "钝了！"},
            fb_bl_ox_defeat_1 = {"你抓住了", "牛角..."},
            fb_bl_ox_gloat_1 = {"现在你破产了！"},
            fb_bl_ox_interrupted_1 = {"哦，原来你是", "这个态度。"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"但我是", "房屋！"},
            fb_bl_house_intro_1 = {"你是", "盲的！"},
            fb_bl_house_intro_2 = {"第一手牌", "盖着发！"},
            fb_bl_house_big_hand_1 = {"盲打居然", "还赢了？！"},
            fb_bl_house_close_1 = {"庄家", "绝不会输！"},
            fb_bl_house_last_hand_1 = {"不会再有", "盲目的好运。"},
            fb_bl_house_disabled_1 = {"我的眼罩！", "掉了！"},
            fb_bl_house_defeat_1 = {"房子...", "塌了。"},
            fb_bl_house_gloat_1 = {"庄家通吃！"},
            fb_bl_house_interrupted_1 = {"家规：还不许", "出牌！"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"但我是", "围墙！"},
            fb_bl_wall_intro_1 = {"你刚刚", "撞墙了"},
            fb_bl_wall_intro_2 = {"试试爬上", "这个分数。"},
            fb_bl_wall_big_hand_1 = {"你爬过了", "我的墙？！"},
            fb_bl_wall_close_1 = {"你休想", "突破！"},
            fb_bl_wall_last_hand_1 = {"已经没有", "可爬的了。"},
            fb_bl_wall_disabled_1 = {"裂缝！我的墙", "裂开了！"},
            fb_bl_wall_defeat_1 = {"围墙...", "倒塌了。"},
            fb_bl_wall_gloat_1 = {"撞墙了吧？"},
            fb_bl_wall_interrupted_1 = {"像在对墙说话…", "等等，我就是墙。"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"但我是", "车轮！"},
            fb_bl_wheel_intro_1 = {"我喜欢...", "赌博！"},
            fb_bl_wheel_intro_2 = {"每七张牌", "就有一张盖着。"},
            fb_bl_wheel_big_hand_1 = {"幸运女神", "今天眷顾你。"},
            fb_bl_wheel_close_1 = {"我的车轮", "要失控了！"},
            fb_bl_wheel_last_hand_1 = {"最后一转。", "感觉走运吗？"},
            fb_bl_wheel_disabled_1 = {"车轮停了？", "有诈！"},
            fb_bl_wheel_defeat_1 = {"命运之轮...", "转向了我。"},
            fb_bl_wheel_gloat_1 = {"轮到你输了！"},
            fb_bl_wheel_interrupted_1 = {"慢着！我还在", "转呢！"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"但我是", "手臂！"},
            fb_bl_arm_intro_1 = {"我来平衡", "你的力量"},
            fb_bl_arm_intro_2 = {"每次出牌", "牌型降一级。"},
            fb_bl_arm_big_hand_1 = {"这手牌", "有点肌肉..."},
            fb_bl_arm_close_1 = {"掰手腕？", "我要输了！"},
            fb_bl_arm_last_hand_1 = {"最后一手。", "别逞强。"},
            fb_bl_arm_disabled_1 = {"我的手臂软了！", "作弊！"},
            fb_bl_arm_defeat_1 = {"你击败了", "我的强臂。"},
            fb_bl_arm_gloat_1 = {"降级！"},
            fb_bl_arm_interrupted_1 = {"放手！我还没", "秀完肌肉！"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"但我是", "梅花！"},
            fb_bl_club_intro_1 = {"我讨厌", "{C:green,E:1}走运{}的玩家"},
            fb_bl_club_intro_2 = {"梅花被削弱了。", "抱歉。"},
            fb_bl_club_big_hand_1 = {"没了梅花", "也没问题？！"},
            fb_bl_club_close_1 = {"别用那个", "打我！"},
            fb_bl_club_last_hand_1 = {"最后一手。", "把梅花留家里。"},
            fb_bl_club_disabled_1 = {"我的梅花", "没了威力！"},
            fb_bl_club_defeat_1 = {"俱乐部打烊。", "该走了..."},
            fb_bl_club_gloat_1 = {"打烊啦！"},
            fb_bl_club_interrupted_1 = {"喂！在我的俱乐部", "我先说话！"},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"但我是", "鱼！"},
            fb_bl_fish_intro_1 = {"想清楚", "再出牌"},
            fb_bl_fish_intro_2 = {"每次出牌后", "牌都盖着发。"},
            fb_bl_fish_big_hand_1 = {"这手牌", "有点可疑！"},
            fb_bl_fish_close_1 = {"别把我", "钓上岸！"},
            fb_bl_fish_last_hand_1 = {"最后一竿。", "收线吧。"},
            fb_bl_fish_disabled_1 = {"我的鳞片！", "掉光了！"},
            fb_bl_fish_defeat_1 = {"被钓上来了...", "高手啊。"},
            fb_bl_fish_gloat_1 = {"你落水了！"},
            fb_bl_fish_interrupted_1 = {"你扯断了", "我的鱼线！"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"但我是", "灵媒！"},
            fb_bl_psychic_intro_1 = {"我讨厌", "犹豫不决的人"},
            fb_bl_psychic_intro_2 = {"必须五张牌。", "我早就预见了。"},
            fb_bl_psychic_big_hand_1 = {"这个我可", "没预见到。"},
            fb_bl_psychic_close_1 = {"水晶球显示", "...失败！"},
            fb_bl_psychic_last_hand_1 = {"我预见了你的", "最后一手。"},
            fb_bl_psychic_disabled_1 = {"我的幻象！", "消失了！"},
            fb_bl_psychic_defeat_1 = {"我早预见了。", "...是吗？"},
            fb_bl_psychic_gloat_1 = {"我早说了！"},
            fb_bl_psychic_interrupted_1 = {"我就知道你会这样。", "…还是没礼貌。"},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"但我是", "挑衅！"},
            fb_bl_goad_intro_1 = {"我讨厌", "{C:black,E:1}权力{}"},
            fb_bl_goad_intro_2 = {"黑桃被削弱。", "挖深点。"},
            fb_bl_goad_big_hand_1 = {"没了黑桃", "也不赖。"},
            fb_bl_goad_close_1 = {"别想挖", "我的坟！"},
            fb_bl_goad_last_hand_1 = {"往深处挖。", "最后一手了。"},
            fb_bl_goad_disabled_1 = {"我现在", "没法挑衅了！"},
            fb_bl_goad_defeat_1 = {"该死，", "你赢了。"},
            fb_bl_goad_gloat_1 = {"自己挖坟吧！"},
            fb_bl_goad_interrupted_1 = {"挑衅我？", "好啊！"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"但我是", "水！"},
            fb_bl_water_intro_1 = {"把你的", "弃牌给我"},
            fb_bl_water_intro_2 = {"没有弃牌。", "一滴都没有。"},
            fb_bl_water_big_hand_1 = {"没有弃牌", "还能赢？！"},
            fb_bl_water_close_1 = {"我在淹水！", "扔根绳子！"},
            fb_bl_water_last_hand_1 = {"最后一手。", "游起来或沉下去。"},
            fb_bl_water_disabled_1 = {"弃牌又", "流动了！"},
            fb_bl_water_defeat_1 = {"我彻底", "干涸了..."},
            fb_bl_water_gloat_1 = {"你泡汤了！"},
            fb_bl_water_interrupted_1 = {"打断我？你要", "陷入深水了！"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"但我是", "窗口！"},
            fb_bl_window_intro_1 = {"我讨厌", "{C:yellow,E:1}资本主义{}"},
            fb_bl_window_intro_2 = {"方片被削弱。", "继续闪耀吧。"},
            fb_bl_window_big_hand_1 = {"谁还需要", "方片？"},
            fb_bl_window_close_1 = {"别打碎", "我的窗！"},
            fb_bl_window_last_hand_1 = {"最后一手。", "禁止闪闪发光。"},
            fb_bl_window_disabled_1 = {"我的窗裂了！", "方片闪耀了！"},
            fb_bl_window_defeat_1 = {"我的机会之窗", "关上了。"},
            fb_bl_window_gloat_1 = {"方片？削弱！"},
            fb_bl_window_interrupted_1 = {"我的话被你", "扔出窗外？！"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"但我是", "镣铐！"},
            fb_bl_manacle_intro_1 = {"我要夺走", "你的{C:blue,E:1}选择{}"},
            fb_bl_manacle_intro_2 = {"手牌少一张。"},
            fb_bl_manacle_big_hand_1 = {"戴着镣铐", "还能赢？！"},
            fb_bl_manacle_close_1 = {"你要挣脱", "锁链了！"},
            fb_bl_manacle_last_hand_1 = {"最后一手。", "还戴着镣铐。"},
            fb_bl_manacle_disabled_1 = {"镣铐！", "掉了！"},
            fb_bl_manacle_defeat_1 = {"终于自由了...", "摆脱了我。"},
            fb_bl_manacle_gloat_1 = {"束手就擒！"},
            fb_bl_manacle_interrupted_1 = {"站住！就凭这个", "我要锁住你！"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"但我是", "眼睛！"},
            fb_bl_eye_intro_1 = {"我不喜欢", "一成不变"},
            fb_bl_eye_intro_2 = {"同一牌型", "不许出两次。"},
            fb_bl_eye_big_hand_1 = {"新牌型？", "我看见你了。"},
            fb_bl_eye_close_1 = {"我不忍", "再看了！"},
            fb_bl_eye_last_hand_1 = {"我看见你的", "最后一手。"},
            fb_bl_eye_disabled_1 = {"我的眼睛！谁", "戳我眼睛？！"},
            fb_bl_eye_defeat_1 = {"眼不见，", "心不烦..."},
            fb_bl_eye_gloat_1 = {"早就看穿了！"},
            fb_bl_eye_interrupted_1 = {"我看见了！", "真没礼貌。"},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"但我是", "嘴巴！"},
            fb_bl_mouth_intro_1 = {"我喜欢", "一成不变"},
            fb_bl_mouth_intro_2 = {"选一种牌型，", "坚持到底。"},
            fb_bl_mouth_big_hand_1 = {"还是老牌型，", "依然很强..."},
            fb_bl_mouth_close_1 = {"我的嘴", "张得好大！"},
            fb_bl_mouth_last_hand_1 = {"最后一手。同牌型。", "闭嘴吧。"},
            fb_bl_mouth_disabled_1 = {"谁给我", "戴了口套？！"},
            fb_bl_mouth_defeat_1 = {"我无话可说..."},
            fb_bl_mouth_gloat_1 = {"闭嘴，输家！"},
            fb_bl_mouth_interrupted_1 = {"喂！这张嘴", "还在说话！"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"但我是", "植物！"},
            fb_bl_plant_intro_1 = {"我讨厌", "友善的面孔"},
            fb_bl_plant_intro_2 = {"K、Q、J：", "全部被削弱。"},
            fb_bl_plant_big_hand_1 = {"没有人头牌？！", "难以置信。"},
            fb_bl_plant_close_1 = {"别连根", "拔起我！"},
            fb_bl_plant_last_hand_1 = {"直面你的", "最后一手。"},
            fb_bl_plant_disabled_1 = {"我的花瓣！", "全没了！"},
            fb_bl_plant_defeat_1 = {"枯萎了...", "我会再长出来。"},
            fb_bl_plant_gloat_1 = {"面对现实吧！"},
            fb_bl_plant_interrupted_1 = {"先让我长大，", "急什么！"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"但我是", "巨蟒！"},
            fb_bl_serpent_intro_1 = {"这里有", "一个赤字"},
            fb_bl_serpent_intro_2 = {"出牌或弃牌，", "只抽三张。"},
            fb_bl_serpent_big_hand_1 = {"只有三张牌，", "你还能出击！"},
            fb_bl_serpent_close_1 = {"现在别", "溜走！"},
            fb_bl_serpent_last_hand_1 = {"最后一击。", "三张牌。"},
            fb_bl_serpent_disabled_1 = {"我的毒牙！嘶...", "毒液没了！"},
            fb_bl_serpent_defeat_1 = {"蜕了皮...", "也丢了尊严。"},
            fb_bl_serpent_gloat_1 = {"嘶嘶，再见！"},
            fb_bl_serpent_interrupted_1 = {"嘶嘶！别插嘴！"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"但我是", "支柱！"},
            fb_bl_pillar_intro_1 = {"我从你过往的", "牌里学到不少"},
            fb_bl_pillar_intro_2 = {"打出过的牌", "本底注都被削弱。"},
            fb_bl_pillar_big_hand_1 = {"新牌？", "聪明。"},
            fb_bl_pillar_close_1 = {"我的支柱", "要塌了！"},
            fb_bl_pillar_last_hand_1 = {"最后一手。", "旧牌没用了。"},
            fb_bl_pillar_disabled_1 = {"我的记忆！", "...在消退。"},
            fb_bl_pillar_defeat_1 = {"社区的支柱", "倒下了。"},
            fb_bl_pillar_gloat_1 = {"我还站着！"},
            fb_bl_pillar_interrupted_1 = {"不懂得", "尊老吗？"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"但我是", "针！"},
            fb_bl_needle_intro_1 = {"你只有", "一次机会"},
            fb_bl_needle_intro_2 = {"一手牌。", "仅此而已。"},
            fb_bl_needle_big_hand_1 = {"只一手牌，", "竟然这么强？！"},
            fb_bl_needle_close_1 = {"不！一手牌", "怎么可能！"},
            fb_bl_needle_last_hand_1 = {"这手牌是你", "唯一的一手。"},
            fb_bl_needle_disabled_1 = {"我的针！", "钝了！"},
            fb_bl_needle_defeat_1 = {"打得犀利。", "你赢了。"},
            fb_bl_needle_gloat_1 = {"重点是你输了！"},
            fb_bl_needle_interrupted_1 = {"真扎人。", "我还没说完！"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"但我是", "头部！"},
            fb_bl_head_intro_1 = {"我讨厌", "{C:red,E:1}恋人{}"},
            fb_bl_head_intro_2 = {"红桃被削弱。", "冷吧？"},
            fb_bl_head_big_hand_1 = {"没有红桃", "你也赢了？！"},
            fb_bl_head_close_1 = {"有点良心，", "别灭了我！"},
            fb_bl_head_last_hand_1 = {"最后一手。无红桃。", "无怜悯。"},
            fb_bl_head_disabled_1 = {"我头好痛！", "红桃又能用了？"},
            fb_bl_head_defeat_1 = {"为你丢了脑袋..."},
            fb_bl_head_gloat_1 = {"没心没肺吧？"},
            fb_bl_head_interrupted_1 = {"你昏头了吗？", "我在说话！"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"但我是", "牙齿！"},
            fb_bl_tooth_intro_1 = {"我热衷", "政治"},
            fb_bl_tooth_intro_2 = {"你每出一张牌", "就付 $1。"},
            fb_bl_tooth_big_hand_1 = {"你付了钱", "还赢了？！"},
            fb_bl_tooth_close_1 = {"别逼我去", "付牙仙的钱！"},
            fb_bl_tooth_last_hand_1 = {"最后一手，", "最后的美元。"},
            fb_bl_tooth_disabled_1 = {"我的獠牙！", "没了！"},
            fb_bl_tooth_defeat_1 = {"拼尽全力，", "我还是输了。"},
            fb_bl_tooth_gloat_1 = {"付钱吧，", "冤大头！"},
            fb_bl_tooth_interrupted_1 = {"咕噜！你要为此", "付出代价！"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"但我是", "燧石！"},
            fb_bl_flint_intro_1 = {"你必须", "缴税"},
            fb_bl_flint_intro_2 = {"筹码和倍率", "都减半。"},
            fb_bl_flint_big_hand_1 = {"只剩一半威力，", "还能命中？！"},
            fb_bl_flint_close_1 = {"你在点燃", "我的末日！"},
            fb_bl_flint_last_hand_1 = {"最后一手。", "火花减半。"},
            fb_bl_flint_disabled_1 = {"全力以赴？！", "不公平！"},
            fb_bl_flint_defeat_1 = {"我的火花", "熄灭了。"},
            fb_bl_flint_gloat_1 = {"乐趣减半！"},
            fb_bl_flint_interrupted_1 = {"别冒火星！", "我在说话！"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"但我是", "标记！"},
            fb_bl_mark_intro_1 = {"我不喜欢", "被人看见"},
            fb_bl_mark_intro_2 = {"所有人头牌", "都盖着发。"},
            fb_bl_mark_big_hand_1 = {"被标记的牌，", "还赢了？！"},
            fb_bl_mark_close_1 = {"我被标记为", "失败！"},
            fb_bl_mark_last_hand_1 = {"最后一手。", "盲选人头牌。"},
            fb_bl_mark_disabled_1 = {"人头牌！", "我看见了！"},
            fb_bl_mark_defeat_1 = {"你在我身上", "留下了标记。"},
            fb_bl_mark_gloat_1 = {"标记为输家！"},
            fb_bl_mark_interrupted_1 = {"记住了。你被", "盯上了。"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"但我是", "琥珀之实！"},
            fb_bl_final_acorn_intro_1 = {"我喜欢", "混乱！"},
            fb_bl_final_acorn_intro_2 = {"小丑盖牌，", "然后洗牌！"},
            fb_bl_final_acorn_big_hand_1 = {"身处混乱", "你也能赢？！"},
            fb_bl_final_acorn_close_1 = {"真是个坚果！", "我要裂了！"},
            fb_bl_final_acorn_last_hand_1 = {"最后一手。", "你的小丑呢？"},
            fb_bl_final_acorn_disabled_1 = {"我的果实！", "秩序恢复了？！"},
            fb_bl_final_acorn_defeat_1 = {"你敲开了", "我的外壳..."},
            fb_bl_final_acorn_gloat_1 = {"壳都碎了！"},
            fb_bl_final_acorn_interrupted_1 = {"慢着！我还没", "发芽呢！"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"但我是", "翠绿之叶！"},
            fb_bl_final_leaf_intro_1 = {"你必须", "脱离你的根"},
            fb_bl_final_leaf_intro_2 = {"卖掉一张小丑，", "否则继续被削弱。"},
            fb_bl_final_leaf_big_hand_1 = {"你翻开了", "新的一页。哼。"},
            fb_bl_final_leaf_close_1 = {"我的叶子", "要掉了！"},
            fb_bl_final_leaf_last_hand_1 = {"最后一手。", "卖掉小丑吗？"},
            fb_bl_final_leaf_disabled_1 = {"我的叶子！", "枯萎了！"},
            fb_bl_final_leaf_defeat_1 = {"我要离开了...", "如一片落叶。"},
            fb_bl_final_leaf_gloat_1 = {"落叶归根！"},
            fb_bl_final_leaf_interrupted_1 = {"好吧。客套话", "就免了。"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"但我是", "靛紫之杯！"},
            fb_bl_final_vessel_intro_1 = {"你刚撞上了", "万里长城"},
            fb_bl_final_vessel_intro_2 = {"一个无比巨大", "的盲注。扬帆！"},
            fb_bl_final_vessel_big_hand_1 = {"对庞大的目标", "打出庞大一击。"},
            fb_bl_final_vessel_close_1 = {"弃船！", "...我的船。"},
            fb_bl_final_vessel_last_hand_1 = {"最后一手。", "这船不会沉。"},
            fb_bl_final_vessel_disabled_1 = {"我的杯子！", "在下沉！"},
            fb_bl_final_vessel_defeat_1 = {"杯子...", "空了。"},
            fb_bl_final_vessel_gloat_1 = {"一败涂地！"},
            fb_bl_final_vessel_interrupted_1 = {"我还没讲完就", "起航？真大胆。"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"但我是", "绯红之心！"},
            fb_bl_final_heart_intro_1 = {"我要借走", "一张小丑"},
            fb_bl_final_heart_intro_2 = {"每手牌，一张", "小丑失去力量。"},
            fb_bl_final_heart_big_hand_1 = {"少了一张小丑，", "还这么强？"},
            fb_bl_final_heart_close_1 = {"别伤了", "我的心！"},
            fb_bl_final_heart_last_hand_1 = {"最后一手。哪张", "小丑被沉默？"},
            fb_bl_final_heart_disabled_1 = {"我的心！", "漏跳了一拍。"},
            fb_bl_final_heart_defeat_1 = {"我的心...", "碎了。"},
            fb_bl_final_heart_gloat_1 = {"心碎了吗？"},
            fb_bl_final_heart_interrupted_1 = {"打断我？", "真无情！"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"但我是", "蔚蓝之铃！"},
            fb_bl_final_bell_intro_1 = {"我想", "为你指路"},
            fb_bl_final_bell_intro_2 = {"每手牌都被", "强制选一张牌。"},
            fb_bl_final_bell_big_hand_1 = {"你让我的强制牌", "响起来了？！"},
            fb_bl_final_bell_close_1 = {"钟声响起...", "为我而鸣？！"},
            fb_bl_final_bell_last_hand_1 = {"最后一手。", "一张牌被强制。"},
            fb_bl_final_bell_disabled_1 = {"我的铃哑了！", "作弊！"},
            fb_bl_final_bell_defeat_1 = {"钟声响起", "为我而鸣。"},
            fb_bl_final_bell_gloat_1 = {"叮咚，你输了！"},
            fb_bl_final_bell_interrupted_1 = {"被铃声救了？", "这次可不行！"},
        }
    }
}
