return {
    misc = {
        dictionary = {
            fb_tab_showdowns = "決戰",
            fb_cfg_dialogue = "Boss對話",
            fb_cfg_music = "決戰音樂",
            fb_cfg_fx = "螢幕特效",
            fb_cfg_cinematic = "決戰過場動畫",
            fb_showdown_title = "決戰",
            fb_cfg_intro_speed = "開場速度",
            fb_speed_slow = "慢速",
            fb_speed_normal = "普通",
            fb_speed_fast = "快速",
            fb_cfg_min_ante = "對話起始底注",
            fb_cfg_dev_mode = "開發者按鍵 (F5-F7)",
            fb_cfg_showdown_enabled = "自訂決戰安排",
            fb_cfg_start_ante = "首次決戰底注",
            fb_cfg_every = "之後每N個底注",
            fb_cfg_preview = "決戰底注:",
            fb_cfg_hard = "困難！前期決戰極其殘酷。",
            fb_cfg_next_ante = "變更將從下個底注起生效。",
        },
        quips = {
            -- Shared intro bookends (full tier only)
            fb_opener_1 = {"你走得太遠了..."},
            fb_opener_2 = {"很遺憾，我得", "告訴你..."},
            fb_opener_3 = {"那麼。你", "還是來了。"},
            fb_closer_1 = {"你不可能", "打敗我。"},
            fb_closer_2 = {"你的這局", "到此為止。"},
            fb_closer_3 = {"讓我看看", "你的本事。"},
            fb_gloat = {"那個Boss", "太強了..."},

            -- Generic fallbacks for bosses without their own lines (#1# = boss name)
            fb_generic_name_1 = {"我是", "#1#！"},
            fb_generic_name_2 = {"人稱", "#1#。"},
            fb_generic_name_3 = {"看好了：", "#1#！"},
            fb_generic_intro_1 = {"你的好運", "到此為止。"},
            fb_generic_intro_2 = {"看你怎麼", "應付這個。"},
            fb_generic_intro_3 = {"仔細讀讀", "我的規則..."},
            fb_generic_big_hand_1 = {"...還不賴。"},
            fb_generic_big_hand_2 = {"走運的一手。"},
            fb_generic_big_hand_3 = {"哼。又來？"},
            fb_generic_close_1 = {"等等，等等，", "等一下！"},
            fb_generic_close_2 = {"你敢..."},
            fb_generic_close_3 = {"這不可能..."},
            fb_generic_last_hand_1 = {"只剩一手了。", "好好打。"},
            fb_generic_last_hand_2 = {"滴答，滴答..."},
            fb_generic_last_hand_3 = {"最後的機會，", "小丑。"},
            fb_generic_disabled_1 = {"我的力量...！", "你做了什麼？"},
            fb_generic_disabled_2 = {"喂！這是", "作弊！"},
            fb_generic_disabled_3 = {"我覺得...", "好虛弱。"},
            fb_generic_defeat_1 = {"不可能..."},
            fb_generic_defeat_2 = {"下個底注", "我會回來..."},
            fb_generic_defeat_3 = {"打得好..."},
            fb_generic_gloat_1 = {"那個Boss", "太強了..."},
            fb_generic_gloat_2 = {"莊家", "永遠會贏。"},
            fb_generic_gloat_3 = {"下局", "好運吧。"},

            -- The Hook: discards 2 random cards per hand played
            fb_bl_hook_name_1 = {"但我是", "鉤子！"},
            fb_bl_hook_intro_1 = {"我要拿走", "你幾張牌"},
            fb_bl_hook_intro_2 = {"每次出牌，", "棄掉兩張牌。"},
            fb_bl_hook_big_hand_1 = {"牌少了", "還能贏？！"},
            fb_bl_hook_close_1 = {"放開我的", "牌！"},
            fb_bl_hook_last_hand_1 = {"終於把你", "鉤住了！"},
            fb_bl_hook_disabled_1 = {"我的鉤子！", "斷了！"},
            fb_bl_hook_defeat_1 = {"好吧...", "放你走。"},
            fb_bl_hook_gloat_1 = {"上鉤了！"},

            -- The Ox: playing your most played hand sets money to $0
            fb_bl_ox_name_1 = {"但我是", "公牛！"},
            fb_bl_ox_intro_1 = {"我要拿走", "你所有的錢"},
            fb_bl_ox_intro_2 = {"出最常用牌型", "錢就歸零。"},
            fb_bl_ox_big_hand_1 = {"身無分文", "還能贏？！"},
            fb_bl_ox_close_1 = {"別急！", "...我也是。"},
            fb_bl_ox_last_hand_1 = {"最後一手。", "花光或失去。"},
            fb_bl_ox_disabled_1 = {"我的角！", "鈍了！"},
            fb_bl_ox_defeat_1 = {"你抓住了", "牛角..."},
            fb_bl_ox_gloat_1 = {"現在你破產了！"},

            -- The House: first hand is drawn face down
            fb_bl_house_name_1 = {"但我是", "房子！"},
            fb_bl_house_intro_1 = {"你是", "盲的！"},
            fb_bl_house_intro_2 = {"第一手牌", "蓋著發！"},
            fb_bl_house_big_hand_1 = {"盲打居然", "還贏了？！"},
            fb_bl_house_close_1 = {"莊家", "絕不會輸！"},
            fb_bl_house_last_hand_1 = {"不會再有", "盲目的好運。"},
            fb_bl_house_disabled_1 = {"我的眼罩！", "掉了！"},
            fb_bl_house_defeat_1 = {"房子...", "塌了。"},
            fb_bl_house_gloat_1 = {"莊家通吃！"},

            -- The Wall: extra large blind
            fb_bl_wall_name_1 = {"但我是", "高牆！"},
            fb_bl_wall_intro_1 = {"你剛剛", "撞牆了"},
            fb_bl_wall_intro_2 = {"試試爬上", "這個分數。"},
            fb_bl_wall_big_hand_1 = {"你爬過了", "我的牆？！"},
            fb_bl_wall_close_1 = {"你休想", "突破！"},
            fb_bl_wall_last_hand_1 = {"已經沒有", "可爬的了。"},
            fb_bl_wall_disabled_1 = {"裂縫！我的牆", "裂開了！"},
            fb_bl_wall_defeat_1 = {"高牆...", "倒塌了。"},
            fb_bl_wall_gloat_1 = {"撞牆了吧？"},

            -- The Wheel: 1 in 7 cards get drawn face down
            fb_bl_wheel_name_1 = {"但我是", "巨輪！"},
            fb_bl_wheel_intro_1 = {"我喜歡...", "賭博！"},
            fb_bl_wheel_intro_2 = {"每七張牌", "就有一張蓋著。"},
            fb_bl_wheel_big_hand_1 = {"幸運女神", "今天眷顧你。"},
            fb_bl_wheel_close_1 = {"我的巨輪", "要失控了！"},
            fb_bl_wheel_last_hand_1 = {"最後一轉。", "感覺走運嗎？"},
            fb_bl_wheel_disabled_1 = {"巨輪停了？", "有詐！"},
            fb_bl_wheel_defeat_1 = {"命運之輪...", "轉向了我。"},
            fb_bl_wheel_gloat_1 = {"輪到你輸了！"},

            -- The Arm: decrease level of played poker hand
            fb_bl_arm_name_1 = {"但我是", "手臂！"},
            fb_bl_arm_intro_1 = {"我來平衡", "你的力量"},
            fb_bl_arm_intro_2 = {"每次出牌", "牌型降一級。"},
            fb_bl_arm_big_hand_1 = {"這手牌", "有點肌肉..."},
            fb_bl_arm_close_1 = {"掰手腕？", "我要輸了！"},
            fb_bl_arm_last_hand_1 = {"最後一手。", "別逞強。"},
            fb_bl_arm_disabled_1 = {"我的手臂軟了！", "作弊！"},
            fb_bl_arm_defeat_1 = {"你擊敗了", "我的強臂。"},
            fb_bl_arm_gloat_1 = {"降級！"},

            -- The Club: all Club cards are debuffed
            fb_bl_club_name_1 = {"但我是", "梅花！"},
            fb_bl_club_intro_1 = {"我討厭", "{C:green,E:1}走運{}的玩家"},
            fb_bl_club_intro_2 = {"梅花被削弱了。", "抱歉。"},
            fb_bl_club_big_hand_1 = {"沒了梅花", "也沒問題？！"},
            fb_bl_club_close_1 = {"別用那個", "打我！"},
            fb_bl_club_last_hand_1 = {"最後一手。", "把梅花留家裡。"},
            fb_bl_club_disabled_1 = {"我的梅花", "沒了威力！"},
            fb_bl_club_defeat_1 = {"俱樂部打烊。", "該走了..."},
            fb_bl_club_gloat_1 = {"打烊啦！"},

            -- The Fish: cards drawn face down after each hand played
            fb_bl_fish_name_1 = {"但我是", "魚！"},
            fb_bl_fish_intro_1 = {"想清楚", "再出牌"},
            fb_bl_fish_intro_2 = {"每次出牌後", "牌都蓋著發。"},
            fb_bl_fish_big_hand_1 = {"這手牌", "有點可疑！"},
            fb_bl_fish_close_1 = {"別把我", "釣上岸！"},
            fb_bl_fish_last_hand_1 = {"最後一竿。", "收線吧。"},
            fb_bl_fish_disabled_1 = {"我的鱗片！", "掉光了！"},
            fb_bl_fish_defeat_1 = {"被釣上來了...", "高手啊。"},
            fb_bl_fish_gloat_1 = {"你落水了！"},

            -- The Psychic: must play 5 cards
            fb_bl_psychic_name_1 = {"但我是", "靈媒！"},
            fb_bl_psychic_intro_1 = {"我討厭", "猶豫不決的人"},
            fb_bl_psychic_intro_2 = {"必須五張牌。", "我早就預見了。"},
            fb_bl_psychic_big_hand_1 = {"這個我可", "沒預見到。"},
            fb_bl_psychic_close_1 = {"水晶球顯示", "...失敗！"},
            fb_bl_psychic_last_hand_1 = {"我預見了你的", "最後一手。"},
            fb_bl_psychic_disabled_1 = {"我的幻象！", "消失了！"},
            fb_bl_psychic_defeat_1 = {"我早預見了。", "...是嗎？"},
            fb_bl_psychic_gloat_1 = {"我早說了！"},

            -- The Goad: all Spade cards are debuffed
            fb_bl_goad_name_1 = {"但我是", "鞭策！"},
            fb_bl_goad_intro_1 = {"我討厭", "{C:black,E:1}權力{}"},
            fb_bl_goad_intro_2 = {"黑桃被削弱。", "挖深點。"},
            fb_bl_goad_big_hand_1 = {"沒了黑桃", "也不賴。"},
            fb_bl_goad_close_1 = {"別想挖", "我的墳！"},
            fb_bl_goad_last_hand_1 = {"往深處挖。", "最後一手了。"},
            fb_bl_goad_disabled_1 = {"我現在", "沒法鞭策了！"},
            fb_bl_goad_defeat_1 = {"該死，", "你贏了。"},
            fb_bl_goad_gloat_1 = {"自己挖墳吧！"},

            -- The Water: start with 0 discards
            fb_bl_water_name_1 = {"但我是", "清水！"},
            fb_bl_water_intro_1 = {"把你的", "棄牌給我"},
            fb_bl_water_intro_2 = {"沒有棄牌。", "一滴都沒有。"},
            fb_bl_water_big_hand_1 = {"沒有棄牌", "還能贏？！"},
            fb_bl_water_close_1 = {"我在淹水！", "丟根繩子！"},
            fb_bl_water_last_hand_1 = {"最後一手。", "游起來或沉下去。"},
            fb_bl_water_disabled_1 = {"棄牌又", "流動了！"},
            fb_bl_water_defeat_1 = {"我徹底", "乾涸了..."},
            fb_bl_water_gloat_1 = {"你泡湯了！"},

            -- The Window: all Diamond cards are debuffed
            fb_bl_window_name_1 = {"但我是", "窗戶！"},
            fb_bl_window_intro_1 = {"我討厭", "{C:yellow,E:1}資本主義{}"},
            fb_bl_window_intro_2 = {"方塊被削弱。", "繼續閃耀吧。"},
            fb_bl_window_big_hand_1 = {"誰還需要", "方塊？"},
            fb_bl_window_close_1 = {"別打碎", "我的窗！"},
            fb_bl_window_last_hand_1 = {"最後一手。", "禁止閃閃發光。"},
            fb_bl_window_disabled_1 = {"我的窗裂了！", "方塊閃耀了！"},
            fb_bl_window_defeat_1 = {"我的機會之窗", "關上了。"},
            fb_bl_window_gloat_1 = {"方塊？削弱！"},

            -- The Manacle: -1 hand size
            fb_bl_manacle_name_1 = {"但我是", "手銬！"},
            fb_bl_manacle_intro_1 = {"我要奪走", "你的{C:blue,E:1}選擇{}"},
            fb_bl_manacle_intro_2 = {"手牌少一張。"},
            fb_bl_manacle_big_hand_1 = {"戴著手銬", "還能贏？！"},
            fb_bl_manacle_close_1 = {"你要掙脫", "鎖鏈了！"},
            fb_bl_manacle_last_hand_1 = {"最後一手。", "還戴著手銬。"},
            fb_bl_manacle_disabled_1 = {"手銬！", "掉了！"},
            fb_bl_manacle_defeat_1 = {"終於自由了...", "擺脫了我。"},
            fb_bl_manacle_gloat_1 = {"束手就擒！"},

            -- The Eye: no repeat hand types this round
            fb_bl_eye_name_1 = {"但我是", "眼睛！"},
            fb_bl_eye_intro_1 = {"我不喜歡", "一成不變"},
            fb_bl_eye_intro_2 = {"同一牌型", "不許出兩次。"},
            fb_bl_eye_big_hand_1 = {"新牌型？", "我看見你了。"},
            fb_bl_eye_close_1 = {"我不忍", "再看了！"},
            fb_bl_eye_last_hand_1 = {"我看見你的", "最後一手。"},
            fb_bl_eye_disabled_1 = {"我的眼睛！誰", "戳我眼睛？！"},
            fb_bl_eye_defeat_1 = {"眼不見，", "心不煩..."},
            fb_bl_eye_gloat_1 = {"早就看穿了！"},

            -- The Mouth: play only 1 hand type this round
            fb_bl_mouth_name_1 = {"但我是", "嘴巴！"},
            fb_bl_mouth_intro_1 = {"我喜歡", "一成不變"},
            fb_bl_mouth_intro_2 = {"選一種牌型，", "堅持到底。"},
            fb_bl_mouth_big_hand_1 = {"還是老牌型，", "依然很強..."},
            fb_bl_mouth_close_1 = {"我的嘴", "張得好大！"},
            fb_bl_mouth_last_hand_1 = {"最後一手。同牌型。", "閉嘴吧。"},
            fb_bl_mouth_disabled_1 = {"誰給我", "戴了口罩？！"},
            fb_bl_mouth_defeat_1 = {"我無話可說..."},
            fb_bl_mouth_gloat_1 = {"閉嘴，輸家！"},

            -- The Plant: all face cards are debuffed
            fb_bl_plant_name_1 = {"但我是", "星球！"},
            fb_bl_plant_intro_1 = {"我討厭", "友善的面孔"},
            fb_bl_plant_intro_2 = {"K、Q、J：", "全部被削弱。"},
            fb_bl_plant_big_hand_1 = {"沒有人頭牌？！", "難以置信。"},
            fb_bl_plant_close_1 = {"別連根", "拔起我！"},
            fb_bl_plant_last_hand_1 = {"直面你的", "最後一手。"},
            fb_bl_plant_disabled_1 = {"我的花瓣！", "全沒了！"},
            fb_bl_plant_defeat_1 = {"枯萎了...", "我會再長出來。"},
            fb_bl_plant_gloat_1 = {"面對現實吧！"},

            -- The Serpent: after play or discard, always draw 3 cards
            fb_bl_serpent_name_1 = {"但我是", "蛇！"},
            fb_bl_serpent_intro_1 = {"這裡有", "一個赤字"},
            fb_bl_serpent_intro_2 = {"出牌或棄牌，", "只抽三張。"},
            fb_bl_serpent_big_hand_1 = {"只有三張牌，", "你還能出擊！"},
            fb_bl_serpent_close_1 = {"現在別", "溜走！"},
            fb_bl_serpent_last_hand_1 = {"最後一擊。", "三張牌。"},
            fb_bl_serpent_disabled_1 = {"我的毒牙！嘶...", "毒液沒了！"},
            fb_bl_serpent_defeat_1 = {"蛻了皮...", "也丟了尊嚴。"},
            fb_bl_serpent_gloat_1 = {"嘶嘶，再見！"},

            -- The Pillar: cards played previously this ante are debuffed
            fb_bl_pillar_name_1 = {"但我是", "支柱！"},
            fb_bl_pillar_intro_1 = {"我從你過往的", "牌裡學到不少"},
            fb_bl_pillar_intro_2 = {"打出過的牌", "本底注都被削弱。"},
            fb_bl_pillar_big_hand_1 = {"新牌？", "聰明。"},
            fb_bl_pillar_close_1 = {"我的支柱", "要塌了！"},
            fb_bl_pillar_last_hand_1 = {"最後一手。", "舊牌沒用了。"},
            fb_bl_pillar_disabled_1 = {"我的記憶！", "...在消退。"},
            fb_bl_pillar_defeat_1 = {"社區的支柱", "倒下了。"},
            fb_bl_pillar_gloat_1 = {"我還站著！"},

            -- The Needle: play only 1 hand
            fb_bl_needle_name_1 = {"但我是", "細針！"},
            fb_bl_needle_intro_1 = {"你只有", "一次機會"},
            fb_bl_needle_intro_2 = {"一手牌。", "僅此而已。"},
            fb_bl_needle_big_hand_1 = {"只一手牌，", "竟然這麼強？！"},
            fb_bl_needle_close_1 = {"不！一手牌", "怎麼可能！"},
            fb_bl_needle_last_hand_1 = {"這手牌是你", "唯一的一手。"},
            fb_bl_needle_disabled_1 = {"我的針！", "鈍了！"},
            fb_bl_needle_defeat_1 = {"打得犀利。", "你贏了。"},
            fb_bl_needle_gloat_1 = {"重點是你輸了！"},

            -- The Head: all Heart cards are debuffed
            fb_bl_head_name_1 = {"但我是", "頭顱！"},
            fb_bl_head_intro_1 = {"我討厭", "{C:red,E:1}戀人{}"},
            fb_bl_head_intro_2 = {"紅心被削弱。", "冷吧？"},
            fb_bl_head_big_hand_1 = {"沒有紅心", "你也贏了？！"},
            fb_bl_head_close_1 = {"有點良心，", "別滅了我！"},
            fb_bl_head_last_hand_1 = {"最後一手。無紅心。", "無憐憫。"},
            fb_bl_head_disabled_1 = {"我頭好痛！", "紅心又能用了？"},
            fb_bl_head_defeat_1 = {"為你丟了腦袋..."},
            fb_bl_head_gloat_1 = {"沒心沒肺吧？"},

            -- The Tooth: lose $1 per card played
            fb_bl_tooth_name_1 = {"但我是", "尖齒！"},
            fb_bl_tooth_intro_1 = {"我熱衷", "政治"},
            fb_bl_tooth_intro_2 = {"你每出一張牌", "就付 $1。"},
            fb_bl_tooth_big_hand_1 = {"你付了錢", "還贏了？！"},
            fb_bl_tooth_close_1 = {"別逼我去", "付牙仙的錢！"},
            fb_bl_tooth_last_hand_1 = {"最後一手，", "最後的美元。"},
            fb_bl_tooth_disabled_1 = {"我的獠牙！", "沒了！"},
            fb_bl_tooth_defeat_1 = {"拼盡全力，", "我還是輸了。"},
            fb_bl_tooth_gloat_1 = {"付錢吧，", "冤大頭！"},

            -- The Flint: base Chips and Mult are halved
            fb_bl_flint_name_1 = {"但我是", "燧石！"},
            fb_bl_flint_intro_1 = {"你必須", "繳稅"},
            fb_bl_flint_intro_2 = {"籌碼和倍數", "都減半。"},
            fb_bl_flint_big_hand_1 = {"只剩一半威力，", "還能命中？！"},
            fb_bl_flint_close_1 = {"你在點燃", "我的末日！"},
            fb_bl_flint_last_hand_1 = {"最後一手。", "火花減半。"},
            fb_bl_flint_disabled_1 = {"全力以赴？！", "不公平！"},
            fb_bl_flint_defeat_1 = {"我的火花", "熄滅了。"},
            fb_bl_flint_gloat_1 = {"樂趣減半！"},

            -- The Mark: all face cards are drawn face down
            fb_bl_mark_name_1 = {"但我是", "標記！"},
            fb_bl_mark_intro_1 = {"我不喜歡", "被人看見"},
            fb_bl_mark_intro_2 = {"所有人頭牌", "都蓋著發。"},
            fb_bl_mark_big_hand_1 = {"被標記的牌，", "還贏了？！"},
            fb_bl_mark_close_1 = {"我被標記為", "失敗！"},
            fb_bl_mark_last_hand_1 = {"最後一手。", "盲選人頭牌。"},
            fb_bl_mark_disabled_1 = {"人頭牌！", "我看見了！"},
            fb_bl_mark_defeat_1 = {"你在我身上", "留下了標記。"},
            fb_bl_mark_gloat_1 = {"標記為輸家！"},

            -- Amber Acorn: flips and shuffles all Joker cards
            fb_bl_final_acorn_name_1 = {"但我是", "琥珀橡果！"},
            fb_bl_final_acorn_intro_1 = {"我喜歡", "混亂！"},
            fb_bl_final_acorn_intro_2 = {"小丑蓋牌，", "然後洗牌！"},
            fb_bl_final_acorn_big_hand_1 = {"身處混亂", "你也能贏？！"},
            fb_bl_final_acorn_close_1 = {"真是個堅果！", "我要裂了！"},
            fb_bl_final_acorn_last_hand_1 = {"最後一手。", "你的小丑呢？"},
            fb_bl_final_acorn_disabled_1 = {"我的橡果！", "秩序恢復了？！"},
            fb_bl_final_acorn_defeat_1 = {"你敲開了", "我的外殼..."},
            fb_bl_final_acorn_gloat_1 = {"殼都碎了！"},

            -- Verdant Leaf: all cards debuffed until 1 Joker sold
            fb_bl_final_leaf_name_1 = {"但我是", "翠綠樹葉！"},
            fb_bl_final_leaf_intro_1 = {"你必須", "脫離你的根"},
            fb_bl_final_leaf_intro_2 = {"賣掉一張小丑，", "否則繼續被削弱。"},
            fb_bl_final_leaf_big_hand_1 = {"你翻開了", "新的一頁。哼。"},
            fb_bl_final_leaf_close_1 = {"我的葉子", "要掉了！"},
            fb_bl_final_leaf_last_hand_1 = {"最後一手。", "賣掉小丑嗎？"},
            fb_bl_final_leaf_disabled_1 = {"我的葉子！", "枯萎了！"},
            fb_bl_final_leaf_defeat_1 = {"我要離開了...", "如一片落葉。"},
            fb_bl_final_leaf_gloat_1 = {"落葉歸根！"},

            -- Violet Vessel: very large blind
            fb_bl_final_vessel_name_1 = {"但我是", "紫羅蘭花器！"},
            fb_bl_final_vessel_intro_1 = {"你剛撞上了", "萬里長城"},
            fb_bl_final_vessel_intro_2 = {"一個無比巨大", "的盲注。揚帆！"},
            fb_bl_final_vessel_big_hand_1 = {"對龐大的目標", "打出龐大一擊。"},
            fb_bl_final_vessel_close_1 = {"棄船！", "...我的船。"},
            fb_bl_final_vessel_last_hand_1 = {"最後一手。", "這船不會沉。"},
            fb_bl_final_vessel_disabled_1 = {"我的花器！", "在下沉！"},
            fb_bl_final_vessel_defeat_1 = {"花器...", "空了。"},
            fb_bl_final_vessel_gloat_1 = {"一敗塗地！"},

            -- Crimson Heart: one random Joker disabled every hand
            fb_bl_final_heart_name_1 = {"但我是", "緋紅之心！"},
            fb_bl_final_heart_intro_1 = {"我要借走", "一張小丑"},
            fb_bl_final_heart_intro_2 = {"每手牌，一張", "小丑失去力量。"},
            fb_bl_final_heart_big_hand_1 = {"少了一張小丑，", "還這麼強？"},
            fb_bl_final_heart_close_1 = {"別傷了", "我的心！"},
            fb_bl_final_heart_last_hand_1 = {"最後一手。哪張", "小丑被沉默？"},
            fb_bl_final_heart_disabled_1 = {"我的心！", "漏跳了一拍。"},
            fb_bl_final_heart_defeat_1 = {"我的心...", "碎了。"},
            fb_bl_final_heart_gloat_1 = {"心碎了嗎？"},

            -- Cerulean Bell: forces 1 card to always be selected
            fb_bl_final_bell_name_1 = {"但我是", "蔚藍鐘！"},
            fb_bl_final_bell_intro_1 = {"我想", "為你指路"},
            fb_bl_final_bell_intro_2 = {"每手牌都被", "強制選一張牌。"},
            fb_bl_final_bell_big_hand_1 = {"你讓我的強制牌", "響起來了？！"},
            fb_bl_final_bell_close_1 = {"鐘聲響起...", "為我而鳴？！"},
            fb_bl_final_bell_last_hand_1 = {"最後一手。", "一張牌被強制。"},
            fb_bl_final_bell_disabled_1 = {"我的鐘啞了！", "作弊！"},
            fb_bl_final_bell_defeat_1 = {"鐘聲響起", "為我而鳴。"},
            fb_bl_final_bell_gloat_1 = {"叮咚，你輸了！"},
        }
    }
}
